USE [Pusulam]
GO

/****** Object:  StoredProcedure [dbo].[sp_YaziliYoklama]    Script Date: 12.01.2021 16:16:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[sp_YaziliYoklama]
	@ISLEM					INT				= NULL,
	@TCKIMLIKNO				VARCHAR(11)		= NULL,
	@TC_OGRENCI				VARCHAR(11)		= NULL,
	@OTURUM					VARCHAR(36)		= NULL,
	@ID_MENU				INT				= NULL,
	@ID_KADEME2				VARCHAR(MAX)	= NULL,
	@ID_DERSLER				VARCHAR(MAX)	= NULL,
	@SINIFLAR				VARCHAR(MAX)	= NULL,
	@ID_KADEME3				INT				= NULL,
	@ID_YAZILI				INT				= NULL,
	@DONEM					char(4)			= NULL,
	@YARIYIL				TINYINT			= NULL,
	@PASIF					BIT				= NULL,
	@TAKMAAD				VARCHAR(MAX)	= NULL,
	@ID_DERS				INT				= NULL,
	@ID_SINIF				INT				= NULL,	
	@SQLJSON		 		NVARCHAR(MAX)	= NULL,
	@SQLJSONOGRENCI 		NVARCHAR(MAX)	= NULL,
	@SQLJSONOGRENCICEVAP	NVARCHAR(MAX)	= NULL,
	@OVGORSUN				BIT				= NULL,
	@AKTIF					BIT				= NULL,
	@KARNEDEGORUNSUN		BIT				= NULL
AS
BEGIN
	BEGIN TRY    
		DECLARE @MSG			VARCHAR(4000)
		DECLARE @ErrorSeverity	INT
		DECLARE @ErrorState		INT
		
		DECLARE @return_variable INT
		EXEC @return_variable = [dbo].[sp_OturumKontrol] @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU
	
		IF @return_variable = 1
		BEGIN

			IF @ISLEM = 1	--	KADEME 3 Listele
			BEGIN
				SELECT
				(
					SELECT DISTINCT st.ID_KADEME3, k.AD
					FROM		  [dbo].[v3Sinif]			s
					INNER JOIN	  [dbo].[v3Donem]			d		ON d.ID_DONEM		=	s.ID_DONEM
					INNER JOIN	  [dbo].[v3AktifDonem]		ad		ON ad.DONEM			=	d.KOD			and ad.AKTIF=1
					INNER JOIN	  [dbo].[v3SatisTuru]		st		ON st.ID_SATISTURU	=	s.ID_SATISTURU
					INNER JOIN	  [dbo].[v3Kademe3]			k		ON k.ID_KADEME3		=	st.ID_KADEME3
					FOR JSON PATH
				) AS J
			END

			IF @ISLEM = 2	--	KADEME 2 LİSTELE
			BEGIN
				SELECT
				(
					SELECT KB.ID_KADEME2, K2.AD FROM OkyanusDB.dbo.v3KademeBilgi KB
					INNER JOIN OkyanusDB.dbo.v3Kademe2 K2 ON K2.ID_KADEME2=KB.ID_KADEME2
					where ID_KADEME3 = @ID_KADEME3
					FOR JSON PATH
				) AS J
			END	

			IF @ISLEM = 3	--	EKLE
			BEGIN
				----------
				--YAZILI--
				----------
				DECLARE @ID_YAZILILIST TABLE (ID_YAZILI INT)
				INSERT INTO [dbo].[Yazili]
							([AD] ,[KOD] ,[DONEM] ,[YARIYIL] ,[ID_KADEME3], [ID_DERS], [YAZILITARIH], [KYE_TCKIMLIKNO], [ID_YAZILITURU])
				OUTPUT INSERTED.ID_YAZILI INTO @ID_YAZILILIST(ID_YAZILI)
				select		[AD] ,[KOD] ,(select DONEM from [dbo].[v3AktifDonem] where AKTIF=1) as [DONEM], YARIYIL, [ID_KADEME3], ID_DERS, convert(datetime, [YAZILITARIH], 103), @TCKIMLIKNO, [ID_YAZILITURU]
				from OPENJSON(@SQLJSON)
				with
				(
					[AD] [varchar](50),
					[KOD] [varchar](50),
					[YARIYIL] [tinyint],
					[ID_KADEME3] [int],
					[ID_DERS] [int],
					[YAZILITARIH] [varchar](50),
					[ID_YAZILITURU] [int]
				) AS J

				-----------------
				--YAZILIKADEME2--
				-----------------
				INSERT INTO [dbo].[YaziliKademe2]
							([ID_YAZILI]
							,[ID_KADEME2])
				select (select ID_YAZILI from @ID_YAZILILIST) as [ID_YAZILI], value from OPENJSON(@SQLJSON,'$.JSONKADEME2')
									
				-----------
				--SORULAR--
				-----------
				INSERT INTO [dbo].[YaziliSoru]
						   ([ID_YAZILI]
						   ,[SORUNO]
						   ,[PUAN]
						   ,[KOD]
						   ,[ID_BILGI]
						   ,[ID_BILISSELSUREC])
				SELECT
					(select ID_YAZILI from @ID_YAZILILIST) as [ID_YAZILI]
					,JSON_Value (s.value, '$.SORUNO') as SORUNO
					,ISNULL(CONVERT(float,REPLACE(JSON_Value (s.value, '$.PUAN'),',','.')), 0) as PUAN
					,JSON_Value (s.value, '$.KOD') as KOD
					,CASE WHEN JSON_Value (s.value, '$.ID_BILGI') = 0 THEN NULL ELSE JSON_Value (s.value, '$.ID_BILGI') END AS ID_BILGI
					,CASE WHEN JSON_Value (s.value, '$.ID_BILISSELSUREC') = 0 THEN NULL ELSE JSON_Value (s.value, '$.ID_BILISSELSUREC') END AS ID_BILISSELSUREC
				FROM OPENJSON (@SQLJSON, '$.SORULIST') as s
			
				select ID_YAZILI from @ID_YAZILILIST	
			END

			IF @ISLEM = 4	--	GÜNCELLE
			BEGIN
				----------
				--YAZILI--
				----------
				SELECT ID_YAZILI, AD, KOD, YARIYIL, ID_KADEME3, ID_DERS, YAZILITARIH, ID_YAZILITURU 
				INTO #TEMPYAZILI
				FROM OPENJSON(@SQLJSON)
				WITH
				(
					[ID_YAZILI] [int],
					[AD] [varchar](50),
					[KOD] [varchar](50),
					[YARIYIL] [tinyint],
					[ID_KADEME3] [int],
					[ID_DERS] [int],
					[YAZILITARIH] [varchar](50),
					[ID_YAZILITURU] [int]
				) 

				UPDATE Y SET  Y.[AD] = TY.AD
							 ,Y.[KOD] = TY.KOD
							 ,Y.[DONEM] = (SELECT DONEM FROM OkyanusDB.dbo.v3AktifDonem WHERE AKTIF = 1) 
							 ,Y.[YARIYIL] = TY.YARIYIL
							 ,Y.[ID_KADEME3] = TY.ID_KADEME3
							 ,Y.[ID_DERS] = TY.ID_DERS
							 ,Y.[YAZILITARIH] = TY.YAZILITARIH
							 ,Y.[GUN_TCKIMLIKNO] = @TCKIMLIKNO
							 ,Y.[GUN_TARIH] = GETDATE()
							 ,Y.[ID_YAZILITURU] = TY.ID_YAZILITURU
				FROM [dbo].[Yazili] Y
				INNER JOIN #TEMPYAZILI TY ON TY.ID_YAZILI = Y.ID_YAZILI

				-----------------
				--YAZILIKADEME2--
				-----------------
				DELETE FROM [dbo].[YaziliKademe2] WHERE ID_YAZILI = @ID_YAZILI
				INSERT INTO [dbo].[YaziliKademe2]
							([ID_YAZILI]
							,[ID_KADEME2])
				select @ID_YAZILI as [ID_YAZILI], value from OPENJSON(@SQLJSON,'$.JSONKADEME2')

				UPDATE	 SORU SET SORU.PUAN = CONVERT(float,REPLACE(JSON_Value (s.value, '$.PUAN'),',','.'))
						,SORU.KOD = JSON_Value (s.value, '$.KOD')
						,SORU.ID_BILGI = CASE WHEN JSON_Value (s.value, '$.ID_BILGI') = 0 THEN NULL ELSE JSON_Value (s.value, '$.ID_BILGI') END
						,SORU.ID_BILISSELSUREC = CASE WHEN JSON_Value (s.value, '$.ID_BILISSELSUREC') = 0 THEN NULL ELSE JSON_Value (s.value, '$.ID_BILISSELSUREC') END
				FROM OPENJSON (@SQLJSON, '$.SORULIST') as s
				INNER JOIN YaziliSoru SORU ON SORU.ID_YAZILI = @ID_YAZILI AND SORU.SORUNO = JSON_Value (s.value, '$.SORUNO')
				
				DROP TABLE #TEMPYAZILI
				select @ID_YAZILI	
			END

			IF @ISLEM = 5	--	BİLGİ GETİR
			BEGIN
				SELECT 
				(
					SELECT * FROM
					(
						Select (
							Select  
								s.AD as AD, 
								s.KOD, 
								ID_KADEME3, 
								Convert(varchar, YAZILITARIH, 103) as YAZILITARIH,
								s.ID_DERS,
								(SELECT COUNT(*) FROM YaziliSoru YS WHERE YS.ID_YAZILI=s.ID_YAZILI) as SORUSAYISI,
								SORULIST.SORUNO as SORUNO,
								SORULIST.KOD,
								UNITE = ISNULL(SD.AD, ''), 
								SORULIST.PUAN,
								s.YARIYIL,
								s.ID_YAZILITURU,
								ISNULL(SORULIST.ID_BILGI, 0) AS ID_BILGI,
								ISNULL(SORULIST.ID_BILISSELSUREC, 0) AS ID_BILISSELSUREC
							from	   Yazili			s
							LEFT join YaziliSoru		SORULIST		on	SORULIST.ID_YAZILI		= s.ID_YAZILI 
							LEFT JOIN v3SinavDersUnite	SD				ON	SD.KOD					= SORULIST.KOD
							where s.ID_YAZILI = @ID_YAZILI
						for json auto) as T1
						,(SELECT ID_KADEME2 FROM YaziliKademe2 WHERE ID_YAZILI = @ID_YAZILI FOR JSON AUTO) AS T2
					) AS XTABLE
					FOR JSON AUTO
				) AS J
			END

			IF @ISLEM = 6	--	LISTELE
			BEGIN
				SELECT
				(
					SELECT * FROM
					(
						SELECT DISTINCT 
							S.ID_YAZILI
							,KOD
							,S.AD
							,K3.AD AS GRUP
							,S.ID_KADEME3
							,Convert(varchar, YAZILITARIH, 104) AS YAZILITARIH
							,AKTIF 
							,(SELECT COUNT(*) FROM (SELECT TCKIMLIKNO FROM YaziliOgrenci WHERE ID_YAZILI = S.ID_YAZILI GROUP BY TCKIMLIKNO) XTABLE ) AS KATILIM
							,OVGORSUN
							,KARNEDEGORUNSUN,
							ID_YAZILITURU
						FROM Yazili S
						INNER JOIN OkyanusDB.dbo.v3Kademe3 K3 ON K3.ID_KADEME3=S.ID_KADEME3
						LEFT JOIN YaziliKademe2 K2 ON K2.ID_YAZILI = S.ID_YAZILI
						WHERE	DONEM = @DONEM 
						AND		(@YARIYIL = 0 OR YARIYIL = @YARIYIL)
						AND		(@ID_KADEME3 = 0 OR S.ID_KADEME3 = @ID_KADEME3)
						AND		(@ID_KADEME2 = '[]' OR K2.ID_KADEME2 IN (SELECT VALUE FROM OPENJSON(@ID_KADEME2)) or 0 in (SELECT VALUE FROM OPENJSON(@ID_KADEME2)))
						AND		(S.AKTIF = 1 OR @PASIF = 1)
						AND		(@ID_DERS = 0 OR S.ID_DERS = @ID_DERS)
					)XTABLE
					ORDER BY Convert(datetime, YAZILITARIH, 104) DESC
					FOR JSON AUTO
				) AS J
			END

			IF @ISLEM = 7	--	AKTİF PASİF
			BEGIN
				DECLARE @DURUM BIT = (SELECT CASE WHEN AKTIF = 1 THEN 0 ELSE 1 END FROM Yazili WHERE ID_YAZILI = @ID_YAZILI)
				UPDATE Yazili SET AKTIF = @DURUM, GUN_TCKIMLIKNO = @TCKIMLIKNO, GUN_TARIH = GETDATE() WHERE ID_YAZILI = @ID_YAZILI
				SELECT @DURUM
			END

			IF @ISLEM = 8	--	ÖĞRENCİ LİSTELE
			BEGIN
				--DECLARE @KUR BIT = (
				--			SELECT D.KUR FROM Yazili Y
				--			INNER JOIN eokul_v2.dbo.Ders D ON D.ID_DERS = Y.ID_DERS
				--			WHERE ID_YAZILI = @ID_YAZILI
				--		)

				SELECT X.TCKIMLIKNO, X.AD, X.SOYAD, YOC.ID_YAZILIOGRENCI, X.ID_YAZILI, X.ID_YAZILISORU, X.SORUNO, X.PUAN AS MAXPUAN, ISNULL(YOC.PUAN, 0) AS PUAN, ISNULL(YO.KATILMADI, 0) AS KATILMADI, YO.TELAFI
				INTO #TEMP
				FROM
				(
					SELECT * FROM
					(
						SELECT Y.ID_YAZILI, YS.ID_YAZILISORU, YS.SORUNO, YS.PUAN 
						FROM Yazili Y
						INNER JOIN YaziliSoru YS ON YS.ID_YAZILI = Y.ID_YAZILI
						WHERE Y.ID_YAZILI = @ID_YAZILI
					) AS T1
					CROSS JOIN 
					(
						SELECT DISTINCT O.TCKIMLIKNO, K.AD, K.SOYAD
						FROM OkyanusDb.dbo.v3OgrenciTum O
						INNER JOIN OkyanusDB.dbo.v3Kullanici	K	ON	K.TCKIMLIKNO	= O.TCKIMLIKNO
						INNER JOIN OkyanusDb.dbo.v3Sinif		S	ON	S.ID_SINIF		= O.ID_SINIF
						WHERE S.ID_SINIF = @ID_SINIF --AND @KUR = 0
					UNION 
						SELECT DISTINCT K.TCKIMLIKNO, K.AD, K.SOYAD
						FROM OkyanusDB.dbo.v4SinifOgrenci SO 
						INNER JOIN OkyanusDB.dbo.v3Kullanici	K	ON	K.TCKIMLIKNO	= SO.TC_OGRENCI
						WHERE SO.ID_SINIF = @ID_SINIF AND SO.AKTIF = 1
					--	SELECT DISTINCT O.TCKIMLIKNO, K.AD, K.SOYAD
					--	FROM OkyanusDb.dbo.v3OgrenciTumKur O
					--	INNER JOIN OkyanusDB.dbo.v3Kullanici	K	ON	K.TCKIMLIKNO	= O.TCKIMLIKNO
					--	INNER JOIN OkyanusDb.dbo.v3Sinif		S	ON	S.ID_SINIF		= O.ID_SINIF
					--	WHERE S.ID_SINIF = @ID_SINIF AND @KUR = 1
					--UNION 
					--	SELECT DISTINCT O.TCKIMLIKNO, K.AD, K.SOYAD
					--	FROM eokul_v2.dbo.KurOgrenci			KO
					--	INNER JOIN OkyanusDB.dbo.v3OgrenciTum		O	ON	O.ID_OGRENCI	= KO.ID_OGRENCI
					--	INNER JOIN OkyanusDB.dbo.v3Kullanici	K	ON	K.TCKIMLIKNO	= O.TCKIMLIKNO	
					--	WHERE KO.ID_KUR = @ID_SINIF
					) AS T2
				) AS X
				LEFT JOIN YaziliOgrenci YO ON YO.ID_YAZILI = X.ID_YAZILI AND YO.TCKIMLIKNO = X.TCKIMLIKNO AND AKTIF = 1
				LEFT JOIN YaziliOgrenciCevap YOC ON YOC.ID_YAZILIOGRENCI = YO.ID_YAZILIOGRENCI AND YOC.ID_YAZILISORU = X.ID_YAZILISORU

				SELECT
				(
					SELECT
					(
						SELECT DISTINCT TCKIMLIKNO, ID_YAZILISORU, SORUNO, PUAN, MAXPUAN FROM #TEMP					
						ORDER BY TCKIMLIKNO, SORUNO
						FOR JSON PATH
					) AS T1,
					(
						SELECT DISTINCT TCKIMLIKNO, ID_YAZILI, AD, SOYAD, KATILMADI, TELAFI, COUNT(DISTINCT ID_YAZILISORU) AS SORUSAYISI 
						FROM #TEMP
						GROUP BY TCKIMLIKNO, ID_YAZILI, AD, SOYAD, KATILMADI, TELAFI
						ORDER BY TCKIMLIKNO
						FOR JSON PATH
					) AS T2
					FOR JSON PATH
				) AS J

				DROP TABLE #TEMP
			END

			IF @ISLEM = 9	--	KOPYALA
			BEGIN
				DECLARE @ID_YAZILILISTX TABLE (ID_YAZILI INT)
				INSERT INTO Yazili ([AD],[KOD],[DONEM],[YARIYIL],[ID_YAZILITURU],[ID_KADEME3],[ID_DERS],[YAZILITARIH],[KYE_TCKIMLIKNO],[KYE_TARIH],[AKTIF],[GUN_TARIH],[GUN_TCKIMLIKNO])
				OUTPUT inserted.ID_YAZILI INTO @ID_YAZILILISTX
				SELECT [AD]
					  ,[KOD]
					  ,[DONEM]
					  ,[YARIYIL]
					  ,[ID_YAZILITURU]
					  ,[ID_KADEME3]
					  ,[ID_DERS]
					  ,[YAZILITARIH]
					  ,@TCKIMLIKNO
					  ,GETDATE()
					  ,1
					  ,GETDATE()
					  ,'' 
				FROM Yazili 
				WHERE ID_YAZILI = @ID_YAZILI

				DECLARE @ID_YAZILIX INT = (SELECT ID_YAZILI FROM @ID_YAZILILISTX)  

				INSERT INTO YaziliKademe2 ([ID_YAZILI],[ID_KADEME2])
				SELECT @ID_YAZILIX
					  ,[ID_KADEME2] 
				FROM YaziliKademe2 
				WHERE ID_YAZILI = @ID_YAZILI
			
				INSERT INTO YaziliSoru ([ID_YAZILI],[SORUNO],[PUAN],[KOD])
				SELECT (SELECT ID_YAZILI FROM @ID_YAZILILISTX) AS ID_YAZILI
					  ,[SORUNO]
					  ,[PUAN]
					  ,[KOD] 
				FROM YaziliSoru YS
				WHERE ID_YAZILI = @ID_YAZILI
			END

			IF @ISLEM = 10	--	BİLGİ GETİR LİSTE
			BEGIN
				SELECT
				(
					SELECT DONEM
							,ID_KADEME3
							,ID_DERS
							,YARIYIL
							,(SELECT ID_KADEME2 FROM YaziliKademe2 WHERE ID_YAZILI = @ID_YAZILI FOR JSON PATH) AS ID_KADEME2 
					FROM Yazili 
					WHERE ID_YAZILI = @ID_YAZILI
					FOR JSON AUTO
				) AS J
			END

			IF @ISLEM = 11	--	LİSTELE SELECT
			BEGIN
				SELECT
				(
					SELECT Y.ID_YAZILI, Y.AD, Y.KOD 
					FROM Yazili			Y
					JOIN YaziliKademe2	K2	ON	K2.ID_YAZILI	= Y.ID_YAZILI
					WHERE	ID_KADEME3	= @ID_KADEME3 
						AND DONEM		= @DONEM 
						AND YARIYIL		= @YARIYIL 
						AND AKTIF		= 1 					
						AND (	
							ID_KADEME2 IN (SELECT ID_KADEME2 FROM OkyanusDB.dbo.v4Sinif S
									INNER JOIN OkyanusDB.dbo.v3KademeBilgi K ON K.ID_KADEME3 = S.ID_KADEME3
									WHERE S.ID_SINIF = @ID_SINIF) 
							OR  ID_KADEME2	= (SELECT ST.ID_KADEME2 FROM OkyanusDB.dbo.v3Sinif S INNER JOIN OkyanusDB.dbo.v3SatisTuru ST ON ST.ID_SATISTURU = S.ID_SATISTURU WHERE ID_SINIF = @ID_SINIF))
					GROUP BY Y.ID_YAZILI, Y.AD, Y.KOD
					FOR JSON AUTO
				) AS J
			END

			IF @ISLEM = 12	--	ÖĞRENCİ KAYDET
			BEGIN
				SELECT DISTINCT ID_YAZILI, OG.TCKIMLIKNO, CAST((CASE WHEN TELAFI = '' THEN NULL ELSE TELAFI END) AS INT) AS TELAFI, KATILMADI, @TCKIMLIKNO AS KYE_TCKIMLIKNO
				INTO #TEMPOGRENCI
				FROM OPENJSON(@SQLJSONOGRENCI)
				WITH(
					TCKIMLIKNO VARCHAR(11),
					ID_YAZILI INT,
					TELAFI VARCHAR(5),
					KATILMADI BIT
				) OG

				UPDATE Y SET AKTIF = 0 FROM YaziliOgrenci Y 
				INNER JOIN #TEMPOGRENCI O ON O.ID_YAZILI = Y.ID_YAZILI AND O.TCKIMLIKNO = Y.TCKIMLIKNO
			
				delete c
				from YaziliOgrenci yo
				join YaziliOgrenciCevap c on c.ID_YAZILIOGRENCI = yo.ID_YAZILIOGRENCI
				where yo.AKTIF=0

				UPDATE YO SET AKTIF = 0
				FROM YaziliOgrenci YO
				JOIN #TEMPOGRENCI T ON T.ID_YAZILI = YO.ID_YAZILI AND T.TCKIMLIKNO = YO.TCKIMLIKNO
				WHERE YO.AKTIF = 1

				DECLARE @ID_YAZILIOGRENCILIST TABLE( ID_YAZILIOGRENCI INT, TCKIMLIKNO VARCHAR(20))

				INSERT INTO YaziliOgrenci (ID_YAZILI, TCKIMLIKNO, TELAFI, KATILMADI, KYE_TCKIMLIKNO)
				OUTPUT INSERTED.ID_YAZILIOGRENCI,INSERTED.TCKIMLIKNO INTO @ID_YAZILIOGRENCILIST
				SELECT * FROM #TEMPOGRENCI T

				BEGIN TRY 
					INSERT INTO YaziliOgrenciCevap (ID_YAZILISORU, ID_YAZILIOGRENCI, PUAN)
					SELECT ID_YAZILISORU 
						--(	SELECT ID_YAZILIOGRENCI 
						--	FROM YaziliOgrenci 
						--	WHERE ID_YAZILI = 
						--			(	SELECT ID_YAZILI 
						--				FROM YaziliSoru 
						--				WHERE ID_YAZILISORU = OG.ID_YAZILISORU) 
						--		AND TCKIMLIKNO = OG.TCKIMLIKNO 
						--		AND AKTIF = 1 
						--		AND ISNULL(TELAFI, 0) = 0)
						, L.ID_YAZILIOGRENCI
						, PUAN 
						FROM OPENJSON(@SQLJSONOGRENCICEVAP) 
					WITH(
						TCKIMLIKNO VARCHAR(11),
						ID_YAZILISORU INT,
						PUAN INT
					) OG	
					JOIN @ID_YAZILIOGRENCILIST L ON L.TCKIMLIKNO = OG.TCKIMLIKNO
				END	TRY		
				BEGIN CATCH  
				END CATCH  		

				DROP TABLE #TEMPOGRENCI
			END

			IF @ISLEM = 13	--	ÖĞRENCİ SİL
			BEGIN
				SELECT ID_YAZILI, OG.TCKIMLIKNO, TELAFI, KATILMADI, @TCKIMLIKNO AS KYE_TCKIMLIKNO
				INTO #TEMPOGRENCI2
				FROM OPENJSON(@SQLJSONOGRENCI)
				WITH(
					TCKIMLIKNO VARCHAR(11),
					ID_YAZILI INT,
					TELAFI INT,
					KATILMADI BIT
				) OG
				UPDATE Y SET AKTIF = 0, SIL_TCKIMLIKNO = @TCKIMLIKNO, SIL_TARIH = GETDATE()
				FROM YaziliOgrenci Y 
				INNER JOIN #TEMPOGRENCI2 O ON O.ID_YAZILI = Y.ID_YAZILI AND O.TCKIMLIKNO = Y.TCKIMLIKNO
				WHERE Y.AKTIF=1

				DROP TABLE #TEMPOGRENCI2
			END

			IF @ISLEM = 14	--	ÖĞRENCİ KAYDET TOPLU
			BEGIN
				SELECT DISTINCT ID_YAZILI, OG.TCKIMLIKNO, CAST((CASE WHEN TELAFI = '' THEN NULL ELSE TELAFI END) AS INT) AS TELAFI, KATILMADI, @TCKIMLIKNO AS KYE_TCKIMLIKNO
				INTO #TEMPOGRENCI3
				FROM OPENJSON(@SQLJSONOGRENCI)
				WITH(
					TCKIMLIKNO VARCHAR(11),
					ID_YAZILI INT,
					TELAFI VARCHAR(5),
					KATILMADI BIT
				) OG

				UPDATE Y SET AKTIF = 0 FROM YaziliOgrenci Y 
				INNER JOIN #TEMPOGRENCI3 O ON O.ID_YAZILI = Y.ID_YAZILI AND O.TCKIMLIKNO = Y.TCKIMLIKNO

				delete c
				from YaziliOgrenci yo
				join YaziliOgrenciCevap c on c.ID_YAZILIOGRENCI = yo.ID_YAZILIOGRENCI
				where yo.AKTIF=0
			
				DECLARE @ID_YAZILIOGRENCILIST2 TABLE( ID_YAZILIOGRENCI INT, TCKIMLIKNO VARCHAR(20))

				INSERT INTO YaziliOgrenci (ID_YAZILI, TCKIMLIKNO, TELAFI, KATILMADI, KYE_TCKIMLIKNO)
				OUTPUT INSERTED.ID_YAZILIOGRENCI,INSERTED.TCKIMLIKNO INTO @ID_YAZILIOGRENCILIST2
				SELECT * FROM #TEMPOGRENCI3			
			
				BEGIN TRY 
					INSERT INTO YaziliOgrenciCevap (ID_YAZILISORU, ID_YAZILIOGRENCI, PUAN)
					SELECT DISTINCT ID_YAZILISORU
						--, (SELECT ID_YAZILIOGRENCI FROM YaziliOgrenci WHERE ID_YAZILI = (SELECT ID_YAZILI FROM YaziliSoru WHERE ID_YAZILISORU = OG.ID_YAZILISORU) AND TCKIMLIKNO = OG.TCKIMLIKNO AND AKTIF = 1)
						, L.ID_YAZILIOGRENCI
						, PUAN FROM OPENJSON(@SQLJSONOGRENCICEVAP)
					WITH(
						TCKIMLIKNO VARCHAR(11),
						ID_YAZILISORU INT,
						PUAN INT
					) OG		
					JOIN @ID_YAZILIOGRENCILIST2 L ON L.TCKIMLIKNO = OG.TCKIMLIKNO
				END	TRY		
				BEGIN CATCH  
				END CATCH  	


				DROP TABLE #TEMPOGRENCI3
			END

			IF @ISLEM = 15	--	Yazılı Listele by Sınıf
			BEGIN
				DECLARE  @ID_DERSLER2	VARCHAR(MAX)=@ID_DERSLER	
						,@DONEM2		VARCHAR(MAX)=@DONEM
						,@YARIYIL2		INT			=@YARIYIL
						,@SINIFLAR2		VARCHAR(MAX)=@SINIFLAR
		
				DROP TABLE IF EXISTS #TC
				SELECT DISTINCT TCKIMLIKNO 
				INTO #TC
				FROM v3Ogrenci	O
				WHERE O.ID_SINIF IN (SELECT VALUE FROM OPENJSON (@SINIFLAR2))


				IF @ID_DERS IS NULL 
				BEGIN
					SELECT
					(
						Select DISTINCT sr.ID_YAZILI, AD, YAZILITARIH
						from Yazili				SR
						JOIN YaziliOgrenci		YO	ON	YO.ID_YAZILI	= SR.ID_YAZILI
						JOIN #TC				T	ON	T.TCKIMLIKNO	= YO.TCKIMLIKNO
						where sr.AKTIF=1 
						--AND (@ID_KADEME3 IS NULL OR ID_KADEME3 = @ID_KADEME3)
						AND (@ID_DERSLER2 IS NULL OR @ID_DERSLER2='[]' OR sr.ID_DERS IN (SELECT value FROM OPENJSON(@ID_DERSLER2)))
						AND (@YARIYIL2 IS NULL OR @YARIYIL2=0 OR sr.YARIYIL = @YARIYIL2)
						and sr.DONEM=@DONEM2
						order by YAZILITARIH
						FOR JSON PATH
					) AS J
				END
				ELSE 
				BEGIN	
					SELECT
					(
						Select DISTINCT SR.ID_YAZILI, AD, YAZILITARIH
						from Yazili SR
						JOIN YaziliOgrenci		YO	ON	YO.ID_YAZILI	= SR.ID_YAZILI
						JOIN #TC				T	ON	T.TCKIMLIKNO	= YO.TCKIMLIKNO
						where sr.AKTIF=1 
						--AND (@ID_KADEME3 IS NULL OR ID_KADEME3 = @ID_KADEME3)
						AND (sr.ID_DERS = @ID_DERS)
						AND (@YARIYIL IS NULL OR @YARIYIL=0 OR sr.YARIYIL = @YARIYIL)
						and sr.DONEM=@DONEM
						order by YAZILITARIH
						FOR JSON PATH
					) AS J
				END
			
				DROP TABLE IF EXISTS #TC
			END 

			IF @ISLEM = 16	--	YAZILI EKLE EXCEL
			BEGIN
				SELECT 
						 AD = JSON_Value (J.value, '$.AD') 
						,KOD = JSON_Value (J.value, '$.KOD')
						,ID_KADEME3 = K3.ID_KADEME3
						,ID_DERS = JSON_Value (J.value, '$.DERS')
						,ID_KADEME2 = K2.value
						,TARIH = JSON_Value (J.value, '$.TARIH')
						,YARIYIL = JSON_Value (J.value, '$.YARIYIL')
						,SORUNO = JSON_Value (S.value, '$.SORUNO')
						,UNITEKOD = JSON_Value (S.value, '$.KOD')
						,PUAN = JSON_Value (S.value, '$.PUAN')
						,ID_YAZILITURU = JSON_Value (J.value, '$.ID_YAZILITURU')
						,ID_BILGI = JSON_Value (S.value, '$.ID_BILGI')
						,ID_BILISSELSUREC = JSON_Value (S.value, '$.ID_BILISSELSUREC')
				INTO #YAZILI
				FROM OPENJSON(@SQLJSON) AS J
				CROSS APPLY OPENJSON (J.value, '$.OKULTUR') as K2
				CROSS APPLY OPENJSON (J.value, '$.SORULIST') as S
				INNER JOIN OkyanusDb.dbo.v3Kademe3 K3 ON K3.AD = JSON_Value (J.value, '$.GRUP')

				DECLARE @ID_YAZILIAD TABLE (ID_YAZILI INT, AD VARCHAR(50))
				INSERT INTO [dbo].[Yazili]
							([AD] ,[KOD] ,[DONEM] ,[YARIYIL] ,[ID_KADEME3], [ID_DERS], [YAZILITARIH], [KYE_TCKIMLIKNO], [ID_YAZILITURU])
				OUTPUT INSERTED.ID_YAZILI, INSERTED.AD INTO @ID_YAZILIAD(ID_YAZILI, AD)
				SELECT DISTINCT AD, KOD, (select DONEM from [dbo].[v3AktifDonem] where AKTIF=1), YARIYIL, ID_KADEME3, ID_DERS, TARIH, @TCKIMLIKNO, ID_YAZILITURU FROM #YAZILI Y

				INSERT INTO [dbo].[YaziliKademe2]([ID_YAZILI] ,[ID_KADEME2])
				SELECT DISTINCT YA.ID_YAZILI, ID_KADEME2 
				FROM #YAZILI Y
				INNER JOIN @ID_YAZILIAD YA ON YA.AD = Y.AD 

				INSERT INTO [dbo].[YaziliSoru]([ID_YAZILI], [SORUNO], [PUAN], [KOD], [ID_BILGI], [ID_BILISSELSUREC])
				SELECT DISTINCT YA.ID_YAZILI, Y.SORUNO, ISNULL(Y.PUAN, 0) AS PUAN, Y.UNITEKOD, Y.ID_BILGI, Y.ID_BILISSELSUREC
				FROM #YAZILI Y
				INNER JOIN @ID_YAZILIAD YA ON YA.AD = Y.AD 
			
				SELECT MAX(ID_YAZILI) FROM @ID_YAZILIAD

				DROP TABLE #YAZILI
			END

			IF @ISLEM = 17	--	OVGORSUN DEĞİŞTİR
			BEGIN
				UPDATE Yazili SET OVGORSUN = @OVGORSUN WHERE ID_YAZILI = @ID_YAZILI
			END

			IF @ISLEM = 18	--	AKTIF DEĞİŞTİR
			BEGIN
				UPDATE Yazili SET AKTIF = @AKTIF WHERE ID_YAZILI = @ID_YAZILI
			END

			IF @ISLEM = 19	--	YAZILI TÜRÜ LİSTELE
			BEGIN
				SELECT
				(
					SELECT * 
					FROM YaziliTuru
					WHERE AKTIF = 1
					FOR JSON AUTO
				)
			END

			IF @ISLEM = 20	--	YAZILI BİLGİLERİNİ GÜNCELLE (SORULAR HARİÇ)
			BEGIN
				----------
				--YAZILI--
				----------
				SELECT ID_YAZILI, AD, KOD, YARIYIL, ID_KADEME3, ID_DERS, YAZILITARIH, ID_YAZILITURU 
				INTO #TEMPYAZILIGUNCELLE
				FROM OPENJSON(@SQLJSON)
				WITH
				(
					[ID_YAZILI] [int],
					[AD] [varchar](50),
					[KOD] [varchar](50),
					[YARIYIL] [tinyint],
					[ID_KADEME3] [int],
					[ID_DERS] [int],
					[YAZILITARIH] [varchar](50),
					[ID_YAZILITURU] [int]
				) 

				UPDATE Y SET  Y.[AD] = TY.AD
							 ,Y.[KOD] = TY.KOD
							 ,Y.[DONEM] = (SELECT DONEM FROM OkyanusDB.dbo.v3AktifDonem WHERE AKTIF = 1) 
							 ,Y.[YARIYIL] = TY.YARIYIL
							 ,Y.[ID_KADEME3] = TY.ID_KADEME3
							 ,Y.[ID_DERS] = TY.ID_DERS
							 ,Y.[YAZILITARIH] = TY.YAZILITARIH
							 ,Y.[GUN_TCKIMLIKNO] = @TCKIMLIKNO
							 ,Y.[GUN_TARIH] = GETDATE()
							 ,Y.[ID_YAZILITURU] = TY.ID_YAZILITURU
				FROM [dbo].[Yazili] Y
				INNER JOIN #TEMPYAZILIGUNCELLE TY ON TY.ID_YAZILI = Y.ID_YAZILI

				-----------------
				--YAZILIKADEME2--
				-----------------
				DELETE FROM [dbo].[YaziliKademe2] WHERE ID_YAZILI = @ID_YAZILI
				INSERT INTO [dbo].[YaziliKademe2]
							([ID_YAZILI]
							,[ID_KADEME2])
				select @ID_YAZILI as [ID_YAZILI], value from OPENJSON(@SQLJSON,'$.JSONKADEME2')

				DROP TABLE #TEMPYAZILIGUNCELLE
				SELECT @ID_YAZILI
			END

			IF @ISLEM = 21	--	Yazılı Listele by Sınıf - KOS
			BEGIN
				DECLARE  @ID_DERSLERKOS	VARCHAR(MAX)=@ID_DERSLER	
						,@DONEMKOS		VARCHAR(MAX)=@DONEM
						,@YARIYILKOS	INT			=@YARIYIL
						,@SINIFLARKOS	VARCHAR(MAX)=@SINIFLAR
		
				DROP TABLE IF EXISTS #TCKOS
				SELECT DISTINCT TCKIMLIKNO 
				INTO #TCKOS
				FROM v3Ogrenci	O
				WHERE O.ID_SINIF IN (SELECT VALUE FROM OPENJSON (@SINIFLARKOS))


				IF @ID_DERS IS NULL 
				BEGIN
					SELECT
					(
						Select DISTINCT sr.ID_YAZILI, AD, YAZILITARIH
						from Yazili				SR
						JOIN YaziliOgrenci		YO	ON	YO.ID_YAZILI	= SR.ID_YAZILI
						JOIN #TCKOS				T	ON	T.TCKIMLIKNO	= YO.TCKIMLIKNO
						where sr.AKTIF=1 
						AND (@ID_DERSLERKOS IS NULL OR @ID_DERSLERKOS='[]' OR sr.ID_DERS IN (SELECT value FROM OPENJSON(@ID_DERSLERKOS)))
						AND (@YARIYILKOS IS NULL OR @YARIYILKOS=0 OR sr.YARIYIL = @YARIYILKOS)
						AND sr.DONEM=@DONEMKOS
						AND sr.ID_YAZILITURU = 2
						order by YAZILITARIH
						FOR JSON PATH
					) AS J
				END
				ELSE 
				BEGIN	
					SELECT
					(
						Select DISTINCT SR.ID_YAZILI, AD, YAZILITARIH
						from Yazili SR
						JOIN YaziliOgrenci		YO	ON	YO.ID_YAZILI	= SR.ID_YAZILI
						JOIN #TCKOS				T	ON	T.TCKIMLIKNO	= YO.TCKIMLIKNO
						where sr.AKTIF=1 
						AND (sr.ID_DERS = @ID_DERS)
						AND (@YARIYIL IS NULL OR @YARIYIL=0 OR sr.YARIYIL = @YARIYIL)
						AND sr.DONEM=@DONEMKOS
						AND sr.ID_YAZILITURU = 2
						order by YAZILITARIH
						FOR JSON PATH
					) AS J
				END
			
				DROP TABLE IF EXISTS #TCKOS
			END 

			IF @ISLEM = 22	--	KARNEDEGORUNSUN
			BEGIN
				UPDATE Yazili SET KARNEDEGORUNSUN = @KARNEDEGORUNSUN WHERE ID_YAZILI = @ID_YAZILI
			END

			IF @ISLEM=23 -- YY İşlemleri Excelden Toplu sonuç Yükleme Kayıt Kontrol
			BEGIN
				DECLARE @SINAV_DONEM23 INT=0
				DECLARE @SINAV_GRUP23 INT=0

				--Sınavın yapıldığı dönem ve sınavın grubu
				SELECT TOP 1 @SINAV_DONEM23 = DONEM , @SINAV_GRUP23 = ID_KADEME3 from Yazili where ID_YAZILI =  @ID_YAZILI

					--Hatalı kayıtları listelemek için hata table'ı oluşturuldu.
					DROP TABLE IF EXISTS #HATALI_DATA
					DROP TABLE IF EXISTS #TEMP_EXCEL_OGRENCI_SONUC
					CREATE TABLE #HATALI_DATA(TCKIMLIKNO VARCHAR(11),HATA VARCHAR(100))

					--Jsondan gelen data örneği
					--SET @SQLJSONOGRENCICEVAP ='[{"TCKIMLIKNO":"12538356788","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10057081990","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10022549418","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"12345678912","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10042588862","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10037805868","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"16076206154","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10,"SORU5":10}]'				

									--JSON'dan GELEN DATA TEMP TABLE'A ATILIYOR
						SELECT TCKIMLIKNO,ID_YAZILI,SORU1,SORU2,SORU3,SORU4,SORU5,SORU6,SORU7,SORU8,SORU9,SORU10,SORU11,SORU12,SORU13,SORU14,SORU15,SORU16,SORU17,SORU18,SORU19,SORU20,TELAFI
						INTO #TEMP_EXCEL_OGRENCI_SONUC
						FROM OPENJSON(@SQLJSONOGRENCICEVAP) WITH(TCKIMLIKNO VARCHAR(11),ID_YAZILI INT,SORU1 INT,SORU2 INT,SORU3 INT,SORU4 INT,SORU5 INT,SORU6 INT,SORU7 INT,SORU8 INT,SORU9 INT,SORU10 INT,SORU11 INT,SORU12 INT,SORU13 INT,SORU14 INT,SORU15 INT,SORU16 INT,SORU17 INT,SORU18 INT,SORU19 INT,SORU20 INT,TELAFI INT)

					--TC KONTROL ve Öğrenci tablosunda olmayan kayıtlar Hata tablosuna ekleniyor. 
						INSERT #HATALI_DATA(TCKIMLIKNO,HATA)
						SELECT T.TCKIMLIKNO,'Kayıtlı öğrenci değil'
						FROM #TEMP_EXCEL_OGRENCI_SONUC AS T 
						WHERE NOT EXISTS(SELECT TOP 1 1 FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] O WHERE O.TCKIMLIKNO = T.TCKIMLIKNO)
						--LEFT JOIN [OkyanusDB].[dbo].[vw_OgrenciDetayTum] AS O ON O.TCKIMLIKNO=T.TCKIMLIKNO 
						--WHERE O.TCKIMLIKNO IS NULL


					--TC'si Ogrenci tablosunda olmayan Hatalı datalar temp tabledan siliniyor
						DELETE FROM #TEMP_EXCEL_OGRENCI_SONUC WHERE TCKIMLIKNO IN (SELECT TCKIMLIKNO FROM #HATALI_DATA)

					--Yazılı Donem Kontrolü - Hatalı döneme sahip öğrenciler Hata tablosuna kayıt ediliyor
						INSERT #HATALI_DATA(TCKIMLIKNO,HATA)
						SELECT T.TCKIMLIKNO,'Öğrencinin dönemi hatalı' AS HATA
						FROM #TEMP_EXCEL_OGRENCI_SONUC AS T
						WHERE NOT EXISTS(	SELECT TOP 1 1 
											FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] O 
											WHERE	O.TCKIMLIKNO= T.TCKIMLIKNO 
												AND DONEM		= @SINAV_DONEM23
										)
						--LEFT JOIN (SELECT TCKIMLIKNO FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] WHERE DONEM=@SINAV_DONEM) AS O
						--ON O.TCKIMLIKNO=T.TCKIMLIKNO WHERE O.TCKIMLIKNO IS NULL


					--Dönemi Hatalı datalar temp tabledan siliniyor
						DELETE FROM #TEMP_EXCEL_OGRENCI_SONUC WHERE TCKIMLIKNO IN (SELECT TCKIMLIKNO FROM #HATALI_DATA)

					--GRUP Kontrol
						INSERT #HATALI_DATA(TCKIMLIKNO,HATA)
						SELECT T.TCKIMLIKNO,'Öğrencinin grubu hatalı'
						FROM #TEMP_EXCEL_OGRENCI_SONUC AS T 
						WHERE NOT EXISTS(	SELECT TOP 1 1 
											FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] O 
											WHERE	O.TCKIMLIKNO= T.TCKIMLIKNO 
												AND ID_KADEME3	= @SINAV_GRUP23
										)
								--LEFT JOIN (SELECT * FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] WHERE ID_KADEME3=(SELECT  ID_KADEME3 FROM Yazili WHERE --ID_YAZILI = @ID_YAZILI)) AS O
								--ON O.TCKIMLIKNO=T.TCKIMLIKNO WHERE O.TCKIMLIKNO IS NULL

						

					--Grubu Hatalı datalar temp tabledan siliniyor
						DELETE FROM #TEMP_EXCEL_OGRENCI_SONUC WHERE TCKIMLIKNO IN(SELECT TCKIMLIKNO FROM #HATALI_DATA)

					--Hatalı data tablosu geri JSON olarak dönülüyor
						SELECT * FROM #HATALI_DATA FOR JSON AUTO;

					--Temp table'lar silinyor.
						DROP TABLE #HATALI_DATA
 
			END

			IF @ISLEM=24
			BEGIN
				--@SQLJSONOGRENCICEVAP doğru olarak gelen datalar için CRUD işlemleri yapılıyor
--				DECLARE @SQLJSONOGRENCICEVAP NVARCHAR(MAX)='[{"TCKIMLIKNO":"12538356788","ID_YAZILI":1973,"SORU1":10,"SORU2":9,"SORU3":8,"SORU4":10},{"TCKIMLIKNO":"10057081990","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10022549418","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"12345678912","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10042588862","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"10037805868","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10},{"TCKIMLIKNO":"16076206154","ID_YAZILI":1973,"SORU1":10,"SORU2":10,"SORU3":10,"SORU4":10,"SORU5":10}]'
--DECLARE @ID_YAZILI		INT = 1973
--DECLARE @SINAV_DONEM	INT = 0
--DECLARE @SINAV_GRUP		INT = 0
--DECLARE @TCKIMLIKNO		VARCHAR(MAX) = '32051057542'

				DECLARE @SINAV_DONEM24 INT=0
				DECLARE @SINAV_GRUP24 INT=0

				--Sınavın yapıldığı dönem ve sınavın grubu
				SELECT TOP 1 @SINAV_DONEM24 = DONEM , @SINAV_GRUP24 = ID_KADEME3 from Yazili where ID_YAZILI =  @ID_YAZILI
				
						DROP TABLE IF EXISTS #EXCEL
						CREATE TABLE #EXCEL (
						TCKIMLIKNO	VARCHAR(MAX),
						SORU1		VARCHAR(MAX),
						SORU2		VARCHAR(MAX),
						SORU3		VARCHAR(MAX),
						SORU4		VARCHAR(MAX),
						SORU5		VARCHAR(MAX),
						SORU6		VARCHAR(MAX),
						SORU7		VARCHAR(MAX),
						SORU8		VARCHAR(MAX),
						SORU9		VARCHAR(MAX),
						SORU10		VARCHAR(MAX),
						SORU11		VARCHAR(MAX),
						SORU12		VARCHAR(MAX),
						SORU13		VARCHAR(MAX),
						SORU14		VARCHAR(MAX),
						SORU15		VARCHAR(MAX),
						SORU16		VARCHAR(MAX),
						SORU17		VARCHAR(MAX),
						SORU18		VARCHAR(MAX),
						SORU19		VARCHAR(MAX),
						SORU20		VARCHAR(MAX),
						TELAFI		VARCHAR(MAX),
						ID_YAZILIOGRENCI INT
						)
						​
						INSERT INTO #EXCEL (TCKIMLIKNO, SORU1, SORU2, SORU3, SORU4, SORU5, SORU6, SORU7, SORU8, SORU9, SORU10, SORU11, SORU12, SORU13, SORU14, SORU15, SORU16, SORU17, SORU18, SORU19, SORU20,TELAFI) 
						SELECT TCKIMLIKNO, SORU1, SORU2, SORU3, SORU4, SORU5, SORU6, SORU7, SORU8, SORU9, SORU10, SORU11, SORU12, SORU13, SORU14, SORU15, SORU16, SORU17, SORU18, SORU19, SORU20,TELAFI
						FROM OPENJSON (@SQLJSONOGRENCICEVAP)
						WITH (
							TCKIMLIKNO	VARCHAR(MAX),
							SORU1		VARCHAR(MAX),
							SORU2		VARCHAR(MAX),
							SORU3		VARCHAR(MAX),
							SORU4		VARCHAR(MAX),
							SORU5		VARCHAR(MAX),
							SORU6		VARCHAR(MAX),
							SORU7		VARCHAR(MAX),
							SORU8		VARCHAR(MAX),
							SORU9		VARCHAR(MAX),
							SORU10		VARCHAR(MAX),
							SORU11		VARCHAR(MAX),
							SORU12		VARCHAR(MAX),
							SORU13		VARCHAR(MAX),
							SORU14		VARCHAR(MAX),
							SORU15		VARCHAR(MAX),
							SORU16		VARCHAR(MAX),
							SORU17		VARCHAR(MAX),
							SORU18		VARCHAR(MAX),
							SORU19		VARCHAR(MAX),
							SORU20		VARCHAR(MAX),
							TELAFI		VARCHAR(MAX)
						)

						--SELECT * FROM #EXCEL

						DROP TABLE IF EXISTS #YAZILISORU
						SELECT * INTO #YAZILISORU FROM YaziliSoru WHERE ID_YAZILI = @ID_YAZILI

						--TCKIMLIKNO ve ID_YAZILI ile daha önce eklenen kayıt var ise durumu pasif'e çekiliyor.
						UPDATE Y SET 
							AKTIF = 0 
						FROM YaziliOgrenci Y 
						INNER JOIN #EXCEL O ON O.TCKIMLIKNO = Y.TCKIMLIKNO
						WHERE Y.ID_YAZILI=@ID_YAZILI
						
						DELETE C
						FROM YaziliOgrenci YO
						JOIN YaziliOgrenciCevap C on C.ID_YAZILIOGRENCI = YO.ID_YAZILIOGRENCI
						WHERE YO.AKTIF=0

						-- Tüm öğrencilerde dönemi ve grubu olanları al.
						DROP TABLE IF EXISTS #TUM_OGRENCILER
						SELECT DISTINCT TCKIMLIKNO 
						INTO #TUM_OGRENCILER 
						FROM [OkyanusDB].[dbo].[vw_OgrenciDetayTum] 
						WHERE	ID_KADEME3	= @SINAV_GRUP24
							AND DONEM		= @SINAV_DONEM24
					
					--SELECT * FROM #TUM_OGRENCILER
					DECLARE @INSERTTABLO TABLE (ID_YAZILIOGRENCI INT, TCKIMLIKNO VARCHAR(11))
					INSERT INTO YaziliOgrenci(ID_YAZILI,TCKIMLIKNO,KYE_TCKIMLIKNO,KATILMADI,TELAFI)
					OUTPUT inserted.ID_YAZILIOGRENCI,inserted.TCKIMLIKNO INTO @INSERTTABLO(ID_YAZILIOGRENCI,TCKIMLIKNO)
					SELECT	 @ID_YAZILI
							,OT.TCKIMLIKNO
							,@TCKIMLIKNO
							,KATILMADI	= CASE WHEN EXISTS (SELECT TOP 1 1 FROM #EXCEL AS E WHERE E.TCKIMLIKNO = OT.TCKIMLIKNO)
												THEN 0 
												ELSE 1	
											END
							,TELAFI		= (SELECT ISNULL(E.TELAFI,NULL) FROM #EXCEL AS E WHERE OT.TCKIMLIKNO=E.TCKIMLIKNO)
					FROM #TUM_OGRENCILER AS OT

					UPDATE E SET
							E.ID_YAZILIOGRENCI = I.ID_YAZILIOGRENCI
					FROM #EXCEL E
					JOIN  @INSERTTABLO I ON I.TCKIMLIKNO = E.TCKIMLIKNO
 
					DECLARE @sqlCommand varchar(1000)	
						DROP TABLE IF EXISTS #WHILE
						SELECT * INTO #WHILE FROM #YAZILISORU
						WHILE EXISTS( SELECT TOP 1 1 FROM #WHILE)
						BEGIN
							DECLARE @SORUNO VARCHAR(2) = (SELECT TOP 1 CAST(SORUNO AS varchar) FROM #WHILE ORDER BY SORUNO)
							SET @sqlCommand	= 'SELECT SORU'+ @SORUNO  +' FROM #EXCEL ' 
	
							SET @sqlCommand = 
							'	INSERT INTO YaziliOgrenciCevap (ID_YAZILISORU, ID_YAZILIOGRENCI, PUAN)
								SELECT (SELECT TOP 1 ID_YAZILISORU FROM #YAZILISORU YS WHERE YS.SORUNO = '+@SORUNO+') AS ID_YAZILISORU, ID_YAZILIOGRENCI, SORU'+@SORUNO+' FROM #EXCEL'
							EXEC (@sqlCommand)
						​
							DELETE FROM #WHILE WHERE SORUNO = @SORUNO
						END
 
						DROP TABLE #TUM_OGRENCILER					
			END
		END
	END TRY
	BEGIN CATCH
		SELECT 
			@ErrorSeverity	= ERROR_SEVERITY(),
			@ErrorState		= ERROR_STATE()
							
		SELECT @MSG = /*'Prosedür: ' + ISNULL(ERROR_PROCEDURE(), '') + ', Satır: ' + CAST(ERROR_LINE() as varchar) + ', Hata: ' +*/ ERROR_MESSAGE()
			
		RAISERROR (@MSG , -- Message text.
					@ErrorSeverity, -- Severity.
					@ErrorState -- State.
					);
	END CATCH;
END


GO


