USE [eokul_v2]
GO

/****** Object:  StoredProcedure [dbo].[sp_OgrenciVeliSifreSifirla]    Script Date: 13.01.2021 13:43:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[sp_OgrenciVeliSifreSifirla]
@ISLEM INT,
@TCKIMLIKNO VARCHAR(11)='',
@ADSOYAD	VARCHAR(300)=NULL,
@REFERANCENAME	VARCHAR(300)=NULL,
@REFERANCE_TCNO VARCHAR(300)=NULL,
@BIRTHDAY			DATE=NULL,
@SIFRE			VARCHAR(50)=NULL,
@MASKADSOYAD	VARCHAR(300)=NULL,
@KULLANICI_TIP		INT=NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	BEGIN TRY
 
	DECLARE @ERRMESSAGE VARCHAR(200)=''
	DECLARE @ERRCODE INT=0

		IF @ISLEM=1
			BEGIN
				DROP TABLE IF EXISTS #TempData
				CREATE TABLE #TempData
				(
 					ADSOYAD		varchar(300),
					MASKED_ADSOYAD	VARCHAR(300),
					ERRCODE		INT,
					ERRMESSAGE  varchar(200),
					KULLANICITIP INT
				)

				SET @KULLANICI_TIP= (SELECT TOP 1 ID_KULLANICITIPI FROM OkyanusDB.dbo.v3SubeYetki WHERE TCKIMLIKNO=@TCKIMLIKNO AND (ID_KULLANICITIPI=4 OR ID_KULLANICITIPI=5))
	
				IF (@KULLANICI_TIP IS NOT NULL) AND (@KULLANICI_TIP>0)
					BEGIN
					
						IF @KULLANICI_TIP=4 --Öðrenciye ait veli adý soyadý *** olarak çekiliyor
							BEGIN

								SET @ADSOYAD=(SELECT TOP 1 (TUMKULLANICI.AD+' '+TUMKULLANICI.SOYAD) AS ADSOYAD 
												FROM OkyanusDb.dbo.v3OgrenciVeli		AS TUMVELI
												INNER JOIN OkyanusDB.dbo.v3Kullanici	AS TUMKULLANICI ON	TUMKULLANICI.TCKIMLIKNO	= TUMVELI.TCKIMLIKNO
												WHERE TUMVELI.TCKIMLIKNO_OGR=@TCKIMLIKNO AND TUMKULLANICI.AKTIF=1 ORDER BY NEWID())

								SET @MASKADSOYAD=SUBSTRING(@ADSOYAD,1,2)+'****'+' '+'****'+RIGHT(@ADSOYAD,LEN(@ADSOYAD)-(LEN(@ADSOYAD)-1))

								SET @ERRCODE=0

							END

						ELSE -- Veliye ait öðrenci/öðrencilerden birtanesinin adý soyadý ***** olarak çekiliyor
							BEGIN

							DECLARE @AKTIFDONEM INT =(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)

							SET @ADSOYAD=(SELECT TOP 1 (AD+' '+SOYAD) AS ADSOYAD 
							FROM OkyanusDB.dbo.v3OgrenciTum AS TUMOGRENCILER
							INNER JOIN OkyanusDB.dbo.v3OgrenciVeli AS VELI  ON VELI.TCKIMLIKNO_OGR=TUMOGRENCILER.TCKIMLIKNO
							INNER JOIN OkyanusDB.dbo.v3Kullanici AS K ON K.TCKIMLIKNO=(SELECT TOP 1 TCKIMLIKNO_OGR FROM OkyanusDB.dbo.v3OgrenciVeli
							WHERE TCKIMLIKNO=@TCKIMLIKNO ORDER BY NEWID())
							WHERE TUMOGRENCILER.TCKIMLIKNO=(SELECT TOP 1 TCKIMLIKNO_OGR FROM OkyanusDB.dbo.v3OgrenciVeli
															WHERE TCKIMLIKNO=@TCKIMLIKNO AND K.AKTIF=1 ORDER BY NEWID()) AND DONEM=@AKTIFDONEM)

							SET @MASKADSOYAD=SUBSTRING(@ADSOYAD,1,2)+'****'+' '+'****'+RIGHT(@ADSOYAD,LEN(@ADSOYAD)-(LEN(@ADSOYAD)-1))

							SET @ERRCODE=0

							END
					END
					ELSE
					BEGIN
 						SET @ERRMESSAGE='Sadece Veli yada Öðrenci þifre oluþturabilir'
						SET @ERRCODE=1

					END
				
					INSERT INTO #TempData(ADSOYAD,MASKED_ADSOYAD,ERRCODE,ERRMESSAGE,KULLANICITIP) Values(@ADSOYAD,@MASKADSOYAD,@ERRCODE,@ERRMESSAGE,@KULLANICI_TIP);
					SELECT * FROM #TempData FOR JSON AUTO
					
			END
		IF @ISLEM=2
			BEGIN

				DROP TABLE IF EXISTS #UPDATE_TABLE
				CREATE TABLE #UPDATE_TABLE
				( 
					ERRCODE		INT,
					ERRMESSAGE  varchar(200), 
				)


				DECLARE @TABLE_DOGUMTARIHI NVARCHAR(MAX)=''
				DECLARE @TABLE_ADSOYAD NVARCHAR(MAX)=''
				DECLARE @TCKONTROL INT
 
				SET @TABLE_ADSOYAD=(SELECT AD+SOYAD FROM OkyanusDB.dbo.v3Kullanici WHERE TCKIMLIKNO=@TCKIMLIKNO)

				SET @TABLE_DOGUMTARIHI = (SELECT DOGUMTARIHI FROM OkyanusDB.dbo.v3Kullanici WHERE TCKIMLIKNO=@TCKIMLIKNO)

				IF @KULLANICI_TIP=4
					BEGIN
						SET @TCKONTROL= (SELECT COUNT(1) FROM Veli WHERE TCKIMLIKNO=@REFERANCE_TCNO AND ADSOYAD =@REFERANCENAME)
					END

				IF @KULLANICI_TIP=5
					BEGIN
						SET @TCKONTROL=(SELECT COUNT(1) FROM v3Kullanici WHERE TCKIMLIKNO=@REFERANCE_TCNO AND AD+' '+SOYAD=@REFERANCENAME)
					END

				IF @TCKONTROL=0 AND @KULLANICI_TIP=4
					BEGIN
						SET @ERRMESSAGE='Referans veli TC Kimlik numarasý hatalý'
					END
				ELSE IF @TCKONTROL=0 AND @KULLANICI_TIP=5
					BEGIN
						SET @ERRMESSAGE='Referans öðrenci TC Kimlik numarasý hatalý'
					END
				ELSE IF @TABLE_ADSOYAD!=REPLACE(@ADSOYAD,' ','') OR @TABLE_ADSOYAD=''
					BEGIN
						SET @ERRMESSAGE='Adýnýz Soyadýz Hatalý'
					END
				ELSE IF @TABLE_DOGUMTARIHI!=@BIRTHDAY OR @TABLE_DOGUMTARIHI=''
					BEGIN
						SET @ERRMESSAGE='Doðum Tarihi Hatalý'
					END
				ELSE
					BEGIN
						UPDATE OkyanusDB.dbo.v3Kullanici 
						SET SIFRE = @SIFRE,
						SIFREHASH=eokul_v2.dbo.clr_Crypto_HashPass(@SIFRE) 
						WHERE TCKIMLIKNO = @TCKIMLIKNO

						SET @ERRCODE=0
						SET @ERRMESSAGE='Þifreniz baþarýyla oluþturuldu.'
						
					END

				INSERT INTO #UPDATE_TABLE (ERRCODE,ERRMESSAGE) VALUES(@ERRCODE,@ERRMESSAGE)
				SELECT * FROM #UPDATE_TABLE FOR JSON AUTO


			END
		
	END TRY

	BEGIN CATCH

	END CATCH

	SET NOCOUNT OFF;
END
GO


