
GO
PRINT N'Creating Table [dbo].[ZumreBilgi]...';


GO
CREATE TABLE [dbo].[ZumreBilgi] (
    [ID_ZUMRE]       INT          IDENTITY (1, 1) NOT NULL,
    [ID_KADEME3]     INT          NOT NULL,
    [ID_DERS]        INT          NOT NULL,
    [BAS_TARIH]      DATE         NOT NULL,
    [BIT_TARIH]      DATE         NOT NULL,
    [KYE_TCKIMLIKNO] VARCHAR (11) NOT NULL,
    CONSTRAINT [PK_,] PRIMARY KEY CLUSTERED ([ID_ZUMRE] ASC)
);


GO
PRINT N'Creating Table [dbo].[ZumreKazanim]...';


GO
CREATE TABLE [dbo].[ZumreKazanim] (
    [ID_ZUMRE_KAZANIM] INT IDENTITY (1, 1) NOT NULL,
    [ID_ZUMRE]         INT NOT NULL,
    [ID_KAZANIM]       INT NOT NULL,
    [SECILI]           BIT NOT NULL,
    CONSTRAINT [PK_ZumreKazanim] PRIMARY KEY CLUSTERED ([ID_ZUMRE_KAZANIM] ASC)
);


GO
PRINT N'Creating Table [dbo].[ZumreLog]...';


GO
CREATE TABLE [dbo].[ZumreLog] (
    [ID_ZUMRE_LOG] INT          IDENTITY (1, 1) NOT NULL,
    [ID_ZUMRE_TUR] INT          NOT NULL,
    [BAS_TARIH]    DATE         NOT NULL,
    [BIT_TARIH]    DATE         NOT NULL,
    [SECILI]       INT          NOT NULL,
    [TCKIMLIKNO]   VARCHAR (11) NOT NULL,
    CONSTRAINT [PK_ZumreLog] PRIMARY KEY CLUSTERED ([ID_ZUMRE_LOG] ASC)
);


GO
PRINT N'Creating Table [dbo].[ZumreOzellik]...';


GO
CREATE TABLE [dbo].[ZumreOzellik] (
    [ID_ZUMREOZELLIK]   INT           IDENTITY (1, 1) NOT NULL,
    [ID_ZUMREBILGILERI] INT           NOT NULL,
    [ID_ZUMRETUR]       TINYINT       NOT NULL,
    [ICERIK]            VARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_ZumreOzellik] PRIMARY KEY CLUSTERED ([ID_ZUMREOZELLIK] ASC)
);


GO
PRINT N'Creating Table [dbo].[ZumreOzellikDosya]...';


GO
CREATE TABLE [dbo].[ZumreOzellikDosya] (
    [ID_ZUMREOZELLIKDOSYA] INT           IDENTITY (1, 1) NOT NULL,
    [ID_ZUMREOZELLIK]      INT           NOT NULL,
    [DOSYA_GUID]           VARCHAR (MAX) NOT NULL,
    [AD]                   VARCHAR (MAX) NULL,
    CONSTRAINT [PK_ZumreOzellikDosya] PRIMARY KEY CLUSTERED ([ID_ZUMREOZELLIKDOSYA] ASC)
);


GO
PRINT N'Creating Table [dbo].[ZumreTur]...';


GO
CREATE TABLE [dbo].[ZumreTur] (
    [ID_ZUMRETUR] INT          IDENTITY (1, 1) NOT NULL,
    [AD]          VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ZumreTur] PRIMARY KEY CLUSTERED ([ID_ZUMRETUR] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_ZumreKazanim_SECILI]...';


GO
ALTER TABLE [dbo].[ZumreKazanim]
    ADD CONSTRAINT [DF_ZumreKazanim_SECILI] DEFAULT ((0)) FOR [SECILI];


GO
PRINT N'Creating Procedure [dbo].[sp_Zumre]...';


GO
CREATE PROC [dbo].[sp_Zumre]
	@ISLEM							INT				= NULL,
	@TCKIMLIKNO						VARCHAR(11)		= NULL,
	@OTURUM							VARCHAR(36)		= NULL,
	@ID_MENU						INT				= NULL,
	@SQLJSON						VARCHAR(MAX)	= NULL,
	@DONEM							VARCHAR(4)		= NULL,
	@ID_KADEME3						INT				= NULL,
	@ID_DERS						INT				= NULL,
	@BAS_TARIH						VARCHAR(MAX)    = NULL,
	@BIT_TARIH						VARCHAR(MAX)	= NULL,
	@DOSYALIST						VARCHAR(MAX)	= NULL,
	@ID_ZUMRE_OZELLIK				INT				= NULL,
	@HAFTANIN_KAZANIMI				VARCHAR(MAX)    = NULL,
	@ID_ZUMRE						INT				= NULL,
	@ID_HAFTANIN_KAZANIMI			INT				= NULL,
	@ID_DOSYA						INT				= NULL,
	@ID_ZUMREOZELLIKDOSYA			INT				= NULL,
	@ODEV							VARCHAR(MAX)	= NULL,
	@ID_ZUMRE_OZELLIK_ODEV			VARCHAR(15)		= NULL,
	@ID_ZUMRE_TUR					INT				= NULL
	
	
AS
BEGIN
	BEGIN TRY    
		DECLARE @MSG			VARCHAR(4000)
		DECLARE @ErrorSeverity	INT
		DECLARE @ErrorState		INT
		DECLARE @_ID_LOG INT = 0
		DECLARE @return_variable INT
		EXEC @return_variable = [dbo].[sp_OturumKontrol] @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU
		DECLARE @AKTIFDONEM VARCHAR(4) = (SELECT DONEM FROM OkyanusDB.dbo.v3AktifDonem WHERE AKTIF = 1)

		IF @return_variable = 1
		BEGIN
			IF @ISLEM = 1  --Kullanıcı Tip Getir
			BEGIN
			    SELECT ISNULL((
					SELECT DISTINCT
					    OGRETMEN = ISNULL((SELECT TOP 1 1 FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO AND ID_KULLANICITIPI = 3),0)
					   ,BASKAN	 = ISNULL((SELECT TOP 1 1 FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO AND ID_KULLANICITIPI IN(27,59) ),0)
					 FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO
					FOR JSON AUTO
				),'[]')
			END
			
			IF @ISLEM = 2  --Kazanım Getir
			BEGIN
			
				SELECT ISNULL((
					SELECT	 D1.ID_DERS
							,D1.ID_DERSUNITE
							,D1.KOD
							,D1.AD
							,LINKLIST = ISNULL((SELECT LINK
												FROM OKYANUSDB.DBO.v3SinavDersUniteLink L
												WHERE	L.KOD	= D1.KOD
													AND L.AKTIF = 1
												FOR JSON PATH, INCLUDE_NULL_VALUES
											),'[{"LINK":""}]')
							,DOSYASAYISI = (SELECT COUNT(1) FROM KazanimDosya KD WHERE KD.KOD = D1.KOD AND KD.AKTIF = 1)
							,SECILI = IIF(EXISTS(SELECT TOP 1 1 
												 FROM ZumreKazanim ZK 
												 JOIN ZumreBilgi   ZB ON ZB.ID_ZUMRE = ZK.ID_ZUMRE
												 WHERE ZK.ID_KAZANIM = D1.ID_DERSUNITE AND ZB.BAS_TARIH = @BAS_TARIH AND ZB.BIT_TARIH = @BIT_TARIH) ,1,0)
							,ID_ZUMRE_KAZANIM = ISNULL((SELECT 
													Z.ID_ZUMRE_KAZANIM 
												FROM ZumreKazanim Z 
												JOIN ZumreBilgi ZZB ON ZZB.ID_ZUMRE = Z.ID_ZUMRE
												WHERE Z.ID_KAZANIM =D1.ID_DERSUNITE AND Z.SECILI = 1 AND ZZB.ID_KADEME3 = @ID_KADEME3 AND ZZB.ID_DERS = @ID_DERS AND ZZB.BAS_TARIH = @BAS_TARIH AND ZZB.BIT_TARIH = @BIT_TARIH),0)
							,KAZANIM = ISNULL((
											SELECT  DISTINCT
												ZO.ID_ZUMRETUR
											   ,ZO.ID_ZUMREBILGILERI
											   ,ZO.ID_ZUMREOZELLIK
											   ,ICERIK = ISNULL(ZO.ICERIK,'')
											   ,DOSYA = ISNULL((SELECT ZOD.DOSYA_GUID FROM ZumreOzellikDosya ZOD WHERE ZOD.ID_ZUMREOZELLIK = ZO.ID_ZUMREOZELLIK 
																		FOR JSON PATH, INCLUDE_NULL_VALUES
																	),'[]')
											FROM ZumreBilgi					ZB
											JOIN ZumreOzellik				ZO ON ZO.ID_ZUMREBILGILERI = ZB.ID_ZUMRE
											WHERE ZB.ID_KADEME3 = @ID_KADEME3 AND ZB.ID_DERS = @ID_DERS AND ZB.BAS_TARIH = @BAS_TARIH AND ZB.BIT_TARIH = @BIT_TARIH
											ORDER BY ZO.ID_ZUMRETUR
											FOR JSON PATH, INCLUDE_NULL_VALUES
										),'[]')
					FROM v3SinavDersUnite		D1
					inner join v3SinavDers		SD  ON SD.ID_DERS = D1.ID_DERS
					WHERE SD.ID_KADEME3=@ID_KADEME3 AND  D1.ID_DERS = @ID_DERS AND D1.AKTIF=1
					ORDER BY d1.KOD
					FOR JSON PATH
					), '[]')
			END

			IF @ISLEM = 3  -- Zümre Kaydet
			BEGIN
				DECLARE @ID_ZUMRELIST TABLE (ID_ZUMRE INT)
				DECLARE @KAZANIM_LIST TABLE (ID_KAZANIM INT)


				DECLARE @KAZANIM_ANALIZ	INT = NULL, @OGRETIM_YONTEM INT = NULL,@KAYNAK_KITAP INT = NULL,@ATASOZ_DEYIM INT= NULL,@OKUMA_KITAP INT=NULL, @DEGERELEN_BILINC INT = NULL,
				 @HAFTANIN_ARASTIRMASI INT = NULL, @BELIRLI_GUN INT= NULL, @HAFTANIN_ODEVI INT = NULL

				CREATE TABLE #ODEV(ICERIK1 INT, ICERIK2 INT, ICERIK3 INT, ICERIK4 INT, ICERIK5 INT, ICERIK6 INT, ICERIK7 INT, ICERIK8 INT, ICERIK9 INT, ICERIK10 INT, ICERIK11 INT, ICERIK12 INT, ICERIK13 INT, ICERIK14 INT, ICERIK15 INT)

				 INSERT INTO ZumreBilgi (ID_KADEME3, ID_DERS,BAS_TARIH,BIT_TARIH,KYE_TCKIMLIKNO)
				 OUTPUT INSERTED.ID_ZUMRE INTO @ID_ZUMRELIST(ID_ZUMRE)
				 VALUES(@ID_KADEME3,@ID_DERS,@BAS_TARIH,@BIT_TARIH,@TCKIMLIKNO)			

				 SET @ID_ZUMRE = (select TOP 1 ID_ZUMRE from @ID_ZUMRELIST)

				 INSERT INTO  ZumreKazanim(ID_ZUMRE,ID_KAZANIM,SECILI)
				 SELECT @ID_ZUMRE,ID_DERSUNITE,SECILI
				 FROM OPENJSON(@HAFTANIN_KAZANIMI)
				 WITH
				 (
					SECILI BIT,
					ID_DERSUNITE INT
				 ) AS J WHERE J.SECILI = 1

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK1)
				 SELECT @ID_ZUMRE, 10,ICERIK1
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK1 VARCHAR(MAX)
				 ) AS J WHERE ICERIK1 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK2)
				 SELECT @ID_ZUMRE, 10,ICERIK2
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK2 VARCHAR(MAX)
				 ) AS J WHERE ICERIK2 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK3)
				 SELECT @ID_ZUMRE, 10,ICERIK3
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK3 VARCHAR(MAX)
				 ) AS J WHERE ICERIK3 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK4)
				 SELECT @ID_ZUMRE, 10,ICERIK4
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK4 VARCHAR(MAX)
				 ) AS J WHERE ICERIK4 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK5)
				 SELECT @ID_ZUMRE, 10,ICERIK5
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK5 VARCHAR(MAX)
				 ) AS J WHERE ICERIK5 != ''

				 
				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK6)
				 SELECT @ID_ZUMRE, 10,ICERIK6
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK6 VARCHAR(MAX)
				 ) AS J WHERE ICERIK6 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK7)
				 SELECT @ID_ZUMRE, 10,ICERIK7
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK7 VARCHAR(MAX)
				 ) AS J WHERE ICERIK7 != ''

				 
				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK8)
				 SELECT @ID_ZUMRE, 10,ICERIK8
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK8 VARCHAR(MAX)
				 ) AS J WHERE ICERIK8 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK9)
				 SELECT @ID_ZUMRE, 10,ICERIK9
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK9 VARCHAR(MAX)
				 ) AS J WHERE ICERIK9 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK10)
				 SELECT @ID_ZUMRE, 10,ICERIK10
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK10 VARCHAR(MAX)
				 ) AS J WHERE ICERIK10 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK11)
				 SELECT @ID_ZUMRE, 10,ICERIK11
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK11 VARCHAR(MAX)
				 ) AS J WHERE ICERIK11 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK12)
				 SELECT @ID_ZUMRE, 10,ICERIK12
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK12 VARCHAR(MAX)
				 ) AS J WHERE ICERIK12 != ''
				 
				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK13)
				 SELECT @ID_ZUMRE, 10,ICERIK13
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK13 VARCHAR(MAX)
				 ) AS J WHERE ICERIK13 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK14)
				 SELECT @ID_ZUMRE, 10,ICERIK14
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK14 VARCHAR(MAX)
				 ) AS J WHERE ICERIK14 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO #ODEV(ICERIK15)
				 SELECT @ID_ZUMRE, 10,ICERIK15
				 FROM OPENJSON(@ODEV)
				 WITH
				 (
				 ICERIK15 VARCHAR(MAX)
				 ) AS J WHERE ICERIK15 != ''

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR KAZIM ANALİZ
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,2 ,[KAZANIM_ANALIZ]  
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[KAZANIM_ANALIZ] [varchar](MAX)
				 
				 ) AS J 


				 
				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR OGRETIM YONTEM 
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,3 ,[OGRETIM_YONTEM] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[OGRETIM_YONTEM] [varchar](MAX)
				 
				 ) AS J 

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR KAYNAK_KITAP
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,4 ,[KAYNAK_KITAP] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[KAYNAK_KITAP] [varchar](MAX)
				 
				 ) AS J

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR ATASOZ_DEYIM
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,5 ,[ATASOZ_DEYIM] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[ATASOZ_DEYIM] [varchar](MAX)
				 
				 ) AS J 

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR OKUMA_KITAP
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,6 ,[OKUMA_KITAP] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[OKUMA_KITAP] [varchar](MAX)
				 
				 ) AS J 

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR DEGERELEN_BILINC
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,7 ,[DEGERELEN_BILINC] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[DEGERELEN_BILINC] [varchar](MAX)
				 
				 ) AS J 

				 INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR HAFTANIN_ARASTIRMASI
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,8 ,[HAFTANIN_ARASTIRMASI] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[HAFTANIN_ARASTIRMASI] [varchar](MAX)
				 
				 ) AS J 

				  INSERT INTO ZumreOzellik (ID_ZUMREBILGILERI,ID_ZUMRETUR,ICERIK)	-- ZÜMRE TÜR BELIRLI_GUN
				 OUTPUT INSERTED.ID_ZUMREOZELLIK INTO @KAZANIM_LIST(ID_KAZANIM)
				 select		@ID_ZUMRE ,9 ,[BELIRLI_GUN] 
				 from OPENJSON(@SQLJSON)
				 with
				 (					
				 	[BELIRLI_GUN] [varchar](MAX)
				 
				 ) AS J 

				  SELECT ISNULL((
					SELECT DISTINCT
					    ID_ZUMREOZELLIK
					   ,ICERIK
					   ,ID_ZUMRETUR
					   ,ODEV = (SELECT ISNULL((SELECT * FROM #ODEV FOR JSON AUTO),'[]' ))
				     FROM ZumreOzellik WHERE ID_ZUMREBILGILERI = @ID_ZUMRE
					FOR JSON AUTO
				),'[]')		

			END

			IF @ISLEM = 4  -- Zumre Dosya Kaydet 
			BEGIN
					
					

				
				
					INSERT INTO ZumreOzellikDosya (ID_ZUMREOZELLIK,DOSYA_GUID,AD)
					SELECT @ID_ZUMRE_OZELLIK, GUID,AD
					FROM OPENJSON(@DOSYALIST,'$.DOSYA')
					WITH(
						GUID	VARCHAR(MAX),
						AD		VARCHAR(MAX)
					) 
				
				SELECT ISNULL((
					SELECT  
						ZO.ICERIK	
					FROM ZumreBilgi				ZB
					JOIN ZumreOzellik			ZO	ON ZO.ID_ZUMREBILGILERI = ZB.ID_ZUMRE
					JOIN ZumreOzellikDosya		ZOD ON ZOD.ID_ZUMREOZELLIK  = ZO.ID_ZUMREOZELLIK
					WHERE ZO.ID_ZUMREOZELLIK = @ID_ZUMRE_OZELLIK
					FOR JSON PATH, INCLUDE_NULL_VALUES
				),'[]')
			END
		    
			IF @ISLEM = 5  -- Zumre Güncelle
			BEGIN 
			

				 UPDATE ZumreBilgi SET ID_KADEME3 = @ID_KADEME3, ID_DERS = @ID_DERS,BAS_TARIH = @BAS_TARIH,BIT_TARIH = @BIT_TARIH,KYE_TCKIMLIKNO=@TCKIMLIKNO
				 WHERE ID_ZUMRE = @ID_ZUMRE
				 

				 UPDATE U									-- ZÜMRE TÜR KAZANIM ANALİZ
				 SET U.ICERIK = J.KAZANIM_ANALIZ
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_KAZANIM_ANALIZ INT,
				 [KAZANIM_ANALIZ] [varchar](MAX)
				 ) AS J ON J.ID_KAZANIM_ANALIZ = U.ID_ZUMREOZELLIK

				  UPDATE U									-- ZÜMRE TÜR KAZANIM ANALİZ
				 SET U.ICERIK = J.OGRETIM_YONTEM
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_OGRETIM_YONTEM INT,
				 [OGRETIM_YONTEM] [varchar](MAX)
				 ) AS J ON J.ID_OGRETIM_YONTEM = U.ID_ZUMREOZELLIK

				 UPDATE U									--  ZÜMRE TÜR KAYNAK_KITAP
				 SET U.ICERIK = J.KAYNAK_KITAP
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_KAYNAK_KITAP INT,
				 [KAYNAK_KITAP] [varchar](MAX)
				 ) AS J ON J.ID_KAYNAK_KITAP = U.ID_ZUMREOZELLIK

				  UPDATE U									-- ZÜMRE TÜR ATASOZ_DEYIM
				 SET U.ICERIK = J.ATASOZ_DEYIM
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_ATASOZ_DEYIM INT,
				 [ATASOZ_DEYIM] [varchar](MAX)
				 ) AS J ON J.ID_ATASOZ_DEYIM = U.ID_ZUMREOZELLIK

				   UPDATE U											-- ZÜMRE TÜR OKUMA_KITAP
				 SET U.ICERIK = J.OKUMA_KITAP
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_OKUMA_KITAP INT,
				 [OKUMA_KITAP] [varchar](MAX)
				 ) AS J ON J.ID_OKUMA_KITAP = U.ID_ZUMREOZELLIK

				 UPDATE U										  -- ZÜMRE TÜR DEGERELEN_BILINC
				 SET U.ICERIK = J.DEGERELEN_BILINC
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_DEGERELEN_BILINC INT,
				 [DEGERELEN_BILINC] [varchar](MAX)
				 ) AS J ON J.ID_DEGERELEN_BILINC = U.ID_ZUMREOZELLIK

				 UPDATE U										 -- ZÜMRE TÜR HAFTANIN_ARASTIRMASI
				 SET U.ICERIK = J.HAFTANIN_ARASTIRMASI
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_HAFTANIN_ARASTIRMASI INT,
				 [HAFTANIN_ARASTIRMASI] [varchar](MAX)
				 ) AS J ON J.ID_HAFTANIN_ARASTIRMASI = U.ID_ZUMREOZELLIK

				 UPDATE U												-- ZÜMRE TÜR BELIRLI_GUN
				 SET U.ICERIK = J.BELIRLI_GUN
				 FROM ZumreOzellik AS U
				 JOIN OPENJSON(@SQLJSON)
				 WITH (
				 ID_BELIRLI_GUN INT,
				 [BELIRLI_GUN] [varchar](MAX)
				 ) AS J ON J.ID_BELIRLI_GUN = U.ID_ZUMREOZELLIK
					
				--UPDATE U 
				--SET U.ID_KAZANIM = J.ID_DERSUNITE, U.SECILI = J.SECILI
				--FROM ZumreKazanim AS U
				--JOIN OPENJSON(@HAFTANIN_KAZANIMI)
				--WITH
				--(
				--	SECILI BIT,
				--	ID_DERSUNITE INT
				--) AS J ON J.SECILI = 0 AND J.ID_DERSUNITE = U.ID_KAZANIM AND U.ID_ZUMRE_KAZANIM = @ID_HAFTANIN_KAZANIMI
				
				CREATE TABLE #ZumreKazanim (ID_ZUMRE_KAZANIM INT)
				
				INSERT INTO #ZumreKazanim (ID_ZUMRE_KAZANIM)
				SELECT ID_ZUMRE_KAZANIM
				FROM OPENJSON(@HAFTANIN_KAZANIMI)
				WITH
				(
					ID_ZUMRE_KAZANIM INT,
					SECILI BIT
				) AS J WHERE J.SECILI = 0 

				DELETE FROM ZumreKazanim WHERE ID_ZUMRE_KAZANIM IN (SELECT ID_ZUMRE_KAZANIM FROM #ZumreKazanim)				


				 INSERT INTO  ZumreKazanim(ID_ZUMRE,ID_KAZANIM,SECILI)
				 SELECT @ID_ZUMRE,ID_DERSUNITE,SECILI
				 FROM OPENJSON(@HAFTANIN_KAZANIMI)
				 WITH
				 (
					SECILI BIT,
					ID_DERSUNITE INT,
					ID_ZUMRE_KAZANIM INT
				 ) AS J WHERE J.SECILI = 1 AND J.ID_ZUMRE_KAZANIM < 1

				  SELECT ISNULL((
					SELECT DISTINCT
					    ID_ZUMREOZELLIK
					   ,ICERIK
					   ,ID_ZUMRETUR
					 FROM ZumreOzellik WHERE ID_ZUMREBILGILERI = @ID_ZUMRE
					FOR JSON AUTO
				),'[]')	
			
			END

			IF @ISLEM = 6  -- DOSYA DETAY GÖR
			BEGIN
				SELECT ISNULL((
					SELECT 
						 DOSYA_GUID
						,AD
						,ID_ZUMREOZELLIKDOSYA
					FROM ZumreOzellikDosya			ZOD
					WHERE ZOD.ID_ZUMREOZELLIK = @ID_DOSYA
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 7  -- DOSYA SİL
			BEGIN
				SELECT @ID_DOSYA = ID_ZUMREOZELLIK  FROM ZumreOzellikDosya WHERE ID_ZUMREOZELLIKDOSYA = @ID_ZUMREOZELLIKDOSYA
				DELETE FROM ZumreOzellikDosya WHERE ID_ZUMREOZELLIKDOSYA = @ID_ZUMREOZELLIKDOSYA

				SELECT ISNULL((
					SELECT 
						 DOSYA_GUID
						,AD
						,ID_ZUMREOZELLIKDOSYA
					FROM ZumreOzellikDosya			ZOD
					WHERE ZOD.ID_ZUMREOZELLIK = @ID_DOSYA
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 8  -- Log Kaydet
			BEGIN
				INSERT INTO ZumreLog (ID_ZUMRE_TUR,SECILI,TCKIMLIKNO,BAS_TARIH,BIT_TARIH) VALUES (@ID_ZUMRE_TUR, 1,@TCKIMLIKNO,@BAS_TARIH,@BIT_TARIH)
			END
			
			IF @ISLEM = 9  -- Log Listele
			BEGIN
				SELECT ISNULL ((
							SELECT 
								 TUR=ZT.AD 
								,TOPLAM=SUM(ZL.SECILI) 
								,TCKIMLIKNO=ZL.TCKIMLIKNO
								,AD=K.AD + ' ' + K.SOYAD
							FROM ZumreLog			ZL
							JOIN ZumreTur			ZT ON ZT.ID_ZUMRETUR = ZL.ID_ZUMRE_TUR
							JOIN v3Kullanici		K  ON K.TCKIMLIKNO   = ZL.TCKIMLIKNO  
							WHERE ZL.BAS_TARIH = @BAS_TARIH AND ZL.BIT_TARIH = @BIT_TARIH
							GROUP BY ZT.AD,ZL.TCKIMLIKNO,K.AD,K.SOYAD
							FOR JSON PATH, INCLUDE_NULL_VALUES
				),'[]')
			END

			IF @ISLEM = 10 --  Sınıf
			BEGIN
				select distinct 					   
					   SGS.ID_KADEME3					  
					   ,AD = SGS.KADEME3
				  from eokul_v2.dbo.DersOgretmen do
			 left join OkyanusDB.dbo.v3Kullanici pb on pb.TCKIMLIKNO=do.TC_OGRETMEN
			 inner join eokul_v2.dbo.Ders   d on d.ID_DERS=do.ID_DERS
			 INNER JOIN OkyanusDB.dbo.v3Ogretmen O ON O.ID_OGRETMEN = do.ID_OGRETMEN
			 left join OKYANUSDB.DBO.V3EgitimTuru e on e.ID_EGITIMTURU=do.ID_EGITIMTURU
			 JOIN OkyanusDB.dbo.vw_SubeGrupSinif SGS ON SGS.ID_SINIF = DO.ID_SINIF
	   			 WHERE 	DONEMKOD='2020' 
				 --pb.TCKIMLIKNO = @TCKIMLIKNO
				   AND d.AKTIF=1
				   AND SGS.ID_KADEME3 IN (7,8,9,10) AND SGS.SINIF NOT LIKE 'ÜZİ%'
				ORDER BY AD
			END	

			IF @ISLEM = 11 -- Öğretmen Ders Getir
			BEGIN 
				DECLARE @BASKAN  BIT = 0, @OGRETMEN BIT = 0

					SELECT DISTINCT
					    @OGRETMEN = ISNULL((SELECT TOP 1 1 FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO AND ID_KULLANICITIPI = 3),0)
					   ,@BASKAN	 = ISNULL((SELECT TOP 1 1  FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO AND (ID_KULLANICITIPI = 27 OR ID_KULLANICITIPI = 59)),0)
					 FROM OkyanusDB.dbo.vw_KullaniciYetki WHERE TCKIMLIKNO = @TCKIMLIKNO



					 IF @BASKAN = 1 
					 BEGIN
						SELECT d.ID_DERS, d.AD FROM [dbo].[v3SinavDers] d where d.ID_KADEME3=@ID_KADEME3 
					 END 

					IF @OGRETMEN = 1 
					BEGIN
						select distinct 
							 do.ID_DERS,
							 AD=d.DERSAD
					   from eokul_v2.dbo.DersOgretmen do
					   left join OkyanusDB.dbo.v3Kullanici pb on pb.TCKIMLIKNO=do.TC_OGRETMEN
					   inner join eokul_v2.dbo.Ders d on d.ID_DERS=do.ID_DERS
					   INNER JOIN OkyanusDB.dbo.v3Ogretmen O ON O.ID_OGRETMEN = do.ID_OGRETMEN
					   left join OKYANUSDB.DBO.V3EgitimTuru e on e.ID_EGITIMTURU=do.ID_EGITIMTURU
					   JOIN OkyanusDB.dbo.vw_SubeGrupSinif SGS ON SGS.ID_SINIF = DO.ID_SINIF
	   				   	 WHERE 	DONEMKOD= (SELECT DONEM FROM OkyanusDB.dbo.v3AktifDonem WHERE AKTIF = 1)
					   	 AND pb.TCKIMLIKNO = @TCKIMLIKNO
					   	   AND d.AKTIF=1
					   	   AND SGS.ID_KADEME3 = @ID_KADEME3 AND SGS.SINIF NOT LIKE 'ÜZİ%'
					    order by d.DERSAD
					END
				
			END

		END
	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @_ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END
GO
PRINT N'Reenabling DDL triggers...'
GO
ENABLE TRIGGER [CaptureStoredProcedureChanges] ON DATABASE
GO
PRINT N'Update complete.';


GO




INSERT INTO ZumreTur (AD)VALUES('Haftanın Kazanımı')
INSERT INTO ZumreTur (AD)VALUES('Kazanım Analiz Etkinlik')
INSERT INTO ZumreTur (AD)VALUES('Ögretim Yöntem Tekniği')
INSERT INTO ZumreTur (AD)VALUES('Kaynak Kitap Sayfa Aralığı')
INSERT INTO ZumreTur (AD)VALUES('Haftanın Atasözü ve Deyimi')
INSERT INTO ZumreTur (AD)VALUES('Okuma Kitabı')
INSERT INTO ZumreTur (AD)VALUES('Değerlen Bilinci')
INSERT INTO ZumreTur (AD)VALUES('Haftanın Araştırması')
INSERT INTO ZumreTur (AD)VALUES('Belirli Gün ve Haftalar')
INSERT INTO ZumreTur (AD)VALUES('Haftanın Ödevi')
