USE [Pusulam]
GO
/****** Object:  StoredProcedure [dbo].[sp_v2FrekansSistem]    Script Date: 9.11.2020 13:54:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[sp_v2FrekansSistem]
	@ISLEM				INT				= NULL,
	@TCKIMLIKNO			VARCHAR(11)		= NULL,
	@TC_OGRENCI			VARCHAR(11)		= NULL,
	@TC_OGRETMEN		VARCHAR(11)		= NULL,
	@OTURUM				VARCHAR(36)		= NULL,
	@ID_MENU			INT				= NULL,
	@DONEM				char(4)			= NULL,
	@ID_KADEMEs			VARCHAR(MAX)	= NULL,
	@ID_KADEME3			VARCHAR(MAX)	= NULL,
	@ID_SINAVTURU		VARCHAR(MAX)	= NULL,	
	@ID_SUBE			VARCHAR(MAX)	= NULL,
	@ID_SINIF			INT				= NULL,		
	@DERSLIST			VARCHAR(MAX)	= NULL,
	@DERSAD				VARCHAR(MAX)	= NULL,
	@FREKANSKARNE		BIT				= 0	,
	@RAPOR_DONUS_TIP    BIT				= 0
AS
BEGIN
	
	DECLARE
	@_ISLEM				INT				= @ISLEM			,
	@_TCKIMLIKNO		VARCHAR(11)		= @TCKIMLIKNO		,
	@_TC_OGRENCI		VARCHAR(11)		= @TC_OGRENCI		,
	@_TC_OGRETMEN		VARCHAR(11)		= @TC_OGRETMEN		,
	@_OTURUM			VARCHAR(36)		= @OTURUM			,
	@_ID_MENU			INT				= @ID_MENU			,
	@_DONEM				char(4)			= @DONEM			,
	@_ID_KADEMEs		VARCHAR(MAX)	= @ID_KADEMEs		,
	@_ID_KADEME3		VARCHAR(MAX)	= @ID_KADEME3		,
	@_ID_SINAVTURU		VARCHAR(MAX)	= @ID_SINAVTURU		,	
	@_ID_SUBE			VARCHAR(MAX)	= @ID_SUBE			,
	@_ID_SINIF			INT				= @ID_SINIF			,		
	@_DERSLIST			VARCHAR(MAX)	= @DERSLIST			,
	@_DERSAD			VARCHAR(MAX)	= @DERSAD			,
	@_FREKANSKARNE		BIT				= @FREKANSKARNE		,
	@_RAPOR_DONUS_TIP   BIT				= @RAPOR_DONUS_TIP

	DECLARE @_PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @_LOGJSON VARCHAR(MAX)
	SET @_LOGJSON = (
		SELECT	 ISLEM				= @_ISLEM				
				,TCKIMLIKNO			= @_TCKIMLIKNO			
				,TC_OGRENCI			= @_TC_OGRENCI			
				,TC_OGRETMEN		= @_TC_OGRETMEN	
				,OTURUM				= @_OTURUM				
				,ID_MENU			= @_ID_MENU		
				,DONEM				= @_DONEM				
				,ID_KADEMEs			= @_ID_KADEMEs			
				,ID_KADEME3			= @_ID_KADEME3			
				,ID_SINAVTURU		= @_ID_SINAVTURU		
				,ID_SUBE			= @_ID_SUBE		
				,ID_SINIF			= @_ID_SINIF		
				,DERSLIST			= @_DERSLIST		
				,DERSAD				= @_DERSAD			
				,FREKANSKARNE		= @_FREKANSKARNE		
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @_ID_LOG INT = 0

	BEGIN TRY    
	
		EXEC @_ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @_OTURUM, @TCKIMLIKNO = @_TCKIMLIKNO, @ID_MENU = @_ID_MENU, @LOGJSON = @_LOGJSON, @ISLEM = @_ISLEM, @PROSEDURADI = @_PROCNAME
		
		IF @_ID_LOG > 0
		BEGIN
			
			DECLARE @_ID_STGENEL INT=999999

			IF @_DONEM='' OR @_DONEM IS NULL			
				SET @_DONEM= (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)			

				
			SELECT DISTINCT ID_SUBE INTO #SUBELER FROM v3SubeYetki WHERE TCKIMLIKNO = @_TCKIMLIKNO AND ID_KULLANICITIPI NOT IN (4,5)

			IF @_ISLEM NOT IN (6,7,8)
			BEGIN
				--	INTO #SINAVTURU
				--DECLARE @_SINAVTURU TABLE(ID_SINAVTURU INT,AD VARCHAR(MAX),KISAAD VARCHAR(MAX),AKTIF BIT,SIRA INT)
				--INSERT INTO @_SINAVTURU (ID_SINAVTURU,AD,KISAAD,AKTIF,SIRA) VALUES(0,'YAZILI','YAZ',1,0)
				--INSERT INTO @_SINAVTURU SELECT ID_SINAVTURU,AD,KISAAD,AKTIF,1 FROM SinavTuru
				--SELECT * INTO #SINAVTURU FROM @_SINAVTURU

				SELECT ID_SINAVTURU,AD,KISAAD,AKTIF,1 AS SIRA INTO #SINAVTURU FROM SinavTuru
				SET IDENTITY_INSERT #SINAVTURU ON
				-- 2,3,4,5
					
				
					select	 F.ID_FREKANSOGRENCIDETAY
							,F.DERSAD
							,F.SUBEAD
							,F.OGRETMENADSOYAD
							,F.TC_OGRETMEN
							,F.ID_SUBE
							,F.ID_SINAVTURU
							,F.FREKANS
							,F.HBNET
							,F.ILK_SS
							,F.ID_KADEME3
							,F.TC_OGRENCI
							,F.ID_SINIF
							,F.TAKMAAD
							,F.SINIFAD
							,F.NET
							,F.ID_SINAV
							,F.ILK_NET
							,F.SS
							,F.DONEM
							,F.ID_DERS
							,kb.ID_KADEME 
				into #v2FrekansOgrenciDetayDonem 
				from v2FrekansOgrenciDetay			F
				join OkyanusDB.dbo.v3KademeBilgi	kb	on	kb.ID_KADEME3	= F.ID_KADEME3
				where	DONEM = @_DONEM 
					AND (TC_OGRETMEN IS NOT NULL AND TC_OGRETMEN <> '')
				-- 1,2,3,4,5,6
			END
		
			
			IF @_ISLEM IN (1,2)
			BEGIN
				
				DECLARE @ID_FREKANSSORGU	 INT = NULL
				DECLARE @ID_FREKANSSORGUDERS INT = NULL
					
				SET @ID_FREKANSSORGU	= (	SELECT ID_FREKANSSORGU 
											FROM v2FrekansSorgu 
											WHERE	DONEM			= @_DONEM 
												AND ID_SINAVTURULIST= @_ID_SINAVTURU 
												AND ID_KADEME3LIST	= @_ID_KADEME3
												AND DERSLIST		IS NULL
										)				
				IF @ID_FREKANSSORGU IS NULL		
				BEGIN
					DECLARE @TABLEADD TABLE (ID INT)

					INSERT INTO v2FrekansSorgu (DONEM, ID_SINAVTURULIST, ID_KADEME3LIST, DERSLIST) 
					OUTPUT inserted.ID_FREKANSSORGU INTO @TABLEADD(ID)
					VALUES (@_DONEM , @_ID_SINAVTURU, @_ID_KADEME3, NULL)

					SET @ID_FREKANSSORGU = (SELECT TOP 1 ID FROM @TABLEADD)

					INSERT INTO v2FrekansSorguDetay (ID_FREKANSSORGU , ID_FREKANSOGRENCIDETAY)--, ID_SINAVTURU, TC_OGRETMEN, DERSAD, ID_SUBE, FREKANS)
					SELECT @ID_FREKANSSORGU , ID_FREKANSOGRENCIDETAY
					FROM v2FrekansOgrenciDetay WITH(NOLOCK) 
					WHERE	(ID_SINAVTURU	IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU	)) )--OR  -1	IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU	))
						AND (ID_KADEME3		IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3	)) )--OR  0	IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3	))
						AND DONEM = @_DONEM
					ORDER BY FREKANS

				END

				SET @ID_FREKANSSORGUDERS= (	SELECT ID_FREKANSSORGU 
											FROM v2FrekansSorgu 
											WHERE	DONEM			= @_DONEM 
												AND ID_SINAVTURULIST= @_ID_SINAVTURU 
												AND ID_KADEME3LIST	= @_ID_KADEME3
												AND (DERSLIST		= @_DERSLIST  OR (@_DERSLIST IS NULL AND DERSLIST IS NULL) )
										)
				IF @ID_FREKANSSORGUDERS IS NULL	
				BEGIN
					DELETE FROM @TABLEADD 
					INSERT INTO v2FrekansSorgu (DONEM, ID_SINAVTURULIST, ID_KADEME3LIST, DERSLIST) 
					OUTPUT INSERTED.ID_FREKANSSORGU INTO @TABLEADD(ID)
					VALUES (@_DONEM , @_ID_SINAVTURU, @_ID_KADEME3, @_DERSLIST)

					SET @ID_FREKANSSORGUDERS = (SELECT TOP 1 ID FROM @TABLEADD)

					INSERT INTO v2FrekansSorguDetay (ID_FREKANSSORGU , ID_FREKANSOGRENCIDETAY)--, ID_SINAVTURU, TC_OGRETMEN, DERSAD, ID_SUBE, FREKANS)
					SELECT @ID_FREKANSSORGUDERS , S.ID_FREKANSOGRENCIDETAY
					FROM v2FrekansSorguDetay	S
					JOIN v2FrekansOgrenciDetay	T WITH(NOLOCK) 	ON	T.ID_FREKANSOGRENCIDETAY = S.ID_FREKANSOGRENCIDETAY
					WHERE	(DERSAD			IN	(SELECT VALUE FROM OPENJSON( @_DERSLIST		)) OR  'Tümü'	IN	(SELECT VALUE FROM OPENJSON( @_DERSLIST		)))
						AND S.ID_FREKANSSORGU	= @ID_FREKANSSORGU
						AND DONEM				= @_DONEM
					ORDER BY FREKANS

				END

			END

			
			IF @_ISLEM = 1	--	İLK LİSTE (FR SİSTEM)		
			BEGIN 
		
				SET @_DERSAD = CASE WHEN (SELECT COUNT(VALUE) FROM OPENJSON( @_DERSLIST)) = 1 THEN  (SELECT TOP 1 VALUE FROM OPENJSON( @_DERSLIST)) ELSE 'Tümü' END

				SELECT	 
						 DERSAD
						,SUBEAD
						,OGRETMENADSOYAD
						,TC_OGRETMEN
						,T.ID_SUBE
						,ID_SINAVTURU
						,ID_KADEME3
				INTO #Filtre 
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				JOIN #SUBELER						S	ON	S.ID_SUBE				= T.ID_SUBE
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGUDERS
					AND (T.ID_SUBE		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)) OR  0		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)))
				GROUP BY TC_OGRETMEN, DERSAD, SUBEAD, OGRETMENADSOYAD, T.ID_SUBE, SUBEAD,ID_SINAVTURU,ID_KADEME3


				SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, FREKANS = CONVERT(DECIMAL(18, 2), AVG(D.FREKANS)), HBNET =  CONVERT(DECIMAL(18, 2), AVG(D.HBNET)), SORUSAYISI = CONVERT(DECIMAL(18, 2), AVG(D.ILK_SS))
				INTO #FiltreFrekans FROM #Filtre	O
				INNER JOIN #v2FrekansOgrenciDetayDonem	D	ON D.TC_OGRETMEN = O.TC_OGRETMEN AND D.DERSAD = O.DERSAD AND D.ID_SUBE = O.ID_SUBE AND D.ID_SINAVTURU = O.ID_SINAVTURU AND D.ID_KADEME3 = O.ID_KADEME3
				GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD
				ORDER BY O.OGRETMENADSOYAD


				-- Öğretmen Genel
				SELECT TC_OGRETMEN, DERSAD, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
				INTO #GenelFrekans 
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
				GROUP BY TC_OGRETMEN, DERSAD

				DECLARE @_GENELADET INT = (SELECT COUNT(DISTINCT TC_OGRETMEN) FROM #GenelFrekans)

				SELECT *, SN = ROW_NUMBER() OVER (/*PARTITION BY DERSAD*/  ORDER BY FREKANS DESC)
				INTO #GenelSira FROM #GenelFrekans
				WHERE FREKANS IS NOT NULL
				--------------------------------------------------------------------

				-- Öğretmen Zümre Genel
				SELECT TC_OGRETMEN, DERSAD, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
				INTO #GenelZumreFrekans 
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
				GROUP BY TC_OGRETMEN, DERSAD


				SELECT *, SN = ROW_NUMBER() OVER (PARTITION BY DERSAD ORDER BY FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelZumreFrekans G WHERE G.DERSAD = F.DERSAD)
				INTO #GenelZumreSira FROM #GenelZumreFrekans	F
				WHERE FREKANS IS NOT NULL
				--------------------------------------------------------------------

				-- Öğretmen Kampus Genel
				SELECT TC_OGRETMEN, ID_SUBE, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
				INTO #GenelKampusFrekans 
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
				GROUP BY TC_OGRETMEN, ID_SUBE


				SELECT F.*, SN = ROW_NUMBER() OVER (PARTITION BY F.ID_SUBE ORDER BY F.FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelKampusFrekans G WHERE G.ID_SUBE = F.ID_SUBE), SUBEAD = S.AD
				INTO #GenelKampusSira FROM #GenelKampusFrekans	F
				INNER JOIN V3Sube	S ON S.ID_SUBE = F.ID_SUBE
				WHERE F.FREKANS IS NOT NULL
				--------------------------------------------------------------------

				-- Öğretmen Zümre Kampus Genel
				SELECT TC_OGRETMEN, ID_SUBE, DERSAD, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
				INTO #GenelZumreKampusFrekans 
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
				GROUP BY TC_OGRETMEN, ID_SUBE, DERSAD

				SELECT F.*, SN = ROW_NUMBER() OVER (PARTITION BY F.ID_SUBE, F.DERSAD ORDER BY F.FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelZumreKampusFrekans G WHERE G.ID_SUBE = F.ID_SUBE AND G.DERSAD = F.DERSAD), SUBEAD = S.AD
				INTO #GenelZumreKampusSira FROM #GenelZumreKampusFrekans	F
				INNER JOIN V3Sube	S ON S.ID_SUBE = F.ID_SUBE
				WHERE F.FREKANS IS NOT NULL
				--------------------------------------------------------------------


				SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, OGRSAY = COUNT(DISTINCT D.TC_OGRENCI) , SINIFSAY = COUNT(DISTINCT D.ID_SINIF) 
				INTO #OgrenciSinifListe 
				FROM #Filtre					O
				INNER JOIN #v2FrekansOgrenciDetayDonem	D	ON D.TC_OGRETMEN = O.TC_OGRETMEN AND D.DERSAD = O.DERSAD AND D.ID_SUBE = O.ID_SUBE AND D.ID_SINAVTURU = O.ID_SINAVTURU AND D.ID_KADEME3 = O.ID_KADEME3
				GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD

				-- Liste
				SELECT   [SIRA]				= F.FREKANS--ISNULL(G.SN,@_ID_STGENEL) --CASE WHEN @_DERSAD = 'Tümü' THEN ISNULL(G.SN,@_ID_STGENEL) ELSE (SELECT MIN(SN) FROM #GenelZumreSira K WHERE K.TC_OGRETMEN=F.TC_OGRETMEN AND K.DERSAD=@_DERSAD )   END
						,[BRANŞ]			= F.DERSAD 
						,[KAMPÜS]			= ISNULL( (SELECT STUFF((SELECT   '<br>' +CAST(K.SUBEAD AS VARCHAR)	FROM #GenelKampusSira K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN ORDER BY K.SUBEAD FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'-')
						,[ÖĞRETMEN]			= F.OGRETMENADSOYAD 
						,[SORU SAYISI]		= SORUSAYISI
						,[HB NET]			= F.HBNET
						,[TC_OGRETMEN]		= F.TC_OGRETMEN
						,[FREKANS]			= ISNULL(CAST(F.FREKANS AS VARCHAR),'-')
						,[SINIF SAYISI]		= O.SINIFSAY
						,[ÖĞRENCİ SAYISI]	= O.OGRSAY
						,[KAMPÜS ZÜMRE]		= ISNULL( (SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelZumreKampusSira tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN  AND K.DERSAD = tt.DERSAD )>1 then k.SUBEAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelZumreKampusSira	K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN AND K.DERSAD = F.DERSAD ORDER BY K.SUBEAD FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'-')
						,[KAMPÜS GENEL]		= ISNULL( (SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelKampusSira		 tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN)>1 then k.SUBEAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelKampusSira		K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN ORDER BY K.SUBEAD FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'-')
						,[GENEL ZÜMRE]		= ISNULL( (SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelZumreSira		 tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN AND K.DERSAD = tt.DERSAD )>1 then k.DERSAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelZumreSira		K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN AND K.DERSAD = F.DERSAD FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'-')
						,[GENEL]			= ISNULL(CAST(G.SN AS VARCHAR) + ' / ' + CAST(@_GENELADET AS VARCHAR),'-')
					
				INTO		#T
				FROM		#FiltreFrekans		F
				INNER JOIN #OgrenciSinifListe	O ON O.TC_OGRETMEN = F.TC_OGRETMEN AND O.DERSAD = F.DERSAD
				LEFT  JOIN #GenelSira			G ON G.TC_OGRETMEN = F.TC_OGRETMEN AND G.DERSAD = F.DERSAD

				IF @RAPOR_DONUS_TIP=0
				BEGIN 
				select(
							select * from(
								select 
								(					
									SELECT		*
									FROM		#T 
									--ORDER BY [GENEL]--[ÖĞRETMEN]	,[GENEL]
									order by SIRA DESC
									FOR JSON AUTO
								) as t												
							) as tablo FOR JSON AUTO
						) as tt
				END
				ELSE
				BEGIN
				SELECT		*
									FROM		#T 
									--ORDER BY [GENEL]--[ÖĞRETMEN]	,[GENEL]
									order by SIRA DESC
				END
		
				
					
				DROP TABLE IF EXISTS #T
				DROP TABLE IF EXISTS #Filtre
				DROP TABLE IF EXISTS #FiltreFrekans
				DROP TABLE IF EXISTS #OgrenciSinifListe 

				DROP TABLE IF EXISTS #GenelFrekans
				DROP TABLE IF EXISTS #GenelSira

				DROP TABLE IF EXISTS #GenelZumreFrekans
				DROP TABLE IF EXISTS #GenelZumreSira

				DROP TABLE IF EXISTS #GenelKampusFrekans
				DROP TABLE IF EXISTS #GenelKampusSira

				DROP TABLE IF EXISTS #GenelZumreKampusFrekans
				DROP TABLE IF EXISTS #GenelZumreKampusSira

		


			END
			IF @_ISLEM = 2	--	GENEL SIRALAMA				
			BEGIN 

				SELECT	 [SINAV TÜRÜ]	= SINAVTURU
						,STKISAAD
						,[BRANŞ]		= BRANS
						,TC_OGRETMEN
						,FREKANS
						,[FREKANS KATKI]= FREKANSKATKI
						,[KAMPÜS KADEME ZÜMRE] = KAMPUSKADEMEZUMRE
						,[KAMPÜS ZÜMRE] = KAMPUSZUMRE
						,[KAMPÜS GENEL]	= KAMPUSGENEL
						,[KADEME ZÜMRE] = KADEMEZUMRE
						,[GENEL ZÜMRE]	= GENELZUMRE
						,GENEL
						,ID_SINAVTURU 
				INTO	#T1
				FROM	v2FrekansOgretmen
				WHERE	TC_OGRETMEN	= @_TC_OGRETMEN
					AND DONEM = @_DONEM
				


				-- frekans karne değil ise  veya (ders,sinav türü,sınıf)tümü seçilmemişse Frekansogretmendeki gösterecek
				IF (@_FREKANSKARNE=0 
					OR (	@_DERSAD <>	'Tümü' 					 
						AND -1	NOT IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU	)) 
						AND 0	NOT IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3	)) 					
						)
					)
				BEGIN
		
					SELECT	 ID_SINAVTURU
							,FREKANS = CONVERT(DECIMAL(18, 2), AVG(T.FREKANS))
					INTO #GenelFiltre2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
						AND (DERSAD		= @_DERSAD OR @_DERSAD = 'Tümü') 
						AND DONEM = @_DONEM
					GROUP BY ID_SINAVTURU


					SELECT	 
								DERSAD
							,SUBEAD
							,OGRETMENADSOYAD
							,TC_OGRETMEN
							,T.ID_SUBE
							,ID_SINAVTURU
							,ID_KADEME3
					INTO #Filtre2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					JOIN #SUBELER						S	ON	S.ID_SUBE	= T.ID_SUBE
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
						AND (DERSAD		= @_DERSAD OR @_DERSAD = 'Tümü') 
						AND (T.ID_SUBE		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)) OR  0		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)))
						AND TC_OGRETMEN	= @_TC_OGRETMEN
						AND DONEM = @_DONEM
					GROUP BY TC_OGRETMEN, DERSAD, SUBEAD, OGRETMENADSOYAD, T.ID_SUBE, SUBEAD,ID_SINAVTURU,ID_KADEME3


			
					SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, O.ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(D.FREKANS)), HBNET =  CONVERT(DECIMAL(18, 2), AVG(D.HBNET)), SORUSAYISI = CONVERT(DECIMAL(18, 2), AVG(D.ILK_SS))
					INTO #FiltreFrekans2 FROM #Filtre2	O
					INNER JOIN #v2FrekansOgrenciDetayDonem		D	ON D.TC_OGRETMEN = O.TC_OGRETMEN AND D.DERSAD = O.DERSAD AND D.ID_SUBE = O.ID_SUBE AND D.ID_SINAVTURU = O.ID_SINAVTURU AND D.ID_KADEME3 = O.ID_KADEME3
					GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, O.ID_SINAVTURU
				UNION ALL			
					SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(D.FREKANS)), HBNET =  CONVERT(DECIMAL(18, 2), AVG(D.HBNET)), SORUSAYISI = CONVERT(DECIMAL(18, 2), AVG(D.ILK_SS))
					FROM #Filtre2	O
					INNER JOIN #v2FrekansOgrenciDetayDonem		D	ON D.TC_OGRETMEN = O.TC_OGRETMEN AND D.DERSAD = O.DERSAD AND D.ID_SUBE = O.ID_SUBE AND D.ID_SINAVTURU = O.ID_SINAVTURU AND D.ID_KADEME3 = O.ID_KADEME3
					GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD
				ORDER BY O.OGRETMENADSOYAD



				-- Frekans Katkı İçin
					SELECT TC_OGRETMEN, ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS)), DERSAD
					INTO #GenelFrekansKatki 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
						AND (DERSAD		= @_DERSAD OR @_DERSAD = 'Tümü') 
					GROUP BY TC_OGRETMEN, ID_SINAVTURU, DERSAD
				UNION ALL				
					SELECT TC_OGRETMEN, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS)), DERSAD
					FROM #v2FrekansOgrenciDetayDonem	T
					WHERE  (DERSAD	= @_DERSAD OR @_DERSAD = 'Tümü') 						
					GROUP BY TC_OGRETMEN, DERSAD

					-- Öğretmen Genel
					SELECT TC_OGRETMEN, ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					INTO #GenelFrekans2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, ID_SINAVTURU
				UNION ALL				
					SELECT TC_OGRETMEN, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					FROM #v2FrekansOgrenciDetayDonem	T			
					GROUP BY TC_OGRETMEN

					SELECT *, SN = ROW_NUMBER() OVER (PARTITION BY ID_SINAVTURU ORDER BY FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelFrekans2 G WHERE G.ID_SINAVTURU=T.ID_SINAVTURU)
					INTO #GenelSira2 FROM #GenelFrekans2 T
					WHERE FREKANS IS NOT NULL
				
					--------------------------------------------------------------------

					-- Öğretmen Zümre Genel
					SELECT TC_OGRETMEN, DERSAD, ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					INTO #GenelZumreFrekans2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, DERSAD, ID_SINAVTURU
				UNION ALL			
					SELECT TC_OGRETMEN, DERSAD, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, DERSAD


					SELECT *, SN = ROW_NUMBER() OVER (PARTITION BY DERSAD, ID_SINAVTURU ORDER BY FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelZumreFrekans2 G WHERE G.DERSAD = F.DERSAD  AND G.ID_SINAVTURU=F.ID_SINAVTURU)
					INTO #GenelZumreSira2 FROM #GenelZumreFrekans2	F
					WHERE FREKANS IS NOT NULL
					--------------------------------------------------------------------

					-- Öğretmen Kampus Genel
					SELECT TC_OGRETMEN, ID_SUBE, ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					INTO #GenelKampusFrekans2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, ID_SUBE, ID_SINAVTURU
				UNION ALL
					SELECT TC_OGRETMEN, ID_SUBE, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, ID_SUBE


					SELECT F.*, SN = ROW_NUMBER() OVER (PARTITION BY F.ID_SUBE, ID_SINAVTURU ORDER BY F.FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelKampusFrekans2 G WHERE G.ID_SUBE = F.ID_SUBE AND  G.ID_SINAVTURU=F.ID_SINAVTURU), SUBEAD = S.AD
					INTO #GenelKampusSira2 FROM #GenelKampusFrekans2	F
					INNER JOIN V3Sube	S ON S.ID_SUBE = F.ID_SUBE
					WHERE F.FREKANS IS NOT NULL
					--------------------------------------------------------------------

					-- Öğretmen Zümre Kampus Genel
					SELECT TC_OGRETMEN, ID_SUBE, DERSAD, ID_SINAVTURU, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					INTO #GenelZumreKampusFrekans2 
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, ID_SUBE, DERSAD, ID_SINAVTURU
				UNION ALL
					SELECT TC_OGRETMEN, ID_SUBE, DERSAD, @_ID_STGENEL, FREKANS = CONVERT(DECIMAL(18, 2), AVG(FREKANS))
					FROM v2FrekansSorguDetay			SD
					JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
					WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU
					GROUP BY TC_OGRETMEN, ID_SUBE, DERSAD

					SELECT F.*, SN = ROW_NUMBER() OVER (PARTITION BY F.ID_SUBE, F.DERSAD, ID_SINAVTURU ORDER BY F.FREKANS DESC), OGRTSAY = (SELECT COUNT(DISTINCT G.TC_OGRETMEN) FROM #GenelZumreKampusFrekans2 G WHERE G.ID_SUBE = F.ID_SUBE AND G.DERSAD = F.DERSAD  AND G.ID_SINAVTURU=F.ID_SINAVTURU), SUBEAD = S.AD
					INTO #GenelZumreKampusSira2 FROM #GenelZumreKampusFrekans2	F
					INNER JOIN V3Sube	S ON S.ID_SUBE = F.ID_SUBE
					WHERE F.FREKANS IS NOT NULL
					--------------------------------------------------------------------


					SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, O.ID_SINAVTURU, OGRSAY = COUNT(DISTINCT D.TC_OGRENCI) , SINIFSAY = COUNT(DISTINCT D.ID_SINIF) 
					INTO #OgrenciSinifListe2 
					FROM #Filtre2				O
					JOIN #v2FrekansOgrenciDetayDonem	D	ON	D.TC_OGRETMEN = O.TC_OGRETMEN 
													AND D.DERSAD = O.DERSAD 
													AND D.ID_SUBE = O.ID_SUBE 
													AND D.ID_SINAVTURU = O.ID_SINAVTURU 
													AND D.ID_KADEME3 = O.ID_KADEME3
					GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, O.ID_SINAVTURU
				UNION ALL 			
					SELECT O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD, @_ID_STGENEL, OGRSAY = COUNT(DISTINCT D.TC_OGRENCI) , SINIFSAY = COUNT(DISTINCT D.ID_SINIF) 			 
					FROM #Filtre2				O
					JOIN #v2FrekansOgrenciDetayDonem	D	ON	D.TC_OGRETMEN = O.TC_OGRETMEN 
													AND D.DERSAD = O.DERSAD 
													AND D.ID_SUBE = O.ID_SUBE 
													AND D.ID_SINAVTURU = O.ID_SINAVTURU 
													AND D.ID_KADEME3 = O.ID_KADEME3
					GROUP BY O.TC_OGRETMEN, O.DERSAD, O.OGRETMENADSOYAD

			
					INSERT INTO #SINAVTURU (ID_SINAVTURU,AD,KISAAD,AKTIF,SIRA) VALUES(@_ID_STGENEL,'GENEL','GNL',1,2)

					-- Liste
					DELETE FROM #T1


					SELECT ID_SINAVTURU
						,(MAX(GF.FREKANS)- MIN(GF.FREKANS) )/5 ARALIK
						,MAX(GF.FREKANS) MAXIMUM
						,MIN(GF.FREKANS) MINIMUM 
						--,MINIMUM	= IIF(MIN(GF.FREKANS) < 0, 0 , MIN(GF.FREKANS) )
						, DERSAD
					INTO #ARALIK 
					FROM #GenelFrekansKatki	GF
					GROUP BY ID_SINAVTURU, DERSAD

					--INSERT INTO #ARALIK
					--SELECT 
					--	 @_ID_STGENEL
					--	,(MAX(GF.FREKANS)-MIN(GF.FREKANS))/5 ARALIK
					--	,MAX(GF.FREKANS) MAXIMUM
					--	,MIN(GF.FREKANS) MINIMUM 
					--FROM #GenelFiltre2	GF


					SELECT ID_SINAVTURU
						,KADEME1 = MINIMUM + ARALIK
						,KADEME2 = MINIMUM + (ARALIK*2)
						,KADEME3 = MINIMUM + (ARALIK*3)
						,KADEME4 = MINIMUM + (ARALIK*4)
						, DERSAD
					INTO #ETKI
					FROM #ARALIK
				

					INSERT INTO #T1 (
					 [SINAV TÜRÜ]	
					,STKISAAD
					,[BRANŞ]		
					,TC_OGRETMEN
					,FREKANS
					,[FREKANS KATKI]
					,[KAMPÜS ZÜMRE] 
					,[KAMPÜS GENEL]	
					,[GENEL ZÜMRE]	
					,GENEL
					,ID_SINAVTURU 
					)
					SELECT 
						 [SINAV TÜRÜ]		= S.AD 
						,[STKISAAD]			= S.KISAAD
						,[BRANŞ]			= F.DERSAD
						,[TC_OGRETMEN]		= F.TC_OGRETMEN
						,[FREKANS]			= ISNULL( MAX(F.FREKANS) ,0)
						--,[FREKANS KATKI]	= CASE 
						--						WHEN (AVG(F.FREKANS)/(SELECT MAX(FREKANS) FROM #GenelFiltre2 GF WHERE GF.ID_SINAVTURU = F.ID_SINAVTURU )*100.0 )>75	THEN	'ÇOK ETKİLİ'
						--						WHEN (AVG(F.FREKANS)/(SELECT MAX(FREKANS) FROM #GenelFiltre2 GF WHERE GF.ID_SINAVTURU = F.ID_SINAVTURU )*100.0 )>50	THEN	'ETKİLİ'
						--						WHEN (AVG(F.FREKANS)/(SELECT MAX(FREKANS) FROM #GenelFiltre2 GF WHERE GF.ID_SINAVTURU = F.ID_SINAVTURU )*100.0 )>25	THEN	'NORMAL ETKİLİ'
						--						WHEN (AVG(F.FREKANS)/(SELECT MAX(FREKANS) FROM #GenelFiltre2 GF WHERE GF.ID_SINAVTURU = F.ID_SINAVTURU )*100.0 )>-1	THEN	'AZ ETKİLİ'
						--						ELSE 'ETKİSİZ'
						--					END

						,[FREKANS KATKI]	= --CASE WHEN AVG(F.FREKANS) < 0 THEN 'NEGATİF EKTİ'
												--ELSE 
													CASE
														WHEN AVG(F.FREKANS) <  (SELECT E.KADEME1 FROM #ETKI E WHERE E.ID_SINAVTURU = F.ID_SINAVTURU AND E.DERSAD = F.DERSAD) THEN 'ETKİSİZ'
														WHEN AVG(F.FREKANS) <  (SELECT E.KADEME2 FROM #ETKI E WHERE E.ID_SINAVTURU = F.ID_SINAVTURU AND E.DERSAD = F.DERSAD) THEN 'AZ ETKİLİ'
														WHEN AVG(F.FREKANS) <  (SELECT E.KADEME3 FROM #ETKI E WHERE E.ID_SINAVTURU = F.ID_SINAVTURU AND E.DERSAD = F.DERSAD) THEN 'NORMAL'
														WHEN AVG(F.FREKANS) <  (SELECT E.KADEME4 FROM #ETKI E WHERE E.ID_SINAVTURU = F.ID_SINAVTURU AND E.DERSAD = F.DERSAD) THEN 'ETKİLİ'
														WHEN AVG(F.FREKANS) >= (SELECT E.KADEME4 FROM #ETKI E WHERE E.ID_SINAVTURU = F.ID_SINAVTURU AND E.DERSAD = F.DERSAD) THEN 'ÇOK ETKİLİ'
														ELSE '---'
													END
												--END
						,[KAMPÜS ZÜMRE]		= ISNULL((SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelZumreKampusSira2	tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN AND F.ID_SINAVTURU=TT.ID_SINAVTURU AND K.DERSAD = tt.DERSAD	)>1 then k.SUBEAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelZumreKampusSira2	K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN AND K.ID_SINAVTURU=F.ID_SINAVTURU  AND K.DERSAD = F.DERSAD ORDER BY K.SUBEAD	FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'---')
						,[KAMPÜS GENEL]		= ISNULL((SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelKampusSira2			tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN AND F.ID_SINAVTURU=TT.ID_SINAVTURU							)>1 then k.SUBEAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelKampusSira2		K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN AND K.ID_SINAVTURU=F.ID_SINAVTURU							 ORDER BY K.SUBEAD	FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'---')					
						,[GENEL ZÜMRE]		= ISNULL((SELECT STUFF((SELECT '<br>' + (case when (select count(1)  FROM #GenelZumreSira2			tt  WHERE tt.TC_OGRETMEN=k.TC_OGRETMEN AND F.ID_SINAVTURU=TT.ID_SINAVTURU AND K.DERSAD = tt.DERSAD	)>1 then k.DERSAD +' : ' else '' end )+ CAST(K.SN AS VARCHAR) + ' / ' + CAST(K.OGRTSAY AS VARCHAR)	FROM #GenelZumreSira2		K WHERE K.TC_OGRETMEN = F.TC_OGRETMEN AND K.ID_SINAVTURU=F.ID_SINAVTURU AND K.DERSAD = F.DERSAD						FOR XML PATH(''), TYPE).value('.', 'VARCHAR(MAX)'), 1, 4, '')),'---')
						,[GENEL]			= CAST(G.SN AS VARCHAR) + ' / ' + CAST(MAX(G.OGRTSAY) AS VARCHAR)
						--,[GENEL]			= CAST(G.SN AS VARCHAR) + ' / ' + CAST(@_GENELADET2 AS VARCHAR)
						--,[GENEL]			= CASE WHEN G.ID_SINAVTURU=@_ID_STGENEL THEN CAST(G.SN AS VARCHAR) + ' / ' + CAST(@_GENELADET3 AS VARCHAR) ELSE CAST(G.SN AS VARCHAR) + ' / ' + CAST(@_GENELADET2 AS VARCHAR) END 
							,F.ID_SINAVTURU
					--INTO	#T1
					FROM #FiltreFrekans2				F
					INNER JOIN #OgrenciSinifListe2	O ON O.TC_OGRETMEN	= F.TC_OGRETMEN		AND O.ID_SINAVTURU = F.ID_SINAVTURU		AND O.DERSAD = F.DERSAD		
					INNER JOIN #SINAVTURU			S ON S.ID_SINAVTURU = F.ID_SINAVTURU
					LEFT  JOIN #GenelSira2			G ON G.TC_OGRETMEN	= F.TC_OGRETMEN		AND G.ID_SINAVTURU = S.ID_SINAVTURU
					GROUP BY S.AD, F.TC_OGRETMEN, F.ID_SINAVTURU, F.DERSAD, G.SN,S.KISAAD

		

				END


				-------------------------------------------------	(2.2)	2. SAYFA ALT


				print 11
				SELECT	 DERSAD
						,SUBEAD
						,OGRETMENADSOYAD
						,MAX(T.SS) SORUSAYISI
						,[FREKANS]	= CAST( CASE WHEN T.ID_SINAVTURU=0 THEN AVG(NET) ELSE 	AVG(FREKANS) END AS DECIMAL(8,2) )
						--,CAST(AVG(FREKANS) AS decimal(8,2)) FREKANS --coalesce(some_column, 0)
						,COUNT(DISTINCT ID_SINIF) SINIFSAYISI
						,COUNT(DISTINCT TC_OGRENCI) OGRENCISAYISI
						,TC_OGRETMEN
						,ID_DERS
						,T.ID_SUBE
						,T.ID_SINAVTURU
						,ID_SINIF
						,SINIFAD
						,CAST(AVG(HBNET) AS DECIMAL(8,2)) HBNET
						,AVG(ILK_SS) ILK_SS
				INTO	#ORTALAMA3
				FROM v2FrekansSorguDetay			SD
				JOIN #v2FrekansOgrenciDetayDonem	T	ON	T.ID_FREKANSOGRENCIDETAY= SD.ID_FREKANSOGRENCIDETAY
				JOIN #SUBELER						S	ON	S.ID_SUBE	= T.ID_SUBE
				WHERE SD.ID_FREKANSSORGU = @ID_FREKANSSORGU								
					AND (T.ID_SUBE		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)) OR  0		IN	(SELECT VALUE FROM OPENJSON( @_ID_SUBE		)))
					AND (DERSAD		= @_DERSAD OR @_DERSAD = 'Tümü') 
					AND TC_OGRETMEN	= @_TC_OGRETMEN
					AND DONEM		= @_DONEM
					
				GROUP BY TC_OGRETMEN,DERSAD,SUBEAD,OGRETMENADSOYAD,ID_DERS,T.ID_SUBE,ID_SINAVTURU,ID_SINIF,SINIFAD
			
				SELECT	[ÖĞRETMEN]		= OGRETMENADSOYAD
						,[BRANŞ]		= DERSAD
						,[SINAV TÜRÜ]	= ST.AD
						,[KAMPÜS]		= SUBEAD
						,[SINIF]		= ORT.SINIFAD	
						,[H.B. NET ORT.]= ORT.HBNET	
						,[HEDEFE UZAKLIK] = cast( ILK_SS-HBNET as decimal(8,2))
						,ORT.FREKANS		
						,ID_SINIF
						,TC_OGRETMEN
						,SIRA
						,ORT.ID_SINAVTURU
				INTO	#T2
				FROM	#ORTALAMA3	ORT
				JOIN	#SINAVTURU	ST	ON	ST.ID_SINAVTURU	= ORT.ID_SINAVTURU 
										AND ST.SIRA			<> 2
				WHERE	ORT.FREKANS IS NOT NULL
				ORDER BY ST.SIRA


				select(
							select * from(
								select 
								(						 
									SELECT * FROM #T1
									ORDER BY BRANŞ,ID_SINAVTURU
									FOR JSON AUTO
								) as t1
								,( 
									SELECT * FROM #T2
									ORDER BY FREKANS desc--SIRA,ID_SINAVTURU,[KAMPÜS],[SINIF]
									FOR JSON AUTO
								)as t2							
							) as tablo FOR JSON AUTO
						) as tt


					
					
				DROP TABLE IF EXISTS #ORTALAMA3
				DROP TABLE IF EXISTS #T2
					DROP TABLE #T1
					DROP TABLE #Filtre2
					DROP TABLE #GenelFiltre2
					DROP TABLE #FiltreFrekans2
					DROP TABLE #OgrenciSinifListe2 

					DROP TABLE #GenelFrekans2
					DROP TABLE #GenelSira2

					DROP TABLE #GenelZumreFrekans2
					DROP TABLE #GenelZumreSira2

					DROP TABLE #GenelKampusFrekans2
					DROP TABLE #GenelKampusSira2

					DROP TABLE #GenelZumreKampusFrekans2
					DROP TABLE #GenelZumreKampusSira2

				
				DROP TABLE IF EXISTS #T
				DROP TABLE IF EXISTS #Filtre
				DROP TABLE IF EXISTS #FiltreFrekans
				DROP TABLE IF EXISTS #OgrenciSinifListe 

				DROP TABLE IF EXISTS #GenelFrekans
				DROP TABLE IF EXISTS #GenelSira

				DROP TABLE IF EXISTS #GenelZumreFrekans
				DROP TABLE IF EXISTS #GenelZumreSira

				DROP TABLE IF EXISTS #GenelKampusFrekans
				DROP TABLE IF EXISTS #GenelKampusSira

				DROP TABLE IF EXISTS #GenelZumreKampusFrekans
				DROP TABLE IF EXISTS #GenelZumreKampusSira

				DROP TABLE IF EXISTS #GenelFrekansKatki


			END	
			IF @_ISLEM = 3	--	SINIF ÖĞRENCİ LİSTESİ		
			BEGIN 

				SELECT	[KAMPÜS]	= SUBEAD,
						[SINIF]		= SINIFAD,
						[BRANŞ]		= TAKMAAD,
						[SINAV TÜRÜ]= ST.AD,
						[AD SOYAD]	= K.AD+' '+K.SOYAD,
						[SORU SAYISI]=MAX(T.ILK_SS),
						[H.B NET]	= CAST(MAX(T.HBNET) AS DECIMAL(8,2)),
						[NET ORT]	= CAST(AVG(T.NET) AS DECIMAL(8,2)),
						[HEDEFE UZAKLIK]= cast(AVG(T.ILK_SS)-AVG(T.NET) as decimal(8,2)),
						--[FREKANS]	= CAST( CASE WHEN T.ID_SINAVTURU=0 THEN AVG(NET) ELSE 	AVG(FREKANS) END AS DECIMAL(8,2) ) -- YAZILI İSE FREKANSI YERİNE PUAN ORTLAMASI İSTENİYOR.
						[FREKANS]	= CAST(		CASE
										WHEN T.ID_SINAVTURU = 0		  THEN AVG(NET) 
										WHEN T.ID_SINAVTURU IN (5,6)  THEN (	SELECT TOP 1 FREKANS 
																				FROM #v2FrekansOgrenciDetayDonem DD
																				JOIN (SELECT TOP 1 S.ID_SINAV
																							FROM #v2FrekansOgrenciDetayDonem D 
																							JOIN Sinav						 S	ON	S.ID_SINAV	= D.ID_SINAV
																							WHERE	D.TC_OGRENCI	= T.TC_OGRENCI 
																								AND D.ID_SINAVTURU	= T.ID_SINAVTURU
																								AND D.TC_OGRETMEN	= T.TC_OGRETMEN
																								AND D.DERSAD		= T.DERSAD
																							ORDER BY S.SINAVTARIH DESC, ID_SINAV
																				) AS SD  ON DD.TC_OGRENCI	= T.TC_OGRENCI 
																						AND DD.ID_SINAVTURU	= T.ID_SINAVTURU
																						AND DD.TC_OGRETMEN	= T.TC_OGRETMEN
																						AND DD.DERSAD		= T.DERSAD
																						AND DD.ID_SINAV		= SD.ID_SINAV
																			) 
										ELSE 	AVG(FREKANS) 
									END 
							AS DECIMAL(8,2) ) ,-- YAZILI İSE FREKANSI YERİNE PUAN ORTLAMASI İSTENİYOR.
					
					
						[TC_OGRENCI]	    = TC_OGRENCI,		
						[TC_OGRETMEN]	    = TC_OGRETMEN,	
						[ID_SINIF]			= T.ID_SINIF,		
						[ID_SINAVTURU]		= T.ID_SINAVTURU	
				INTO	#v2FrekansOgrenciDetay
				FROM	#v2FrekansOgrenciDetayDonem	T
				JOIN	#SINAVTURU		ST	ON	ST.ID_SINAVTURU	= T.ID_SINAVTURU
				JOIN	v3Kullanici		K	ON	K.TCKIMLIKNO	= T.TC_OGRENCI
				WHERE 	T.ID_SINIF	= @_ID_SINIF
					AND TC_OGRETMEN	= @_TC_OGRETMEN
					AND T.DERSAD	= @_DERSAD
					AND FREKANS		IS NOT NULL
					AND T.ID_SINAVTURU IN (SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU))
				GROUP BY TC_OGRETMEN,T.ID_SINIF,T.ID_SINAVTURU,SUBEAD,SINIFAD ,TAKMAAD,ST.AD ,K.AD+' '+K.SOYAD ,TC_OGRENCI,T.ILK_SS-T.ILK_NET,T.DERSAD
			
				select(
							select * from(
								select 
								(					
									SELECT		* 
									FROM		#v2FrekansOgrenciDetay
									ORDER BY	[AD SOYAD]
									FOR JSON AUTO
								) as t3
												
							) as tablo FOR JSON AUTO
						) as tt
				DROP TABLE #v2FrekansOgrenciDetay
			END
			IF @_ISLEM = 4	--	ÖĞRENCİ FREKANS SINAV LST	
			BEGIN 

				SELECT	 SUBEAD
						,TAKMAAD
						,ST.AD SINAVTURU
						,CASE 
							WHEN ST.ID_SINAVTURU=0 THEN (SELECT AD FROM Yazili WHERE ID_YAZILI=T.ID_SINAV) 
							ELSE (SELECT TOP 1 AD FROM Sinav S WHERE S.ID_SINAV=T.ID_SINAV) 
						END SINAVADI
						,CAST(CASE 
							WHEN ST.ID_SINAVTURU=0 THEN (	SELECT ISNULL(YO.TELAFI, SUM(YOC.PUAN)) FROM YaziliOgrenci YO
															INNER JOIN YaziliOgrenciCevap YOC ON YOC.ID_YAZILIOGRENCI = YO.ID_YAZILIOGRENCI
															WHERE YO.ID_YAZILI = T.ID_SINAV AND YO.TCKIMLIKNO = T.TC_OGRENCI AND YO.AKTIF = 1 AND YO.KATILMADI = 0
															GROUP BY YO.TELAFI	) 
							ELSE						(	T.FREKANS			)
						END AS decimal(8,2)) SINAVPUANI
						,K.AD+' '+K.SOYAD ADSOYAD
						,SINIFAD
						,SS 
						,CAST(HBNET AS DECIMAL(8,2)) HBNET
						,ILK_SS HEDEF
						,CAST(NET AS DECIMAL(8,2)) NET
						,S.SINAVTARIH
						,S.ID_SINAVTURU
				INTO	#OGRENCISINAV
				FROM	#v2FrekansOgrenciDetayDonem	T
				JOIN	#SINAVTURU		ST	ON	ST.ID_SINAVTURU	= T.ID_SINAVTURU
				JOIN	v3Kullanici		K	ON	K.TCKIMLIKNO	= T.TC_OGRENCI
				LEFT JOIN Sinav			S	ON	S.ID_SINAV		= T.ID_SINAV
				WHERE	TC_OGRENCI		=	@_TC_OGRENCI
					AND TAKMAAD			=	@_DERSAD
					AND ST.ID_SINAVTURU IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU))
					AND T.FREKANS IS NOT NULL
				GROUP BY	SUBEAD,TAKMAAD,ST.AD,ST.ID_SINAVTURU,K.AD+' '+K.SOYAD,T.ID_SINAV,T.TC_OGRENCI ,T.FREKANS	, SINIFAD,SS,HBNET,ILK_SS,NET,S.SINAVTARIH,S.ID_SINAVTURU


				IF (SELECT COUNT(*) FROM #OGRENCISINAV WHERE ID_SINAVTURU != 6 )>1
				BEGIN
					INSERT INTO #OGRENCISINAV (SUBEAD,TAKMAAD,SINAVTURU,SINAVADI,SINAVPUANI		,SINIFAD,SS,HBNET,HEDEF,NET,SINAVTARIH)
					SELECT	SUBEAD,TAKMAAD,SINAVTURU,'ORTALAMA',AVG(SINAVPUANI)		,SINIFAD,SS,CAST(AVG(HBNET) AS decimal(8,2)),HEDEF,CAST(AVG(NET) AS DECIMAL(8,2)),GETDATE()
					FROM	#OGRENCISINAV 
					GROUP BY SUBEAD,TAKMAAD,SINAVTURU	,SINIFAD,SS,HEDEF
				END

				select(
							select * from(
								select 
								(					
									SELECT		[KAMPÜS]		= SUBEAD,
												[SINIF]			= SINIFAD,
												[BRANŞ]			= TAKMAAD,
												[SINAV TÜRÜ]	= SINAVTURU,
												[SINAV]			= SINAVADI,
												[SORU SAYISI]	= SS,
												[H.B. NET ORT.] = HBNET,
												[HEDEFE UZAKLIK]= HEDEF-HBNET,
												[ÖĞR NET]		= NET,
												[PUAN]			= SINAVPUANI,
												[FREKANS]		= SINAVPUANI,
												ADSOYAD
									FROM		#OGRENCISINAV 
									ORDER BY SINAVTARIH
									FOR JSON AUTO
								) as t4
												
							) as tablo FOR JSON AUTO
						) as tt
			
				DROP TABLE IF EXISTS #OGRENCISINAV
			END
			IF @_ISLEM = 5	--	ÖĞRETMEN SINIF GRAFİĞİ		
			BEGIN 
			
					
			

				DECLARE @_SINAVLAR TABLE(SINAVADI VARCHAR(MAX))
				IF (0 IN (SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU)))
				BEGIN
						DROP TABLE IF EXISTS #PIVOT
						DROP TABLE IF EXISTS #FREKANSOGRETMEN2

						SELECT	TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,SINIFAD SINIF,ST.AD [SINAV TÜRÜ],cast(AVG(FREKANS) as decimal(8,2)) FREKANS
								,'FREKANS' SINAVADI
						INTO	#FREKANSOGRETMEN2
						FROM	#v2FrekansOgrenciDetayDonem	T
						JOIN	#SINAVTURU		ST	ON ST.ID_SINAVTURU	= T.ID_SINAVTURU
						WHERE 	TC_OGRETMEN	= @_TC_OGRETMEN --'56377383260'
							AND FREKANS IS NOT NULL
							AND ST.ID_SINAVTURU IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU))
							AND (	T.ID_KADEME3	IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3)) 
								OR	0				IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3))
								)
							AND T.DONEM		= @_DONEM
						GROUP BY TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,SINIFAD,ST.AD,ST.ID_SINAVTURU

						SELECT TC_OGRETMEN,ID_SINIF,ID_SINAVTURU,SINIF,[SINAV TÜRÜ],FREKANS,SINAVADI INTO #PIVOT  FROM #FREKANSOGRETMEN2

						INSERT INTO @_SINAVLAR (SINAVADI) VALUES ('FREKANS')

						select(
							select * from(
								select 
								(					
									SELECT		*
									FROM		#PIVOT 
									FOR JSON AUTO
								) as t5,
								(					
									SELECT	SINAVADI
									FROM	@_SINAVLAR
									FOR JSON AUTO
								) as t6
												
							) as tablo FOR JSON AUTO
						) as tt

					
						DROP TABLE IF EXISTS #PIVOT
						DROP TABLE IF EXISTS #FREKANSOGRETMEN2

				END
				ELSE
				BEGIN
			
						DROP TABLE IF EXISTS #v2FrekansOgretmen


						SELECT	TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,ID_SINAV,SINIFAD SINIF,ST.AD [SINAV TÜRÜ],cast(AVG(FREKANS) as decimal(8,2)) FREKANS
								,CASE 
									WHEN ST.ID_SINAVTURU=0 THEN (SELECT AD FROM Yazili WHERE ID_YAZILI=T.ID_SINAV) 
									ELSE (SELECT TOP 1 SUBSTRING(K.AD ,1, CHARINDEX('.',K.AD)-1 )+'-'+S.AD FROM Sinav S JOIN v3Kademe3 K ON K.ID_KADEME3 = S.ID_KADEME3 WHERE S.ID_SINAV=T.ID_SINAV) 
									--ELSE (SELECT TOP 1 AD FROM Sinav S WHERE S.ID_SINAV=T.ID_SINAV) 								
								END SINAVADI
						INTO	#v2FrekansOgretmen
						FROM	#v2FrekansOgrenciDetayDonem	T
						JOIN	#SINAVTURU				ST	ON ST.ID_SINAVTURU	= T.ID_SINAVTURU
						WHERE 	TC_OGRETMEN	= @_TC_OGRETMEN --'56377383260'
							AND T.DONEM		= @_DONEM
							AND FREKANS		IS NOT NULL
							AND ST.ID_SINAVTURU IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU))
							AND (	T.ID_KADEME3	IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3)) 
								OR	0				IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3))
								)
						GROUP BY TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,ID_SINAV,SINIFAD,ST.AD,ST.ID_SINAVTURU

						--TAHSİN--
						INSERT INTO #v2FrekansOgretmen
						SELECT	TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,999999999 as ID_SINAV,SINIFAD SINIF,ST.AD [SINAV TÜRÜ],cast(AVG(FREKANS) as decimal(8,2)) FREKANS
								,ST.KISAAD+' ORT' as SINAVADI
						FROM	#v2FrekansOgrenciDetayDonem	T
						JOIN	#SINAVTURU		ST	ON ST.ID_SINAVTURU	= T.ID_SINAVTURU
						WHERE 	TC_OGRETMEN	= @_TC_OGRETMEN --'56377383260'
							AND T.DONEM		= @_DONEM
							AND FREKANS		IS NOT NULL
							AND ST.ID_SINAVTURU IN	(SELECT VALUE FROM OPENJSON( @_ID_SINAVTURU))
							AND (	T.ID_KADEME3	IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3)) 
								OR	0				IN	(SELECT VALUE FROM OPENJSON( @_ID_KADEME3))
								)
							AND ST.ID_SINAVTURU NOT IN (5,6) -- AAYKS VEYA YDS DEĞİLSE
						GROUP BY TC_OGRETMEN,ID_SINIF,T.ID_SINAVTURU,SINIFAD,ST.AD,ST.ID_SINAVTURU, ST.KISAAD
						--TAHSİN--
					
						DECLARE @_cols	AS NVARCHAR(MAX),
								@_cols2	AS NVARCHAR(MAX),
								@_cols3	AS NVARCHAR(MAX),
								@_SQL	AS NVARCHAR(MAX);

						--SET @_cols = STUFF((SELECT distinct ',' + QUOTENAME(c.SINAVADI) 
						--			FROM #v2FrekansOgretmen c
						--			FOR XML PATH(''), TYPE
						--			).value('.', 'NVARCHAR(MAX)') 
						--		,1,1,'')

						--SET @_cols2 = STUFF((SELECT distinct ',ISNULL(' + QUOTENAME(c.SINAVADI) + ', ''0'') ' + QUOTENAME(c.SINAVADI)
						----',' + QUOTENAME(c.SINAVADI) 
						--			FROM #v2FrekansOgretmen c
						--			FOR XML PATH(''), TYPE
						--			).value('.', 'NVARCHAR(MAX)') 
						--		,1,1,'')

						--		--SUM DAN DOLAYI SORUN OLABILIR
						--SET @_cols3 = STUFF((SELECT distinct ',SUM(' + QUOTENAME(c.SINAVADI) + ') ' + QUOTENAME(c.SINAVADI)
						----',' + QUOTENAME(c.SINAVADI) 
						--			FROM #v2FrekansOgretmen c
						--			FOR XML PATH(''), TYPE
						--			).value('.', 'NVARCHAR(MAX)') 
						--		,1,1,'')

						--TAHSİN--
						SET @_cols = STUFF((SELECT ',' + QUOTENAME(c.SINAVADI) 
									FROM #v2FrekansOgretmen c GROUP BY c.SINAVADI, c.ID_SINAV ORDER BY c.ID_SINAV
									FOR XML PATH(''), TYPE
									).value('.', 'NVARCHAR(MAX)') 
								,1,1,'')
		
						SET @_cols2 = STUFF((SELECT ',ISNULL(' + QUOTENAME(c.SINAVADI) + ', ''0'') ' + QUOTENAME(c.SINAVADI)
						--',' + QUOTENAME(c.SINAVADI) 
									FROM #v2FrekansOgretmen c GROUP BY c.SINAVADI, c.ID_SINAV ORDER BY c.ID_SINAV
									FOR XML PATH(''), TYPE
									).value('.', 'NVARCHAR(MAX)') 
								,1,1,'')

								--SUM DAN DOLAYI SORUN OLABILIR
						SET @_cols3 = STUFF((SELECT ',SUM(' + QUOTENAME(c.SINAVADI) + ') ' + QUOTENAME(c.SINAVADI)
						--',' + QUOTENAME(c.SINAVADI) 
									FROM #v2FrekansOgretmen c GROUP BY c.SINAVADI, c.ID_SINAV ORDER BY c.ID_SINAV
									FOR XML PATH(''), TYPE
									).value('.', 'NVARCHAR(MAX)') 
								,1,1,'')
						--TAHSİN--

						INSERT INTO @_SINAVLAR (SINAVADI)
							SELECT	DISTINCT SINAVADI
							FROM	#v2FrekansOgretmen

						SET @_SQL='
					
							DROP TABLE IF EXISTS #PVT
							DROP TABLE IF EXISTS #PVT1


							SELECT TC_OGRETMEN,ID_SINIF,ID_SINAVTURU,SINIF,[SINAV TÜRÜ],'+CAST(@_cols2 AS varchar(MAX))+' INTO #PVT1 FROM (
								SELECT * FROM #v2FrekansOgretmen
							)AS TABLO
							PIVOT (MAX(FREKANS) FOR SINAVADI IN ('+CAST(@_cols AS varchar(MAX))+')) AS P
					

							SELECT		TC_OGRETMEN,ID_SINIF,ID_SINAVTURU,SINIF,[SINAV TÜRÜ],'+CAST(@_cols3 AS varchar(MAX))+'
										INTO		#PVT
										FROM		#PVT1 
										group by TC_OGRETMEN,ID_SINIF,ID_SINAVTURU,SINIF,[SINAV TÜRÜ]
					
							select(
								select * from(
									select 
									(					
										SELECT		*
										FROM		#PVT 
										FOR JSON AUTO
									) as t5,
									(					
										SELECT	DISTINCT SINAVADI
										FROM	#v2FrekansOgretmen
										FOR JSON AUTO
									) as t6
												
								) as tablo FOR JSON AUTO
							) as tt

					
							DROP TABLE IF EXISTS #PVT
							DROP TABLE IF EXISTS #PVT1

						'
					
						print @_SQL
						EXECUTE (@_SQL)

						--set @_SQL='
						--	'

						--			execute (@_SQL)
								

				DROP TABLE IF EXISTS #v2FrekansOgretmen
					
				END
			

			
			END
			IF @_ISLEM = 6	--	DERSLER						
			BEGIN 
			
				--	INTO #DERSLER
				SELECT	D.* 
				INTO	#DERSLER 
				FROM	v3SinavDers D
				INNER JOIN [OkyanusDB].[dbo].[v3FrekansDers] FD ON FD.ID_KADEME3=D.ID_KADEME3 AND FD.AD=D.AD

				select(
							select * from(
								select 
								(	

									SELECT	DISTINCT D.AD
									FROM	#DERSLER			D
									JOIN	v2FrekansOgrenciDetay OD	ON	OD.DERSAD=D.AD
									WHERE	OD.ID_KADEME3	in (SELECT VALUE FROM OPENJSON(@_ID_KADEME3)) 
										AND OD.ID_SINAVTURU	in (SELECT VALUE FROM OPENJSON(@_ID_SINAVTURU)) 
										AND OD.DONEM = @_DONEM

									FOR JSON AUTO
								) as t5
												
							) as tablo FOR JSON AUTO
						) as tt
			END
			IF @_ISLEM = 7	--	SINAV TURU					
			BEGIN 
			
			

				select ID_SINAVTURU,15 ID_KADEME3 , AD, KISAAD 
				INTO #GrupSinavTuru 
				from SinavTuru s where ID_SINAVTURU in (6,5)
			union 
				select ID_SINAVTURU,16 , AD, KISAAD from SinavTuru s where ID_SINAVTURU in (6,5)
			union 
				select ID_SINAVTURU,17 , AD, KISAAD from SinavTuru s where ID_SINAVTURU in (6,5,2)
			union 
				select ID_SINAVTURU,18 , AD, KISAAD from SinavTuru s where ID_SINAVTURU in (3,2)
			--union 
			--	select 0,15 , 'YAZILI', 'YAZ'
			--union 
			--	select 0,16 , 'YAZILI', 'YAZ'
			--union 
			--	select 0,17 , 'YAZILI', 'YAZ'
			--union 
			--	select 0,18 , 'YAZILI', 'YAZ'

					INSERT INTO #GrupSinavTuru (ID_SINAVTURU, ID_KADEME3 , AD, KISAAD )
					SELECT ST.ID_SINAVTURU,K.ID_KADEME3,ST.AD,ST.KISAAD
					FROM v3Kademe3	K
					JOIN SinavTuru	ST	ON ST.ID_SINAVTURU IN (8,9)	
					WHERE ID_KADEME3 IN ( 11,12,13,14)


					--INSERT INTO #GrupSinavTuru (ID_SINAVTURU, ID_KADEME3 , AD, KISAAD )
					--SELECT 0,K.ID_KADEME3,'YAZILI', 'YAZ'
					--FROM v3Kademe3	K
					--WHERE ID_KADEME3 IN ( 11,12,13,14)

					
				SELECT distinct	ID_SINAVTURU,AD,KISAAD
				FROM	#GrupSinavTuru 
				WHERE	ID_KADEME3	in (SELECT VALUE FROM OPENJSON(@_ID_KADEME3)) 


				drop table #GrupSinavTuru
			END		
			IF @_ISLEM = 8	--	SON FİLTRE GETİR			
			BEGIN 


				SELECT ISNULL((
					SELECT TOP 1 PARAMETRELER
					FROM [Log]
					WHERE	TCKIMLIKNO	= @_TCKIMLIKNO
						AND ID_MENU		= 1099
						AND ISLEM		= 1
					ORDER BY KYE_TARIH DESC
				),'[]')
			END
		
			DROP TABLE IF EXISTS #DERSLER
			DROP TABLE IF EXISTS #SINAVTURU
			DROP TABLE IF EXISTS #ARALIK
			DROP TABLE IF EXISTS #ETKI
			DROP TABLE IF EXISTS #v2FrekansOgrenciDetayDonem

		END

	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @_ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END
