
USE [Pusulam]
GO
UPDATE Menu SET KOD='006' WHERE ID_MENU=1106 

USE [Pusulam]
GO
/****** Object:  StoredProcedure [dbo].[sp___TASLAK_SP]    Script Date: 10.11.2020 10:21:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
alter procedure [dbo].[sp_ViuBildirimRapor]
	@ISLEM					INT				= NULL,
	@TCKIMLIKNO				VARCHAR(11)		= NULL,
	@OTURUM					VARCHAR(36)		= NULL,
	@ID_MENU				INT				= NULL,
	
	@SQLJSON				NVARCHAR(MAX)	= NULL,
	@BASTARIH				VARCHAR(MAX)	= NULL,
	@BITTARIH				VARCHAR(MAX)    = NULL,
	@TC_KULLANICI			VARCHAR(11)		= NULL,
	@DATATABLE				BIT				= NULL

AS
BEGIN
/*

	Oluşturan		: Burhan Akyüz
	Oluşturma Tarih	: 10.11.2020
	
	--	sp Create 
		--	ISLEM = 1 ADD
	--	Viu Bildirim raporları

*/	


	DECLARE @PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @LOGJSON VARCHAR(MAX)
	SET @LOGJSON = (
		SELECT	 ISLEM					= @ISLEM	
				,TCKIMLIKNO				= @TCKIMLIKNO
				,OTURUM					= @OTURUM
				,ID_MENU				= @ID_MENU

				,SQLJSON				= @SQLJSON
				,BASTARIH				= @BASTARIH
				,BITTARIH				= @BITTARIH
				,TC_KULLANIC			= @TC_KULLANICI
				,DATATABLE				= @DATATABLE
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @_ID_LOG INT = 0

	BEGIN TRY    
		DECLARE @_DESTEK_KONTROL INT
		EXEC @_ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU, @LOGJSON = @LOGJSON, @ISLEM = @ISLEM, @PROSEDURADI = @PROCNAME
		

		IF @_ID_LOG > 0
		BEGIN

			
			IF @ISLEM = 1	--	KATEGORI LİSTESİ			
			BEGIN
				DROP TABLE IF EXISTS #TEMP_BILDIRIM_RAPORU
				CREATE TABLE #TEMP_BILDIRIM_RAPORU
				(
				ID_BILDIRIM INT,
				KYE_TCKIMLIKNO VARCHAR(MAX),
				KYE_TARIH DATE,
				MESAJ VARCHAR(MAX),
				TCKIMLIKNO_KIME VARCHAR(MAX),
				HEADER VARCHAR(MAX),
				LINK VARCHAR(MAX),
				ID_UYGULAMA INT ,
				RESIM_URL VARCHAR(MAX),
				GONDERILDI BIT,
				MESAJTAM VARCHAR(MAX),
				LINK_ETIKET VARCHAR(MAX),
				UYGULAMA VARCHAR(MAX)
				)

				INSERT INTO #TEMP_BILDIRIM_RAPORU
				SELECT   [ID_BILDIRIM]
						,[KYE_TCKIMLIKNO]
						,[KYE_TARIH]
						,[MESAJ]
						,[TCKIMLIKNO_KIME]
						,[HEADER]
						,[LINK]
						,B.[ID_UYGULAMA]
						,[RESIM_URL]
						,[GONDERILDI]
						,[MESAJTAM]
						,[LINK_ETIKET]
						,U.AD AS UYGULAMA 
				FROM OkyanusIletisim.dbo.Bildirim		B
				LEFT JOIN OkyanusIletisim.dbo.Uygulama	U	ON	B.ID_UYGULAMA	= U.ID_UYGULAMA
				WHERE
						B.KYE_TARIH >= CAST(@BASTARIH AS DATE)
				AND		B.KYE_TARIH <= CAST(@BITTARIH AS DATE)
				AND		B.TCKIMLIKNO_KIME = @TC_KULLANICI
				AND		B.GONDERILDI=1
				ORDER BY B.KYE_TARIH DESC

				IF ISNULL(@DATATABLE ,0 ) = 0
					SELECT (
						SELECT(
							SELECT * 
							FROM #TEMP_BILDIRIM_RAPORU 
							ORDER BY KYE_TARIH DESC 
							FOR JSON PATH
						)AS BILDIRIMRAPORU
					)
				ELSE
					SELECT	 [TARİH]		= CONVERT(VARCHAR,KYE_TARIH,104)
							,[TC KIMLIK NO]	= TCKIMLIKNO_KIME
							,UYGULAMA		= UYGULAMA
							,[BAŞLIK]		= HEADER
							,MESAJ			= MESAJ
							,[MESAJ TAM]	= MESAJTAM
					FROM #TEMP_BILDIRIM_RAPORU
					


			END

		END


	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @_ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END