/*
Deployment script for Pusulam

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Pusulam"
:setvar DefaultFilePrefix "Pusulam"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Disabling all DDL triggers...'
GO
DISABLE TRIGGER ALL ON DATABASE
GO
PRINT N'Altering [dbo].[fn_GenelHak]...';


GO
ALTER FUNCTION [dbo].[fn_GenelHak]
(
	@TCKIMLIKNO	VARCHAR(11)		= ''
)
RETURNS bit
AS
BEGIN
	DECLARE @R bit
	SET @R = (SELECT COUNT(TCKIMLIKNO) 
	FROM [OkyanusDB].[dbo].[v3Kullanici] 
	WHERE TCKIMLIKNO = @TCKIMLIKNO 
		AND @TCKIMLIKNO IN ('56545519606','52432651008','32051057542', '13955371880', '11462506566' ,'22723353928','62362359264','16733919908', '16142297406','31913154276') 
		AND AKTIF = 1)
	RETURN @R
END
GO
PRINT N'Creating [dbo].[sp_RehberDanismanYoklama]...';


GO
CREATE procedure [dbo].[sp_RehberDanismanYoklama]
	@ISLEM					INT				= NULL,
	@TCKIMLIKNO				VARCHAR(11)		= NULL,
	@OTURUM					VARCHAR(36)		= NULL,
	@ID_MENU				INT				= NULL,
	
	@ID_SINIFLIST			NVARCHAR(MAX)	= NULL,	
	@YOKLAMATARIH			NVARCHAR(MAX)	= NULL,	
	@SQLJSON				NVARCHAR(MAX)	= NULL

AS
BEGIN
/*

	Değiştiren Adı		: Kadir Cengiz
	Değiştirilen Tarih	: 27.10.2020
	
	--	sp Create 
	--	Öğrenci Yoklama Raporu

*/	
	
	DECLARE @PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @LOGJSON VARCHAR(MAX)
	SET @LOGJSON = (
		SELECT	 ISLEM					= @ISLEM	
				,TCKIMLIKNO				= @TCKIMLIKNO
				,OTURUM					= @OTURUM
				,ID_MENU				= @ID_MENU

				,ID_SINIFLIST			= @ID_SINIFLIST	
				,YOKLAMATARIH			= @YOKLAMATARIH	
				,SQLJSON				= @SQLJSON						
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @_ID_LOG INT = 0

	BEGIN TRY    
		DECLARE @_DESTEK_KONTROL INT
		EXEC @_ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU, @LOGJSON = @LOGJSON, @ISLEM = @ISLEM, @PROSEDURADI = @PROCNAME
		

		IF @_ID_LOG > 0
		BEGIN
			
			IF @ISLEM = 1	--	OGRENCI YOKLAMA LİSTESİ			
			BEGIN
				
				DROP TABLE IF EXISTS #OGRLIST

				SELECT	 O.TCKIMLIKNO
						,DP.DERSSAAT
						,YK.GELDI 
						,O.ID_SINIF
				INTO #OGRLIST
				FROM v3Ogrenci								O
				JOIN OPENJSON ( @ID_SINIFLIST )				SL	ON	SL.VALUE			= O.ID_SINIF
				LEFT JOIN OkyanusIletisim..Yoklama			Y	ON	Y.ID_SINIF			= O.ID_SINIF
																AND Y.TARIH				= CAST(@YOKLAMATARIH AS date)
				LEFT JOIN OkyanusDB..v3DersProgram			DP	ON	DP.ID_DERSPROGRAM	= Y.ID_DERSPROGRAM
				LEFT JOIN OkyanusIletisim..YoklamaKullanici	YK	ON	YK.ID_YOKLAMA		= Y.ID_YOKLAMA
																AND YK.TCKIMLIKNO		= O.TCKIMLIKNO

				SELECT (
					SELECT DISTINCT 
						 GS.SUBEAD
						,GS.SINIF
						,O.TCKIMLIKNO
						,K.AD
						,K.SOYAD
						,YOKLAMALISTE= (SELECT ODS.DERSNO, GELDI = CAST(ISNULL(OG.GELDI,0) AS BIT)
										FROM OnlineDersSaat	ODS
										LEFT JOIN #OGRLIST	OG	ON	OG.DERSSAAT		= ODS.DERSNO
																AND OG.TCKIMLIKNO	= O.TCKIMLIKNO
										ORDER BY ODS.DERSNO
										FOR JSON PATH
										)
					FROM #OGRLIST			O
					JOIN v3Kullanici		K	ON	K.TCKIMLIKNO	= O.TCKIMLIKNO
					JOIN vw_SubeGrupSinif	GS	ON	GS.ID_SINIF		= O.ID_SINIF
					ORDER BY GS.SUBEAD, GS.SINIF, K.AD, K.SOYAD
					FOR JSON PATH
				)

				DROP TABLE IF EXISTS #OGRLIST

				
			END

			IF @ISLEM = 2	--	PERSONEL SINIF LİSTESİ			
			BEGIN
			
				DECLARE @ID_KULLANICITIPI	INT
				
				IF EXISTS ( SELECT TOP 1 1
							FROM v3SubeYetki
							WHERE TCKIMLIKNO			= @TCKIMLIKNO
								AND ID_KULLANICITIPI	= 26	
							)
					SET @ID_KULLANICITIPI = 26	-- REHBER
				ELSE
					SET @ID_KULLANICITIPI = 100	-- DANIŞMAN ÖĞRETMEN

				SELECT ISNULL((
					SELECT GS.ID_SINIF, GS.SUBEAD, GS.SINIF AS AD
					FROM OkyanusDB..v3SinifPersonel	SP
					JOIN vw_SubeGrupSinif			GS	ON	GS.ID_SINIF	= SP.ID_SINIF
					WHERE	ID_KULLANICITIPI	= @ID_KULLANICITIPI
						AND TCKIMLIKNO			= @TCKIMLIKNO
					ORDER BY SUBEAD, SINIF
					FOR JSON PATH
				),'[]')

			END

		END


	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @_ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END
GO
PRINT N'Altering [dbo].[sp___TASLAK_SP]...';


GO
ALTER procedure [dbo].[sp___TASLAK_SP]
	@ISLEM					INT				= NULL,
	@TCKIMLIKNO				VARCHAR(11)		= NULL,
	@OTURUM					VARCHAR(36)		= NULL,
	@ID_MENU				INT				= NULL,
	
	@SQLJSON				NVARCHAR(MAX)	= NULL

AS
BEGIN
/*

	Değiştiren Adı		: Kadir Cengiz
	Değiştirilen Tarih	: 11.09.2020
	
	--	sp Alter 
		--	ISLEM = 12 ADD
	--	ONLINE SINAV DA OPTIK ÇOKLU KITAPCIK

*/	
	
	DECLARE @PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @LOGJSON VARCHAR(MAX)
	SET @LOGJSON = (
		SELECT	 ISLEM					= @ISLEM	
				,TCKIMLIKNO				= @TCKIMLIKNO
				,OTURUM					= @OTURUM
				,ID_MENU				= @ID_MENU

				,SQLJSON				= @SQLJSON						
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @_ID_LOG INT = 0

	BEGIN TRY    
		DECLARE @_DESTEK_KONTROL INT
		EXEC @_ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU, @LOGJSON = @LOGJSON, @ISLEM = @ISLEM, @PROSEDURADI = @PROCNAME
		

		IF @_ID_LOG > 0
		BEGIN
			
			IF @ISLEM = 1	--	KATEGORI LİSTESİ			
			BEGIN
				
				SELECT 1 
				
			END

		END


	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @_ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END
GO
PRINT N'Refreshing [dbo].[sp_OturumKontrol]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OturumKontrol]';


GO
PRINT N'Refreshing [dbo].[sp_OturumKontrolMenuYetkiLog]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OturumKontrolMenuYetkiLog]';


GO
PRINT N'Refreshing [dbo].[sp_Sinav]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Sinav]';


GO
PRINT N'Refreshing [dbo].[sp_Sinav2]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Sinav2]';


GO
PRINT N'Refreshing [dbo].[sp_Abide]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Abide]';


GO
PRINT N'Refreshing [dbo].[sp_AraKarne]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AraKarne]';


GO
PRINT N'Refreshing [dbo].[sp_AraKarneCoklu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AraKarneCoklu]';


GO
PRINT N'Refreshing [dbo].[sp_AraKarneCokluEski]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AraKarneCokluEski]';


GO
PRINT N'Refreshing [dbo].[sp_AraKarneEski]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AraKarneEski]';


GO
PRINT N'Refreshing [dbo].[sp_BirimYetki]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_BirimYetki]';


GO
PRINT N'Refreshing [dbo].[sp_BurslulukBursOraniBelirle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_BurslulukBursOraniBelirle]';


GO
PRINT N'Refreshing [dbo].[sp_BurslulukOgrenciIslemleri]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_BurslulukOgrenciIslemleri]';


GO
PRINT N'Refreshing [dbo].[sp_CevapAnahtariDuzenle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_CevapAnahtariDuzenle]';


GO
PRINT N'Refreshing [dbo].[sp_CevapAnahtariKullaniciYetki]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_CevapAnahtariKullaniciYetki]';


GO
PRINT N'Refreshing [dbo].[sp_DemoOgrenci]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DemoOgrenci]';


GO
PRINT N'Refreshing [dbo].[sp_DenemeSinavRaporlari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DenemeSinavRaporlari]';


GO
PRINT N'Refreshing [dbo].[sp_DersCalismaProgrami]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DersCalismaProgrami]';


GO
PRINT N'Refreshing [dbo].[sp_DersUnite]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DersUnite]';


GO
PRINT N'Refreshing [dbo].[sp_Dokuman]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Dokuman]';


GO
PRINT N'Refreshing [dbo].[sp_Donem]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Donem]';


GO
PRINT N'Refreshing [dbo].[sp_DSNetPuanOrtalamalariOS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DSNetPuanOrtalamalariOS]';


GO
PRINT N'Refreshing [dbo].[sp_Etut]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Etut]';


GO
PRINT N'Refreshing [dbo].[sp_EtutOgretmenRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_EtutOgretmenRapor]';


GO
PRINT N'Refreshing [dbo].[sp_EtutProgramiOV]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_EtutProgramiOV]';


GO
PRINT N'Refreshing [dbo].[sp_EtutSabitOlustur]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_EtutSabitOlustur]';


GO
PRINT N'Refreshing [dbo].[sp_EtutSinifRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_EtutSinifRapor]';


GO
PRINT N'Refreshing [dbo].[sp_EtutTakvimi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_EtutTakvimi]';


GO
PRINT N'Refreshing [dbo].[sp_FrekansSistem]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_FrekansSistem]';


GO
PRINT N'Refreshing [dbo].[sp_FrekansSistemEksikKazanim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_FrekansSistemEksikKazanim]';


GO
PRINT N'Refreshing [dbo].[sp_GelisimRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GelisimRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_GelisimRaporuLS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GelisimRaporuLS]';


GO
PRINT N'Refreshing [dbo].[sp_GelisimRaporuOgrenciBelge]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GelisimRaporuOgrenciBelge]';


GO
PRINT N'Refreshing [dbo].[sp_GelisimRaporuOO]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GelisimRaporuOO]';


GO
PRINT N'Refreshing [dbo].[sp_GenelKazanimAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GenelKazanimAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_GenelListeler]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GenelListeler]';


GO
PRINT N'Refreshing [dbo].[sp_GenelSinavRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GenelSinavRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_GenelSoruAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GenelSoruAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_HataLog]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_HataLog]';


GO
PRINT N'Refreshing [dbo].[sp_HedefBelirlemeRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_HedefBelirlemeRapor]';


GO
PRINT N'Refreshing [dbo].[sp_KarmaListe]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KarmaListe]';


GO
PRINT N'Refreshing [dbo].[sp_KarmaListe3]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KarmaListe3]';


GO
PRINT N'Refreshing [dbo].[sp_KazanimAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KazanimAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_KazanimAnaliziOO]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KazanimAnaliziOO]';


GO
PRINT N'Refreshing [dbo].[sp_KonuAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KonuAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_KonuAnaliziCoklu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KonuAnaliziCoklu]';


GO
PRINT N'Refreshing [dbo].[sp_Kullanici]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Kullanici]';


GO
PRINT N'Refreshing [dbo].[sp_KullaniciYetki]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_KullaniciYetki]';


GO
PRINT N'Refreshing [dbo].[sp_LUSRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_LUSRapor]';


GO
PRINT N'Refreshing [dbo].[sp_MaddeFrekansAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_MaddeFrekansAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_OdevTakibi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OdevTakibi]';


GO
PRINT N'Refreshing [dbo].[sp_OdulListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OdulListesi]';


GO
PRINT N'Refreshing [dbo].[sp_Ogrenci]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Ogrenci]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciDersMuaf]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciDersMuaf]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciFrekansMuaf]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciFrekansMuaf]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciHedef]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciHedef]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciHedefOO]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciHedefOO]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciIzleme]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciIzleme]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciMaddeAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciMaddeAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciRaporlari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciRaporlari]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciTakvim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciTakvim]';


GO
PRINT N'Refreshing [dbo].[sp_OkulNetPuanOrtalamalari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OkulNetPuanOrtalamalari]';


GO
PRINT N'Refreshing [dbo].[sp_OkulRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OkulRapor]';


GO
PRINT N'Refreshing [dbo].[sp_OkulRaporEski]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OkulRaporEski]';


GO
PRINT N'Refreshing [dbo].[sp_OptikYukle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OptikYukle]';


GO
PRINT N'Refreshing [dbo].[sp_OrtalamaListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OrtalamaListesi]';


GO
PRINT N'Refreshing [dbo].[sp_OSYM]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OSYM]';


GO
PRINT N'Refreshing [dbo].[sp_ProjeDonem]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_ProjeDonem]';


GO
PRINT N'Refreshing [dbo].[sp_ProjeDonemRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_ProjeDonemRapor]';


GO
PRINT N'Refreshing [dbo].[sp_PuanaGoreYaziliSonuclari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_PuanaGoreYaziliSonuclari]';


GO
PRINT N'Refreshing [dbo].[sp_RehberlikEnvanter]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_RehberlikEnvanter]';


GO
PRINT N'Refreshing [dbo].[sp_RehberlikEnvanterTanimlama]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_RehberlikEnvanterTanimlama]';


GO
PRINT N'Refreshing [dbo].[sp_SinavaKatilmayanOgrenciler]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavaKatilmayanOgrenciler]';


GO
PRINT N'Refreshing [dbo].[sp_SinavAnaliz]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavAnaliz]';


GO
PRINT N'Refreshing [dbo].[sp_SinavHariciPuanSira]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavHariciPuanSira]';


GO
PRINT N'Refreshing [dbo].[sp_SinavIstatistik]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavIstatistik]';


GO
PRINT N'Refreshing [dbo].[sp_SinavKatilim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavKatilim]';


GO
PRINT N'Refreshing [dbo].[sp_SinavKonuAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavKonuAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_SinavListele]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavListele]';


GO
PRINT N'Refreshing [dbo].[sp_SinavSonuclari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavSonuclari]';


GO
PRINT N'Refreshing [dbo].[sp_SinifBazindaKazanimAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifBazindaKazanimAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_SinifDersAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifDersAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_SinifMaddeAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifMaddeAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_SinifNetPuanOrtalamalari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifNetPuanOrtalamalari]';


GO
PRINT N'Refreshing [dbo].[sp_SoruMaddeAnaliziOS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SoruMaddeAnaliziOS]';


GO
PRINT N'Refreshing [dbo].[sp_Takvim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Takvim]';


GO
PRINT N'Refreshing [dbo].[sp_TestMaddeAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_TestMaddeAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_TKTTest]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_TKTTest]';


GO
PRINT N'Refreshing [dbo].[sp_TopluSinavSonuclari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_TopluSinavSonuclari]';


GO
PRINT N'Refreshing [dbo].[sp_TopluYaziliYoklamaSonuclari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_TopluYaziliYoklamaSonuclari]';


GO
PRINT N'Refreshing [dbo].[sp_UniteTarama]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UniteTarama]';


GO
PRINT N'Refreshing [dbo].[sp_UniteTaramaSinifPuanOrtalamalari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UniteTaramaSinifPuanOrtalamalari]';


GO
PRINT N'Refreshing [dbo].[sp_UpgradeSoru]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UpgradeSoru]';


GO
PRINT N'Refreshing [dbo].[sp_v2FrekansSistemEksikKazanim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_v2FrekansSistemEksikKazanim]';


GO
PRINT N'Refreshing [dbo].[sp_Yardim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Yardim]';


GO
PRINT N'Refreshing [dbo].[sp_YaziliYoklama]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YaziliYoklama]';


GO
PRINT N'Refreshing [dbo].[sp_YaziliYoklamaSonuclari]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YaziliYoklamaSonuclari]';


GO
PRINT N'Refreshing [dbo].[sp_YetenekGelisim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YetenekGelisim]';


GO
PRINT N'Refreshing [dbo].[sp_YG_Karne]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_Karne]';


GO
PRINT N'Refreshing [dbo].[sp_YG_YetenekGelisim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_YetenekGelisim]';


GO
PRINT N'Refreshing [dbo].[sp_YG_YorumEkle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_YorumEkle]';


GO
PRINT N'Refreshing [dbo].[sp_ZekaTest]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_ZekaTest]';


GO
PRINT N'Refreshing [dbo].[sp_ZumreCalisma]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_ZumreCalisma]';


GO
PRINT N'Refreshing [dbo].[sp_OnlineSinav]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OnlineSinav]';


GO
PRINT N'Refreshing [dbo].[sp_RehberlikOnlineYukle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_RehberlikOnlineYukle]';


GO
PRINT N'Refreshing [dbo].[sp_AkilliOgretimBarkod]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AkilliOgretimBarkod]';


GO
PRINT N'Refreshing [dbo].[sp_AmazonChime]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AmazonChime]';


GO
PRINT N'Refreshing [dbo].[sp_AnaSayfa]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AnaSayfa]';


GO
PRINT N'Refreshing [dbo].[sp_Assessment]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Assessment]';


GO
PRINT N'Refreshing [dbo].[sp_AssessmentOgrenciSinavRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AssessmentOgrenciSinavRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_AssessmentSinavaKatilmayanlar]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AssessmentSinavaKatilmayanlar]';


GO
PRINT N'Refreshing [dbo].[sp_AssessmentSinavOgrenciRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AssessmentSinavOgrenciRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_AssessmentSinavSoruAnalizi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AssessmentSinavSoruAnalizi]';


GO
PRINT N'Refreshing [dbo].[sp_AssessmentSinifSinavRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_AssessmentSinifSinavRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_Bulten]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Bulten]';


GO
PRINT N'Refreshing [dbo].[sp_CurpusStudyYukle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_CurpusStudyYukle]';


GO
PRINT N'Refreshing [dbo].[sp_DegerlendirmeFormu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_DegerlendirmeFormu]';


GO
PRINT N'Refreshing [dbo].[sp_Fatura]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Fatura]';


GO
PRINT N'Refreshing [dbo].[sp_FrekansEtkiListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_FrekansEtkiListesi]';


GO
PRINT N'Refreshing [dbo].[sp_FrekansSinavOgrenci]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_FrekansSinavOgrenci]';


GO
PRINT N'Refreshing [dbo].[sp_MentalUp]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_MentalUp]';


GO
PRINT N'Refreshing [dbo].[sp_Morpa]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Morpa]';


GO
PRINT N'Refreshing [dbo].[sp_Odev]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Odev]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciBilgiSistemi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciBilgiSistemi]';


GO
PRINT N'Refreshing [dbo].[sp_OgrenciHarcama]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OgrenciHarcama]';


GO
PRINT N'Refreshing [dbo].[sp_OnlineDers]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OnlineDers]';


GO
PRINT N'Refreshing [dbo].[sp_OsOdevListele]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OsOdevListele]';


GO
PRINT N'Refreshing [dbo].[sp_OzelSayfaIslemleri]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OzelSayfaIslemleri]';


GO
PRINT N'Refreshing [dbo].[sp_Parametre]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Parametre]';


GO
PRINT N'Refreshing [dbo].[sp_SinifDersProgram]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifDersProgram]';


GO
PRINT N'Refreshing [dbo].[sp_SinifListeRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifListeRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_SinifOgretmenListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinifOgretmenListesi]';


GO
PRINT N'Refreshing [dbo].[sp_TercihListeRapor]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_TercihListeRapor]';


GO
PRINT N'Refreshing [dbo].[sp_UniteTaramaSinavSonucListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UniteTaramaSinavSonucListesi]';


GO
PRINT N'Refreshing [dbo].[sp_UniteTaramaTopluKarne]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UniteTaramaTopluKarne]';


GO
PRINT N'Refreshing [dbo].[sp_UyariSistemleri]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_UyariSistemleri]';


GO
PRINT N'Refreshing [dbo].[sp_v2FrekansEtkiListesi]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_v2FrekansEtkiListesi]';


GO
PRINT N'Refreshing [dbo].[sp_v2FrekansKampus]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_v2FrekansKampus]';


GO
PRINT N'Refreshing [dbo].[sp_v2FrekansSinif]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_v2FrekansSinif]';


GO
PRINT N'Refreshing [dbo].[sp_v2FrekansSistem]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_v2FrekansSistem]';


GO
PRINT N'Refreshing [dbo].[sp_VeliUniteTaramaRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_VeliUniteTaramaRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_VIU]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_VIU]';


GO
PRINT N'Refreshing [dbo].[sp_ViuRandevuTakip]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_ViuRandevuTakip]';


GO
PRINT N'Refreshing [dbo].[sp_WhatsApp]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_WhatsApp]';


GO
PRINT N'Refreshing [dbo].[sp_YG_KotaBelirle]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_KotaBelirle]';


GO
PRINT N'Refreshing [dbo].[sp_YG_MevcutDagilim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_MevcutDagilim]';


GO
PRINT N'Refreshing [dbo].[sp_YG_OgrenciSecimRaporu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_OgrenciSecimRaporu]';


GO
PRINT N'Refreshing [dbo].[sp_YG_Secim]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_Secim]';


GO
PRINT N'Refreshing [dbo].[sp_YG_SecimAyar]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_SecimAyar]';


GO
PRINT N'Refreshing [dbo].[sp_YG_SecimYapmayanlar]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YG_SecimYapmayanlar]';


GO
PRINT N'Refreshing [dbo].[sp_Yillik]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Yillik]';


GO
PRINT N'Refreshing [dbo].[sp_YYS]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_YYS]';


GO
PRINT N'Refreshing [dbo].[sp_OptikIslemleriOnline]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OptikIslemleriOnline]';


GO
PRINT N'Refreshing [dbo].[sp_OptikIslemleri]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OptikIslemleri]';


GO
PRINT N'Refreshing [dbo].[sp_OptikIslemleriEski]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_OptikIslemleriEski]';


GO
PRINT N'Refreshing [dbo].[sp_SinavDegerlendir]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavDegerlendir]';


GO
PRINT N'Refreshing [dbo].[sp_SinavDegerlendirTumSinavlar]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_SinavDegerlendirTumSinavlar]';


GO
PRINT N'Refreshing [dbo].[sp_Sube]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Sube]';


GO
PRINT N'Refreshing [dbo].[sp_Filtre]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Filtre]';


GO
PRINT N'Refreshing [dbo].[sp_Grup]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Grup]';


GO
PRINT N'Refreshing [dbo].[sp_Sinif]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Sinif]';


GO
PRINT N'Refreshing [dbo].[sp_FiltreEk]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_FiltreEk]';


GO
PRINT N'Refreshing [dbo].[sp_Menu]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Menu]';


GO
PRINT N'Refreshing [dbo].[sp_Degerlendirme]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_Degerlendirme]';


GO
PRINT N'Refreshing [dbo].[sp_GenelHak]...';


GO
EXECUTE sp_refreshsqlmodule N'[dbo].[sp_GenelHak]';


GO
PRINT N'Reenabling DDL triggers...'
GO
ENABLE TRIGGER [CaptureStoredProcedureChanges] ON DATABASE
GO
PRINT N'Update complete.';


GO
