USE [Pusulam]
GO
/****** Object:  StoredProcedure [dbo].[sp_Abide]    Script Date: 4.11.2020 16:46:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[sp_Abide]
	@ISLEM				INT				= NULL,
	@TCKIMLIKNO			VARCHAR(11)		= NULL,
	@OTURUM				VARCHAR(36)		= NULL,
	@ID_MENU			INT				= NULL,
	@DONEM				VARCHAR(4)		= NULL,
	@AD					VARCHAR(MAX)	= NULL,
	@ID_ABIDESINAV		INT				= NULL,
	@SQLJSON			VARCHAR(MAX)	= NULL,
	@ID_SINIF			INT				= NULL,
	@ID_SUBE			INT				= NULL,
	@O_TCKIMLIKNO		VARCHAR(11)		= NULL,
	@DERS				VARCHAR(MAX)	= NULL,
	@ID_ABIDERESIM		INT				= NULL,
	@ID_ABIDESAYFATUR	INT				= NULL,
	@SIRA				INT				= NULL,
	@KITAPCIKSAYISI		INT				= NULL,
	@ID_KADEME3			INT				= NULL,
	@OVGORSUN			BIT				= NULL,
	@ID_ABIDEKITAPCIK	INT				= NULL		
AS
BEGIN
--BEGIN TRANSACTION [Tran1]
	BEGIN TRY    
		DECLARE @MSG			VARCHAR(4000)
		DECLARE @ErrorSeverity	INT
		DECLARE @ErrorState		INT
		
		DECLARE @return_variable INT
		EXEC @return_variable = [dbo].[sp_OturumKontrol] @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU
	
				DECLARE @_ID_ABIDESINAV INT			= @ID_ABIDESINAV
				DECLARE @_ID_SINIF		INT			= @ID_SINIF
				DECLARE @_DONEM			VARCHAR(4)	= ISNULL(@DONEM, OkyanusDB.dbo.fn_AktifDonem() )

		IF @return_variable = 1
		BEGIN
			IF @ISLEM = 1	--	SINAV TANIMLA
			BEGIN
				DECLARE @INSERTED TABLE(ID INT NOT NULL);  

				INSERT INTO AbideSinav(AD, DONEM, KYE_TCKIMLIKNO, ID_KADEME3)
				OUTPUT inserted.ID_ABIDESINAV
				INTO @INSERTED
				SELECT @AD, @DONEM, @TCKIMLIKNO, @ID_KADEME3

				DECLARE @cnt INT = 0;

				WHILE @cnt < @KITAPCIKSAYISI
				BEGIN
					INSERT INTO AbideKitapcik(ID_ABIDESINAV, AD)
					SELECT ID, CHAR(65 + @cnt) FROM @INSERTED
					SET @cnt = @cnt + 1;
				END;
			END

			IF @ISLEM = 2	--	SINAV LİSTELE
			BEGIN
				SELECT
				(
					SELECT	 S.ID_ABIDESINAV
							,S.AD
							,KADEME3		= K3.AD
							,TARIH			= CONVERT(varchar, S.KYE_TARIH, 104) 
							,ADSOYAD		= K.AD + ' ' + K.SOYAD 
							,KITAPCIKSAYISI	= (SELECT COUNT(*) FROM AbideKitapcik SK WHERE SK.ID_ABIDESINAV = S.ID_ABIDESINAV) 
							,S.OVGORSUN
					FROM AbideSinav S 
					INNER JOIN OkyanusDb.dbo.v3Kullanici K ON K.TCKIMLIKNO = S.KYE_TCKIMLIKNO
					INNER JOIN v3Kademe3				 K3 ON K3.ID_KADEME3	= S.ID_KADEME3
					WHERE	S.DONEM		 = @DONEM 
						AND S.ID_KADEME3 = @ID_KADEME3
						AND S.AKTIF		 = 1 
					ORDER BY S.KYE_TARIH DESC 
					FOR JSON PATH
				)
			END

			IF @ISLEM = 3	--	SINAV DUZENLE
			BEGIN
				UPDATE AbideSinav SET 
					 AD			= @AD
					,ID_KADEME3 = @ID_KADEME3 
				WHERE ID_ABIDESINAV = @ID_ABIDESINAV

				DECLARE @MEVCUTKITAPCIKSAYISI INT = (SELECT COUNT(*) FROM AbideKitapcik WHERE ID_ABIDESINAV = @ID_ABIDESINAV)

				IF @KITAPCIKSAYISI <> @MEVCUTKITAPCIKSAYISI
				BEGIN
					IF @KITAPCIKSAYISI > @MEVCUTKITAPCIKSAYISI
					BEGIN
						DECLARE @cntx INT = @MEVCUTKITAPCIKSAYISI;

						WHILE @cntx < @KITAPCIKSAYISI
						BEGIN
							INSERT INTO AbideKitapcik(ID_ABIDESINAV, AD)
							SELECT @ID_ABIDESINAV, CHAR(65 + @cntx)

							DECLARE @YENIID_ABIDEKITAPCIK INT = (SELECT ID_ABIDEKITAPCIK FROM AbideKitapcik WHERE ID_ABIDESINAV = @ID_ABIDESINAV AND AD = CHAR(65 + @cntx))

							IF EXISTS (SELECT * FROM AbideSoru WHERE ID_ABIDESINAV = @ID_ABIDESINAV)
							BEGIN
								INSERT INTO AbideSoruKarsilik(ID_ABIDESORU, ID_ABIDEKITAPCIK, SORUNO)
								SELECT S.ID_ABIDESORU, @YENIID_ABIDEKITAPCIK, S.SORUNO
								FROM AbideSoru S
							END
							
							SET @cntx = @cntx + 1;
						END;
					END
					ELSE
					BEGIN
						SELECT TOP(@MEVCUTKITAPCIKSAYISI - @KITAPCIKSAYISI) ID_ABIDEKITAPCIK 
						INTO #TEMPKITAPCIK
						FROM AbideKitapcik WHERE ID_ABIDESINAV = @ID_ABIDESINAV
						ORDER BY ID_ABIDEKITAPCIK DESC

						DELETE SK FROM AbideSoruKarsilik SK
						INNER JOIN #TEMPKITAPCIK K ON K.ID_ABIDEKITAPCIK = SK.ID_ABIDEKITAPCIK

						DELETE K FROM AbideKitapcik K
						INNER JOIN #TEMPKITAPCIK T ON T.ID_ABIDEKITAPCIK = K.ID_ABIDEKITAPCIK
					END
				END
			END

			IF @ISLEM = 4	--	SINAV SİL
			BEGIN
				UPDATE AbideSinav SET AKTIF = 0 WHERE ID_ABIDESINAV = @ID_ABIDESINAV
			END

			IF @ISLEM = 5	--	SINAV EXCEL YÜKLE
			BEGIN
				IF EXISTS (	
							SELECT * FROM AbideOgrenci O 
							INNER JOIN AbideSoru S ON S.ID_ABIDESORU = O.ID_ABIDESORU
							WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV
						)
				BEGIN
					RAISERROR ('Seçilen sınav için öğrenci girişi yapıldığından güncelleme işlemi yapılamaz!', 16, 1);
				END
				ELSE
				BEGIN
					DELETE SK 
					FROM AbideSoruKarsilik	SK
					INNER JOIN AbideSoru	S	ON	S.ID_ABIDESORU	= SK.ID_ABIDESORU 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV
				
					DELETE FROM AbideSoru		WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					DELETE FROM AbideYorum		WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					DELETE FROM AbidePuanAralik WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					DELETE FROM AbideBeceri		WHERE ID_ABIDESINAV = @ID_ABIDESINAV

					DECLARE @INSERTEDSORU TABLE(ID INT NOT NULL, SORUNO INT NOT NULL);  

					INSERT INTO AbideSoru (ID_ABIDESINAV, DERS, SORUNO, KAZANIM, BECERI, PUAN, ID_BILGI, ID_BILISSELSUREC)
					OUTPUT inserted.ID_ABIDESORU, inserted.SORUNO
					INTO @INSERTEDSORU
					SELECT @ID_ABIDESINAV, DERS, SORUNO, KAZANIM, BECERI, PUAN, ID_BILGI, ID_BILISSELSUREC 
					FROM OPENJSON(@SQLJSON, '$.SORULIST')
					WITH (
						DERS				VARCHAR(MAX),
						SORUNO				INT,
						KAZANIM				VARCHAR(MAX),
						BECERI				VARCHAR(MAX),
						PUAN				INT,
						ID_BILGI			INT,
						ID_BILISSELSUREC	INT
					)

					INSERT INTO AbideSoruKarsilik
					SELECT ID, K.ID_ABIDEKITAPCIK, S.SORUNO FROM @INSERTEDSORU S
					CROSS JOIN AbideKitapcik K WHERE K.ID_ABIDESINAV = @ID_ABIDESINAV
				
					INSERT INTO AbideYorum (ID_ABIDESINAV, DERS, DUZEY, YORUM, ONERI)
					SELECT @ID_ABIDESINAV, DERS, DUZEY, YORUM, ONERI FROM OPENJSON(@SQLJSON, '$.YORUMLIST')
					WITH (
						DERS  VARCHAR(MAX),
						DUZEY VARCHAR(MAX),
						YORUM VARCHAR(MAX),
						ONERI VARCHAR(MAX)
					)
				
					INSERT INTO AbidePuanAralik(ID_ABIDESINAV, MAXIMUMPUAN, DUZEY)
					SELECT @ID_ABIDESINAV, MAXIMUMPUAN, DUZEY FROM OPENJSON(@SQLJSON, '$.PUANARALIKLIST')
					WITH (
						MAXIMUMPUAN INT,
						DUZEY		VARCHAR(MAX)
					)
				
					INSERT INTO AbideBeceri(ID_ABIDESINAV, DERS, BECERI, ACIKLAMA)
					SELECT @ID_ABIDESINAV, DERS, BECERI, ACIKLAMA FROM OPENJSON(@SQLJSON, '$.BECERILIST')
					WITH (
						DERS		VARCHAR(MAX),
						BECERI		VARCHAR(MAX),
						ACIKLAMA	VARCHAR(MAX)
					)
				END
			END

			IF @ISLEM = 6	--	SINAV EXCEL LİSTELE
			BEGIN
				SELECT
				(
					SELECT
					(SELECT [ID_ABIDESORU] ,[ID_ABIDESINAV] ,[DERS] ,[SORUNO] ,[KAZANIM] ,[BECERI] ,[PUAN] ,ID_BILGI = ISNULL([ID_BILGI], 0) ,ID_BILISSELSUREC = ISNULL([ID_BILISSELSUREC], 0) FROM [Pusulam].[dbo].[AbideSoru] WHERE ID_ABIDESINAV = @ID_ABIDESINAV FOR JSON PATH) AS SORULIST,
					(SELECT * FROM [Pusulam].[dbo].[AbideYorum] WHERE ID_ABIDESINAV = @ID_ABIDESINAV FOR JSON PATH) AS YORUMLIST,
					(SELECT * FROM [Pusulam].[dbo].[AbidePuanAralik] WHERE ID_ABIDESINAV = @ID_ABIDESINAV FOR JSON PATH) AS PUANARALIKLIST,
					(SELECT * FROM [Pusulam].[dbo].[AbideBeceri] WHERE ID_ABIDESINAV = @ID_ABIDESINAV FOR JSON PATH) AS BECERILIST
					FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
				)
			END

			IF @ISLEM = 7	--	ÖĞRENCİ LİSTELE
			BEGIN
			

				SELECT
				(
					SELECT	O.OGRNO 
							,O.TCKIMLIKNO
							,K.AD + ' ' + K.SOYAD AS ADSOYAD
							,(	
								SELECT S.DERS, SUM(CASE WHEN AO.PUAN IS NULL THEN 0 ELSE 1 END) AS CEVAPSAYISI 
								FROM AbideSoru S
								LEFT JOIN AbideOgrenci AO ON AO.ID_ABIDESORU = S.ID_ABIDESORU AND AO.TCKIMLIKNO = O.TCKIMLIKNO AND AO.AKTIF = 1
								WHERE S.ID_ABIDESINAV = @_ID_ABIDESINAV
								GROUP BY S.DERS
								FOR JSON PATH
							 ) AS CEVAP
					FROM OkyanusDB.dbo.v3OgrenciTum O
					INNER JOIN OkyanusDB.dbo.v3Kullanici K ON K.TCKIMLIKNO = O.TCKIMLIKNO
					WHERE O.ID_SINIF = @_ID_SINIF AND O.DONEM = @_DONEM
					ORDER BY K.AD + ' ' + K.SOYAD
					FOR JSON PATH
				)
			END

			IF @ISLEM = 8	--	ÖĞRENCİ PUAN LİSTELE
			BEGIN
				SELECT
				(
					SELECT S.ID_ABIDESORU, SK.SORUNO, S.KAZANIM, S.BECERI, S.PUAN AS MAXPUAN, AO.PUAN
					FROM AbideSoru S
					INNER JOIN AbideSoruKarsilik SK ON SK.ID_ABIDESORU = S.ID_ABIDESORU
					LEFT JOIN AbideOgrenci AO ON AO.ID_ABIDESORU = S.ID_ABIDESORU AND AO.TCKIMLIKNO = @O_TCKIMLIKNO AND AO.AKTIF = 1
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV AND S.DERS = @DERS AND (@ID_ABIDEKITAPCIK IS NULL OR SK.ID_ABIDEKITAPCIK = @ID_ABIDEKITAPCIK)
					ORDER BY SK.SORUNO
					FOR JSON PATH, INCLUDE_NULL_VALUES
				)
			END

			IF @ISLEM = 9	--	ÖĞRENCİ PUAN KAYDET
			BEGIN
				UPDATE AbideOgrenci SET AKTIF = 0 WHERE TCKIMLIKNO = @O_TCKIMLIKNO AND ID_ABIDESORU IN (SELECT ID_ABIDESORU FROM OPENJSON(@SQLJSON) WITH (ID_ABIDESORU INT))

				INSERT INTO AbideOgrenci (ID_ABIDESORU, TCKIMLIKNO, PUAN, KYE_TCKIMLIKNO, ID_ABIDEKITAPCIK)
				SELECT ID_ABIDESORU, @O_TCKIMLIKNO, PUAN, @TCKIMLIKNO, @ID_ABIDEKITAPCIK FROM OPENJSON(@SQLJSON)
				WITH
				(
					ID_ABIDESORU INT,
					PUAN INT
				)
				WHERE PUAN IS NOT NULL
			END

			IF @ISLEM = 10	--	ÖĞRENCİ DERS PUAN SİL
			BEGIN
				UPDATE AO SET AO.AKTIF = 0 
				FROM AbideOgrenci AO 
				INNER JOIN AbideSoru S ON S.ID_ABIDESORU = AO.ID_ABIDESORU
				WHERE TCKIMLIKNO = @O_TCKIMLIKNO AND S.DERS = @DERS AND S.ID_ABIDESINAV = @ID_ABIDESINAV
			END

			IF @ISLEM = 11	--	RAPOR SAYFA TUR LİSTELE
			BEGIN
				
				DROP TABLE IF EXISTS #BOLUMNO11
				
				;WITH AB AS (
					SELECT DERS, MIN(ID_ABIDESORU) RN
					FROM AbideSoru
					WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					GROUP BY DERS
				)
				SELECT @ID_ABIDESINAV AS ID_ABIDESINAV, DERS, ROW_NUMBER() OVER(ORDER BY RN) AS BOLUMNO
				INTO #BOLUMNO11
				FROM AB

				SELECT * FROM (
					SELECT(
						SELECT
						(
							SELECT ST.ID_ABIDESAYFATUR
								,ST.AD
								,SIRA		= ISNULL(RD.SIRA, '')
								,RESIMGOR	= ISNULL(RD.RESIMGOR,0)
								,RD.AKTIF
								,ST.RESIMMI
								,RESIMLER	= (	SELECT	 R.ID_ABIDERESIM
														,R.SIRA
														,R.AD
														,R.ID_ABIDESAYFATUR 
														,R.DERS
												FROM AbideResim R 
												WHERE	R.ID_ABIDESAYFATUR	= ST.ID_ABIDESAYFATUR 
													AND R.ID_ABIDESINAV		= @ID_ABIDESINAV 
												ORDER BY SIRA 
												FOR JSON PATH, INCLUDE_NULL_VALUES
											)
							FROM AbideSayfaTur			ST
							LEFT JOIN AbideRaporDuzen	RD	ON	RD.ID_ABIDESAYFATUR = ST.ID_ABIDESAYFATUR 
															AND RD.ID_ABIDESINAV	= @ID_ABIDESINAV 
															AND RD.AKTIF			= 1
							ORDER BY ISNULL(CASE WHEN RD.SIRA = 0 THEN 999 ELSE RD.SIRA END, ST.ID_ABIDESAYFATUR)
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)AS LIST
						,(
							SELECT BOLUMNO, DERS, ID_ABIDESINAV
							FROM #BOLUMNO11
							ORDER BY BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)AS DERSLIST
						FOR JSON PATH, INCLUDE_NULL_VALUES
					)AS LIST
				)AS J
								
				DROP TABLE IF EXISTS #BOLUMNO11

			END

			IF @ISLEM = 12	--	RAPOR SAYFA SIRA KAYDET
			BEGIN
				UPDATE AbideRaporDuzen SET AKTIF = 0 WHERE ID_ABIDESINAV = @ID_ABIDESINAV
				DELETE AbideResim WHERE ID_ABIDESINAV = @ID_ABIDESINAV

				/*		RESIMGOR (Beceri Adı ve Açıklama)
					0 => Resim + Aciklama
					1 => Sadece Aciklama 
					2 => Sadece Resim
				*/

				INSERT INTO AbideRaporDuzen(ID_ABIDESAYFATUR, ID_ABIDESINAV, SIRA, RESIMGOR)
				SELECT ID_ABIDESAYFATUR, @ID_ABIDESINAV, SIRA, RESIMGOR FROM OPENJSON(@SQLJSON)
				WITH
				(
					ID_ABIDESAYFATUR INT,
					RESIMGOR INT,
					SIRA INT
				)

				INSERT INTO AbideResim(ID_ABIDESINAV, ID_ABIDESAYFATUR, AD ,SIRA, DERS)
				SELECT	@ID_ABIDESINAV
						,JSON_Value (S.value, '$.ID_ABIDESAYFATUR') AS ID_ABIDESAYFATUR 
						,JSON_Value (S.value, '$.AD') AS AD 
						,JSON_Value (S.value, '$.SIRA') AS SIRA 
						,JSON_Value (S.value, '$.DERS') AS DERS 
				FROM OPENJSON (@SQLJSON) AS D
				CROSS APPLY OPENJSON (D.value, '$.RESIMLER') AS S
			END

			IF @ISLEM = 13	--	RESİM SİL
			BEGIN
				SELECT
				(
					SELECT AD, ID_ABIDESAYFATUR, ID_ABIDESINAV FROM AbideResim WHERE ID_ABIDERESIM = @ID_ABIDERESIM FOR JSON PATH, WITHOUT_ARRAY_WRAPPER 
				)
				DELETE FROM AbideResim WHERE ID_ABIDERESIM = @ID_ABIDERESIM
			END

			IF @ISLEM = 14	--	RESİM EKLE
			BEGIN
				INSERT INTO AbideResim(ID_ABIDESINAV, ID_ABIDESAYFATUR, AD ,SIRA,DERS)
				SELECT @ID_ABIDESINAV, @ID_ABIDESAYFATUR, @AD, @SIRA, @DERS
			END

			IF @ISLEM = 15	--	ÖĞRENCİ LİSTELE (RAPOR)
			BEGIN
				
				--DECLARE @ID_ABIDESINAV15	INT = @ID_ABIDESINAV
				--DECLARE @ID_SINIF15			INT = @ID_SINIF

				SELECT
				(
					SELECT	O.OGRNO 
							,O.TCKIMLIKNO
							,K.AD + ' ' + K.SOYAD AS ADSOYAD
							,(	
								SELECT COUNT(1) 
								FROM AbideSoru S
								WHERE S.ID_ABIDESINAV = @_ID_ABIDESINAV 
								AND S.ID_ABIDESORU NOT IN (SELECT AO.ID_ABIDESORU FROM AbideOgrenci AO WHERE AO.TCKIMLIKNO = O.TCKIMLIKNO AND AO.AKTIF = 1)
							) AS GIRILMEYENCEVAPSAYISI
					FROM OkyanusDB.dbo.v3OgrenciTum O
					INNER JOIN OkyanusDB.dbo.v3Kullanici K ON K.TCKIMLIKNO = O.TCKIMLIKNO
					WHERE O.ID_SINIF = @_ID_SINIF
					ORDER BY ADSOYAD
					FOR JSON PATH
				)
			END

			IF @ISLEM = 16	--	RAPOR
			BEGIN

				DROP TABLE IF EXISTS #BOLUMNO
				
				;WITH AB AS (
					SELECT DERS, MIN(ID_ABIDESORU) RN
					FROM AbideSoru
					WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					GROUP BY DERS
				)
				SELECT @ID_ABIDESINAV AS ID_ABIDESINAV, DERS, ROW_NUMBER() OVER(ORDER BY RN) AS BOLUMNO
				INTO #BOLUMNO
				FROM AB


				DECLARE @SORUSAYISI INT = (SELECT COUNT(1) FROM AbideSoru WHERE ID_ABIDESINAV = @ID_ABIDESINAV)



				
				SELECT	 K.TCKIMLIKNO
						,O.ID_SINIF
						,AD		= K.AD + ' ' + K.SOYAD
						,SUBE	= SB.AD 
						,SINIF	= S.AD
						,KADEME3= UPPER(K3.AD)
						,ID_KADEME
						,YARIYIL= IIF ( EXISTS (SELECT 1 FROM AbideSinav A WHERE A.ID_ABIDESINAV = @ID_ABIDESINAV AND MONTH(A.KYE_TARIH) IN (9,10,11,12,1)) , '1. DÖNEM' , '2. DÖNEM')
				INTO #OGRENCI
				FROM OkyanusDB.dbo.v3Kullanici			K
				INNER JOIN OkyanusDB.dbo.v3OgrenciTum	O	ON	O.TCKIMLIKNO	= K.TCKIMLIKNO 
				INNER JOIN OkyanusDB.dbo.v3SinifTum		S	ON	S.ID_SINIF		= O.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Sube			SB	ON	SB.ID_SUBE		= O.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3SatisTuru	ST	ON	ST.ID_SATISTURU	= S.ID_SATISTURU
				INNER JOIN OkyanusDB.dbo.v3Kademe3		K3	ON	K3.ID_KADEME3	= ST.ID_KADEME3
				INNER JOIN OkyanusDB.dbo.v3Donem		D	ON	D.ID_DONEM		= O.ID_DONEM
															AND D.KOD			= O.DONEM
				WHERE	O.DONEM = @DONEM
					AND (@ID_SUBE		IS NULL OR @ID_SUBE			= 0  OR O.ID_SUBE	= @ID_SUBE		)
					AND (@ID_SINIF		IS NULL OR @ID_SINIF		= 0  OR O.ID_SINIF	= @ID_SINIF		)
					AND (@O_TCKIMLIKNO	IS NULL OR @O_TCKIMLIKNO	= '' OR K.TCKIMLIKNO= @O_TCKIMLIKNO	)

				SELECT * FROM #OGRENCI

				SELECT ST.ID_ABIDESAYFATUR
						,ST.AD
						,ST.RESIMMI
						,RD.SIRA
						,RD.RESIMGOR
				INTO #DUZEN
				FROM AbideRaporDuzen RD
				INNER JOIN AbideSayfaTur ST ON ST.ID_ABIDESAYFATUR = RD.ID_ABIDESAYFATUR
				WHERE RD.AKTIF = 1 AND RD.SIRA > 0 AND RD.ID_ABIDESINAV = @ID_ABIDESINAV
				
				SELECT * FROM #DUZEN ORDER BY SIRA

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 1)	--	Kapak Sayfa
				BEGIN
					SELECT * FROM AbideResim WHERE ID_ABIDESAYFATUR = 1 AND ID_ABIDESINAV = @ID_ABIDESINAV ORDER BY SIRA
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 2)	--	Önsöz
				BEGIN
					SELECT * FROM AbideResim WHERE ID_ABIDESAYFATUR = 2 AND ID_ABIDESINAV = @ID_ABIDESINAV ORDER BY SIRA
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 3)	--	Rapor Neyi İçerir
				BEGIN
					SELECT * FROM AbideResim WHERE ID_ABIDESAYFATUR = 3 AND ID_ABIDESINAV = @ID_ABIDESINAV ORDER BY SIRA
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 4)	--	Arka Kapak
				BEGIN
					SELECT * FROM AbideResim WHERE ID_ABIDESAYFATUR = 4 AND ID_ABIDESINAV = @ID_ABIDESINAV ORDER BY SIRA
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 5)	--	Beceri Adı ve Açıklama
				BEGIN

				
				/*		RESIMGOR (Beceri Adı ve Açıklama)
					0 => Resim + Aciklama
					1 => Sadece Aciklama 
					2 => Sadece Resim
				*/

					DECLARE @RESIMGOR INT = (SELECT TOP 1 ISNULL(RESIMGOR,0) FROM #DUZEN WHERE ID_ABIDESAYFATUR = 5)
									   
					SELECT T.*,B.BOLUMNO, @RESIMGOR AS RESIMGOR
					FROM AbideBeceri	T
					JOIN #BOLUMNO		B	ON	B.DERS	= T.DERS
					WHERE T.ID_ABIDESINAV = @ID_ABIDESINAV
					ORDER BY DERS, ID_ABIDEBECERI
										
					SELECT R.AD, R.DERS, B.BOLUMNO
					FROM AbideResim R 
					JOIN #BOLUMNO	B	ON	B.DERS	= R.DERS
					WHERE	R.ID_ABIDESINAV		= @ID_ABIDESINAV 
						AND R.ID_ABIDESAYFATUR	= 5
				END
				ELSE
				BEGIN
					SELECT 1
					
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 6)	--	Kazanım ve Alt Becerileri
				BEGIN
					SELECT *
					INTO #TEMP6
					FROM #OGRENCI O
					CROSS JOIN AbideSoru S 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV 
	
					SELECT T.TCKIMLIKNO
							,CASE WHEN AO.ID_ABIDEOGRENCI IS NULL THEN T.SORUNO ELSE (SELECT SK.SORUNO FROM AbideSoruKarsilik SK WHERE SK.ID_ABIDEKITAPCIK = AO.ID_ABIDEKITAPCIK AND SK.ID_ABIDESORU = AO.ID_ABIDESORU) END AS SORUNO
							,T.DERS
							,B.BOLUMNO
							,T.KAZANIM
							,T.BECERI
							,ISNULL((CASE	WHEN T.PUAN = AO.PUAN THEN ':)'
									WHEN AO.PUAN > 0 AND T.PUAN > AO.PUAN THEN ':|'
									WHEN AO.PUAN = 0 THEN ':(' 
								END), '') AS DURUM
					FROM #TEMP6				T
					JOIN #BOLUMNO			B	ON	B.DERS	= T.DERS
					LEFT JOIN AbideOgrenci	AO	ON	AO.TCKIMLIKNO = T.TCKIMLIKNO AND AO.ID_ABIDESORU = T.ID_ABIDESORU AND AO.AKTIF = 1
					ORDER BY TCKIMLIKNO, DERS, SORUNO

					DROP TABLE #TEMP6
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 7)	--	Soruların Çözülme Oranı
				BEGIN
					SELECT *
					INTO #TEMP7
					FROM #OGRENCI O
					CROSS JOIN AbideSoru S 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV 	

					SELECT	 T.DERS
							,B.BOLUMNO
							,CASE WHEN AO.ID_ABIDEOGRENCI IS NULL THEN T.SORUNO ELSE (SELECT SK.SORUNO FROM AbideSoruKarsilik SK WHERE SK.ID_ABIDEKITAPCIK = AO.ID_ABIDEKITAPCIK AND SK.ID_ABIDESORU = AO.ID_ABIDESORU) END AS SORUNO
							,T.TCKIMLIKNO
							,OO.ID_SINIF
							,OO.ID_SUBE
							,AO.PUAN AS PUAN
							,T.PUAN AS MAXPUAN
							,T.ID_ABIDESORU
					INTO #OP
					FROM #TEMP7	T
					JOIN #BOLUMNO			B	ON	B.DERS	= T.DERS
					INNER JOIN OkyanusDB.dbo.v3OgrenciTum OO ON OO.TCKIMLIKNO = T.TCKIMLIKNO AND OO.DONEM = @DONEM
					LEFT JOIN AbideOgrenci AO ON AO.TCKIMLIKNO = T.TCKIMLIKNO AND AO.ID_ABIDESORU = T.ID_ABIDESORU AND AO.AKTIF = 1	

					SELECT   S.DERS
							,B.BOLUMNO
							,SK.SORUNO
							,O.TCKIMLIKNO
							,OO.ID_SINIF
							,OO.ID_SUBE
							,O.PUAN
							,S.PUAN AS MAXPUAN
							,S.ID_ABIDESORU
					INTO #OPGENEL
					FROM AbideOgrenci O
					INNER JOIN AbideSoru S ON S.ID_ABIDESORU = O.ID_ABIDESORU
					JOIN #BOLUMNO			B	ON	B.DERS	= S.DERS
					INNER JOIN OkyanusDB.dbo.v3OgrenciTum OO ON OO.TCKIMLIKNO = O.TCKIMLIKNO AND OO.DONEM = @DONEM
					INNER JOIN AbideSoruKarsilik SK ON SK.ID_ABIDEKITAPCIK = O.ID_ABIDEKITAPCIK AND SK.ID_ABIDESORU = O.ID_ABIDESORU
					WHERE O.AKTIF = 1 AND S.ID_ABIDESINAV = @ID_ABIDESINAV
			
					SELECT	OP.TCKIMLIKNO
							,DERS
							,BOLUMNO
							,SORUNO
							,ID_ABIDESORU
							,OP.ID_SINIF
							,CASE WHEN PUAN IS NULL THEN '-' ELSE CAST(CONVERT(decimal(5,0), CAST(PUAN AS FLOAT) / CAST(MAXPUAN AS FLOAT) * 100.0) AS varchar) END AS OGRENCI 
							,(SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL AS SUBOP WHERE SUBOP.ID_SINIF = OP.ID_SINIF AND SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU) AS SINIF
							,(SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL AS SUBOP WHERE SUBOP.ID_SUBE = OP.ID_SUBE AND SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU) AS OKUL
							,(SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL AS SUBOP WHERE SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU) AS GENEL
					FROM #OP AS OP
					INNER JOIN #OGRENCI O ON O.TCKIMLIKNO = OP.TCKIMLIKNO
					ORDER BY OP.TCKIMLIKNO, DERS, SORUNO

					DROP TABLE #OP
					DROP TABLE #OPGENEL
					DROP TABLE #TEMP7
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 8)	--	Öğrenci Performansı
				BEGIN
					SELECT *
					INTO #TEMP8
					FROM #OGRENCI O
					CROSS JOIN AbideSoru S 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV

					SELECT	T.TCKIMLIKNO
							,T.DERS
							,B.BOLUMNO
							,T.ID_ABIDESINAV
							,SUM(O.PUAN) AS PUAN
							,DUZEY	=	CASE	WHEN SUM(O.PUAN) IS NULL				THEN NULL 
												WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = T.ID_ABIDESINAV), '1') AS VARCHAR)												
												ELSE CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = T.ID_ABIDESINAV), 1) AS VARCHAR) 
										END 
					INTO #DERSPUAN
					FROM #TEMP8 T
					JOIN #BOLUMNO			B	ON	B.DERS	= T.DERS
					LEFT JOIN AbideOgrenci O ON O.TCKIMLIKNO = T.TCKIMLIKNO AND O.ID_ABIDESORU = T.ID_ABIDESORU AND O.AKTIF = 1
					GROUP BY T.TCKIMLIKNO, T.DERS, T.ID_ABIDESINAV,B.BOLUMNO, B.DERS

					SELECT	 DP.TCKIMLIKNO
							,DP.DERS
							,DP.BOLUMNO
							,ISNULL(DP.DUZEY + '. Düzey', '-') AS DUZEY
							,ISNULL(Y.YORUM, '-') AS YORUM
							,ISNULL(Y.ONERI, '-') AS ONERI
					FROM #DERSPUAN DP
					LEFT JOIN AbideYorum Y ON Y.DERS = DP.DERS AND Y.DUZEY = DP.DUZEY AND Y.ID_ABIDESINAV = DP.ID_ABIDESINAV
					ORDER BY DP.TCKIMLIKNO, DP.DERS					
					
					
					SELECT B.BOLUMNO, T.TCKIMLIKNO, T.DERS, T.BECERI, SUM(T.PUAN) MAXPUAN, SUM(O.PUAN) OGRPUAN, CAST( SUM(O.PUAN) / CAST(SUM(T.PUAN) AS float) * 100.0  AS decimal(8,2)) ORT
					FROM #TEMP8			T
					JOIN #BOLUMNO		B	ON	B.DERS			= T.DERS
					JOIN AbideOgrenci	O	ON	O.TCKIMLIKNO	= T.TCKIMLIKNO 
											AND O.ID_ABIDESORU	= T.ID_ABIDESORU 
											AND O.AKTIF			= 1
					GROUP BY B.BOLUMNO, T.TCKIMLIKNO, T.DERS, T.BECERI

					DROP TABLE #DERSPUAN
					DROP TABLE #TEMP8
				END
				ELSE
				BEGIN
					SELECT *
					FROM #BOLUMNO
					
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 9)	--	Grafiksel Gösterim (Her bir ders ayrı)
				BEGIN


--*********************************************************************************
					SELECT	O.TCKIMLIKNO
							,SN.AD AS SINAV
							,S.DERS
							,BOLUMNO = ISNULL(B.BOLUMNO, 999)
							--,ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), 1) AS DUZEY
							
							,DUZEY	=	CASE	WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1') AS VARCHAR) 												
												ELSE CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), 1) AS VARCHAR) 
										END 
					FROM AbideOgrenci O
					INNER JOIN AbideSoru S ON S.ID_ABIDESORU = O.ID_ABIDESORU
					LEFT  JOIN #BOLUMNO			B	ON	B.DERS	= S.DERS
					INNER JOIN AbideSinav SN ON SN.ID_ABIDESINAV = S.ID_ABIDESINAV
					WHERE O.TCKIMLIKNO IN (SELECT TCKIMLIKNO FROM #OGRENCI) AND O.AKTIF = 1 AND SN.AKTIF = 1
					GROUP BY O.TCKIMLIKNO, SN.AD, S.DERS, S.ID_ABIDESINAV,B.BOLUMNO, B.DERS
					ORDER BY O.TCKIMLIKNO, S.DERS, SN.AD DESC
				END
				ELSE
				BEGIN
					SELECT 1
				END

				IF EXISTS (SELECT * FROM #DUZEN WHERE ID_ABIDESAYFATUR = 10)	--	Grafiksel Gösterim (Tek grafikte tüm dersler)
				BEGIN
					SELECT	O.TCKIMLIKNO
							,SN.AD AS SINAV
							,S.DERS
							,BOLUMNO = ISNULL(B.BOLUMNO, 999)
							
							,DUZEY	=	CASE WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1')
											 ELSE ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1') 
										END 
							--,ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), 1) AS DUZEY
							,(SELECT MAX(DUZEY) FROM AbidePuanAralik PA WHERE PA.ID_ABIDESINAV = S.ID_ABIDESINAV) AS MAXDUZEY
					FROM AbideOgrenci		O
					INNER JOIN AbideSoru	S	ON	S.ID_ABIDESORU	 = O.ID_ABIDESORU
					LEFT  JOIN #BOLUMNO		B	ON	B.DERS			 = S.DERS
					INNER JOIN AbideSinav	SN	ON	SN.ID_ABIDESINAV = S.ID_ABIDESINAV
					WHERE O.TCKIMLIKNO IN (SELECT TCKIMLIKNO FROM #OGRENCI) AND O.AKTIF = 1 AND SN.AKTIF = 1
					GROUP BY O.TCKIMLIKNO, SN.AD, S.DERS, S.ID_ABIDESINAV,B.BOLUMNO, B.DERS
					ORDER BY O.TCKIMLIKNO, S.DERS, SN.AD DESC
				END
				ELSE
				BEGIN
					SELECT 1
				END

				SELECT   S.DERS
						,S.SORUNO
						,B.BOLUMNO
				FROM AbideSoru	S				
				JOIN #BOLUMNO	B	ON	B.DERS	= S.DERS
				WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV

				DROP TABLE #DUZEN
				DROP TABLE #OGRENCI
				DROP TABLE #BOLUMNO

			END
						
			IF @ISLEM = 17	--	SINAV LİSTELE by OGRENCI
			BEGIN
				SELECT
				(
					SELECT DISTINCT S.ID_ABIDESINAV, S.AD, CONVERT(varchar, S.KYE_TARIH, 104) AS TARIH, K.AD + ' ' + K.SOYAD AS ADSOYAD,S.KYE_TARIH
					FROM AbideSinav		S 
					JOIN v3Kullanici	K	ON	K.TCKIMLIKNO	= S.KYE_TCKIMLIKNO
					JOIN AbideSoru		SO	ON	SO.ID_ABIDESINAV= S.ID_ABIDESINAV
					JOIN AbideOgrenci	O	ON	O.ID_ABIDESORU	= SO.ID_ABIDESORU
					WHERE	S.DONEM			= @DONEM 
						AND O.TCKIMLIKNO	= @O_TCKIMLIKNO
						AND S.AKTIF			= 1 
						AND S.OVGORSUN		= 1
					ORDER BY S.KYE_TARIH DESC
					FOR JSON PATH
				)
			END

			IF @ISLEM = 18	--	PUAN LİSTESİ GETİR (EXCEL)
			BEGIN
				SELECT DERS, MAX(SORUNO) AS SORUNO 
				FROM AbideSinav S
				INNER JOIN AbideSoru SS ON SS.ID_ABIDESINAV = S.ID_ABIDESINAV 
				WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV
				GROUP BY DERS ORDER BY DERS

				DROP TABLE IF EXISTS #TEMP
				DROP TABLE IF EXISTS #DERS

				SELECT 
						SB.AD AS SUBE
						,K3.AD AS GRUP
						,K.AD + ' ' + K.SOYAD AS ADSOYAD
						,SN.AD AS SINIF
						,SN.ID_SINIF
						,AO.TCKIMLIKNO
						,SORU.DERS
						,SORU.SORUNO
						,AO.PUAN
				INTO #TEMP
				FROM AbideOgrenci AO
				INNER JOIN AbideSoru SORU ON SORU.ID_ABIDESORU = AO.ID_ABIDESORU
				INNER JOIN AbideSinav SINAV ON SINAV.ID_ABIDESINAV = SORU.ID_ABIDESINAV
				INNER JOIN OkyanusDB.dbo.v3Kullanici K ON K.TCKIMLIKNO = AO.TCKIMLIKNO
				INNER JOIN OkyanusDB.dbo.v3OgrenciTum O ON O.TCKIMLIKNO = AO.TCKIMLIKNO AND O.DONEM = SINAV.DONEM
				INNER JOIN OkyanusDB.dbo.v3Sube SB ON SB.ID_SUBE = O.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3SinifTum SN ON SN.ID_SINIF = O.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3SatisTuru ST ON ST.ID_SATISTURU = SN.ID_SATISTURU
				INNER JOIN OkyanusDB.dbo.v3Kademe3 K3 ON K3.ID_KADEME3 = ST.ID_KADEME3
				WHERE	SINAV.ID_ABIDESINAV = @ID_ABIDESINAV 
					AND SINAV.DONEM = @DONEM
					AND SINAV.AKTIF = 1 
					AND AO.AKTIF = 1
					AND (@ID_SUBE	IS NULL OR @ID_SUBE		= 0 OR O.ID_SUBE	= @ID_SUBE)
					AND (@ID_SINIF	IS NULL OR @ID_SINIF	= 0 OR O.ID_SINIF	= @ID_SINIF)

				DECLARE 
						@COLS AS NVARCHAR(MAX),
						@QUERY  AS NVARCHAR(MAX)

				SELECT DERS+'-'+CAST(SORUNO AS VARCHAR) AS DERS
				INTO #DERS
				FROM #TEMP
				GROUP BY DERS, SORUNO
				ORDER BY DERS, SORUNO

				SELECT @COLS = STUFF((SELECT ','+QUOTENAME(DERS2)+' VARCHAR(MAX) DEFAULT ''-''' 
									  FROM (
												SELECT
													T.DERS + '-' + CAST(T.SORUNO AS VARCHAR) AS DERS2
												FROM #TEMP T 
												GROUP BY T.DERS, T.SORUNO
											) AS S
										FOR XML PATH(''), TYPE
										).value('.', 'NVARCHAR(MAX)') 
									,1,1,'')

				SET @QUERY = '
					DROP TABLE IF EXISTS #T
					CREATE TABLE #T (SUBE VARCHAR(MAX), GRUP VARCHAR(MAX), ADSOYAD VARCHAR(MAX), SINIF VARCHAR(MAX), TCKIMLIKNO VARCHAR(MAX),' + @COLS + ')

					INSERT INTO #T (SUBE, GRUP, ADSOYAD, SINIF, TCKIMLIKNO)
					SELECT SUBE, GRUP, ADSOYAD, SINIF, TCKIMLIKNO FROM #TEMP

					WHILE EXISTS ( SELECT *  FROM #DERS)
					BEGIN

						DECLARE @DERSAD VARCHAR(100) = (SELECT TOP(1) DERS FROM #DERS ORDER BY DERS)	
						DECLARE @QUERY2 NVARCHAR(MAX)

						SET @QUERY2=	
						''
							UPDATE T
							SET T.[''+@DERSAD+''] = P.PUAN
							FROM #T T
							JOIN #TEMP P ON T.TCKIMLIKNO = P.TCKIMLIKNO AND P.DERS + ''''-'''' +  CAST(P.SORUNO AS VARCHAR) = ''''''+@DERSAD+''''''
						''
						EXEC sp_executesql @QUERY2; 

						DELETE FROM #DERS WHERE DERS = @DERSAD
					END
					SELECT DISTINCT * FROM #T
					DROP TABLE IF EXISTS #T
				'
				PRINT @QUERY
				EXEC sp_executesql @QUERY; 

				DROP TABLE IF EXISTS #TEMP
				DROP TABLE IF EXISTS #DERS
			END

			IF @ISLEM = 19	--	SINAV KARŞILIK YÜKLE
			BEGIN
				SELECT   ID_ABIDESINAV = JSON_Value (D.value, '$.ID_ABIDESINAV')
						,ID_ABIDESORU = JSON_Value (D.value, '$.ID_ABIDESORU')
						,ID_ABIDEKITAPCIK = JSON_Value (s.value, '$.ID_ABIDEKITAPCIK')
						,KITAPCIK = JSON_Value (s.value, '$.KITAPCIK')
						,SORUNO = JSON_Value (s.value, '$.SORUNO')
				INTO #TEMPKARSILIK
				FROM OPENJSON(@SQLJSON) d
				CROSS APPLY OPENJSON (d.value, '$.KARSILIKLIST') as s

				DELETE SK FROM AbideSoruKarsilik SK
				INNER JOIN AbideSoru S ON S.ID_ABIDESORU = SK.ID_ABIDESORU
				INNER JOIN AbideKitapcik K ON K.ID_ABIDEKITAPCIK = SK.ID_ABIDEKITAPCIK
				WHERE S.ID_ABIDESINAV = (SELECT TOP 1 ID_ABIDESINAV FROM #TEMPKARSILIK) AND K.AD <> 'A'

				--DELETE FROM AbideKitapcik WHERE ID_ABIDESINAV = (SELECT TOP 1 ID_ABIDESINAV FROM #TEMPKARSILIK) AND AD <> 'A'

				--DECLARE @INSERTEDKITAPCIK TABLE(ID_ABIDEKITAPCIK INT NOT NULL, KITAPCIK CHAR(1) NOT NULL);  

				--INSERT INTO AbideKitapcik (ID_ABIDESINAV, AD)
				--OUTPUT inserted.ID_ABIDEKITAPCIK, inserted.ad
				--INTO @INSERTEDKITAPCIK
				--SELECT DISTINCT ID_ABIDESINAV, KITAPCIK
				--FROM #TEMPKARSILIK

				INSERT INTO AbideSoruKarsilik(ID_ABIDESORU, ID_ABIDEKITAPCIK, SORUNO)
				SELECT T.ID_ABIDESORU, T.ID_ABIDEKITAPCIK, T.SORUNO
				FROM #TEMPKARSILIK T

				DROP TABLE #TEMPKARSILIK
			END

			IF @ISLEM = 20	--	SINAV KARŞILIK LİSTELE
			BEGIN
				SELECT
				(	
					SELECT  S.ID_ABIDESINAV, S.DERS, S.ID_ABIDESORU, S.SORUNO, S.KAZANIM, S.BECERI, S.PUAN, 
							(
								SELECT K.ID_ABIDEKITAPCIK, SK.SORUNO, K.AD AS KITAPCIK FROM AbideSoruKarsilik SK
								INNER JOIN AbideKitapcik K ON K.ID_ABIDEKITAPCIK = SK.ID_ABIDEKITAPCIK AND K.ID_ABIDESINAV = S.ID_ABIDESINAV
								WHERE SK.ID_ABIDESORU = S.ID_ABIDESORU AND K.AD <> 'A'
								FOR JSON PATH
							) AS KARSILIKLIST
					FROM AbideSoru S 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV FOR JSON PATH
				)
			END

			IF @ISLEM = 21	--	SINAV KİTAPÇIK LİSTELE
			BEGIN
				SELECT	DISTINCT K.ID_ABIDEKITAPCIK
						,K.AD
						,CASE WHEN EXISTS(	
							SELECT 1 
							FROM AbideOgrenci O 
							INNER JOIN AbideSoru S ON S.ID_ABIDESORU = O.ID_ABIDESORU
							WHERE O.ID_ABIDEKITAPCIK = K.ID_ABIDEKITAPCIK AND S.DERS = @DERS AND O.TCKIMLIKNO = @O_TCKIMLIKNO AND O.AKTIF = 1
						)
						THEN 1
						ELSE 0 
						END AS SECILI
				INTO #TEMPKITAPCIKSEC
				FROM AbideKitapcik K
				WHERE K.ID_ABIDESINAV = @ID_ABIDESINAV

				--IF NOT EXISTS (SELECT * FROM #TEMPKITAPCIKSEC WHERE SECILI = 1)
				--BEGIN
				--	UPDATE #TEMPKITAPCIKSEC SET SECILI = 1 WHERE AD = 'A'
				--END

				SELECT
				(
					SELECT * FROM #TEMPKITAPCIKSEC
					ORDER BY AD
					FOR JSON PATH
				)

				DROP TABLE #TEMPKITAPCIKSEC
			END

			IF @ISLEM = 22	--	PUANA GÖRE SIRALI GENEL SONUÇ LİSTELERİ
			BEGIN
				SELECT SNV.ID_ABIDESINAV, SB.AD AS KAMPUS, SNF.AD AS SINIF, O.TCKIMLIKNO, KO.AD + ' ' + KO.SOYAD AS ADSOYAD, S.DERS, K.AD AS KITAPCIK, SK.SORUNO, S.PUAN AS MAXPUAN, O.PUAN
				INTO #OGRENCISORULIST
				FROM AbideSinav							SNV 
				INNER JOIN AbideSoru					S	ON S.ID_ABIDESINAV = SNV.ID_ABIDESINAV
				INNER JOIN AbideKitapcik				K	ON K.ID_ABIDESINAV = SNV.ID_ABIDESINAV 
				INNER JOIN AbideOgrenci					O	ON O.ID_ABIDESORU = S.ID_ABIDESORU AND O.ID_ABIDEKITAPCIK = K.ID_ABIDEKITAPCIK AND O.AKTIF = 1
				INNER JOIN AbideSoruKarsilik			SK	ON SK.ID_ABIDESORU = S.ID_ABIDESORU AND SK.ID_ABIDEKITAPCIK = O.ID_ABIDEKITAPCIK
				INNER JOIN OkyanusDB.dbo.v3OgrenciTum	OO	ON OO.TCKIMLIKNO = O.TCKIMLIKNO AND OO.DONEM = SNV.DONEM
				INNER JOIN OkyanusDB.dbo.v3Sube			SB	ON SB.ID_SUBE = OO.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3SinifTum		SNF ON SNF.ID_SINIF = OO.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3SubeGrupSinifTum SGS ON SGS.ID_SINIF = SNF.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KO	ON KO.TCKIMLIKNO = OO.TCKIMLIKNO
				WHERE SNV.ID_ABIDESINAV = @ID_ABIDESINAV AND (@ID_KADEME3 = 0 OR SGS.ID_KADEME3 = @ID_KADEME3)

				SELECT * 
				FROM #OGRENCISORULIST
				ORDER BY KAMPUS, SINIF, TCKIMLIKNO, DERS, SORUNO

				SELECT 
					 TCKIMLIKNO
					,DERS
					,SUM(PUAN) AS TOPLAMPUAN
					,SUM(MAXPUAN) AS TOPLAMMAXPUAN
					,MAX(SORUNO) AS SORUSAYISI
					--,ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = O.ID_ABIDESINAV), 1) AS DUZEY					
					,DUZEY	=	CASE WHEN O.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') 
										THEN ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = O.ID_ABIDESINAV), '1')  
									 ELSE ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = O.ID_ABIDESINAV),'1') 
								END 
				INTO #OGRENCILIST
				FROM #OGRENCISORULIST O
				GROUP BY TCKIMLIKNO, DERS, ID_ABIDESINAV


				SELECT   TCKIMLIKNO
						,DERS
						,TOPLAMPUAN
						,DUZEY 
						,SORUSAYISI
						,TOPLAMMAXPUAN
				FROM #OGRENCILIST ORDER BY DERS, TCKIMLIKNO DESC

				SELECT DERS, SORUSAYISI, TOPLAMMAXPUAN FROM #OGRENCILIST GROUP BY DERS, SORUSAYISI, TOPLAMMAXPUAN ORDER BY DERS

				DROP TABLE #OGRENCISORULIST
				DROP TABLE #OGRENCILIST
			END

			IF @ISLEM = 23	--	SINIFLARA GÖRE SORULARIN ÇÖZÜLME ORANLARI
			BEGIN
				SELECT SNV.ID_ABIDESINAV, SB.AD AS KAMPUS, SNF.AD AS SINIF, O.TCKIMLIKNO, KO.AD + ' ' + KO.SOYAD AS ADSOYAD, S.DERS, S.ID_ABIDESORU, S.SORUNO, S.PUAN AS MAXPUAN, O.PUAN
				INTO #OGRENCISORULIST2
				FROM AbideSinav							SNV 
				INNER JOIN AbideSoru					S	ON S.ID_ABIDESINAV = SNV.ID_ABIDESINAV
				INNER JOIN AbideKitapcik				K	ON K.ID_ABIDESINAV = SNV.ID_ABIDESINAV 
				INNER JOIN AbideOgrenci					O	ON O.ID_ABIDESORU = S.ID_ABIDESORU AND O.ID_ABIDEKITAPCIK = K.ID_ABIDEKITAPCIK AND O.AKTIF = 1
				INNER JOIN OkyanusDB.dbo.v3OgrenciTum	OO	ON OO.TCKIMLIKNO = O.TCKIMLIKNO AND OO.DONEM = SNV.DONEM
				INNER JOIN OkyanusDB.dbo.v3Sube			SB	ON SB.ID_SUBE = OO.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3SinifTum		SNF ON SNF.ID_SINIF = OO.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3SubeGrupSinifTum SGS ON SGS.ID_SINIF = SNF.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KO	ON KO.TCKIMLIKNO = OO.TCKIMLIKNO
				WHERE SNV.ID_ABIDESINAV = @ID_ABIDESINAV AND (@ID_KADEME3 = 0 OR SGS.ID_KADEME3 = @ID_KADEME3)

				SELECT OS.DERS, OS.SORUNO, S.BECERI, S.KAZANIM, OS.KAMPUS, OS.SINIF, CONVERT(decimal(18,2), (CAST(SUM(OS.PUAN) AS FLOAT) / CAST(SUM(OS.MAXPUAN) AS FLOAT) * 100.0)) AS ORAN
				FROM #OGRENCISORULIST2 OS
				INNER JOIN AbideSoru S ON S.ID_ABIDESORU = OS.ID_ABIDESORU
				GROUP BY OS.DERS, OS.SORUNO, S.BECERI, S.KAZANIM, OS.KAMPUS, OS.SINIF
				
				SELECT OS.DERS, OS.SORUNO, S.BECERI, S.KAZANIM, 'GENEL', 'GENEL', CONVERT(decimal(18,2), (CAST(SUM(OS.PUAN) AS FLOAT) / CAST(SUM(OS.MAXPUAN) AS FLOAT) * 100.0)) AS ORAN
				FROM #OGRENCISORULIST2 OS
				INNER JOIN AbideSoru S ON S.ID_ABIDESORU = OS.ID_ABIDESORU
				GROUP BY OS.DERS, OS.SORUNO, S.BECERI, S.KAZANIM
				ORDER BY DERS, SORUNO
				
				SELECT KAMPUS, SINIF FROM #OGRENCISORULIST2 GROUP BY KAMPUS, SINIF ORDER BY KAMPUS, SINIF
				SELECT DERS, MAX(SORUNO) AS SORUSAYISI FROM #OGRENCISORULIST2 GROUP BY DERS ORDER BY DERS

				DROP TABLE #OGRENCISORULIST2
			END

			IF @ISLEM = 24	--	Yeterlilik Düzeylerine Göre Kampüs Öğrenci Sayıları
			BEGIN
			
				DECLARE @ID_KADEME3_ INT = @ID_KADEME3
				DECLARE @ID_ABIDESINAV_ INT = @ID_ABIDESINAV
				DECLARE @DONEM_ VARCHAR(4) = @DONEM

				SELECT SNV.ID_ABIDESINAV, SNV.AD AS SINAVAD, SB.AD AS KAMPUS, SNF.AD AS SINIF, O.TCKIMLIKNO, KO.AD + ' ' + KO.SOYAD AS ADSOYAD, S.DERS, S.ID_ABIDESORU, S.SORUNO, S.PUAN AS MAXPUAN, O.PUAN
				INTO #OGRENCISORULIST3
				FROM AbideSinav							SNV 
				INNER JOIN AbideSoru					S	ON S.ID_ABIDESINAV = SNV.ID_ABIDESINAV
				INNER JOIN AbideKitapcik				K	ON K.ID_ABIDESINAV = SNV.ID_ABIDESINAV 
				INNER JOIN AbideOgrenci					O	ON O.ID_ABIDESORU = S.ID_ABIDESORU AND O.ID_ABIDEKITAPCIK = K.ID_ABIDEKITAPCIK AND O.AKTIF = 1
				INNER JOIN OkyanusDB.dbo.v3OgrenciTum	OO	ON OO.TCKIMLIKNO = O.TCKIMLIKNO AND OO.DONEM = SNV.DONEM
				INNER JOIN OkyanusDB.dbo.v3Sube			SB	ON SB.ID_SUBE = OO.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3SinifTum		SNF ON SNF.ID_SINIF = OO.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3SubeGrupSinifTum SGS ON SGS.ID_SINIF = SNF.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KO	ON KO.TCKIMLIKNO = OO.TCKIMLIKNO
				WHERE SGS.ID_KADEME3 = @ID_KADEME3 AND (@ID_ABIDESINAV = 0 OR SNV.ID_ABIDESINAV = @ID_ABIDESINAV) AND SNV.DONEM = @DONEM

				SELECT 
					 SINAVAD
					,DERS
					,KAMPUS
					,TCKIMLIKNO					
					,DUZEY	=	CASE WHEN O.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') 
										THEN ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = O.ID_ABIDESINAV), '1')  
								  	 ELSE ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = O.ID_ABIDESINAV),'1') 
								END 
				INTO #OGRENCILIST3
				FROM #OGRENCISORULIST3 O
				GROUP BY KAMPUS, TCKIMLIKNO, DERS, ID_ABIDESINAV, SINAVAD
				ORDER BY SINAVAD, DERS, KAMPUS, TCKIMLIKNO

				--DÜZEY ÖĞRENCİ SAYILARI KAMPÜS--
				SELECT DERS, SINAVAD, KAMPUS, DUZEY, COUNT(1) AS DUZEYOGRENCISAYISI
				INTO #KAMPUSDUZEYOGRENCISAYILIST
				FROM #OGRENCILIST3
				GROUP BY DERS, SINAVAD, KAMPUS, DUZEY
				ORDER BY DERS, SINAVAD, KAMPUS, DUZEY

				--TOPLAM ÖĞRENCİ SAYILARI KAMPÜS--
				SELECT DERS, KAMPUS, COUNT(1) AS TOPLAMOGRENCISAYISI
				INTO #KAMPUSTOPLAMOGRENCISAYILIST
				FROM #OGRENCILIST3
				GROUP BY DERS, KAMPUS
				ORDER BY DERS, KAMPUS

				--DÜZEY ÖĞRENCİ SAYILARI--
				SELECT DERS, SINAVAD, DUZEY, COUNT(1) AS DUZEYOGRENCISAYISI
				INTO #DUZEYOGRENCISAYILIST
				FROM #OGRENCILIST3
				GROUP BY DERS, SINAVAD, DUZEY
				ORDER BY DERS, SINAVAD, DUZEY

				--TOPLAM ÖĞRENCİ SAYILARI--
				SELECT DERS, COUNT(1) AS TOPLAMOGRENCISAYISI
				INTO #TOPLAMOGRENCISAYILIST
				FROM #OGRENCILIST3
				GROUP BY DERS
				ORDER BY DERS

				--SONUÇ--
				SELECT 1 AS TUR, TOS.DERS, TOS.KAMPUS, TOS.TOPLAMOGRENCISAYISI, DOS.DUZEY, DOS.SINAVAD, DOS.DUZEYOGRENCISAYISI, CONVERT(DECIMAL(18,2), (CAST(DOS.DUZEYOGRENCISAYISI AS FLOAT) / CAST(TOS.TOPLAMOGRENCISAYISI AS FLOAT) * 100.0)) AS ORAN
				FROM #KAMPUSDUZEYOGRENCISAYILIST DOS
				INNER JOIN #KAMPUSTOPLAMOGRENCISAYILIST TOS ON TOS.KAMPUS = DOS.KAMPUS AND TOS.DERS = DOS.DERS
				UNION
				SELECT 2 AS TUR, TOS.DERS, 'TOPLAM', TOS.TOPLAMOGRENCISAYISI, DOS.DUZEY, DOS.SINAVAD, DOS.DUZEYOGRENCISAYISI, CONVERT(DECIMAL(18,2), (CAST(DOS.DUZEYOGRENCISAYISI AS FLOAT) / CAST(TOS.TOPLAMOGRENCISAYISI AS FLOAT) * 100.0)) AS ORAN
				FROM #DUZEYOGRENCISAYILIST DOS
				INNER JOIN #TOPLAMOGRENCISAYILIST TOS ON TOS.DERS = DOS.DERS
				ORDER BY DERS, TUR, KAMPUS, SINAVAD, DUZEY

				SELECT DUZEY FROM #DUZEYOGRENCISAYILIST GROUP BY DUZEY ORDER BY DUZEY
				SELECT KAMPUS FROM #KAMPUSDUZEYOGRENCISAYILIST GROUP BY KAMPUS ORDER BY KAMPUS
				SELECT SINAVAD FROM #DUZEYOGRENCISAYILIST GROUP BY SINAVAD ORDER BY SINAVAD
				SELECT DERS FROM #DUZEYOGRENCISAYILIST GROUP BY DERS ORDER BY DERS

				DROP TABLE #OGRENCISORULIST3
				DROP TABLE #OGRENCILIST3
				DROP TABLE #KAMPUSDUZEYOGRENCISAYILIST
				DROP TABLE #KAMPUSTOPLAMOGRENCISAYILIST
				DROP TABLE #DUZEYOGRENCISAYILIST
				DROP TABLE #TOPLAMOGRENCISAYILIST
			END
						
			IF @ISLEM = 25	--	OVGORSUN DEĞİŞTİR
			BEGIN
				UPDATE AbideSinav SET OVGORSUN = @OVGORSUN WHERE ID_ABIDESINAV = @ID_ABIDESINAV

				select 1
			END

			IF @ISLEM = 26	--	RAPOR ÖĞRENCİ HTML(JSON)
			BEGIN
				DROP TABLE IF EXISTS #BOLUMNO26
				DROP TABLE IF EXISTS #DUZEN26
				DROP TABLE IF EXISTS #OGRENCI26
				DROP TABLE IF EXISTS #TEMP5_1_26
				DROP TABLE IF EXISTS #TEMP5_2_26
				DROP TABLE IF EXISTS #TEMP6_26
				DROP TABLE IF EXISTS #TEMP7_26
				DROP TABLE IF EXISTS #TEMP8_1_26
				DROP TABLE IF EXISTS #TEMP8_2_26
				DROP TABLE IF EXISTS #TEMP9_26
				DROP TABLE IF EXISTS #TEMP10_26
				--DROP TABLE IF EXISTS #TEMP_SON_26
				
				;WITH AB AS (
					SELECT DERS, MIN(ID_ABIDESORU) RN
					FROM AbideSoru
					WHERE ID_ABIDESINAV = @ID_ABIDESINAV
					GROUP BY DERS
				)
				SELECT @ID_ABIDESINAV AS ID_ABIDESINAV, DERS, ROW_NUMBER() OVER(ORDER BY RN) AS BOLUMNO
				INTO #BOLUMNO26
				FROM AB
				ORDER BY BOLUMNO

				--DECLARE @SORUSAYISI INT = (SELECT COUNT(1) FROM AbideSoru WHERE ID_ABIDESINAV = @ID_ABIDESINAV)
				
				SELECT DISTINCT
					 TCKIMLIKNO	= OD.TCKIMLIKNO
					,ID_SINIF	= OD.ID_SINIF
					,AD			= OD.AD + ' ' + OD.SOYAD
					,SUBE		= OD.SUBEAD
					,SINIF		= OD.SINIFAD
					,KADEME3	= UPPER(OD.KADEME3)
					,ID_KADEME	= KB.ID_KADEME
					,YARIYIL	= IIF ( EXISTS (SELECT TOP 1 1 FROM AbideSinav A WHERE A.ID_ABIDESINAV = @ID_ABIDESINAV AND MONTH(A.KYE_TARIH) IN (9,10,11,12,1)) , '1. DÖNEM' , '2. DÖNEM')
				INTO #OGRENCI26
				FROM OkyanusDB..vw_OgrenciDetayTum	OD
				JOIN OkyanusDB..v3KademeBilgi		KB	ON	KB.ID_KADEME3	= OD.ID_KADEME3
				WHERE	OD.DONEM = @_DONEM
					AND (@ID_SUBE		IS NULL OR @ID_SUBE			= 0  OR OD.ID_SUBE		= @ID_SUBE		)
					AND (@ID_SINIF		IS NULL OR @ID_SINIF		= 0  OR OD.ID_SINIF		= @ID_SINIF		)
					AND (@O_TCKIMLIKNO	IS NULL OR @O_TCKIMLIKNO	= '' OR OD.TCKIMLIKNO	= @O_TCKIMLIKNO	)
	
				SELECT	 ST.ID_ABIDESAYFATUR
						,ST.AD
						,ST.RESIMMI
						,RD.SIRA
						,RD.RESIMGOR
				INTO #DUZEN26
				FROM AbideRaporDuzen	RD
				JOIN AbideSayfaTur		ST	ON	ST.ID_ABIDESAYFATUR	= RD.ID_ABIDESAYFATUR
				WHERE	RD.AKTIF		= 1 
					AND RD.SIRA			> 0 
					AND RD.ID_ABIDESINAV= @ID_ABIDESINAV
					AND ST.ID_ABIDESAYFATUR NOT IN (1,2,3,4)

				
				-- CREATE TEMP TABLE
				BEGIN
				CREATE TABLE #TEMP5_1_26 
				(	
					 ID_ABIDEBECERI	INT
					,ID_ABIDESINAV	INT
					,DERS			VARCHAR(MAX)
					,BECERI			VARCHAR(MAX)
					,ACIKLAMA		VARCHAR(MAX)
					,BOLUMNO		INT
					,RESIMGOR		INT
				)

				CREATE TABLE #TEMP5_2_26 (
					AD	VARCHAR(MAX),
					DERS		VARCHAR(MAX),
					BOLUMNO		INT
				)
				END
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 5)	--	Beceri Adı ve Açıklama							
				BEGIN

				
				/*		RESIMGOR (Beceri Adı ve Açıklama)
					0 => Resim + Aciklama
					1 => Sadece Aciklama 
					2 => Sadece Resim
				*/

					DECLARE @RESIMGOR_26 INT = (SELECT TOP 1 ISNULL(RESIMGOR,0) FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 5)
									   
					INSERT INTO #TEMP5_1_26
					SELECT	 T.ID_ABIDEBECERI
							,T.ID_ABIDESINAV
							,T.DERS
							,T.BECERI
							,T.ACIKLAMA
							,B.BOLUMNO
							,RESIMGOR	= @RESIMGOR_26
					FROM AbideBeceri	T
					JOIN #BOLUMNO26		B	ON	B.DERS	= T.DERS
					WHERE T.ID_ABIDESINAV = @ID_ABIDESINAV
					ORDER BY DERS, ID_ABIDEBECERI
										
					INSERT INTO #TEMP5_2_26
					SELECT R.AD, R.DERS, B.BOLUMNO
					FROM AbideResim R 
					JOIN #BOLUMNO26	B	ON	B.DERS	= R.DERS
					WHERE	R.ID_ABIDESINAV		= @ID_ABIDESINAV 
						AND R.ID_ABIDESAYFATUR	= 5
				END

				-- CREATE TEMP TABLE
				CREATE TABLE #TEMP6_26 (
					TCKIMLIKNO	VARCHAR(MAX),
					SORUNO		INT,
					DERS		VARCHAR(MAX),
					BOLUMNO		INT,
					KAZANIM		VARCHAR(MAX),
					BECERI		VARCHAR(MAX),
					DURUM		VARCHAR(2),
				)
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 6)	--	Kazanım ve Alt Becerileri						
				BEGIN

	
					;WITH TEMP6 AS(
						SELECT O.TCKIMLIKNO, S.SORUNO, S.DERS, S.KAZANIM, S.BECERI, S.PUAN, S.ID_ABIDESORU		
						FROM #OGRENCI26		 O
						CROSS JOIN AbideSoru S 
						WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV 
					)
					INSERT INTO #TEMP6_26
					SELECT   T.TCKIMLIKNO
							,SORUNO	= CASE WHEN AO.ID_ABIDEOGRENCI IS NULL THEN T.SORUNO ELSE (SELECT SK.SORUNO FROM AbideSoruKarsilik SK WHERE SK.ID_ABIDEKITAPCIK = AO.ID_ABIDEKITAPCIK AND SK.ID_ABIDESORU = AO.ID_ABIDESORU) END 
							,T.DERS
							,B.BOLUMNO
							,T.KAZANIM
							,T.BECERI
							,DURUM	= ISNULL((CASE	WHEN T.PUAN = AO.PUAN THEN ':)'
													WHEN AO.PUAN > 0 AND T.PUAN > AO.PUAN THEN ':|'
													WHEN AO.PUAN = 0 THEN ':(' 
												END), '')
					FROM TEMP6				T
					JOIN #BOLUMNO26			B	ON	B.DERS			= T.DERS
					LEFT JOIN AbideOgrenci	AO	ON	AO.TCKIMLIKNO	= T.TCKIMLIKNO 
												AND AO.ID_ABIDESORU = T.ID_ABIDESORU 
												AND AO.AKTIF		= 1
					ORDER BY TCKIMLIKNO, DERS, SORUNO

				END


				-- CREATE TEMP TABLE
				CREATE TABLE #TEMP7_26 (
					TCKIMLIKNO		VARCHAR(MAX),
					DERS			VARCHAR(MAX),
					BOLUMNO			INT,
					SORUNO			INT,
					ID_ABIDESORU	INT,
					ID_SINIF		INT,
					OGRENCI			VARCHAR(MAX),
					SINIF			decimal(5,0),
					OKUL			decimal(5,0),
					GENEL			decimal(5,0)
				)
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 7)	--	Soruların Çözülme Oranı							
				BEGIN
	
					WITH TEMP7 AS (
						SELECT O.TCKIMLIKNO, S.DERS, S.SORUNO, S.PUAN, S.ID_ABIDESORU	
						FROM #OGRENCI26 O
						CROSS JOIN AbideSoru S 
						WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV 	
					)
					SELECT	 T.DERS
							,B.BOLUMNO
							,SORUNO	= CASE WHEN AO.ID_ABIDEOGRENCI IS NULL THEN T.SORUNO ELSE (SELECT SK.SORUNO FROM AbideSoruKarsilik SK WHERE SK.ID_ABIDEKITAPCIK = AO.ID_ABIDEKITAPCIK AND SK.ID_ABIDESORU = AO.ID_ABIDESORU) END
							,T.TCKIMLIKNO
							,OO.ID_SINIF
							,OO.ID_SUBE
							,AO.PUAN
							,MAXPUAN	= T.PUAN 
							,T.ID_ABIDESORU
					INTO #OP26
					FROM TEMP7	T
					JOIN #BOLUMNO26							B	ON	B.DERS			= T.DERS
					INNER JOIN OkyanusDB.dbo.v3OgrenciTum	OO	ON	OO.TCKIMLIKNO	= T.TCKIMLIKNO 
																AND OO.DONEM		= @_DONEM
					LEFT JOIN AbideOgrenci					AO	ON	AO.TCKIMLIKNO	= T.TCKIMLIKNO 
																AND AO.ID_ABIDESORU = T.ID_ABIDESORU 
																AND AO.AKTIF		= 1	

					SELECT   S.DERS
							,B.BOLUMNO
							,SK.SORUNO
							,O.TCKIMLIKNO
							,OO.ID_SINIF
							,OO.ID_SUBE
							,O.PUAN
							,MAXPUAN	= S.PUAN 
							,S.ID_ABIDESORU
					INTO #OPGENEL26
					FROM AbideOgrenci						O
					INNER JOIN AbideSoru					S	ON	S.ID_ABIDESORU		= O.ID_ABIDESORU
					JOIN #BOLUMNO26							B	ON	B.DERS				= S.DERS
					INNER JOIN OkyanusDB.dbo.v3OgrenciTum	OO	ON	OO.TCKIMLIKNO		= O.TCKIMLIKNO 
																AND OO.DONEM			= @_DONEM
					INNER JOIN AbideSoruKarsilik			SK	ON	SK.ID_ABIDEKITAPCIK = O.ID_ABIDEKITAPCIK 
																AND SK.ID_ABIDESORU		= O.ID_ABIDESORU
					WHERE	O.AKTIF			= 1 
						AND S.ID_ABIDESINAV = @ID_ABIDESINAV
			
					INSERT INTO #TEMP7_26
					SELECT	OP.TCKIMLIKNO
							,DERS
							,BOLUMNO
							,SORUNO
							,ID_ABIDESORU
							,OP.ID_SINIF
							,OGRENCI= CASE WHEN PUAN IS NULL THEN '-' ELSE CAST(CONVERT(decimal(5,0), CAST(PUAN AS FLOAT) / CAST(MAXPUAN AS FLOAT) * 100.0) AS varchar) END 
							,SINIF	= (SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL26 AS SUBOP WHERE SUBOP.ID_SINIF = OP.ID_SINIF AND SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU)
							,OKUL	= (SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL26 AS SUBOP WHERE SUBOP.ID_SUBE = OP.ID_SUBE AND SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU)
							,GENEL	= (SELECT CONVERT(decimal(5,0), CAST(SUM(PUAN) AS FLOAT) / CAST(SUM(MAXPUAN) AS FLOAT) * 100.0) FROM #OPGENEL26 AS SUBOP WHERE SUBOP.DERS = OP.DERS AND SUBOP.ID_ABIDESORU = OP.ID_ABIDESORU GROUP BY SUBOP.DERS, SUBOP.ID_ABIDESORU)
					FROM #OP26			OP
					INNER JOIN #OGRENCI26 O	ON	O.TCKIMLIKNO	= OP.TCKIMLIKNO
					ORDER BY OP.TCKIMLIKNO, DERS, SORUNO

					DROP TABLE IF EXISTS #OP26
					DROP TABLE IF EXISTS #OPGENEL26
				END

				-- CREATE TEMP TABLE
				CREATE TABLE #TEMP8_1_26 (
					TCKIMLIKNO	VARCHAR(MAX),
					DERS		VARCHAR(MAX),
					BOLUMNO		INT,
					DUZEY		VARCHAR(MAX),
					YORUM		VARCHAR(MAX),
					ONERI		VARCHAR(MAX)
				)
				CREATE TABLE #TEMP8_2_26 (
					BOLUMNO		INT,
					TCKIMLIKNO	VARCHAR(MAX),
					DERS		VARCHAR(MAX),
					BECERI		VARCHAR(MAX),
					MAXPUAN		INT,
					OGRPUAN		INT,
					ORT			decimal(8,2)
				)
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 8)	--	Öğrenci Performansı								
				BEGIN
					SELECT O.TCKIMLIKNO, S.DERS, S.ID_ABIDESINAV, S.ID_ABIDESORU, S.BECERI, S.PUAN
					INTO #TEMP8_26
					FROM #OGRENCI26 O
					CROSS JOIN AbideSoru S 
					WHERE S.ID_ABIDESINAV = @ID_ABIDESINAV

					SELECT	T.TCKIMLIKNO
							,T.DERS
							,B.BOLUMNO
							,T.ID_ABIDESINAV
							,SUM(O.PUAN) AS PUAN
							,DUZEY	=	CASE	WHEN SUM(O.PUAN) IS NULL				THEN NULL 
												WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = T.ID_ABIDESINAV), '1') AS VARCHAR)												
												ELSE CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = T.ID_ABIDESINAV), 1) AS VARCHAR) 
										END 
					INTO #DERSPUAN26
					FROM #TEMP8_26			T
					JOIN #BOLUMNO26			B	ON	B.DERS			= T.DERS
					LEFT JOIN AbideOgrenci	O	ON	O.TCKIMLIKNO	= T.TCKIMLIKNO 
												AND O.ID_ABIDESORU	= T.ID_ABIDESORU 
												AND O.AKTIF			= 1
					GROUP BY T.TCKIMLIKNO, T.DERS, T.ID_ABIDESINAV,B.BOLUMNO, B.DERS

					INSERT INTO #TEMP8_1_26
					SELECT	 DP.TCKIMLIKNO
							,DP.DERS
							,DP.BOLUMNO
							,DUZEY	= ISNULL(DP.DUZEY + '. Düzey', '-')
							,YORUM	= REPLACE( ISNULL(Y.YORUM, '-'),N'*','<br>*') 
							,ONERI	= REPLACE( ISNULL(Y.ONERI, '-'),N'*','<br>*')
					FROM #DERSPUAN26 DP
					LEFT JOIN AbideYorum Y ON Y.DERS = DP.DERS AND Y.DUZEY = DP.DUZEY AND Y.ID_ABIDESINAV = DP.ID_ABIDESINAV
					ORDER BY DP.TCKIMLIKNO, DP.DERS					
					
					
					INSERT INTO #TEMP8_2_26
					SELECT	 B.BOLUMNO
							,T.TCKIMLIKNO
							, T.DERS
							, T.BECERI
							, SUM(T.PUAN) MAXPUAN
							, SUM(O.PUAN) OGRPUAN
							, CAST( SUM(O.PUAN) / CAST(SUM(T.PUAN) AS float) * 100.0  AS decimal(8,2)) ORT
					FROM #TEMP8_26		T
					JOIN #BOLUMNO26		B	ON	B.DERS			= T.DERS
					JOIN AbideOgrenci	O	ON	O.TCKIMLIKNO	= T.TCKIMLIKNO 
											AND O.ID_ABIDESORU	= T.ID_ABIDESORU 
											AND O.AKTIF			= 1
					GROUP BY B.BOLUMNO, T.TCKIMLIKNO, T.DERS, T.BECERI

					DROP TABLE IF EXISTS #DERSPUAN26
					DROP TABLE IF EXISTS #TEMP8_26
				END		

				-- CREATE TEMP TABLE
				CREATE TABLE #TEMP9_26 (
					TCKIMLIKNO	VARCHAR(MAX),
					SINAV		VARCHAR(MAX),
					DERS		VARCHAR(MAX),
					BOLUMNO		INT,
					DUZEY		VARCHAR(MAX)
				)
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 9)	--	Grafiksel Gösterim (Her bir ders ayrı)			
				BEGIN

					INSERT INTO #TEMP9_26
					SELECT	 O.TCKIMLIKNO
							,SN.AD AS SINAV
							,S.DERS
							,BOLUMNO = ISNULL(B.BOLUMNO, 999)							
							,DUZEY	=	CASE	WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN 
													CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1') AS VARCHAR) 												
												ELSE 
													CAST(ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), 1) AS VARCHAR) 
										END 	
					FROM AbideOgrenci		O
					INNER JOIN #OGRENCI26		SO	ON	SO.TCKIMLIKNO		= O.TCKIMLIKNO
					INNER JOIN AbideSoru	S	ON	S.ID_ABIDESORU		= O.ID_ABIDESORU
					LEFT  JOIN #BOLUMNO26		B	ON	B.DERS				= S.DERS
					INNER JOIN AbideSinav	SN	ON	SN.ID_ABIDESINAV	= S.ID_ABIDESINAV
					WHERE	O.AKTIF = 1 
						AND SN.AKTIF = 1
						--AND EXISTS (SELECT TOP 1 1 FROM #OGRENCI26 SO WHERE SO.TCKIMLIKNO = O.TCKIMLIKNO) 
					GROUP BY O.TCKIMLIKNO, SN.AD, S.DERS, S.ID_ABIDESINAV,B.BOLUMNO, B.DERS
					ORDER BY O.TCKIMLIKNO, S.DERS, SN.AD DESC

				END

				-- CREATE TEMP TABLE
				CREATE TABLE #TEMP10_26 (
					TCKIMLIKNO	VARCHAR(MAX),
					SINAV		VARCHAR(MAX),
					DERS		VARCHAR(MAX),
					BOLUMNO		INT,
					DUZEY		VARCHAR(MAX),
					MAXDUZEY	VARCHAR(MAX)
				)
				IF EXISTS (SELECT TOP 1 1 FROM #DUZEN26 WHERE ID_ABIDESAYFATUR = 10)--	Grafiksel Gösterim (Tek grafikte tüm dersler)	
				BEGIN
					INSERT INTO #TEMP10_26
					SELECT	 O.TCKIMLIKNO
							,SINAV		= SN.AD
							,S.DERS
							,BOLUMNO	= ISNULL(B.BOLUMNO, 999)
							
							,DUZEY		=	CASE WHEN B.DERS IN ('Türkçe', 'Türk Dili ve Edebiyatı', 'Fen Bilimleri') THEN 
													 ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE DUZEY != '1' AND SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1')
												ELSE ISNULL((SELECT MIN(DUZEY) FROM AbidePuanAralik PA WHERE SUM(O.PUAN) <= PA.MAXIMUMPUAN AND PA.ID_ABIDESINAV = S.ID_ABIDESINAV), '1') 
											END 
							,MAXDUZEY	= (SELECT MAX(DUZEY) FROM AbidePuanAralik PA WHERE PA.ID_ABIDESINAV = S.ID_ABIDESINAV)
					FROM AbideOgrenci		O
					INNER JOIN #OGRENCI26		SO	ON	SO.TCKIMLIKNO		= O.TCKIMLIKNO
					INNER JOIN AbideSoru	S	ON	S.ID_ABIDESORU		= O.ID_ABIDESORU
					LEFT  JOIN #BOLUMNO26		B	ON	B.DERS				= S.DERS
					INNER JOIN AbideSinav	SN	ON	SN.ID_ABIDESINAV	= S.ID_ABIDESINAV
					WHERE	O.AKTIF		= 1 
						AND SN.AKTIF	= 1
						--O.TCKIMLIKNO IN (SELECT TCKIMLIKNO FROM #OGRENCI26) AND 
					GROUP BY O.TCKIMLIKNO, SN.AD, S.DERS, S.ID_ABIDESINAV,B.BOLUMNO, B.DERS
					ORDER BY O.TCKIMLIKNO, S.DERS, SN.AD DESC
				END

				--SELECT   S.DERS
				--		,S.SORUNO
				--		,B.BOLUMNO
				--INTO #TEMP_SON_26
				--FROM AbideSoru	S				
				--JOIN #BOLUMNO26	B	ON	B.DERS	= S.DERS
				--WHERE S.ID_ABIDESINAV	= @ID_ABIDESINAV

				SELECT (
					SELECT (	SELECT * 
								FROM #OGRENCI26
								FOR JSON PATH
							) OGRENCI,
							(	SELECT * FROM #DUZEN26 --ORDER BY SIRA
								FOR JSON PATH
							) DUZEN,
							(SELECT	 DERS
									,BOLUMNO
									,BECERI				= IIF (NOT EXISTS(SELECT TOP 1 1 FROM #TEMP5_1_26),NULL,
														(SELECT 
															(	SELECT *
																FROM #TEMP5_1_26	T
																WHERE T.BOLUMNO = B.BOLUMNO
																FOR JSON PATH
															  ) AS BECERI,
															  (	SELECT *
																FROM #TEMP5_2_26	T
																WHERE T.BOLUMNO = B.BOLUMNO
																FOR JSON PATH
															  ) AS RESIM
															FOR JSON PATH
															))	
									,KAZANIMALTBECERI	= (	SELECT *
															FROM #TEMP6_26	T
															WHERE T.BOLUMNO = B.BOLUMNO
															FOR JSON PATH
														  )
									,SORUCOZULMEORANI	= (	SELECT *
															FROM #TEMP7_26	T
															WHERE T.BOLUMNO = B.BOLUMNO
															FOR JSON PATH
														  )
									,OGRENCIPERFORMANS	= IIF (NOT EXISTS(SELECT TOP 1 1 FROM #TEMP8_1_26),NULL,
														(SELECT 
															(	SELECT *
																FROM #TEMP8_1_26	T
																WHERE T.BOLUMNO = B.BOLUMNO
																FOR JSON PATH
															  ) AS ONERI,
															  (	SELECT *
																FROM #TEMP8_2_26	T
																WHERE T.BOLUMNO = B.BOLUMNO
																FOR JSON PATH
															  ) AS PUAN
															FOR JSON PATH
															))
									,GRAFIK				= (	SELECT *
															FROM #TEMP9_26	T
															WHERE T.BOLUMNO = B.BOLUMNO
															FOR JSON PATH
														  )
									,TEKGRAFIK			= (	SELECT *
															FROM #TEMP10_26	T
															WHERE T.BOLUMNO = B.BOLUMNO
															FOR JSON PATH
														  )
									--,SORULIST			= (	SELECT *
									--						FROM #TEMP_SON_26	T
									--						WHERE T.BOLUMNO = B.BOLUMNO
									--						FOR JSON PATH
									--					  )
								FROM #BOLUMNO26	B
								FOR JSON PATH
								) DERS
					FOR JSON PATH
				)

				DROP TABLE IF EXISTS #BOLUMNO26
				DROP TABLE IF EXISTS #DUZEN26
				DROP TABLE IF EXISTS #OGRENCI26
				DROP TABLE IF EXISTS #TEMP5_1_26
				DROP TABLE IF EXISTS #TEMP5_2_26
				DROP TABLE IF EXISTS #TEMP6_26
				DROP TABLE IF EXISTS #TEMP7_26
				DROP TABLE IF EXISTS #TEMP8_1_26
				DROP TABLE IF EXISTS #TEMP8_2_26
				DROP TABLE IF EXISTS #TEMP9_26
				DROP TABLE IF EXISTS #TEMP10_26
				--DROP TABLE IF EXISTS #TEMP_SON_26

			END

		END
	
		--COMMIT TRANSACTION [Tran1]
	END TRY
	BEGIN CATCH
		--ROLLBACK TRANSACTION [Tran1]
		SELECT 
			@ErrorSeverity	= ERROR_SEVERITY(),
			@ErrorState		= ERROR_STATE()
							
		SELECT @MSG = /*'Prosedür: ' + ISNULL(ERROR_PROCEDURE(), '') + ', Satır: ' + CAST(ERROR_LINE() as varchar) + ', Hata: ' +*/ ERROR_MESSAGE()
			
		RAISERROR (@MSG , -- Message text.
					@ErrorSeverity, -- Severity.
					@ErrorState -- State.
					);
	END CATCH;
END


