ALTER PROCEDURE [dbo].[sp_SifremiUnuttumOV]
	@ISLEM					INT				= NULL,
	@TCKIMLIKNO				VARCHAR(11)		= NULL,
	@OTURUM					VARCHAR(36)		= NULL,
	@ID_MENU				INT				= NULL,
	
	
	@ADSOYAD				VARCHAR(300)	= NULL,
	@REFERANCENAME			VARCHAR(300)	= NULL,
	@REFERANCE_TCNO			VARCHAR(300)	= NULL,
	@BIRTHDAY				DATE			= NULL,
	@SIFRE					VARCHAR(50)		= NULL,
	@MASKADSOYAD			VARCHAR(300)	= NULL,
	@KULLANICI_TIP			INT				= NULL

AS
BEGIN
/*

	Oluşturan Adı		: Kadir Cengiz
	Oluşturulanan Tarih	: 17.04.2021
	
	--	sp CREATE 

*/

	BEGIN TRY
		
		DECLARE @ERRMESSAGE VARCHAR(200)= ''
		DECLARE @ERRCODE	INT			= 0
		DECLARE @AKTIFDONEM INT			= (SELECT OkyanusDB.dbo.fn_AktifDonem())

		IF @ISLEM = 1	--	ÖĞRENCİ/VELİ BİLGİ GETİR		
		BEGIN

			DROP TABLE IF EXISTS #KULLANICITIPILIST
			SELECT DISTINCT ID_KULLANICITIPI
			INTO #KULLANICITIPILIST
			FROM OkyanusDB..vw_KullaniciYetki 
			WHERE TCKIMLIKNO = @TCKIMLIKNO

			IF		EXISTS (SELECT TOP 1 1 FROM #KULLANICITIPILIST WHERE ID_KULLANICITIPI IN (4,5))
				AND NOT EXISTS (SELECT TOP 1 1 FROM #KULLANICITIPILIST WHERE ID_KULLANICITIPI NOT IN (4,5))
			BEGIN

				IF EXISTS (SELECT TOP 1 1 FROM #KULLANICITIPILIST WHERE ID_KULLANICITIPI  = 4)
				BEGIN

					SET @ADSOYAD=(	SELECT TOP 1 CONCAT_WS(' ', K.AD, K.SOYAD)
									FROM OkyanusDb.dbo.v3OgrenciVeli	AS OV
									JOIN OkyanusDB.dbo.v3Kullanici		AS K ON	K.TCKIMLIKNO	= OV.TCKIMLIKNO
									WHERE OV.TCKIMLIKNO_OGR=@TCKIMLIKNO 
										AND K.AKTIF=1 
									ORDER BY NEWID())

					SET @MASKADSOYAD=SUBSTRING(@ADSOYAD,1,2)+'****'+' '+'****'+RIGHT(@ADSOYAD,LEN(@ADSOYAD)-(LEN(@ADSOYAD)-1))

					SET @ERRCODE=0

				END
				ELSE 
				BEGIN

					SET @ADSOYAD=(	SELECT TOP 1 (AD+' '+SOYAD) AS ADSOYAD 
									FROM OkyanusDB.dbo.v3OgrenciTum AS TUMOGRENCILER
									INNER JOIN OkyanusDB.dbo.v3OgrenciVeli AS VELI  ON VELI.TCKIMLIKNO_OGR=TUMOGRENCILER.TCKIMLIKNO
									INNER JOIN OkyanusDB.dbo.v3Kullanici AS K ON K.TCKIMLIKNO=(SELECT TOP 1 TCKIMLIKNO_OGR FROM OkyanusDB.dbo.v3OgrenciVeli
									WHERE TCKIMLIKNO=@TCKIMLIKNO ORDER BY NEWID())
									WHERE TUMOGRENCILER.TCKIMLIKNO=(SELECT TOP 1 TCKIMLIKNO_OGR FROM OkyanusDB.dbo.v3OgrenciVeli
																	WHERE TCKIMLIKNO=@TCKIMLIKNO AND K.AKTIF=1 ORDER BY NEWID()) AND DONEM=@AKTIFDONEM)

					SET @MASKADSOYAD=SUBSTRING(@ADSOYAD,1,2)+'****'+' '+'****'+RIGHT(@ADSOYAD,LEN(@ADSOYAD)-(LEN(@ADSOYAD)-1))

					SET @ERRCODE=0
				END

			END
			ELSE
			BEGIN
 				SET @ERRMESSAGE='Sadece Veli yada Öğrenci şifre oluşturabilir'
				SET @ERRCODE=1
			END
			SELECT (
				SELECT	 ADSOYAD		= @ADSOYAD
						,MASKED_ADSOYAD	= @MASKADSOYAD
						,ERRCODE		= @ERRCODE
						,ERRMESSAGE		= @ERRMESSAGE
						,KULLANICITIP 	= @KULLANICI_TIP
				FOR JSON PATH
			)

			DROP TABLE IF EXISTS #KULLANICITIPILIST
				
		END
		IF @ISLEM = 2	--	ÖĞRENCİ/VELİ ŞİFRE DEĞİŞTİR		
		BEGIN
				
				DECLARE @TABLE_DOGUMTARIHI	NVARCHAR(MAX)	=''
				DECLARE @TABLE_ADSOYAD		NVARCHAR(MAX)	=''
				DECLARE @TCKONTROL			BIT				= 0

				SELECT TOP 1 
					 @TABLE_ADSOYAD		= AD + SOYAD
					,@TABLE_DOGUMTARIHI	= DOGUMTARIHI
				FROM OkyanusDB.dbo.v3Kullanici 
				WHERE TCKIMLIKNO=@TCKIMLIKNO
 
				IF @KULLANICI_TIP=4
				BEGIN
					SET @TCKONTROL = IIF (EXISTS (	SELECT TOP 1 1
													FROM v3Kullanici	K 
													JOIN v3OgrenciVeli	OV	ON	OV.TCKIMLIKNO_OGR	= K.TCKIMLIKNO
													JOIN v3Kullanici	V	ON	V.TCKIMLIKNO		= OV.TCKIMLIKNO
													WHERE	K.TCKIMLIKNO		= @TCKIMLIKNO
														AND V.TCKIMLIKNO		= @REFERANCE_TCNO
														AND V.AD + ' ' + V.SOYAD= @REFERANCENAME
											),1,0)
											
					--(SELECT COUNT(1) FROM OkyanusDB..v3OgrenciVeli OV  WHERE TCKIMLIKNO=@REFERANCE_TCNO AND ADSOYAD =@REFERANCENAME)
				END

				IF @KULLANICI_TIP=5
				BEGIN
					SET @TCKONTROL = IIF (EXISTS (	SELECT TOP 1 1
													FROM v3Kullanici	K 
													JOIN v3OgrenciVeli	OV	ON	OV.TCKIMLIKNO	= K.TCKIMLIKNO
													JOIN v3Kullanici	O	ON	O.TCKIMLIKNO	= OV.TCKIMLIKNO_OGR
													WHERE	K.TCKIMLIKNO		= @TCKIMLIKNO
														AND O.TCKIMLIKNO		= @REFERANCE_TCNO
														AND O.AD + ' ' + O.SOYAD= @REFERANCENAME
											),1,0)
					--SET @TCKONTROL=(SELECT COUNT(1) FROM v3Kullanici WHERE TCKIMLIKNO=@REFERANCE_TCNO AND AD+' '+SOYAD=@REFERANCENAME)
				END

				IF @TCKONTROL=0 AND @KULLANICI_TIP=4
				BEGIN
					SET @ERRMESSAGE='Referans veli TC Kimlik numarası hatalı'
				END
				ELSE IF @TCKONTROL=0 AND @KULLANICI_TIP=5
				BEGIN
					SET @ERRMESSAGE='Referans öğrenci TC Kimlik numarası hatalı'
				END
				ELSE IF @TABLE_ADSOYAD!=REPLACE(@ADSOYAD,' ','') OR @TABLE_ADSOYAD=''
				BEGIN
					SET @ERRMESSAGE='Adınız Soyadız Hatalı'
				END
				ELSE IF @TABLE_DOGUMTARIHI!=@BIRTHDAY OR @TABLE_DOGUMTARIHI=''
				BEGIN
					SET @ERRMESSAGE='Doğum Tarihi Hatalı'
				END
				ELSE
				BEGIN
					UPDATE OkyanusDB.dbo.v3Kullanici SET 
						--SIFRE		= @SIFRE,
						SIFREHASH	= eokul_v2.dbo.clr_Crypto_HashPass(@SIFRE) 
					WHERE TCKIMLIKNO = @TCKIMLIKNO

					SET @ERRCODE	= 0
					SET @ERRMESSAGE	= 'Şifreniz başarıyla oluşturuldu.'
						
				END

				SELECT (
					SELECT @ERRCODE AS ERRCODE,@ERRMESSAGE AS ERRMESSAGE 
					FOR JSON PATH
				)


		END		
		IF @ISLEM = 3	--	ŞİFRE DEĞİTİRME ENGELLENDİ Mİ?	
		BEGIN
			SELECT COUNT(1) AS SD_ENGELLI
			FROM Pusulam.dbo.KullaniciSifreEngel
			WHERE TCKIMLIKNO=@TCKIMLIKNO
		END

	END TRY
	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;
		DECLARE @_MSG VARCHAR(4000)

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState	= ERROR_STATE(),
			@_MSG			= ERROR_MESSAGE()

		RAISERROR (@_MSG, @_ErrorSeverity, @_ErrorState); 

	END CATCH;
END
GO

ALTER PROCEDURE [dbo].[sp_SifremiDegistir] 
@ISLEM			INT				= NULL,
@OLDPASS		VARCHAR(50)		= NULL,
@NEWPASS		VARCHAR(50)		= NULL,
@TCKIMLIKNO		VARCHAR(11)		= NULL,
@OTURUM			VARCHAR(36)		= NULL		
AS
BEGIN
DECLARE @PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @LOGJSON VARCHAR(MAX)
	SET @LOGJSON = (
		SELECT	 
			ISLEM				= @ISLEM		
			,OLDPASS			= @OLDPASS	
			,NEWPASS			= @NEWPASS	
			,TCKIMLIKNO			= @TCKIMLIKNO	
			,OTURUM				= @OTURUM		
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @ID_LOG INT = 0
	
	BEGIN TRY
	EXEC @ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = NULL, @LOGJSON = @LOGJSON, @ISLEM = @ISLEM, @PROSEDURADI = @PROCNAME
		IF @ID_LOG>1
		BEGIN
			IF @ISLEM=1
			BEGIN
				DECLARE @ERRCODE VARCHAR(2),@ERRMESSAGE VARCHAR(300)
				DROP TABLE IF EXISTS #UPDATE_TABLE
					CREATE TABLE #UPDATE_TABLE
					(
						ERRCODE		INT,
						ERRMESSAGE  varchar(200), 
					)

					IF  EXISTS (SELECT TOP 1 1 FROM OkyanusDB.dbo.v3Kullanici WHERE TCKIMLIKNO=@TCKIMLIKNO AND (eokul_v2.dbo.clr_Crypto_CheckPass(@OLDPASS,isnull(SIFREHASH,-1))=1) )
						BEGIN
							UPDATE OkyanusDB.dbo.v3Kullanici 
							SET --SIFRE = @NEWPASS,
							   SIFREHASH=eokul_v2.dbo.clr_Crypto_HashPass(@NEWPASS) 
							WHERE AKTIF=1 
							AND TCKIMLIKNO=@TCKIMLIKNO

							SET @ERRCODE=0
							SET @ERRMESSAGE='Şifreniz başarıyla güncellendi!'
							INSERT INTO #UPDATE_TABLE (ERRCODE,ERRMESSAGE) VALUES(@ERRCODE,@ERRMESSAGE)
							SELECT * FROM #UPDATE_TABLE FOR JSON AUTO
						END
					ELSE
						BEGIN
							SET @ERRCODE=1
							SET @ERRMESSAGE='Eski şifrenizi yanlış girdiniz!'

							INSERT INTO #UPDATE_TABLE (ERRCODE,ERRMESSAGE) VALUES(@ERRCODE,@ERRMESSAGE)
							SELECT * FROM #UPDATE_TABLE FOR JSON AUTO
						END
				END
		END
	END TRY

	BEGIN CATCH
		DECLARE @_ErrorSeverity INT;
		DECLARE @_ErrorState INT;

		SELECT 
			@_ErrorSeverity	= ERROR_SEVERITY(),
			@_ErrorState		= ERROR_STATE()
				
		DECLARE @_MSG VARCHAR(4000)
		SELECT @_MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @_MSG, @SEVERITY = @_ErrorSeverity, @STATE = @_ErrorState, @ID_LOG = @ID_LOG, @ID_LOGTUR = 2
	END CATCH
		

END
GO

