USE [Pusulam]
GO

/*

	Değiştiren Adı		: Tahsin Dalman
	Değiştirilen Tarih	: 04.09.2020
	
	--	2
	--	Detaylı rapor eklendi.

*/

/****** Object:  StoredProcedure [dbo].[sp_HedefBelirlemeRapor]    Script Date: 4.09.2020 10:26:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[sp_HedefBelirlemeRapor]
	@ISLEM				INT				= NULL,
	@ID_MENU			INT				= NULL,
	@TCKIMLIKNO			VARCHAR(11)		= NULL,
	@OTURUM				VARCHAR(36)		= NULL,
	@ID_KADEME3			INT				= NULL,

	@ID_SUBEs			NVARCHAR(MAX)	= NULL,
	@ID_SINIFs			NVARCHAR(MAX)	= NULL,
	@DONEM				NVARCHAR(4)		= NULL,
	@HEDEF				BIT				= NULL,

	@SQLJSON			NVARCHAR(MAX)	= NULL		
AS
BEGIN

BEGIN TRY    
	DECLARE @MSG			VARCHAR(4000)
	DECLARE @ErrorSeverity	INT
	DECLARE @ErrorState		INT
		
	DECLARE @return_variable INT
	EXEC @return_variable = [dbo].[sp_OturumKontrol] @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU
	
	IF @return_variable = 1
	BEGIN
		IF @ISLEM = 1	
		BEGIN

			SELECT O.TCKIMLIKNO
				,SINIFAD	= GS.SINIF
				,SUBEAD		= GS.SUBEAD
				,KADEME3
				,ADSOYAD	= K.AD+' '+K.SOYAD
				,O.DONEM
			INTO #OGRENCILIST
			FROM v3OgrenciTum				O	WITH (NOLOCK)	
			JOIN v3Kullanici				K	WITH (NOLOCK)		ON	K.TCKIMLIKNO	= O.TCKIMLIKNO
			JOIN vw_SubeSinifGrupKademeTum	GS	WITH (NOLOCK)		ON	GS.ID_SINIF		= O.ID_SINIF
			WHERE	GS.ID_SINIF IN (SELECT VALUE FROM OPENJSON(@ID_SINIFs)) 

			SELECT	SIRA = ROW_NUMBER() OVER( ORDER BY SUBEAD, KADEME3, SINIFAD, ADSOYAD) , O.TCKIMLIKNO, O.ADSOYAD, O.KADEME3, O.SINIFAD, O.SUBEAD, 
					(
						SELECT COUNT(*) 
						FROM OgrenciHedef OH 			WITH (NOLOCK)	
						JOIN UniversiteTabanPuanlari TP	WITH (NOLOCK)	 ON TP.PROGRAMKODU = OH.PROGRAMKODU AND TP.YIL = O.DONEM
						WHERE OH.AKTIF = 1 AND OH.TCKIMLIKNO = O.TCKIMLIKNO AND OH.DONEM = O.DONEM
					) AS TERCIHSAYISI
			FROM #OGRENCILIST O
			GROUP BY O.TCKIMLIKNO, O.ADSOYAD, O.KADEME3, O.SINIFAD, O.SUBEAD, O.DONEM
			ORDER BY SIRA
				
			
			--CREATE TABLE #OGRENCIHEDEF ( TCKIMLIKNO VARCHAR(11)
			--							,SUBEAD		VARCHAR(50)
			--							,SINIFAD	VARCHAR(50)
			--							,KADEME3	VARCHAR(50)
			--							,ADSOYAD	VARCHAR(90)
			--							,TERCIHSAYISI INT)


			--IF @HEDEF = 1	--	HEDEF BELİRLEYENLER
			--BEGIN
				
			--	INSERT INTO #OGRENCIHEDEF (TCKIMLIKNO, SUBEAD, SINIFAD, KADEME3, ADSOYAD)
			--	SELECT DISTINCT OL.TCKIMLIKNO, OL.SUBEAD, OL.SINIFAD, KADEME3, ADSOYAD
			--	FROM OgrenciHedef	OH 
			--	JOIN #OGRENCILIST	OL	ON	OL.TCKIMLIKNO	= OH.TCKIMLIKNO
			--						--	AND OL.DONEM		= OH.DONEM  
			--	WHERE OH.AKTIF = 1

			--END
			--ELSE			--	HEDEF BELİRLEMEYENLER
			--BEGIN
				
			--	INSERT INTO #OGRENCIHEDEF (TCKIMLIKNO, SUBEAD, SINIFAD, KADEME3, ADSOYAD)
			--	SELECT DISTINCT OL.TCKIMLIKNO, OL.SUBEAD, OL.SINIFAD, KADEME3, ADSOYAD
			--	FROM #OGRENCILIST OL
			--	WHERE OL.TCKIMLIKNO NOT IN (
			--		SELECT O.TCKIMLIKNO
			--		FROM OgrenciHedef		OH
			--		JOIN v3OgrenciTum		O	ON	O.TCKIMLIKNO	= OH.TCKIMLIKNO		
			--									AND O.DONEM			= OH.DONEM  
			--								--	AND OH.DONEM		= OL.DONEM
			--		WHERE OH.AKTIF = 1
			--	)
			--END

			--SELECT	TCKIMLIKNO, 
			--		SUBEAD, 
			--		SINIFAD, 
			--		KADEME3, 
			--		ADSOYAD, 
			--		SIRA = ROW_NUMBER() OVER( ORDER BY SUBEAD, KADEME3, SINIFAD, ADSOYAD) 
			--FROM #OGRENCIHEDEF

				
			DROP TABLE #OGRENCILIST
			--DROP TABLE #OGRENCIHEDEF
			
		END

		IF @ISLEM = 2 -- DETAYLI	
		BEGIN

			SELECT O.TCKIMLIKNO
				,SINIFAD	= GS.SINIF
				,SUBEAD		= GS.SUBEAD
				,KADEME3
				,ADSOYAD	= K.AD+' '+K.SOYAD
				,O.DONEM
			INTO #OGRENCILIST2
			FROM v3OgrenciTum				O	WITH (NOLOCK)	
			JOIN v3Kullanici				K	WITH (NOLOCK)	ON	K.TCKIMLIKNO	= O.TCKIMLIKNO
			JOIN vw_SubeSinifGrupKademeTum	GS	WITH (NOLOCK)	ON	GS.ID_SINIF		= O.ID_SINIF
			WHERE	GS.ID_SINIF IN (SELECT VALUE FROM OPENJSON(@ID_SINIFs)) 

			SELECT	SIRA = ROW_NUMBER() OVER( ORDER BY SUBEAD, KADEME3, SINIFAD, ADSOYAD, IL, UNIVERSITE, FAKULTE, BOLUM)
					, O.TCKIMLIKNO, O.ADSOYAD, O.KADEME3, O.SINIFAD, O.SUBEAD
					,TP.IL
					,TP.UNIVERSITE
					,TP.FAKULTE
					,TP.BOLUM2 AS BOLUM
			FROM #OGRENCILIST2 O
			JOIN OgrenciHedef OH WITH (NOLOCK) ON	OH.TCKIMLIKNO = O.TCKIMLIKNO AND OH.AKTIF = 1 AND OH.DONEM = O.DONEM
			JOIN UniversiteTabanPuanlari TP WITH (NOLOCK)	ON TP.PROGRAMKODU = OH.PROGRAMKODU AND TP.YIL = O.DONEM
			ORDER BY SIRA

			DROP TABLE #OGRENCILIST2
		END
	
	END

END TRY
		BEGIN CATCH
			SELECT 
				@ErrorSeverity	= ERROR_SEVERITY(),
				@ErrorState		= ERROR_STATE()
							
			SELECT @MSG = /*'Prosedür: ' + ISNULL(ERROR_PROCEDURE(), '') + ', Satır: ' + CAST(ERROR_LINE() as varchar) + ', Hata: ' +*/ ERROR_MESSAGE()
			
			RAISERROR (@MSG , -- Message text.
						@ErrorSeverity, -- Severity.
						@ErrorState -- State.
						);
		END CATCH;
	
END



