USE [Pusulam]
GO
/****** Object:  StoredProcedure [dbo].[sp_Odev]    Script Date: 9.10.2020 10:07:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[sp_Odev]
	@ISLEM				INT				= NULL,
	@TCKIMLIKNO			VARCHAR(11)		= NULL,
	@OTURUM				VARCHAR(36)		= NULL,
	@ID_MENU			INT				= NULL,
	
	@ID_KADEME			INT				= NULL,
	@ID_ODEVTUR			INT				= NULL,
	@DURUM				BIT				= NULL,
	@ID_ODEV			INT				= NULL,
	@ID_SINIF			INT				= NULL,
	@TC_ODEVVEREN		VARCHAR(11)		= NULL,
	@SQLJSON			VARCHAR(MAX)	= NULL,

	@TC_OGRENCI			VARCHAR(11)		= NULL,
	@BASLANGIC_TARIHI	VARCHAR(MAX)	= NULL,
	@BITIS_TARIHI		VARCHAR(MAX)	= NULL,
	@DONEM				VARCHAR(4)		= NULL,
	@ID_DERS			INT				= NULL,

	@ID_DERSLIST		VARCHAR(MAX)	= NULL,
	@ID_KADEME3LIST		VARCHAR(MAX)	= NULL,
	@ID_SUBELIST		VARCHAR(MAX)	= NULL,
	@TC_OGRETMENLIST	VARCHAR(MAX)	= NULL,
	@TUR				INT				= NULL,
	@TC_OGRETMEN		VARCHAR(11)		= NULL,
	@RAPORMU			BIT				= 0,
	@APIKEY				VARCHAR(MAX)	= NULL,
	@GUNCELLEME			BIT				= NULL
AS
BEGIN
	DECLARE @ODEVKONTROLSURESI INT = -16
	DECLARE @PROCNAME VARCHAR(MAX) = (SELECT OBJECT_NAME(@@PROCID))
	DECLARE @LOGJSON VARCHAR(MAX)
	SET @LOGJSON = (
		SELECT	 ISLEM				= @ISLEM
				,TCKIMLIKNO			= @TCKIMLIKNO
				,OTURUM				= @OTURUM
				,ID_MENU			= @ID_MENU

				,ID_KADEME			= @ID_KADEME			
				,ID_ODEVTUR			= @ID_ODEVTUR			
				,DURUM				= @DURUM				
				,ID_ODEV			= @ID_ODEV			
				,ID_SINIF			= @ID_SINIF			
				,TC_ODEVVEREN		= @TC_ODEVVEREN		
				,SQLJSON			= @SQLJSON			
									 
				,TC_OGRENCI			= @TC_OGRENCI			
				,BASLANGIC_TARIHI	= @BASLANGIC_TARIHI	
				,BITIS_TARIHI		= @BITIS_TARIHI		
				,DONEM				= @DONEM				
				,ID_DERS			= @ID_DERS			
									
				,ID_DERSLIST		= @ID_DERSLIST		
				,ID_KADEME3LIST		= @ID_KADEME3LIST		
				,ID_SUBELIST		= @ID_SUBELIST		
				,TC_OGRETMENLIST	= @TC_OGRETMENLIST	
				,TUR				= @TUR				
				,TC_OGRETMEN		= @TC_OGRETMEN		
				,RAPORMU			= @RAPORMU			
				,APIKEY				= @APIKEY
				,GUNCELLEME		= @GUNCELLEME
		FOR JSON PATH, WITHOUT_ARRAY_WRAPPER	   
	)	

	DECLARE @ID_LOG INT = 0

	--BEGIN TRANSACTION [TranOdev]
	BEGIN TRY   
		EXEC @ID_LOG = dbo.sp_OturumKontrolMenuYetkiLog @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU, @LOGJSON = @LOGJSON, @ISLEM = @ISLEM, @PROSEDURADI = @PROCNAME
		IF @ID_LOG > 0
		BEGIN
			IF @ISLEM = 1 -- KADEME ÖDEV TÜR LİSTELE
			BEGIN
				SELECT
				ISNULL(
				(
					SELECT OT.ID_ODEVTUR, OT.AD, CASE WHEN OTK.ID_KADEME IS NULL THEN 0 ELSE 1 END AS DURUM, @ID_KADEME AS ID_KADEME
					FROM OdevTur OT WITH(NOLOCK)
					LEFT JOIN OdevTurKademe OTK WITH(NOLOCK) ON OTK.ID_ODEVTUR = OT.ID_ODEVTUR AND OTK.ID_KADEME = @ID_KADEME
					ORDER BY OT.ID_ODEVTUR
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 2 -- KADEME ÖDEV TÜR DURUM EKLE/GÜNCELLE
			BEGIN
				IF @DURUM = 0
				BEGIN
					DELETE FROM OdevTurKademe WHERE ID_ODEVTUR = @ID_ODEVTUR AND ID_KADEME = @ID_KADEME
				END

				IF @DURUM = 1 AND NOT EXISTS (SELECT * FROM OdevTurKademe WITH(NOLOCK) WHERE ID_ODEVTUR = @ID_ODEVTUR AND ID_KADEME = @ID_KADEME)
				BEGIN
					INSERT INTO OdevTurKademe(ID_ODEVTUR, ID_KADEME, KYE_KULLANICI)
					VALUES (@ID_ODEVTUR, @ID_KADEME, @TCKIMLIKNO)
				END
			END	
			
			IF @ISLEM = 3 -- ÖDEV KAYDET
			BEGIN
				DECLARE @AKTIFDONEM VARCHAR(4) 
				SELECT @AKTIFDONEM = DONEM FROM OkyanusDB.dbo.v3AktifDonem WHERE AKTIF = 1

				DECLARE @ID_ODEVTABLE TABLE (ID_ODEV INT)
				DECLARE @ID_ODEV3 INT

				INSERT INTO Odev (DONEM, ID_KADEME3, ID_DERS, ID_MORPADERS, ID_ODEVTUR, BASLIK, ACIKLAMA, VERILIS_TARIHI, TESLIM_TARIHI, KYE_KULLANICI)
				OUTPUT inserted.ID_ODEV INTO @ID_ODEVTABLE
				SELECT @AKTIFDONEM, ID_KADEME3, ID_DERS, ID_MORPADERS, ID_ODEVTUR, BASLIK, ACIKLAMA, VERILIS_TARIHI, TESLIM_TARIHI, @TCKIMLIKNO 
				FROM OPENJSON (@SQLJSON)
				WITH(
					ID_SUBE			INT,
					ID_KADEME		INT,
					ID_KADEME3		INT,
					ID_ODEVTUR		INT,
					ID_DERS			INT,
					ID_MORPADERS	INT,
					VERILIS_TARIHI	VARCHAR(MAX),
					TESLIM_TARIHI	VARCHAR(MAX),
					BASLIK			VARCHAR(MAX),
					ACIKLAMA		VARCHAR(MAX)
				)

				SELECT @ID_ODEV3 = ID_ODEV FROM @ID_ODEVTABLE

				SELECT DISTINCT ID_SINIF = SO.ID_SINIF, VALUE = JO.VALUE
				INTO #OGRENCISINIF
				FROM OPENJSON (@SQLJSON, '$.TC_OGRENCILIST') JO
				INNER JOIN OkyanusDB.dbo.vw_SinifOgrenci SO ON SO.TCKIMLIKNO = JO.VALUE

				INSERT INTO OdevSinif (ID_ODEV, ID_SINIF)
				SELECT @ID_ODEV3, VALUE
				FROM OPENJSON (@SQLJSON, '$.ID_SINIFLIST')
				WHERE VALUE <> '0' AND VALUE IN (SELECT ID_SINIF FROM #OGRENCISINIF)

				INSERT INTO OdevSinifOgrenci (ID_ODEVSINIF, TCKIMLIKNO)
				SELECT DISTINCT OS.ID_ODEVSINIF, SO.VALUE
				FROM #OGRENCISINIF SO
				INNER JOIN OdevSinif OS ON OS.ID_SINIF = SO.ID_SINIF AND OS.ID_ODEV = @ID_ODEV3
				WHERE SO.VALUE <> '0'

				DROP TABLE IF EXISTS #OGRENCISINIF

				INSERT INTO OdevLink (ID_ODEV, AD, LINK)
				SELECT @ID_ODEV3, AD, LINK
				FROM OPENJSON (@SQLJSON, '$.LINKLIST')
				WITH(
					AD VARCHAR(MAX),
					LINK VARCHAR(MAX)
				)
				WHERE LINK <> ''

				INSERT INTO OdevDosya (ID_ODEV, AD, GUID, UZANTI)
				SELECT @ID_ODEV3, AD, GUID, UZANTI
				FROM OPENJSON (@SQLJSON, '$.DOSYALIST')
				WITH(
					AD VARCHAR(MAX),
					GUID VARCHAR(MAX),
					UZANTI VARCHAR(MAX)
				)

				INSERT INTO OdevMorpaKazanim (ID_ODEV, ID_MORPAKAZANIM)
				SELECT @ID_ODEV3, VALUE
				FROM OPENJSON (@SQLJSON, '$.ID_MORPAKAZANIMLIST')
				WHERE VALUE <> 0

				INSERT INTO OdevMorpaMateryal(ID_ODEV, ID_MORPAMATERYAL)
				SELECT @ID_ODEV3, VALUE
				FROM OPENJSON (@SQLJSON, '$.ID_MORPAMATERYALLIST')
				WHERE VALUE <> 0

				SET @ISLEM		= 19
				SET @ID_ODEV	= @ID_ODEV3
				SET @GUNCELLEME	= 0
				GOTO Branch_Islem19;
			END	

			IF @ISLEM = 4 -- SINIF ÖDEV LİSTELE
			BEGIN
				SELECT
				ISNULL((
					SELECT	 O.ID_ODEV
							,ISNULL(D.DERSAD, '') AS DERSAD
							,O.BASLIK
							,VERILIS_TARIHI = CONVERT(VARCHAR, O.VERILIS_TARIHI, 104)
							,TESLIM_TARIHI = CONVERT(VARCHAR, O.TESLIM_TARIHI, 104)
							,DURUM =	1
					FROM Odev O WITH(NOLOCK)
					INNER JOIN OdevSinif S WITH(NOLOCK) ON S.ID_ODEV = O.ID_ODEV
					LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS
					WHERE O.AKTIF = 1 
					AND KYE_KULLANICI = @TCKIMLIKNO
					AND S.ID_SINIF = @ID_SINIF
					ORDER BY O.VERILIS_TARIHI DESC
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 5 -- ÖDEV SİL
			BEGIN
				UPDATE Odev SET AKTIF = 0 WHERE ID_ODEV = @ID_ODEV
			END

			IF @ISLEM = 6 -- ÖDEV ÖĞRENCİ LİSTELE
			BEGIN
				SELECT
				ISNULL(
				(
					SELECT OSO.ID_ODEVSINIFOGRENCI, K.AD + ' ' + K.SOYAD AS ADSOYAD, ISNULL(CAST(OSO.ID_ODEVDURUM AS VARCHAR), '') AS ID_ODEVDURUM, ISNULL(OSO.ACIKLAMA, '') AS ACIKLAMA
					FROM OdevSinifOgrenci OSO WITH(NOLOCK)
					INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEVSINIF = OSO.ID_ODEVSINIF
					INNER JOIN Odev O WITH(NOLOCK) ON O.ID_ODEV = OS.ID_ODEV
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = OSO.TCKIMLIKNO
					WHERE O.AKTIF = 1
					AND O.ID_ODEV = @ID_ODEV
					AND OS.ID_SINIF = @ID_SINIF
					ORDER BY ADSOYAD
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 7 -- DANIŞMAN MI
			BEGIN
				IF EXISTS (SELECT * FROM OkyanusDB.dbo.v3SinifPersonel WITH(NOLOCK) WHERE TCKIMLIKNO = @TCKIMLIKNO AND ID_KULLANICITIPI = 100)
				BEGIN
					SELECT CAST(1 AS BIT)
				END
				ELSE
				BEGIN
					SELECT CAST(0 AS BIT)
				END
			END
			
			IF @ISLEM = 8 -- SINIF ÖDEV VEREN LİSTESİ
			BEGIN
				SELECT
				ISNULL(
				(
					SELECT DISTINCT K.TCKIMLIKNO, K.AD + ' ' + K.SOYAD AS ADSOYAD
					FROM Odev O WITH(NOLOCK)
					INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
					WHERE OS.ID_SINIF = @ID_SINIF
					ORDER BY ADSOYAD
					FOR JSON PATH
				)
				, '[]')
			END

			IF @ISLEM = 9 -- ÖDEV VEREN ÖDEV LİSTELE
			BEGIN
				SELECT
				ISNULL((
					SELECT   O.ID_ODEV
							,ISNULL(D.DERSAD, '') AS DERSAD
							,O.BASLIK
							,VERILIS_TARIHI = CONVERT(VARCHAR, O.VERILIS_TARIHI, 104)
							,TESLIM_TARIHI = CONVERT(VARCHAR, O.TESLIM_TARIHI, 104)
							,ADSOYAD = K.AD + ' ' + K.SOYAD
							,DURUM =	1
					FROM Odev O WITH(NOLOCK)
					INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
					LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
					WHERE	O.AKTIF = 1
						AND OS.ID_SINIF = @ID_SINIF
						AND (@TC_ODEVVEREN IS NULL OR @TC_ODEVVEREN = '' OR O.KYE_KULLANICI = @TC_ODEVVEREN)
					ORDER BY O.TESLIM_TARIHI DESC
					FOR JSON PATH
				), '[]')
			END

			IF @ISLEM = 10 -- ÖDEV DETAY GETİR
			BEGIN
				SELECT 
				ISNULL((
					SELECT	 O.ID_ODEV
							,O.ID_MORPADERS
							,ISNULL(D.DERSAD, '') AS DERSAD
							,O.BASLIK
							,O.ACIKLAMA
							,LINKLIST = ISNULL((SELECT OL.AD, OL.LINK FROM OdevLink OL WITH(NOLOCK) WHERE OL.ID_ODEV = O.ID_ODEV FOR JSON PATH), '[]')
							,DOSYALIST = ISNULL((SELECT OD.AD , OD.GUID, OD.UZANTI FROM OdevDosya OD WITH(NOLOCK) WHERE OD.ID_ODEV = O.ID_ODEV FOR JSON PATH), '[]')
							,ID_MORPAKAZANIMLIST = ISNULL((SELECT OMK.ID_MORPAKAZANIM FROM OdevMorpaKazanim OMK WITH(NOLOCK) WHERE OMK.ID_ODEV = O.ID_ODEV FOR JSON PATH), '[]')
							,ID_MORPAMATERYALLIST = ISNULL((SELECT OMM.ID_MORPAMATERYAL FROM OdevMorpaMateryal OMM WITH(NOLOCK) WHERE OMM.ID_ODEV = O.ID_ODEV FOR JSON PATH), '[]')
							,VERILIS_TARIHI = O.VERILIS_TARIHI
							,TESLIM_TARIHI = O.TESLIM_TARIHI
					FROM Odev O WITH(NOLOCK)
					LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS
					WHERE O.AKTIF = 1
					AND O.ID_ODEV = @ID_ODEV
					FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
				), '{}')
			END

			IF @ISLEM = 11 -- ÖDEV KONTROL KAYDET
			BEGIN
				UPDATE OSO SET OSO.ID_ODEVDURUM = J.ID_ODEVDURUM, OSO.ACIKLAMA = J.ACIKLAMA
				FROM OdevSinifOgrenci OSO
				INNER JOIN OPENJSON(@SQLJSON)
				WITH(
					ID_ODEVSINIFOGRENCI INT,
					ID_ODEVDURUM INT,
					ACIKLAMA VARCHAR(MAX)				
				) J ON J.ID_ODEVSINIFOGRENCI = OSO.ID_ODEVSINIFOGRENCI

				UPDATE Odev SET KONTROL = 1 WHERE ID_ODEV = (SELECT TOP 1 ID_ODEV FROM OdevSinif OS WITH(NOLOCK) JOIN OdevSinifOgrenci OSO WITH(NOLOCK) ON OSO.ID_ODEVSINIF = OS.ID_ODEVSINIF JOIN OPENJSON(@SQLJSON) WITH(ID_ODEVSINIFOGRENCI INT) J ON J.ID_ODEVSINIFOGRENCI = OSO.ID_ODEVSINIFOGRENCI)

				--BİLDİRİM--
				SELECT	OV.TCKIMLIKNO, 
						OV.TCKIMLIKNO_OGR, SUBSTRING(K.AD + ' ' + K.SOYAD + ' ' + ISNULL(D.DERSAD + ' - ', '') + O.BASLIK + ' ' + 'ödevi yapılmamıştır.', 0, 249) AS ACIKLAMA
				INTO #VELILIST
				FROM OdevSinifOgrenci OSO
				JOIN OdevSinif OS ON OS.ID_ODEVSINIF = OSO.ID_ODEVSINIF
				JOIN Odev O ON O.ID_ODEV = OS.ID_ODEV
				LEFT JOIN eokul_v2.dbo.Ders D ON D.ID_DERS = O.ID_DERS
				JOIN OkyanusDB.dbo.v3Kullanici K ON K.TCKIMLIKNO = OSO.TCKIMLIKNO
				JOIN OkyanusDB.dbo.v3OgrenciVeli OV ON OV.TCKIMLIKNO_OGR = OSO.TCKIMLIKNO
				INNER JOIN OPENJSON(@SQLJSON)
				WITH(
					ID_ODEVSINIFOGRENCI INT,
					ID_ODEVDURUM INT,
					ACIKLAMA VARCHAR(MAX)				
				) J ON J.ID_ODEVSINIFOGRENCI = OSO.ID_ODEVSINIFOGRENCI 
				WHERE J.ID_ODEVDURUM = 3

				DECLARE @VELITCTEMP VARCHAR(11) = '', @OGRENCITCTEMP VARCHAR(11) = ''
				DECLARE @BILDIRIM11 VARCHAR(250)		= ''
				DECLARE @BILDIRIMTAM11 VARCHAR(MAX)	= ''

				WHILE EXISTS (SELECT 1 FROM #VELILIST)
				BEGIN
					SELECT TOP 1 @VELITCTEMP = TCKIMLIKNO, 
								 @OGRENCITCTEMP = TCKIMLIKNO_OGR,
								 @BILDIRIM11 = ACIKLAMA,
								 @BILDIRIMTAM11 = ACIKLAMA
					FROM #VELILIST

					DECLARE @LINK11 VARCHAR(MAX) = '', @LINK_ETIKET11 VARCHAR(MAX) = ''
					SET @LINK11			='https://pusulam.okyanuskoleji.k12.tr/AnaSayfaOutSide.html#OutSide/OSOdevListesi?TC_OGRENCI='+@OGRENCITCTEMP+'&TCKIMLIKNO='+@VELITCTEMP
					SET @LINK_ETIKET11	= 'Ödeve Git'

					SELECT @VELITCTEMP, 
						   @OGRENCITCTEMP,
						   @BILDIRIM11,
						   @BILDIRIMTAM11

					EXEC OkyanusIletisim.dbo.sp_SendPushMessage
						 @TCKIMLIKNO		= @TCKIMLIKNO
						,@HEADER			= 'Interaktif Ödev'
						,@MESAJ				= @BILDIRIM11
						,@LINK				= @LINK11
						,@MENU				= '000'
						,@TCKIMLIKNO_KIME	= @VELITCTEMP
						,@ID_UYGULAMA		= 2
						,@MESAJTAM			= @BILDIRIMTAM11
						,@LINK_ETIKET		= @LINK_ETIKET11

					EXEC OkyanusIletisim.dbo.sp_SendPushMessage
						 @TCKIMLIKNO		= @TCKIMLIKNO
						,@HEADER			= 'Interaktif Ödev'
						,@MESAJ				= @BILDIRIM11
						,@LINK				= @LINK11
						,@MENU				= '000'
						,@TCKIMLIKNO_KIME	= @VELITCTEMP
						,@ID_UYGULAMA		= 1
						,@MESAJTAM			= @BILDIRIMTAM11
						,@LINK_ETIKET		= @LINK_ETIKET11

					DELETE FROM #VELILIST WHERE TCKIMLIKNO = @VELITCTEMP
				END

				DROP TABLE #VELILIST
			END

			IF @ISLEM = 12 -- ÖDEV GÜNCELLE
			BEGIN
				DECLARE @ID_ODEV12 INT
				SELECT @ID_ODEV12 = ID_ODEV
				FROM OPENJSON(@SQLJSON)
				WITH(ID_ODEV INT)

				UPDATE O SET O.BASLIK = J.BASLIK, O.ACIKLAMA = J.ACIKLAMA, O.VERILIS_TARIHI = J.VERILIS_TARIHI, O.TESLIM_TARIHI = J.TESLIM_TARIHI
				FROM Odev O
				INNER JOIN OPENJSON(@SQLJSON)
				WITH(
					ID_ODEV INT,
					BASLIK VARCHAR(MAX),
					ACIKLAMA VARCHAR(MAX),
					VERILIS_TARIHI VARCHAR(MAX),
					TESLIM_TARIHI VARCHAR(MAX)
				) J ON J.ID_ODEV = O.ID_ODEV

				DELETE FROM OdevDosya 
				WHERE ID_ODEV = @ID_ODEV12

				INSERT INTO OdevDosya (ID_ODEV, AD, GUID, UZANTI)
				SELECT @ID_ODEV12, AD, GUID, UZANTI
				FROM OPENJSON(@SQLJSON, '$.DOSYALIST')
				WITH (
					AD VARCHAR(MAX),
					GUID VARCHAR(MAX),
					UZANTI VARCHAR(MAX)
				)

				DELETE FROM OdevLink 
				WHERE ID_ODEV = @ID_ODEV12

				INSERT INTO OdevLink (ID_ODEV, AD, LINK)
				SELECT @ID_ODEV12, AD, LINK
				FROM OPENJSON(@SQLJSON, '$.LINKLIST')
				WITH (
					AD VARCHAR(MAX),
					LINK VARCHAR(MAX)
				) WHERE LINK <> ''

				DELETE FROM OdevMorpaKazanim
				WHERE ID_ODEV = @ID_ODEV12

				INSERT INTO OdevMorpaKazanim (ID_ODEV, ID_MORPAKAZANIM)
				SELECT @ID_ODEV12, VALUE
				FROM OPENJSON(@SQLJSON, '$.ID_MORPAKAZANIMLIST')
				WHERE VALUE <> 0

				DELETE FROM OdevMorpaMateryal
				WHERE ID_ODEV = @ID_ODEV12

				INSERT INTO OdevMorpaMateryal (ID_ODEV, ID_MORPAMATERYAL)
				SELECT @ID_ODEV12, VALUE
				FROM OPENJSON(@SQLJSON, '$.ID_MORPAMATERYALLIST')
				WHERE VALUE <> 0

				EXEC Pusulam.dbo.sp_Odev
								 @TCKIMLIKNO		= @TCKIMLIKNO
								,@OTURUM			= @OTURUM
								,@ID_ODEV			= @ID_ODEV12
								,@ID_MENU			= @ID_MENU
								,@GUNCELLEME		= 1
								,@ISLEM				= 19
			END

			IF @ISLEM = 13 -- ÖDEV RAPOR
			BEGIN
				SELECT	 TCKIMLIKNO = SO.TCKIMLIKNO
						,ADSOYAD = K.AD + ' ' + K.SOYAD
						,KAMPUS = SD.SUBEAD
						,SINIF = SD.SINIF
						,OGRENCINO = OT.OGRNO
						,FOTOGRAF = ISNULL(R.FOTOGRAF,'')
				INTO #OGRENCI13
				FROM OkyanusDB.dbo.vw_SinifOgrenci SO WITH(NOLOCK)
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = SO.TCKIMLIKNO
				INNER JOIN OkyanusDB.dbo.vw_v4SinifDetay SD WITH(NOLOCK) ON SD.ID_SINIF = SO.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Ogrenci OT WITH(NOLOCK) ON OT.TCKIMLIKNO = SO.TCKIMLIKNO
				LEFT JOIN OkyanusDB.dbo.v3Resim R WITH(NOLOCK) ON R.TCKIMLIKNO = SO.TCKIMLIKNO AND R.SIRANO = 1
				WHERE SO.ID_SINIF = @ID_SINIF AND SO.TCKIMLIKNO = @TC_OGRENCI

				SELECT	 DONEM = DO.ACIKLAMA
						,TARIH = CONVERT(VARCHAR(MAX), O.VERILIS_TARIHI, 104)
						,DERS = ISNULL(D.DERSAD, '') 
						,DEGERLENDIRME = OD.AD
						,O.BASLIK
						,OSO.ID_ODEVDURUM
						,O.VERILIS_TARIHI
				INTO #OGRENCIODEV13
				FROM OdevSinifOgrenci OSO WITH(NOLOCK)
				INNER JOIN OdevDurum OD WITH(NOLOCK) ON OD.ID_ODEVDURUM = OSO.ID_ODEVDURUM
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEVSINIF = OSO.ID_ODEVSINIF
				INNER JOIN Odev O WITH(NOLOCK) ON O.ID_ODEV = OS.ID_ODEV
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS
				INNER JOIN OkyanusDB.dbo.v3AktifDonem DO WITH(NOLOCK) ON DO.DONEM = O.DONEM
				WHERE OSO.TCKIMLIKNO = @TC_OGRENCI
				AND OS.ID_SINIF = @ID_SINIF
				AND O.ID_ODEVTUR = @ID_ODEVTUR
				AND O.VERILIS_TARIHI BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI

				SELECT * FROM #OGRENCI13

				SELECT	 O.ID_ODEVDURUM
						,OD.AD AS ODEVDURUM
						,COUNT(*) AS SAYI		
				FROM	#OGRENCIODEV13 O
				INNER JOIN OdevDurum OD WITH(NOLOCK) ON OD.ID_ODEVDURUM = O.ID_ODEVDURUM
				GROUP BY O.ID_ODEVDURUM, OD.AD

				SELECT * FROM #OGRENCIODEV13 ORDER BY VERILIS_TARIHI DESC

				DROP TABLE #OGRENCI13
				DROP TABLE #OGRENCIODEV13
			END

			IF @ISLEM = 14 -- ÖĞRENCİ ÖDEV LİSTESİ
			BEGIN
				SELECT
				ISNULL(
				(
					SELECT O.ID_ODEV, ISNULL(D.DERSAD, '') AS DERSAD, CONVERT(VARCHAR(MAX), O.VERILIS_TARIHI, 104) AS VERILIS_TARIHI, CONVERT(VARCHAR(MAX), O.TESLIM_TARIHI, 104) AS TESLIM_TARIHI, ISNULL(OD.AD, 'Kontrol Edilmedi') AS DURUM, O.BASLIK, K.AD + ' ' + K.SOYAD AS ADSOYAD, O.ID_ODEVTUR
					FROM OdevSinifOgrenci OSO WITH(NOLOCK)
					INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEVSINIF = OSO.ID_ODEVSINIF
					INNER JOIN Odev O WITH(NOLOCK) ON O.ID_ODEV = OS.ID_ODEV
					LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
					LEFT JOIN OdevDurum OD WITH(NOLOCK) ON OD.ID_ODEVDURUM = OSO.ID_ODEVDURUM
					WHERE O.AKTIF = 1 AND O.DONEM = @DONEM AND OSO.TCKIMLIKNO = @TC_OGRENCI AND (O.ID_DERS = @ID_DERS OR @ID_DERS = 0 OR @ID_DERS IS NULL)
					ORDER BY O.TESLIM_TARIHI DESC
					FOR JSON PATH
				)
				, '[]')
			END

			IF @ISLEM = 15 -- VELİ ÖDEV RAPOR
			BEGIN
				SELECT	 TCKIMLIKNO = O.TCKIMLIKNO
						,ADSOYAD = K.AD + ' ' + K.SOYAD
						,KAMPUS = SB.AD
						,SINIF = S.AD
						,OGRENCINO = O.OGRNO
						,FOTOGRAF = ISNULL(R.FOTOGRAF,'')
				INTO #OGRENCI15
				FROM OkyanusDB.dbo.v3OgrenciTum O WITH(NOLOCK)
				INNER JOIN OkyanusDB.dbo.v3SinifTum S WITH(NOLOCK) ON S.ID_SINIF = O.ID_SINIF AND S.DONEM = O.DONEM
				INNER JOIN OkyanusDB.dbo.v3SubeGrupSinifTum SGS WITH(NOLOCK) ON SGS.ID_SINIF = O.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Sube SB WITH(NOLOCK) ON SB.ID_SUBE = SGS.ID_SUBE
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.TCKIMLIKNO
				LEFT JOIN OkyanusDB.dbo.v3Resim R WITH(NOLOCK) ON R.TCKIMLIKNO = K.TCKIMLIKNO AND R.SIRANO = 1
				WHERE O.TCKIMLIKNO = @TC_OGRENCI AND O.DONEM = @DONEM

				SELECT	 DONEM = O.DONEM
						,TARIH = CONVERT(VARCHAR(MAX), O.VERILIS_TARIHI, 104)
						,DERS = ISNULL(D.DERSAD, '') 
						,DEGERLENDIRME = OD.AD
						,O.BASLIK
						,OSO.ID_ODEVDURUM
						,O.VERILIS_TARIHI
				INTO #OGRENCIODEV15
				FROM OdevSinifOgrenci OSO WITH(NOLOCK)
				INNER JOIN OdevDurum OD WITH(NOLOCK) ON OD.ID_ODEVDURUM = OSO.ID_ODEVDURUM
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEVSINIF = OSO.ID_ODEVSINIF
				INNER JOIN Odev O WITH(NOLOCK) ON O.ID_ODEV = OS.ID_ODEV
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS AND (O.ID_DERS = @ID_DERS OR @ID_DERS = 0 OR @ID_DERS IS NULL)
				WHERE OSO.TCKIMLIKNO = @TC_OGRENCI
				AND O.DONEM = @DONEM
				AND ((@ID_DERS > 0 AND O.ID_ODEVTUR <> 5) OR (@ID_DERS = 0 OR @ID_DERS IS NULL))

				SELECT * FROM #OGRENCI15

				SELECT	 O.ID_ODEVDURUM
						,OD.AD AS ODEVDURUM
						,COUNT(*) AS SAYI		
				FROM	#OGRENCIODEV15 O
				INNER JOIN OdevDurum OD WITH(NOLOCK) ON OD.ID_ODEVDURUM = O.ID_ODEVDURUM
				GROUP BY O.ID_ODEVDURUM, OD.AD

				SELECT * FROM #OGRENCIODEV15 
				ORDER BY VERILIS_TARIHI DESC

				IF @ID_DERS > 0
				BEGIN
					SELECT DERSAD + ' Ödev Durumu' AS TITLE
					FROM eokul_v2.dbo.Ders WITH(NOLOCK)
					WHERE ID_DERS= @ID_DERS
				END
				ELSE
				BEGIN
					SELECT 'Genel Ödev Durumu' AS TITLE
				END

				DROP TABLE #OGRENCI15
				DROP TABLE #OGRENCIODEV15
			END

			IF @ISLEM = 16 -- ÖĞRETMEN ÖDEV RAPORU
			BEGIN
				SELECT K.TCKIMLIKNO, K.AD + ' ' + K.SOYAD AS ADSOYAD, S.SUBEAD, S.SINIF AS SINIFAD, S.ID_SINIF, ISNULL(D.DERSAD, '') AS DERSAD, ISNULL(D.ID_DERS, 0) AS ID_DERS, COUNT(*) AS SAYI
				INTO #TUMODEVLER
				FROM Odev O WITH(NOLOCK)
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS AND D.ID_KADEME3 IN (SELECT VALUE FROM OPENJSON(@ID_KADEME3LIST)) AND D.ID_DERS IN (SELECT VALUE FROM OPENJSON(@ID_DERSLIST))
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OkyanusDB.dbo.vw_v4SinifDetay S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
				WHERE O.AKTIF = 1 
				AND O.KYE_KULLANICI IN (SELECT VALUE FROM OPENJSON(@TC_OGRETMENLIST))
				AND S.ID_SUBE IN (SELECT VALUE FROM OPENJSON(@ID_SUBELIST))	
				AND CAST(O.VERILIS_TARIHI AS DATE) BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
				AND O.DONEM = @DONEM
				AND O.ID_ODEVTUR = @ID_ODEVTUR
				GROUP BY K.TCKIMLIKNO, K.AD, K.SOYAD, S.SUBEAD, S.SINIF, S.ID_SINIF, D.DERSAD, D.ID_DERS

				SELECT K.TCKIMLIKNO, K.AD + ' ' + K.SOYAD AS ADSOYAD, S.SUBEAD, S.SINIF AS SINIFAD, S.ID_SINIF, ISNULL(D.DERSAD, '') AS DERSAD, ISNULL(D.ID_DERS, 0) AS ID_DERS, COUNT(*) AS SAYI
				INTO #KONTROLEDILENODEVLER
				FROM Odev O WITH(NOLOCK)
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS AND D.ID_KADEME3 IN (SELECT VALUE FROM OPENJSON(@ID_KADEME3LIST)) AND D.ID_DERS IN (SELECT VALUE FROM OPENJSON(@ID_DERSLIST))
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OkyanusDB.dbo.vw_v4SinifDetay S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
				WHERE O.AKTIF = 1 AND O.KONTROL = 1
				AND O.KYE_KULLANICI IN (SELECT VALUE FROM OPENJSON(@TC_OGRETMENLIST))
				AND S.ID_SUBE IN (SELECT VALUE FROM OPENJSON(@ID_SUBELIST))				
				AND CAST(O.VERILIS_TARIHI AS DATE) BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
				AND O.DONEM = @DONEM
				AND O.ID_ODEVTUR = @ID_ODEVTUR
				GROUP BY K.TCKIMLIKNO, K.AD, K.SOYAD, S.SUBEAD, S.SINIF, S.ID_SINIF, D.DERSAD, D.ID_DERS

				SELECT K.TCKIMLIKNO, K.AD + ' ' + K.SOYAD AS ADSOYAD, S.SUBEAD, S.SINIF AS SINIFAD, S.ID_SINIF, ISNULL(D.DERSAD, '') AS DERSAD, ISNULL(D.ID_DERS, 0) AS ID_DERS, COUNT(*) AS SAYI
				INTO #KONTROLTARIHIGECMEYEN
				FROM Odev O WITH(NOLOCK)
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS AND D.ID_KADEME3 IN (SELECT VALUE FROM OPENJSON(@ID_KADEME3LIST)) AND D.ID_DERS IN (SELECT VALUE FROM OPENJSON(@ID_DERSLIST))
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OkyanusDB.dbo.vw_v4SinifDetay S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
				WHERE O.AKTIF = 1 AND O.KONTROL = 0
				AND O.KYE_KULLANICI IN (SELECT VALUE FROM OPENJSON(@TC_OGRETMENLIST))
				AND S.ID_SUBE IN (SELECT VALUE FROM OPENJSON(@ID_SUBELIST))				
				AND CAST(O.VERILIS_TARIHI AS DATE) BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
				AND O.DONEM = @DONEM
				AND O.ID_ODEVTUR = @ID_ODEVTUR
				AND DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) >= @ODEVKONTROLSURESI
				GROUP BY K.TCKIMLIKNO, K.AD, K.SOYAD, S.SUBEAD, S.SINIF, S.ID_SINIF, D.DERSAD, D.ID_DERS

				SELECT K.TCKIMLIKNO, K.AD + ' ' + K.SOYAD AS ADSOYAD, S.SUBEAD, S.SINIF AS SINIFAD, S.ID_SINIF, ISNULL(D.DERSAD, '') AS DERSAD, ISNULL(D.ID_DERS, 0) AS ID_DERS, COUNT(*) AS SAYI
				INTO #KONTROLTARIHIGECEN
				FROM Odev O WITH(NOLOCK)
				LEFT JOIN eokul_v2.dbo.Ders D WITH(NOLOCK) ON D.ID_DERS = O.ID_DERS AND D.ID_KADEME3 IN (SELECT VALUE FROM OPENJSON(@ID_KADEME3LIST)) AND D.ID_DERS IN (SELECT VALUE FROM OPENJSON(@ID_DERSLIST))
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OkyanusDB.dbo.vw_v4SinifDetay S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.KYE_KULLANICI
				WHERE O.AKTIF = 1 AND O.KONTROL = 0
				AND O.KYE_KULLANICI IN (SELECT VALUE FROM OPENJSON(@TC_OGRETMENLIST))
				AND S.ID_SUBE IN (SELECT VALUE FROM OPENJSON(@ID_SUBELIST))				
				AND CAST(O.VERILIS_TARIHI AS DATE) BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
				AND O.DONEM = @DONEM
				AND O.ID_ODEVTUR = @ID_ODEVTUR
				AND DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) < @ODEVKONTROLSURESI
				GROUP BY K.TCKIMLIKNO, K.AD, K.SOYAD, S.SUBEAD, S.SINIF, S.ID_SINIF, D.DERSAD, D.ID_DERS

				IF @RAPORMU = 0
				BEGIN
				SELECT
				ISNULL(
				(
					SELECT	 T.ID_SINIF
							,T.ID_DERS
							,T.TCKIMLIKNO
							,T.ADSOYAD
							,T.SUBEAD
							,T.SINIFAD
							,T.DERSAD
							,T.SAYI AS VERILEN
							,ISNULL(K.SAYI, 0) AS KONTROLEDILEN
							,ISNULL(KG.SAYI, 0) AS KONTROLEDILMEYEN
							,ISNULL(KGM.SAYI, 0) AS KONTROLSURESIDOLMAYAN
					FROM #TUMODEVLER T
					LEFT JOIN #KONTROLEDILENODEVLER K ON K.TCKIMLIKNO = T.TCKIMLIKNO AND K.ID_SINIF = T.ID_SINIF AND K.ID_DERS = T.ID_DERS
					LEFT JOIN #KONTROLTARIHIGECEN KG ON KG.TCKIMLIKNO = T.TCKIMLIKNO AND KG.ID_SINIF = T.ID_SINIF AND KG.ID_DERS = T.ID_DERS
					LEFT JOIN #KONTROLTARIHIGECMEYEN KGM ON KGM.TCKIMLIKNO = T.TCKIMLIKNO AND KGM.ID_SINIF = T.ID_SINIF AND KGM.ID_DERS = T.ID_DERS
					ORDER BY T.TCKIMLIKNO, T.ADSOYAD, T.SINIFAD, T.DERSAD
					FOR JSON PATH
				)
				, '[]')
				END
				ELSE 
				BEGIN
					SELECT	 T.ID_SINIF
							,T.ID_DERS
							,T.TCKIMLIKNO
							,T.ADSOYAD
							,T.SUBEAD
							,T.SINIFAD
							,T.DERSAD
							,T.SAYI AS VERILEN
							,ISNULL(K.SAYI, 0) AS KONTROLEDILEN
							,ISNULL(KG.SAYI, 0) AS KONTROLEDILMEYEN
							,ISNULL(KGM.SAYI, 0) AS KONTROLSURESIDOLMAYAN
					FROM #TUMODEVLER T
					LEFT JOIN #KONTROLEDILENODEVLER K ON K.TCKIMLIKNO = T.TCKIMLIKNO AND K.ID_SINIF = T.ID_SINIF AND K.ID_DERS = T.ID_DERS
					LEFT JOIN #KONTROLTARIHIGECEN KG ON KG.TCKIMLIKNO = T.TCKIMLIKNO AND KG.ID_SINIF = T.ID_SINIF AND KG.ID_DERS = T.ID_DERS
					LEFT JOIN #KONTROLTARIHIGECMEYEN KGM ON KGM.TCKIMLIKNO = T.TCKIMLIKNO AND KGM.ID_SINIF = T.ID_SINIF AND KGM.ID_DERS = T.ID_DERS
					ORDER BY T.TCKIMLIKNO, T.ADSOYAD, T.SINIFAD, T.DERSAD
				END

				DROP TABLE #TUMODEVLER
				DROP TABLE #KONTROLEDILENODEVLER
				DROP TABLE #KONTROLTARIHIGECMEYEN
				DROP TABLE #KONTROLTARIHIGECEN
			END

			IF @ISLEM = 17 -- ÖĞRETMEN ÖDEV RAPOR DETAY
			BEGIN
				SELECT
				ISNULL(
				(
					SELECT	 O.ID_ODEV
							,O.BASLIK
							,VERILIS_TARIHI = CONVERT(VARCHAR(MAX), O.VERILIS_TARIHI, 104)
							,TESLIM_TARIHI = CONVERT(VARCHAR(MAX), O.TESLIM_TARIHI, 104)
							,DURUM = CASE 
									WHEN O.KONTROL = 1 THEN 1
									WHEN O.KONTROL = 0 and DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) >= @ODEVKONTROLSURESI THEN 2
									WHEN O.KONTROL = 0 and DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) < @ODEVKONTROLSURESI THEN 3
									END
					FROM Odev O WITH(NOLOCK)
					INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
					WHERE O.KYE_KULLANICI = @TC_OGRETMEN
					AND (@ID_DERS IS NULL OR @ID_DERS = 0 OR O.ID_DERS = @ID_DERS)
					AND O.ID_ODEVTUR = @ID_ODEVTUR
					AND OS.ID_SINIF = @ID_SINIF
					AND CAST(O.VERILIS_TARIHI AS DATE) BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
					AND (
						@TUR = 1
						OR (@TUR = 2 AND O.KONTROL = 1)
						OR (@TUR = 3 AND O.KONTROL = 0 AND DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) < @ODEVKONTROLSURESI)
						OR (@TUR = 4 AND O.KONTROL = 0 AND DATEDIFF(DAY, GETDATE(), CONVERT(DATETIME,O.TESLIM_TARIHI)) >= @ODEVKONTROLSURESI)
					)
					FOR JSON PATH
				)
				, '[]')
			END	

			IF @ISLEM = 18 -- MORPA API
			BEGIN
				IF @APIKEY = 'D16EB1CA-062F-4CF8-8E3B-8700E44A06A0'
				BEGIN
					SELECT 
					(
						SELECT SUCCESS = 1,
							   DESCRIPTION = 'Başarılı!',
							   LIST = (
											ISNULL((
												SELECT	 O.ID_ODEV
														,O.ID_MORPADERS	
														,OS.ID_ODEVSINIF
														,SINIF = K3.DUZEY
														,SINIFAD = S.AD
														,BASLIK
														,ACIKLAMA
														,VERILIS_TARIHI
														,TESLIM_TARIHI
														--,KYE_KULLANICI
														,KYE_KULLANICI = (CASE WHEN O.ID_KADEME3 IN (7, 8, 9, 10) THEN (SELECT TOP 1 TCKIMLIKNO FROM OkyanusDB.dbo.v3SinifPersonel P WHERE P.ID_SINIF = OS.ID_SINIF AND P.ID_KULLANICITIPI = 100) ELSE O.KYE_KULLANICI END)
														,KYE_TARIH
														,MATERYALLIST = (SELECT DISTINCT OMM.ID_MORPAMATERYAL FROM OdevMorpaMateryal OMM JOIN MorpaMateryal MM ON MM.ID_MORPAMATERYAL = OMM.ID_MORPAMATERYAL AND MM.ID_MORPADERS = O.ID_MORPADERS WHERE OMM.ID_ODEV = O.ID_ODEV AND MM.AKTIF = 1 FOR JSON PATH)
														,KAZANIMLIST = (SELECT DISTINCT MK.KOD as ID_MORPAKAZANIM FROM OdevMorpaKazanim OMK JOIN MorpaKazanim MK ON MK.ID_MORPAKAZANIM = OMK.ID_MORPAKAZANIM AND MK.AKTIF = 1 WHERE OMK.ID_ODEV = O.ID_ODEV FOR JSON PATH)
														,OGRENCILIST = (
																			SELECT DISTINCT TCKIMLIKNO
																			FROM OdevSinifOgrenci OSO 
																			WHERE OS.ID_ODEV = O.ID_ODEV AND OSO.ID_ODEVSINIF = OS.ID_ODEVSINIF FOR JSON PATH
																		)
												FROM Odev O WITH(NOLOCK)
												INNER JOIN OkyanusDB.dbo.v3Kademe3 K3 WITH(NOLOCK) ON K3.ID_KADEME3 = O.ID_KADEME3
												INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
												INNER JOIN OkyanusDB.dbo.v3Sinif S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
												WHERE O.AKTIF = 1
												AND O.ID_ODEVTUR = 5
												AND O.VERILIS_TARIHI BETWEEN @BASLANGIC_TARIHI AND @BITIS_TARIHI
												ORDER BY O.ID_ODEV
												FOR JSON PATH
											), '[]')
								)
						FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
					)
				END
				ELSE
				BEGIN
					SELECT 
					(
						SELECT SUCCESS = 0,
							   DESCRIPTION = 'Gönderilen apikey hatalı!',
							   LIST = '[]'
						FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
					)
				END
			END

			Branch_Islem19:

			IF @ISLEM = 19 -- ÖDEV BİLDİRİM - MAİL GÖNDER
			BEGIN
				DECLARE	@TC_ALAN VARCHAR(11)

				--DECLARE @MAIL VARCHAR(MAX)
				--DECLARE @MAILKONU VARCHAR(150)
				--DECLARE @ALANMAIL VARCHAR(MAX)
				DECLARE @DERSAD VARCHAR(100)
				DECLARE @ADSOYAD VARCHAR(150)
				DECLARE @BASLIK VARCHAR(150)
				DECLARE @ACIKLAMA VARCHAR(500)
				DECLARE @VERILISTARIHI VARCHAR(50)
				DECLARE @TESLIMTARIHI VARCHAR(50)
	   
				SELECT	 @DERSAD           = ISNULL(D.DERSAD, '')
						,@ADSOYAD          = ISNULL(K.AD + ' ' + K.SOYAD, '')
						,@BASLIK           = OD.BASLIK
						,@ACIKLAMA         = OD.ACIKLAMA
						,@VERILISTARIHI    = CONVERT(VARCHAR(MAX), OD.VERILIS_TARIHI, 104)
						,@TESLIMTARIHI     = CONVERT(VARCHAR(MAX), OD.TESLIM_TARIHI, 104)
				FROM Odev OD WITH(NOLOCK)
				LEFT JOIN eokul_v2.dbo.Ders				D WITH(NOLOCK) ON OD.ID_DERS = D.ID_DERS
				INNER JOIN OkyanusDB.dbo.v3Kullanici	K WITH(NOLOCK) ON K.TCKIMLIKNO = OD.KYE_KULLANICI
				WHERE OD.ID_ODEV = @ID_ODEV 
		

				--SET @MAIL = '<html><head>
				--<style>body{font-family:verdana;}.baslik{background-color:rgb(176, 229, 231);width:150px;}table{width:100%;}td {border:1px solid #e3e3e3;}</style>
				--</head><body><table><tr>
				--<td class="baslik">Öğretmen Ad</td>
				--<td>' + @ADSOYAD + '</td>
				--<td class="baslik">Ders</td>
				--<td>' + @DERSAD + '</td>
				--</tr><tr>
				--<td class="baslik">Konu</td>
				--<td>' + @BASLIK + '</td>
				--<td class="baslik">Veriliş-Teslim Tarihleri</td>
				--<td>' + @VERILISTARIHI + '-' + @TESLIMTARIHI+'</td>
				--</tr><tr>
				--<td colspan="4"><br>' + @ACIKLAMA + '<br></td>
				--</tr><tr>
				--<td colspan="4"><a href="http://interaktif.okyanuskoleji.k12.tr/" target="_blank">Giriş yapmak için tıklayın...</a></td>
				--</tr></table></body></html>'

				--SET @MAILKONU = (SELECT 'Ödev' + (CASE WHEN @GUNCELLEME = 1 THEN 'Güncellendi' ELSE '' END) + ': ' + @DERSAD + ' - ' + @BASLIK)

				SELECT DISTINCT OSO.TCKIMLIKNO
				INTO #OGRENCILIST
				FROM Odev O WITH(NOLOCK)
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OdevSinifOgrenci OSO WITH(NOLOCK) ON OSO.ID_ODEVSINIF = OS.ID_ODEVSINIF
				WHERE O.ID_ODEV = @ID_ODEV
				
				/*
				IF @MAIL IS NOT NULL
				BEGIN
					SELECT DISTINCT
						KO.EMAIL,
						K.TCKIMLIKNO
					INTO #MAILLIST
					FROM #OGRENCILIST O
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.TCKIMLIKNO
					INNER JOIN OkyanusDB.dbo.v3KullaniciBilgi KO WITH(NOLOCK) ON KO.TCKIMLIKNO = K.TCKIMLIKNO
					WHERE KO.EMAIL LIKE '%_@_%_.__%' AND K.AKTIF=1
					UNION 
					SELECT  
						KB.EMAIL,
						K.TCKIMLIKNO
					FROM #OGRENCILIST O
					INNER JOIN OkyanusDB.dbo.v3OgrenciVeli OV WITH(NOLOCK) ON OV.TCKIMLIKNO_OGR = O.TCKIMLIKNO
					INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = OV.TCKIMLIKNO
					INNER JOIN OkyanusDB.dbo.v3KullaniciBilgi KB WITH(NOLOCK) ON KB.TCKIMLIKNO = K.TCKIMLIKNO
					WHERE KB.EMAIL LIKE '%_@_%_.__%' AND K.AKTIF=1

					WHILE EXISTS (SELECT TOP 1 * FROM #MAILLIST)
					BEGIN	
						SELECT TOP 1 
							 @TC_ALAN	= TCKIMLIKNO
							,@ALANMAIL	= EMAIL
						FROM #MAILLIST ORDER BY TCKIMLIKNO 


						EXEC OkyanusIletisim.dbo.sp_SendPushMail
								 @TCKIMLIKNO		= @TCKIMLIKNO
								,@HEADER			= @MAILKONU
								,@MESAJ				= @MAIL
								,@MAILADRES			= @ALANMAIL
								,@LINK				= ''
								,@TCKIMLIKNO_KIME	= @TC_ALAN
								,@ID_UYGULAMA		= 2

						DELETE FROM #MAILLIST WHERE TCKIMLIKNO = @TC_ALAN
					END
				END
				*/
				DECLARE @BILDIRIM VARCHAR(250)		= (SELECT SUBSTRING('Ödev' + (CASE WHEN @GUNCELLEME = 1 THEN ' Güncellendi' ELSE '' END) + ': ' + @DERSAD + ' - ' + @BASLIK, 0, 249))
				DECLARE @BILDIRIMTAM VARCHAR(MAX)	= (SELECT			'Ödev' + (CASE WHEN @GUNCELLEME = 1 THEN ' Güncellendi' ELSE '' END) + ': ' + @DERSAD + ' - ' + @BASLIK)

				SELECT DISTINCT
					O.TCKIMLIKNO , O.TCKIMLIKNO AS TC_OGRENICI
				INTO #BILDIRIMLIST
				FROM #OGRENCILIST O
				INNER JOIN OkyanusDB.dbo.v3Kullanici K WITH(NOLOCK) ON K.TCKIMLIKNO = O.TCKIMLIKNO
				WHERE K.AKTIF=1
				UNION 
				SELECT DISTINCT
					K.TCKIMLIKNO, OV.TCKIMLIKNO_OGR AS TC_OGRENICI
				FROM #OGRENCILIST O
				INNER JOIN OkyanusDB.dbo.v3OgrenciVeli	OV WITH(NOLOCK)	ON OV.TCKIMLIKNO_OGR = O.TCKIMLIKNO
				INNER JOIN OkyanusDB.dbo.v3Kullanici	K WITH(NOLOCK)	ON K.TCKIMLIKNO = ov.TCKIMLIKNO
				WHERE K.AKTIF = 1

				WHILE EXISTS (SELECT TOP 1 * FROM #BILDIRIMLIST)
				BEGIN
					SELECT TOP 1 
						@TC_ALAN	= TCKIMLIKNO,
						@TC_OGRENCI	= TC_OGRENICI
					FROM #BILDIRIMLIST 
					ORDER BY TCKIMLIKNO 

			
					DECLARE @LINK VARCHAR(MAX) = '', @LINK_ETIKET VARCHAR(MAX) = ''

					IF @TC_ALAN <> @TC_OGRENCI
					BEGIN
						SET @LINK			='https://pusulam.okyanuskoleji.k12.tr/AnaSayfaOutSide.html#OutSide/OSOdevListesi?TC_OGRENCI='+@TC_OGRENCI+'&TCKIMLIKNO='+@TC_ALAN
						SET @LINK_ETIKET	= 'Ödeve Git'
					END

					EXEC OkyanusIletisim.dbo.sp_SendPushMessage
							 @TCKIMLIKNO		= @TCKIMLIKNO
							,@HEADER			= 'Interaktif Ödev'
							,@MESAJ				= @BILDIRIM
							,@LINK				= @LINK
							,@MENU				= '000'
							,@TCKIMLIKNO_KIME	= @TC_ALAN
							,@ID_UYGULAMA		= 2
							,@MESAJTAM			= @BILDIRIMTAM
							,@LINK_ETIKET		= @LINK_ETIKET

						EXEC OkyanusIletisim.dbo.sp_SendPushMessage
							 @TCKIMLIKNO		= @TCKIMLIKNO
							,@HEADER			= 'Interaktif Ödev'
							,@MESAJ				= @BILDIRIM
							,@LINK				= @LINK
							,@MENU				= '000'
							,@TCKIMLIKNO_KIME	= @TC_ALAN
							,@ID_UYGULAMA		= 1
							,@MESAJTAM			= @BILDIRIMTAM
							,@LINK_ETIKET		= @LINK_ETIKET

					DELETE FROM #BILDIRIMLIST WHERE TCKIMLIKNO = @TC_ALAN
				END
	
				DROP TABLE IF EXISTS #BILDIRIMLIST
				--DROP TABLE IF EXISTS #MAILLIST
				DROP TABLE IF EXISTS #OGRENCILIST
			END

			IF @ISLEM = 20 -- MORPA API -- METE KONTROL
			BEGIN
				SELECT	 O.ID_ODEV
						,O.ID_MORPADERS	
						,OS.ID_ODEVSINIF
						,SINIF = K3.DUZEY
						,SINIFAD = S.AD
						,BASLIK
						,ACIKLAMA
						,VERILIS_TARIHI
						,TESLIM_TARIHI
						--,KYE_KULLANICI
						,KYE_KULLANICI = (CASE WHEN O.ID_KADEME3 IN (7, 8, 9, 10) THEN (SELECT TOP 1 TCKIMLIKNO FROM OkyanusDB.dbo.v3SinifPersonel P WITH(NOLOCK) WHERE P.ID_SINIF = OS.ID_SINIF AND P.ID_KULLANICITIPI = 100) ELSE O.KYE_KULLANICI END)
						,KYE_TARIH
						,MATERYALLIST = (SELECT DISTINCT OMM.ID_MORPAMATERYAL FROM OdevMorpaMateryal OMM WITH(NOLOCK) JOIN MorpaMateryal MM WITH(NOLOCK) ON MM.ID_MORPAMATERYAL = OMM.ID_MORPAMATERYAL AND MM.ID_MORPADERS = O.ID_MORPADERS WHERE OMM.ID_ODEV = O.ID_ODEV AND MM.AKTIF = 1 FOR JSON PATH)
						,KAZANIMLIST = (SELECT DISTINCT MK.KOD as ID_MORPAKAZANIM FROM OdevMorpaKazanim OMK WITH(NOLOCK) JOIN MorpaKazanim MK WITH(NOLOCK) ON MK.ID_MORPAKAZANIM = OMK.ID_MORPAKAZANIM AND MK.AKTIF = 1 WHERE OMK.ID_ODEV = O.ID_ODEV FOR JSON PATH)
						,OGRENCILIST = (
											SELECT DISTINCT TCKIMLIKNO
											FROM OdevSinifOgrenci OSO  WITH(NOLOCK)
											WHERE OS.ID_ODEV = O.ID_ODEV AND OSO.ID_ODEVSINIF = OS.ID_ODEVSINIF FOR JSON PATH
										)
				FROM Odev O WITH(NOLOCK)
				INNER JOIN OkyanusDB.dbo.v3Kademe3 K3 WITH(NOLOCK) ON K3.ID_KADEME3 = O.ID_KADEME3
				INNER JOIN OdevSinif OS WITH(NOLOCK) ON OS.ID_ODEV = O.ID_ODEV
				INNER JOIN OkyanusDB.dbo.v3Sinif S WITH(NOLOCK) ON S.ID_SINIF = OS.ID_SINIF
				WHERE O.AKTIF = 1
				AND O.ID_ODEVTUR = 5
				AND O.VERILIS_TARIHI >= CAST(DATEADD(DAY, -7, GETDATE()) AS DATE)
				ORDER BY O.ID_ODEV
			END
		END
	
	--COMMIT TRANSACTION [TranOdev]
	END TRY
	BEGIN CATCH
		--ROLLBACK TRANSACTION [TranOdev]
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT 
			@ErrorSeverity 	= ERROR_SEVERITY(),
			@ErrorState		= ERROR_STATE()
				
		DECLARE @MSG VARCHAR(4000)
		SELECT @MSG = ERROR_MESSAGE()

		EXEC [dbo].[sp_CustomRaiseError] @MESSAGE = @MSG, @SEVERITY = @ErrorSeverity , @STATE = @ErrorState , @ID_LOG = @ID_LOG, @ID_LOGTUR = 2
	END CATCH;
END

GO

USE [OkyanusIletisim]
GO
/****** Object:  StoredProcedure [dbo].[sp_Yoklama]    Script Date: 9.10.2020 16:08:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[sp_Yoklama]
	
	@ISLEM				INT					= NULL,
	@TCKIMLIKNO			VARCHAR(MAX)		= NULL,
	@OTURUM				UNIQUEIDENTIFIER	= NULL,
	@ID_MENU			INT					= NULL,

	@SQLJSON			NVARCHAR(MAX)		= NULL,
	@ID_SINIF			INT					= NULL,
	@ID_DERSPROGRAM		INT					= NULL,
	@TARIH				NVARCHAR(MAX)		= NULL,
	@YIL				INT					= NULL,
	@AY					INT					= NULL,
	@TCKIMLIKNO_OGR		NVARCHAR(MAX)		= NULL
	
	
AS
BEGIN

BEGIN TRY    
	
/*

	Değiştiren Adı		: Kadir Cengiz
	Değiştirilen Tarih	: 28.09.2020
	
	--	ID_DERSPROGRAM
	--	Yoklamanın saatlik alınması

*/

		DECLARE @MSG			VARCHAR(4000)
	    DECLARE @ErrorSeverity	INT
		DECLARE @ErrorState		INT
		
		DECLARE @return_variable INT
		EXEC @return_variable = [dbo].[sp_OturumKontrol] @TCKIMLIKNO = @TCKIMLIKNO, @OTURUM = @OTURUM, @ID_MENU = @ID_MENU

	IF @return_variable = 1
	BEGIN
				
		SET @SQLJSON =  REPLACE(@SQLJSON, CHAR(10), '')
		SET @SQLJSON =  REPLACE(@SQLJSON, CHAR(13), '')


		DECLARE @DONEM VARCHAR(MAX)
		SELECT @DONEM = DONEM 
		FROM OkyanusDB.dbo.v3AktifDonem
		WHERE AKTIF = 1
		
		DECLARE @ID_YOKLAMA	INT

		DECLARE @LINK				VARCHAR(MAX)	= ''
		DECLARE @LINKMSG			VARCHAR(MAX)	= ''
		DECLARE @HEADER				VARCHAR(MAX)	= ''
		
		DECLARE @JSONDATA	VARCHAR(MAX) = NULL
		

		IF @ISLEM = 1	--	Yoklama Oluştur
		BEGIN
						
			DECLARE @TBL_YOKLAMA	TABLE (ID_YOKLAMA INT) 
			

			SELECT
				 @ID_SINIF		= ID_SINIF
				,@TARIH			= TARIH
				,@ID_DERSPROGRAM= ID_DERSPROGRAM
			FROM OPENJSON(@SQLJSON)
			WITH
			(
				ID_SINIF		INT,
				ID_DERSPROGRAM	INT,
				TARIH			NVARCHAR(MAX)
			) 
			
			-- KAYITLI ID_YOKLAMA BUL
			SELECT 
				@ID_YOKLAMA = ID_YOKLAMA 
			FROM Yoklama
			WHERE ID_SINIF = @ID_SINIF AND TARIH = @TARIH AND ID_DERSPROGRAM = @ID_DERSPROGRAM

			-- Mevcut Yoklama Listesindeki Öğrencileri ve Durumlarını Al
			SELECT 
				 TCKIMLIKNO
				,GELDI
			INTO #YoklamaKullanici
			FROM YoklamaKullanici
			WHERE ID_YOKLAMA = @ID_YOKLAMA


			-- KAYITLI YOKLAMA SİL
			DELETE FROM Yoklama
			WHERE ID_YOKLAMA = @ID_YOKLAMA

			DELETE FROM YoklamaKullanici
			WHERE ID_YOKLAMA = @ID_YOKLAMA
			-----------------------

			INSERT INTO Yoklama
						(ID_SINIF, ID_DERSPROGRAM, TARIH, KYE_TCKIMLIKNO)
			OUTPUT INSERTED.ID_YOKLAMA INTO @TBL_YOKLAMA(ID_YOKLAMA)
			SELECT
				ID_SINIF, ID_DERSPROGRAM, TARIH, @TCKIMLIKNO
			FROM OPENJSON(@SQLJSON)
			WITH
			(
				ID_SINIF		INT,
				ID_DERSPROGRAM	INT,
				TARIH			NVARCHAR(MAX)
			) 

			SELECT @ID_YOKLAMA = ID_YOKLAMA FROM @TBL_YOKLAMA

			INSERT INTO YoklamaKullanici
						(ID_YOKLAMA, TCKIMLIKNO, GELDI)
			SELECT DISTINCT @ID_YOKLAMA, TCKIMLIKNO, GELDI
			FROM OPENJSON( @SQLJSON, '$.KULLANICILISTE' ) 
			WITH (
					TCKIMLIKNO NVARCHAR(MAX) '$.TCKIMLIKNO',
					GELDI BIT '$.GELDI'
				);
			


			-- PUSH MESSAGE

			
			SELECT 
				 KYE_TCKIMLIKNO		= Y.KYE_TCKIMLIKNO
				,MESAJ				= 'Öğrencimiz ' + KL.AD +' '+ KL.SOYAD +' '+ CONVERT(VARCHAR(10), Y.TARIH, 104) +' Tarihinde ' + DS.BASSAAT + ' - ' + DS.BITSAAT + ' ' + ISNULL(D.DERSAD + ' ', '') + 'dersine '+ CASE YK.GELDI WHEN 0 THEN 'Gelmemiştir.' ELSE 'Gelmiştir.' END
				,TCKIMLIKNO_KIME	= OV.TCKIMLIKNO
				,RN = ROW_NUMBER() OVER(ORDER BY Y.KYE_TCKIMLIKNO)
			INTO #Liste FROM Yoklama							Y
			INNER JOIN YoklamaKullanici				YK	ON	YK.ID_YOKLAMA		= Y.ID_YOKLAMA
			INNER JOIN OkyanusDB.dbo.v3OgrenciVeli	OV	ON	OV.TCKIMLIKNO_OGR	= YK.TCKIMLIKNO
			INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO		= YK.TCKIMLIKNO
			INNER JOIN OkyanusDB.dbo.v3DersProgram	DP	ON	DP.ID_DERSPROGRAM	= Y.ID_DERSPROGRAM
			INNER JOIN eokul_v2.dbo.Ders			D	ON	D.ID_DERS			= DP.ID_DERS
			INNER JOIN DersSaat						DS	ON	DS.DERSSAAT			= DP.DERSSAAT
			WHERE Y.ID_YOKLAMA = @ID_YOKLAMA
			 -- Yeni Liste İle Aynı Olanlara Bildirim Gitmesin
			AND YK.TCKIMLIKNO NOT IN(SELECT SUBYK.TCKIMLIKNO FROM #YoklamaKullanici SUBYK WHERE SUBYK.TCKIMLIKNO = YK.TCKIMLIKNO AND SUBYK.GELDI = YK.GELDI)
			

			DECLARE @I INT = 1, @COUNT INT = 0
			SET @COUNT = (SELECT COUNT(1) FROM #Liste)

			DECLARE @PUSHMESAJ	NVARCHAR(MAX), @TCKIMLIKNO_KIME NVARCHAR(MAX)


			WHILE @I <= @COUNT
			BEGIN	

				SELECT
					 @TCKIMLIKNO_KIME	= TCKIMLIKNO_KIME
					,@PUSHMESAJ			= MESAJ
				FROM #Liste
				WHERE RN = @I

				
				EXEC dbo.sp_SendPushMessage
					 @TCKIMLIKNO		= @TCKIMLIKNO
					,@HEADER			= 'Yoklama Durumu'
					,@MESAJ				= @PUSHMESAJ
					,@LINK				= '001'
					,@MENU				= '001'
					,@TCKIMLIKNO_KIME	= @TCKIMLIKNO_KIME
					,@ID_UYGULAMA		= 1
				
				SET @I = @I + 1

			END


			DROP TABLE #Liste
			DROP TABLE #YoklamaKullanici


			SELECT
			ISNULL((
				SELECT 
					 E.ID_YOKLAMA
					,E.ID_SINIF
					,E.TARIH
					,E.ID_DERSPROGRAM
					,KULLANICILISTE = (SELECT 
											 EK.TCKIMLIKNO
											,KL.AD
											,KL.SOYAD
											,EK.GELDI
											,ACIKLAMA	= ISNULL(YA.ACIKLAMA, '')
										FROM YoklamaKullanici					EK 
										INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO = EK.TCKIMLIKNO
										LEFT  JOIN YoklamaKullaniciAciklama		YA	ON	YA.ID_SINIF = E.ID_SINIF AND YA.TARIH = E.TARIH AND YA.TCKIMLIKNO = EK.TCKIMLIKNO
										WHERE EK.ID_YOKLAMA = E.ID_YOKLAMA 
										FOR JSON PATH)
				FROM Yoklama	E
				WHERE E.ID_YOKLAMA = @ID_YOKLAMA
				FOR JSON PATH, ROOT('Yoklama')
			), '{ "Yoklama" : [] }') AS LISTE
			
						
		END

		IF @ISLEM = 2	--	Yoklama Liste
		BEGIN
			

			SELECT
			ISNULL((
				SELECT 
					 E.ID_YOKLAMA
					,E.ID_SINIF
					,E.TARIH
					,E.ID_DERSPROGRAM
					,KULLANICILISTE = (SELECT	 EK.TCKIMLIKNO
												,KL.AD
												,KL.SOYAD
												,EK.GELDI
												,ACIKLAMA	= ISNULL(YA.ACIKLAMA, '')
										FROM YoklamaKullanici					EK 
										INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO	= EK.TCKIMLIKNO
										LEFT  JOIN YoklamaKullaniciAciklama		YA	ON	YA.ID_SINIF		= E.ID_SINIF 
																					AND YA.TARIH		= E.TARIH 
																					AND YA.TCKIMLIKNO	= EK.TCKIMLIKNO
										WHERE EK.ID_YOKLAMA = E.ID_YOKLAMA 
										FOR JSON PATH)
				FROM Yoklama	E
				WHERE E.ID_DERSPROGRAM = @ID_DERSPROGRAM AND E.TARIH = CAST(@TARIH AS DATE)
				FOR JSON PATH, ROOT('Yoklama')
			), '{ "Yoklama" : [] }') AS LISTE
			
		END
		
		IF @ISLEM = 3	--	Öğrenci	Yoklama Liste
		BEGIN
						
			SELECT
			ISNULL((
				SELECT 
					 E.ID_YOKLAMA
					,E.ID_SINIF
					,E.TARIH
					,KULLANICILISTE = (SELECT 
											 EK.TCKIMLIKNO
											,KL.AD
											,KL.SOYAD
											,EK.GELDI
											,ACIKLAMA	= ISNULL(YA.ACIKLAMA, '')
										FOR JSON PATH)
				FROM Yoklama							E
				INNER JOIN YoklamaKullanici				EK	ON	EK.ID_YOKLAMA	= E.ID_YOKLAMA
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO	= EK.TCKIMLIKNO
				LEFT  JOIN YoklamaKullaniciAciklama		YA	ON	YA.ID_SINIF		= E.ID_SINIF AND YA.TARIH = E.TARIH AND YA.TCKIMLIKNO = EK.TCKIMLIKNO
				WHERE YEAR(E.TARIH) = @YIL AND MONTH(E.TARIH) = @AY AND EK.TCKIMLIKNO = @TCKIMLIKNO_OGR
				ORDER BY E.TARIH
				FOR JSON PATH, ROOT('Yoklama')
			), '{ "Yoklama" : [] }') AS LISTE

		END

		IF @ISLEM = 4	--	Yoklama Açıklama Ekle	BY ID, TCKIMLIKNO
		BEGIN
			
			--SELECT
			--	@ID_YOKLAMA = ID_YOKLAMA
			--FROM OPENJSON(@SQLJSON)
			--WITH
			--(
			--	ID_YOKLAMA	INT
			--) 
			
			DECLARE @ACIKLAMA_ISLEM4 VARCHAR(MAX) = NULL
			SELECT 
				@ID_SINIF = Y.ID_SINIF, @TARIH = Y.TARIH, @TCKIMLIKNO_OGR = YK.TCKIMLIKNO, @ACIKLAMA_ISLEM4 = S.ACIKLAMA
			FROM YoklamaKullanici	YK
			INNER JOIN Yoklama		Y	ON	Y.ID_YOKLAMA = YK.ID_YOKLAMA
			INNER JOIN OPENJSON(@SQLJSON)
			WITH
			(
				ID_YOKLAMA	INT,
				TCKIMLIKNO	NVARCHAR(MAX),
				ACIKLAMA	NVARCHAR(MAX)
			) S	ON	S.ID_YOKLAMA = YK.ID_YOKLAMA	AND S.TCKIMLIKNO = YK.TCKIMLIKNO

			
			-----------------------------------
			DELETE FROM YoklamaKullaniciAciklama
			WHERE ID_SINIF = @ID_SINIF AND TARIH = @TARIH AND TCKIMLIKNO = @TCKIMLIKNO_OGR

			INSERT INTO YoklamaKullaniciAciklama(KYE_TCKIMLIKNO, ID_SINIF, TARIH, TCKIMLIKNO, ACIKLAMA)
			VALUES(@TCKIMLIKNO, @ID_SINIF, @TARIH, @TCKIMLIKNO_OGR, @ACIKLAMA_ISLEM4)
			-----------------------------------


			SELECT
			ISNULL((
				SELECT 
					 E.ID_YOKLAMA
					,E.ID_SINIF
					,E.TARIH
					,KULLANICILISTE = (SELECT 
											 EK.TCKIMLIKNO
											,KL.AD
											,KL.SOYAD
											,EK.GELDI
											,ACIKLAMA	= (SELECT
															ISNULL(YA.ACIKLAMA, '')
															FROM YoklamaKullaniciAciklama	YA
															WHERE YA.ID_SINIF = E.ID_SINIF AND YA.TARIH = E.TARIH AND YA.TCKIMLIKNO = EK.TCKIMLIKNO
															) --ISNULL(EK.ACIKLAMA, '')
										FOR JSON PATH)
				FROM Yoklama							E
				INNER JOIN YoklamaKullanici				EK	ON	EK.ID_YOKLAMA	= E.ID_YOKLAMA
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO	= EK.TCKIMLIKNO
				INNER JOIN OPENJSON(@SQLJSON)
				WITH
				(
					ID_YOKLAMA	INT,
					TCKIMLIKNO	NVARCHAR(MAX),
					ACIKLAMA	NVARCHAR(MAX)
				) S	ON	S.ID_YOKLAMA = EK.ID_YOKLAMA	AND S.TCKIMLIKNO = EK.TCKIMLIKNO
				FOR JSON PATH, ROOT('Yoklama')
			), '{ "Yoklama" : [] }') AS LISTE


		END

		IF @ISLEM = 5	--	Yoklama Açıklama Ekle	BY TARIH, TCKIMLIKNO
		BEGIN
			
			--SELECT
			--	@ID_YOKLAMA = ID_YOKLAMA
			--FROM OPENJSON(@SQLJSON)
			--WITH
			--(
			--	ID_YOKLAMA	INT
			--) 
			
			DECLARE @ACIKLAMA_ISLEM5 VARCHAR(MAX) = NULL
			SELECT 
				@ID_SINIF = Y.ID_SINIF, @TARIH = Y.TARIH, @TCKIMLIKNO_OGR = YK.TCKIMLIKNO, @ACIKLAMA_ISLEM5 = S.ACIKLAMA
			FROM YoklamaKullanici	YK
			INNER JOIN Yoklama		Y	ON	Y.ID_YOKLAMA = YK.ID_YOKLAMA
			INNER JOIN OPENJSON(@SQLJSON)
			WITH
			(
				TARIH		NVARCHAR(MAX),
				TCKIMLIKNO	NVARCHAR(MAX),
				ACIKLAMA	NVARCHAR(MAX)
			) S	ON	S.TARIH = Y.TARIH	AND S.TCKIMLIKNO = YK.TCKIMLIKNO

			
			-----------------------------------
			DELETE FROM YoklamaKullaniciAciklama
			WHERE ID_SINIF = @ID_SINIF AND TARIH = @TARIH AND TCKIMLIKNO = @TCKIMLIKNO_OGR

			INSERT INTO YoklamaKullaniciAciklama(KYE_TCKIMLIKNO, ID_SINIF, TARIH, TCKIMLIKNO, ACIKLAMA)
			VALUES(@TCKIMLIKNO, @ID_SINIF, @TARIH, @TCKIMLIKNO_OGR, @ACIKLAMA_ISLEM5)
			-----------------------------------



			SELECT
			ISNULL((
				SELECT 
					 E.ID_YOKLAMA
					,E.ID_SINIF
					,E.TARIH
					,KULLANICILISTE = (SELECT 
											 EK.TCKIMLIKNO
											,KL.AD
											,KL.SOYAD
											,EK.GELDI
											,ACIKLAMA	= (SELECT
															ISNULL(YA.ACIKLAMA, '')
															FROM YoklamaKullaniciAciklama	YA
															WHERE YA.ID_SINIF = E.ID_SINIF AND YA.TARIH = E.TARIH AND YA.TCKIMLIKNO = EK.TCKIMLIKNO
															) --ISNULL(EK.ACIKLAMA, '')
										FOR JSON PATH)
				FROM Yoklama							E
				INNER JOIN YoklamaKullanici				EK	ON	EK.ID_YOKLAMA	= E.ID_YOKLAMA
				INNER JOIN OkyanusDB.dbo.v3Kullanici	KL	ON	KL.TCKIMLIKNO	= EK.TCKIMLIKNO
				INNER JOIN OPENJSON(@SQLJSON)
				WITH
				(
					TARIH		NVARCHAR(MAX),
					TCKIMLIKNO	NVARCHAR(MAX),
					ACIKLAMA	NVARCHAR(MAX)
				) S	ON	S.TARIH = E.TARIH	AND S.TCKIMLIKNO = EK.TCKIMLIKNO
				FOR JSON PATH, ROOT('Yoklama')
			), '{ "Yoklama" : [] }') AS LISTE


		END

		IF @ISLEM = 6	--	ÖĞRETMEN DERS PROGRAM LİSTE
		BEGIN

			SELECT ISNULL((
				SELECT	 ID_DERSPROGRAM
						,DERSSAAT
						,SUBEAD
						,SINIF
						,SD.ID_SINIF
						,SD.ID_SUBE
				FROM OkyanusDB..v3DersProgram	DP
				JOIN OkyanusDB..vw_v4SinifDetay	SD	ON	SD.ID_SINIF = DP.ID_SINIF
													AND SD.DONEM	= OkyanusDB.dbo.fn_AktifDonem()
				WHERE	TCKIMLIKNO	= @TCKIMLIKNO
					AND DP.GUN		= DATEPART(DW,CAST(@TARIH AS DATE))
				ORDER BY DERSSAAT
				FOR JSON PATH, ROOT('LISTE')
			),'{"LISTE":[]}') AS LISTE

		END

	END

END TRY
		BEGIN CATCH
			
			SELECT 
				@ErrorSeverity	= ERROR_SEVERITY(),
				@ErrorState		= ERROR_STATE()
							
			SELECT @MSG = /*'Prosedür: ' + ISNULL(ERROR_PROCEDURE(), '') + ', Satır: ' + CAST(ERROR_LINE() as varchar) + ', Hata: ' +*/ ERROR_MESSAGE()
			
			RAISERROR (@MSG , -- Message text.
					   @ErrorSeverity, -- Severity.
					   @ErrorState -- State.
					   );
		END CATCH;
	
END


