USE [Pusulam]
GO
/****** Object:  StoredProcedure [dbo].[sp_OgrenciHedef]    Script Date: 28.10.2020 12:32:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER procedure [dbo].[sp_OgrenciHedef]
	@ISLEM				INT				= NULL,
	@TCKIMLIKNO			VARCHAR(11)		= NULL,
	@PROGRAMKODU		VARCHAR(11)		= NULL,
	@OTURUM				VARCHAR(36)		= NULL,
	@ID_MENU			INT				= NULL,
	@PUANTURU			VARCHAR(5)		= NULL,
	@ID_SINAVPUANTURU	INT				= NULL,
	@ID_SINAVTURU		INT				= NULL,
	@SQLJSON			VARCHAR(MAX)	= NULL,
	@OOBP				INT				= NULL,
	@OGRTCKIMLIKNO		VARCHAR(11)		= NULL
AS
BEGIN

BEGIN TRY    
	DECLARE @MSG			VARCHAR(4000)
	DECLARE @ErrorSeverity	INT
	DECLARE @ErrorState		INT
	DECLARE @ID_KADEME3		INT
		
	DECLARE @return_variable INT
	EXEC @return_variable = [dbo].[sp_OturumKontrol] @OTURUM = @OTURUM, @TCKIMLIKNO = @TCKIMLIKNO, @ID_MENU = @ID_MENU

	IF @return_variable = 1
	BEGIN

	DECLARE @AKTIFDONEM VARCHAR(4)= (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) 

		IF @ISLEM = 1	--	Öğrenci Hedef Ekle						
		BEGIN
			IF NOT EXISTS(SELECT * FROM OgrenciHedef WHERE PROGRAMKODU=@PROGRAMKODU and  TCKIMLIKNO= @TCKIMLIKNO and DONEM = (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) and AKTIF = 1)
			BEGIN
				INSERT INTO [dbo].[OgrenciHedef]
						   ([TCKIMLIKNO]
						   ,[PROGRAMKODU]
						   ,[DONEM])
					 VALUES
						   (@TCKIMLIKNO
						   ,@PROGRAMKODU
						   ,(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1))
			END
		END

		IF @ISLEM = 2	--	Öğrenci Hedef Listele					
		BEGIN
			SELECT 
			(
				SELECT	oh.[PROGRAMKODU]
						,tp.[UNIVERSITE]
						,tp.[FAKULTE]
						,tp.[BOLUM]
						,tp.[BOLUM2]
						,tp.[EGITIMDILI]
						,tp.[UCRETBURS]
						,tp.[IL]
						,tp.[UNIVERSITETURU]
						,tp.[OGRENIMSURESI]
						,tp.[OGRENIMTURU]
						,tp.[PUANTURU]
						,tp.[YIL]
						,tp.[TABANPUAN]
						,tp.[KONTENJAN]
						,tp.[PROGRAMTURU]
						,tp.[SONYGSYERLESTIRME]
						,tp.[OKULBIRINCILIGIKONTENJANI]
						,tp.[YERONCELIKLERI]
						,tp.[ENBUYUKPUAN]
						,tp.[BASARISIRALAMA]
						,REPLACE((STUFF((SELECT CAST('@@** ' + [KOSUL] AS VARCHAR(MAX)) 
									FROM UniversiteOzelKosul ok
									WHERE ok.NO IN (SELECT value FROM STRING_SPLIT(REPLACE(tp.OZELKOSULACIKLAMA,' ','') , ','))
									FOR XML PATH ('')), 1, 2, '')),'@@','<br /><br />') AS [OZELKOSULACIKLAMA]
				FROM OgrenciHedef oh
				INNER JOIN UniversiteTabanPuanlari tp on tp.PROGRAMKODU=oh.PROGRAMKODU-- AND tp.YIL = oh.DONEM
				WHERE TCKIMLIKNO=@TCKIMLIKNO  AND TP.YIL = @AKTIFDONEM
					--AND TP.DONEM=(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) 
					AND AKTIF=1
				ORDER BY KYE_TARIH DESC
				FOR JSON PATH, INCLUDE_NULL_VALUES
			) JSONDATA
		END

		IF @ISLEM = 3	--	Öğrenci Hedef Sil						
		BEGIN
			UPDATE OgrenciHedef SET AKTIF=0 where TCKIMLIKNO=@TCKIMLIKNO and PROGRAMKODU=@PROGRAMKODU
		END

		IF @ISLEM = 4	--	Öğrenci Hedef Listele Puan Tür Bazlı	
		BEGIN
			SELECT @ID_KADEME3 = ID_KADEME3 FROM OkyanusDB.dbo.v3KullaniciKademe3 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO

			SELECT
			(
				SELECT 
				(
					SELECT	oh.[PROGRAMKODU]
							,tp.[UNIVERSITE]
							,tp.[FAKULTE]
							,tp.[BOLUM]
							,tp.[BOLUM2]
							,tp.[EGITIMDILI]
							,tp.[UCRETBURS]
							,tp.[IL]
							,tp.[UNIVERSITETURU]
							,tp.[OGRENIMSURESI]
							,tp.[OGRENIMTURU]
							,tp.[PUANTURU]
							,tp.[YIL]
							,[TABANPUAN] = ISNULL(tp.[TABANPUAN], 0)
							,tp.[KONTENJAN]
							,tp.[PROGRAMTURU]
							,tp.[SONYGSYERLESTIRME]
							,tp.[OKULBIRINCILIGIKONTENJANI]
							,tp.[YERONCELIKLERI]
							,tp.[ENBUYUKPUAN]
							,tp.[BASARISIRALAMA]
							,REPLACE((STUFF((SELECT CAST('@@** ' + [KOSUL] AS VARCHAR(MAX)) 
										FROM UniversiteOzelKosul ok
										WHERE ok.NO IN (SELECT value FROM STRING_SPLIT(REPLACE(tp.OZELKOSULACIKLAMA,' ','') , ','))
										FOR XML PATH ('')), 1, 2, '')),'@@','<br /><br />') AS [OZELKOSULACIKLAMA]
					FROM OgrenciHedef oh
					INNER JOIN UniversiteTabanPuanlari tp on tp.PROGRAMKODU=oh.PROGRAMKODU --and tp.YIL = oh.DONEM
					WHERE TCKIMLIKNO=@OGRTCKIMLIKNO 
						--AND DONEM=(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) 
						AND AKTIF=1 
						AND TP.YIL = @AKTIFDONEM
						AND (@PUANTURU = '0' OR tp.PUANTURU= (SELECT KOD FROM SinavPuanTuru WITH(NOLOCK) WHERE ID_SINAVPUANTURU=@PUANTURU))
					ORDER BY tp.[TABANPUAN] DESC
					FOR JSON PATH, INCLUDE_NULL_VALUES
				) AS LIST,
				(
					SELECT COUNT(*) AS TERCIHSAYISI FROM OgrenciHedef WHERE TCKIMLIKNO=@OGRTCKIMLIKNO --and DONEM = @AKTIFDONEM
				) AS TERCIHSAYISI
				FOR JSON PATH, INCLUDE_NULL_VALUES, WITHOUT_ARRAY_WRAPPER
			)
			
			--SELECT 
			--(
			--	SELECT	oh.[PROGRAMKODU]
			--			,tp.[UNIVERSITE]
			--			,tp.[FAKULTE]
			--			,tp.[BOLUM]
			--			,tp.[BOLUM2]
			--			,tp.[EGITIMDILI]
			--			,tp.[UCRETBURS]
			--			,tp.[IL]
			--			,tp.[UNIVERSITETURU]
			--			,tp.[OGRENIMSURESI]
			--			,tp.[OGRENIMTURU]
			--			,tp.[PUANTURU]
			--			,tp.[YIL]
			--			,tp.[TABANPUAN]
			--			,tp.[KONTENJAN]
			--			,tp.[PROGRAMTURU]
			--			,tp.[SONYGSYERLESTIRME]
			--			,tp.[OKULBIRINCILIGIKONTENJANI]
			--			,tp.[YERONCELIKLERI]
			--			,tp.[ENBUYUKPUAN]
			--			,tp.[BASARISIRALAMA]
			--			,REPLACE((STUFF((SELECT CAST('@@** ' + [KOSUL] AS VARCHAR(MAX)) 
			--						FROM UniversiteOzelKosul ok
			--						WHERE ok.NO IN (SELECT value FROM STRING_SPLIT(REPLACE(tp.OZELKOSULACIKLAMA,' ','') , ','))
			--						FOR XML PATH ('')), 1, 2, '')),'@@','<br /><br />') AS [OZELKOSULACIKLAMA]
			--			,(SELECT COUNT(*) FROM OgrenciHedef WHERE TCKIMLIKNO=@OGRTCKIMLIKNO and DONEM = @AKTIFDONEM) AS TERCIHSAYISI
			--	FROM OgrenciHedef oh
			--	INNER JOIN UniversiteTabanPuanlari tp on tp.PROGRAMKODU=oh.PROGRAMKODU 
			--	WHERE TCKIMLIKNO=@OGRTCKIMLIKNO 
			--		--AND DONEM=(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) 
			--		AND AKTIF=1 
			--		AND TP.YIL = @AKTIFDONEM
			--		AND (@PUANTURU = '0' OR tp.PUANTURU= (SELECT KOD FROM SinavPuanTuru WITH(NOLOCK) WHERE ID_SINAVPUANTURU=@PUANTURU))
			--	ORDER BY tp.[TABANPUAN] DESC
			--	FOR JSON PATH, INCLUDE_NULL_VALUES
			--) JSONDATA
			
		END

		IF @ISLEM = 5	--	Öğrenci Puan Turu Son Puan				
		BEGIN
			SELECT 
			ISNULL
			(
			(				
				SELECT TOP 1 sos.PUAN + ISNULL((SELECT OOBP*0.6 FROM OgrenciOOBP WHERE TCKIMLIKNO=SO.TCKIMLIKNO),85*0.6) AS PUAN, ISNULL(HP.PUAN,sos.PUAN + ISNULL((SELECT OOBP*0.6 FROM OgrenciOOBP WHERE TCKIMLIKNO=SO.TCKIMLIKNO),85*0.6)) AS HEDEFPUAN FROM SinavOgrenciSonuc sos WITH(NOLOCK)
				INNER JOIN SinavOgrenci so WITH(NOLOCK) ON so.ID_SINAVOGRENCI=sos.ID_SINAVOGRENCI
				INNER JOIN SinavPuanTuru spt WITH(NOLOCK) ON spt.ID_SINAVPUANTURU=sos.ID_SINAVPUANTURU
				INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=so.ID_SINAV
				LEFT JOIN OgrenciHedefPuan HP ON HP.TCKIMLIKNO=SO.TCKIMLIKNO AND HP.ID_SINAVPUANTURU=spt.ID_SINAVPUANTURU
				WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO and spt.ID_SINAVPUANTURU = @ID_SINAVPUANTURU AND S.OZEL = 0
				ORDER BY s.SINAVTARIH DESC
				FOR JSON PATH, INCLUDE_NULL_VALUES
			), '[{"PUAN": 0, "HEDEFPUAN": 560}]') AS PUANLAR
		END

		IF @ISLEM = 6	--	Öğrenci Net Listele						
		BEGIN
			SELECT @ID_KADEME3 = ID_KADEME3 FROM OkyanusDB.dbo.v3KullaniciKademe3 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO
			IF @ID_SINAVPUANTURU = 6 -- DİL
			BEGIN
				SELECT
				(
					SELECT
					ISNULL((
						SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
						FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
						INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
						INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
						INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
						LEFT JOIN OgrenciHedefNet HN ON HN.ID_SINAVTURU=4 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
						LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=4 AND SUBS.SINAVTARIH<S.SINAVTARIH AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
						WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
						AND S.OZEL = 0
						AND SO.ID_SINAV=(
											SELECT ID_SINAV FROM
											(
												SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
												INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV AND S.AKTIF=1 AND S.OZEL = 0
												WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO AND S.ID_SINAVTURU=4
														AND DONEM = @AKTIFDONEM
											) XTABLE
											WHERE RN=1
										)
						ORDER BY SD.BOLUMNO
						FOR JSON PATH, INCLUDE_NULL_VALUES
					),
					(
						SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'AYT DİL' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
						FROM Sinav S  WITH(NOLOCK)
						INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
						INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
						INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
						LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
						where S.ID_SINAVTURU=4 AND S.OZEL = 0 AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) WHERE ID_SINAVTURU=4  AND DONEM = @AKTIFDONEM AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) AND EXISTS (SELECT * FROM SinavDers WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) AND EXISTS (SELECT * FROM SinavKitapcik WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) AND SUBS.OZEL = 0)
						GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, BOLUMNO, HN.NET, S.AD
						ORDER BY SD.BOLUMNO
						FOR JSON PATH, INCLUDE_NULL_VALUES
					)
					)
					AS YKSSINAVSONUC,
					ISNULL((
						SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
						FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
						INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
						INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
						INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
						LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=2 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
						LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=2 AND SUBS.ID_SINAV<SO.ID_SINAV AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
						WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
						AND S.OZEL = 0
						AND SO.ID_SINAV=(
											SELECT ID_SINAV FROM
											(
												SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
												INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
												WHERE	SO.TCKIMLIKNO = @OGRTCKIMLIKNO 
													AND S.ID_SINAVTURU=2 
													AND S.AKTIF=1 
													AND S.OZEL = 0
													AND DONEM = @AKTIFDONEM
											) XTABLE
											WHERE RN=1
										)
						ORDER BY SD.BOLUMNO
						FOR JSON PATH, INCLUDE_NULL_VALUES
					),
					(
						SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'TYT' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
						FROM Sinav S WITH(NOLOCK) 
						INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
						INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
						INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
						LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
						where S.ID_SINAVTURU=2 
						AND S.ID_SINAV = (SELECT MAX(ID_SINAV) FROM Sinav SUBS WHERE ID_SINAVTURU=2 AND DONEM = @AKTIFDONEM AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) AND SUBS.OZEL = 0) 
						AND S.OZEL = 0
						GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
						ORDER BY SD.BOLUMNO
						FOR JSON PATH, INCLUDE_NULL_VALUES
					)
					) AS TYTSINAVSONUC
					FOR JSON PATH, INCLUDE_NULL_VALUES
				) AS SINAVSONUC
			END
			ELSE 
			BEGIN
				IF @ID_KADEME3 IN (17) -- 11 İse TYT-AYT VE AAYKS
				BEGIN
					SELECT
					(
						SELECT
						ISNULL((
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
							FROM SinavOgrenciCevapBolum		 SOC	WITH(NOLOCK)
							INNER JOIN SinavOgrenci			 SO		WITH(NOLOCK) ON SO.ID_SINAVOGRENCI	=SOC.ID_SINAVOGRENCI
							INNER JOIN SinavDers			 SD		WITH(NOLOCK) ON SD.ID_SINAVDERS		=SOC.ID_SINAVDERS
							INNER JOIN Sinav				 S		WITH(NOLOCK) ON S.ID_SINAV			=SD.ID_SINAV
							LEFT JOIN OgrenciHedefNet		 HN		WITH(NOLOCK) ON HN.ID_SINAVTURU		=3 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
							LEFT JOIN SinavOgrenciCevapBolum SOC2	WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=3 AND SUBS.SINAVTARIH<S.SINAVTARIH AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
							WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
							AND S.OZEL = 0
							AND SO.ID_SINAV=(
												SELECT ID_SINAV FROM
												(
													SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
													INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV AND S.AKTIF=1 AND S.OZEL = 0
													WHERE	SO.TCKIMLIKNO = @OGRTCKIMLIKNO
														AND S.ID_SINAVTURU=3 
														AND DONEM = @AKTIFDONEM
												) XTABLE
												WHERE RN=1
											)
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						),
						(
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'AYT' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
							FROM Sinav S  WITH(NOLOCK)
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
							INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
							INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
							where S.ID_SINAVTURU=3 
							AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) WHERE ID_SINAVTURU=3 
										AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
										AND EXISTS (SELECT * FROM SinavDers WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
										AND EXISTS (SELECT * FROM SinavKitapcik WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV)
										AND SUBS.OZEL = 0
										AND DONEM = @AKTIFDONEM) 
							AND S.OZEL = 0
							GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)
						)
						AS YKSSINAVSONUC,
						ISNULL((
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
							FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
							INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
							INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=2 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
							LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=2 AND SUBS.ID_SINAV<SO.ID_SINAV AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
							WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
							AND S.OZEL = 0
							AND SO.ID_SINAV=(
												SELECT ID_SINAV FROM
												(
													SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
													INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
													WHERE	SO.TCKIMLIKNO = @OGRTCKIMLIKNO 
														AND S.ID_SINAVTURU=2 
														AND S.AKTIF=1 
														AND S.OZEL= 0
														AND DONEM = @AKTIFDONEM
												) XTABLE
												WHERE RN=1
											)
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						),
						(
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'TYT' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
							FROM Sinav S  WITH(NOLOCK)
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
							INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
							INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
							where S.ID_SINAVTURU=2 
							AND S.OZEL = 0
							AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) 
											WHERE ID_SINAVTURU=2 
											AND DONEM = @AKTIFDONEM
											AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV AND SUBS.OZEL = 0))
							GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)
						) AS TYTSINAVSONUC,					
						ISNULL(
							(
								SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
								FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
								INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
								INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
								INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
								LEFT JOIN OgrenciHedefNet HN  WITH(NOLOCK)ON HN.ID_SINAVTURU=6 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
								LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=6 AND SUBS.SINAVTARIH<S.SINAVTARIH AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.SINAVTARIH DESC)
								WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
								AND S.OZEL = 0
								AND SO.ID_SINAV=(
													SELECT ID_SINAV FROM
													(
														SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
														INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
														WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO AND S.ID_SINAVTURU=6 AND S.AKTIF=1 AND S.OZEL = 0
														AND DONEM = @AKTIFDONEM
													) XTABLE
													WHERE RN=1
												)
								ORDER BY SD.BOLUMNO
								FOR JSON PATH, INCLUDE_NULL_VALUES
							),
							(
								SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'AAYKS' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
								FROM Sinav S  WITH(NOLOCK)
								INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
								INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
								INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
								LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
								where S.ID_SINAVTURU=6 
								AND S.OZEL = 0
								AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) WHERE ID_SINAVTURU=6 
												AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
												AND EXISTS (SELECT * FROM SinavDers WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
												AND EXISTS (SELECT * FROM SinavKitapcik WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV)
												AND SUBS.OZEL = 0
												AND DONEM = @AKTIFDONEM)
								GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
								ORDER BY SD.BOLUMNO
								FOR JSON PATH, INCLUDE_NULL_VALUES
							)
						)
						AS AAYKSSINAVSONUC
						FOR JSON PATH, INCLUDE_NULL_VALUES
					) AS SINAVSONUC					
				END
				ELSE IF @ID_KADEME3 IN (18) -- 12 İse TYT-AYT
				BEGIN
					SELECT
					(
						SELECT
						ISNULL((
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
							FROM SinavOgrenciCevapBolum		 SOC	WITH(NOLOCK)
							INNER JOIN SinavOgrenci			 SO		WITH(NOLOCK) ON SO.ID_SINAVOGRENCI	=SOC.ID_SINAVOGRENCI
							INNER JOIN SinavDers			 SD		WITH(NOLOCK) ON SD.ID_SINAVDERS		=SOC.ID_SINAVDERS
							INNER JOIN Sinav				 S		WITH(NOLOCK) ON S.ID_SINAV			=SD.ID_SINAV
							LEFT JOIN OgrenciHedefNet		 HN		WITH(NOLOCK) ON HN.ID_SINAVTURU		=3 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
							LEFT JOIN SinavOgrenciCevapBolum SOC2	WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=3 AND SUBS.SINAVTARIH<S.SINAVTARIH AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
							WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
							AND S.OZEL = 0
							AND SO.ID_SINAV=(
												SELECT ID_SINAV FROM
												(
													SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
													INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV AND S.AKTIF=1 AND S.OZEL = 0
													WHERE	SO.TCKIMLIKNO = @OGRTCKIMLIKNO
														AND S.ID_SINAVTURU=3 
														AND DONEM = @AKTIFDONEM
												) XTABLE
												WHERE RN=1
											)
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						),
						(
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'AYT' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
							FROM Sinav S  WITH(NOLOCK)
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
							INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
							INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
							where S.ID_SINAVTURU=3 
							AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) WHERE ID_SINAVTURU=3 
										AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
										AND EXISTS (SELECT * FROM SinavDers WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
										AND EXISTS (SELECT * FROM SinavKitapcik WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV)
										AND SUBS.OZEL = 0
										AND DONEM = @AKTIFDONEM) 
							AND S.OZEL = 0
							GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)
						)
						AS YKSSINAVSONUC,
						ISNULL((
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
							FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
							INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
							INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=2 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
							LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=2 AND SUBS.ID_SINAV<SO.ID_SINAV AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.ID_SINAV DESC)
							WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
							AND S.OZEL = 0
							AND SO.ID_SINAV=(
												SELECT ID_SINAV FROM
												(
													SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
													INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
													WHERE	SO.TCKIMLIKNO = @OGRTCKIMLIKNO 
														AND S.ID_SINAVTURU=2 
														AND S.AKTIF=1 
														AND S.OZEL= 0
														AND DONEM = @AKTIFDONEM
												) XTABLE
												WHERE RN=1
											)
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						),
						(
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'TYT' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
							FROM Sinav S  WITH(NOLOCK)
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
							INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
							INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
							where S.ID_SINAVTURU=2 
							AND S.OZEL = 0
							AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) 
											WHERE ID_SINAVTURU=2 
											AND DONEM = @AKTIFDONEM
											AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV AND SUBS.OZEL = 0))
							GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)
						) AS TYTSINAVSONUC
						FOR JSON PATH, INCLUDE_NULL_VALUES
					) AS SINAVSONUC					
				END
				ELSE -- 9, 10 İse AAYKS
				BEGIN
					SELECT
					(
						SELECT
						ISNULL((
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SOC.NET, (SOC.DOGRU + SOC.YANLIS + SOC.BOS) AS SORUSAYISI,ISNULL((SELECT DISTINCT S1.AD FROM Sinav S1 WITH(NOLOCK) INNER JOIN SinavDers S2 WITH(NOLOCK) ON S2.ID_SINAV=S1.ID_SINAV AND S2.ID_SINAVDERS=SOC2.ID_SINAVDERS AND S1.OZEL = 0),'YOK') AS BIRONCEKIAD, S.AD AS AD, ISNULL(SOC2.NET,0) AS BIRONCEKINET, (ISNULL(SOC2.DOGRU,0) + ISNULL(SOC2.YANLIS,0) + ISNULL(SOC2.BOS,0)) AS BIRONCEKISORUSAYISI,ISNULL(HN.NET-SOC.NET,0) AS ARTIS,ISNULL(HN.NET,SOC.NET) AS HEDEFNET 
							FROM SinavOgrenciCevapBolum SOC WITH(NOLOCK)
							INNER JOIN SinavOgrenci SO WITH(NOLOCK) ON SO.ID_SINAVOGRENCI=SOC.ID_SINAVOGRENCI
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOC.ID_SINAVDERS
							INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SD.ID_SINAV
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=6 AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=SO.TCKIMLIKNO AND HN.AKTIF=1
							LEFT JOIN SinavOgrenciCevapBolum SOC2 WITH(NOLOCK) ON (SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC2.ID_SINAVDERS)=(SELECT TAKMAAD FROM SinavDers WITH(NOLOCK) WHERE ID_SINAVDERS=SOC.ID_SINAVDERS) AND SOC2.ID_SINAVOGRENCI=(SELECT TOP 1 ID_SINAVOGRENCI FROM SinavOgrenci SUBSO WITH(NOLOCK) INNER JOIN Sinav SUBS WITH(NOLOCK) ON SUBS.ID_SINAV=SUBSO.ID_SINAV WHERE TCKIMLIKNO=SO.TCKIMLIKNO AND SUBS.ID_SINAVTURU=6 AND SUBS.SINAVTARIH<S.SINAVTARIH AND SUBS.AKTIF=1 AND SUBS.OZEL = 0 ORDER BY SUBS.SINAVTARIH DESC)
							WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO
							AND S.OZEL = 0
							AND SO.ID_SINAV=(
												SELECT ID_SINAV FROM
												(
													SELECT ROW_NUMBER() OVER (ORDER BY S.SINAVTARIH DESC) RN, S.ID_SINAV FROM SinavOgrenci SO WITH(NOLOCK)
													INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
													WHERE SO.TCKIMLIKNO = @OGRTCKIMLIKNO AND S.ID_SINAVTURU=6 AND S.AKTIF=1 AND S.OZEL = 0
														AND DONEM = @AKTIFDONEM
												) XTABLE
												WHERE RN=1
											)
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						),
						(
							SELECT S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, 0 AS NET, (COUNT(*)) AS SORUSAYISI, 0 AS BIRONCEKINET,'YOK' AS BIRONCEKIAD, 'AAYKS' AS AD, (COUNT(*)) AS BIRONCEKISORUSAYISI, ISNULL(HN.NET,0) AS ARTIS, ISNULL(HN.NET,0) AS HEDEFNET 
							FROM Sinav S  WITH(NOLOCK)
							INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAV=S.ID_SINAV
							INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=S.ID_SINAV AND SK.AD='A'
							INNER JOIN SinavAnahtar SA WITH(NOLOCK) ON SA.ID_SINAVDERS=SD.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK
							LEFT JOIN OgrenciHedefNet HN WITH(NOLOCK) ON HN.ID_SINAVTURU=S.ID_SINAVTURU AND HN.TAKMAAD=SD.TAKMAAD AND HN.TCKIMLIKNO=@OGRTCKIMLIKNO AND HN.AKTIF=1
							where S.ID_SINAVTURU=6 
							AND S.OZEL = 0
							AND S.ID_SINAV=(SELECT MAX(ID_SINAV) FROM Sinav SUBS WITH(NOLOCK) WHERE ID_SINAVTURU=6 
											AND EXISTS (SELECT * FROM SinavKatsayi WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
											AND EXISTS (SELECT * FROM SinavDers WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV) 
											AND EXISTS (SELECT * FROM SinavKitapcik WITH(NOLOCK) WHERE ID_SINAV=SUBS.ID_SINAV)
											AND SUBS.OZEL = 0
											AND DONEM = @AKTIFDONEM)
							GROUP BY S.ID_SINAV, S.ID_SINAVTURU, SD.TAKMAAD, SD.BOLUMNO, HN.NET, S.AD
							ORDER BY SD.BOLUMNO
							FOR JSON PATH, INCLUDE_NULL_VALUES
						)
						)
						AS AAYKSSINAVSONUC
						FOR JSON PATH, INCLUDE_NULL_VALUES
					) AS SINAVSONUC
				END
			END
		END

		IF @ISLEM = 7	--	Öğrenci Hedef Net Ekle					
		BEGIN
			DECLARE @OOOBP INT 
			IF EXISTS (SELECT OOBP FROM OgrenciOOBP WHERE TCKIMLIKNO = @OGRTCKIMLIKNO)
			BEGIN
				SET @OOOBP = (SELECT OOBP FROM OgrenciOOBP WHERE TCKIMLIKNO = @OGRTCKIMLIKNO)
			END
			ELSE
			BEGIN
				SET @OOOBP =  85
			END	

			SELECT @ID_KADEME3 = ID_KADEME3 FROM OkyanusDB.dbo.v3KullaniciKademe3 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO

			IF @ID_SINAVPUANTURU = 6 -- DİL
			BEGIN
				UPDATE [OgrenciHedefNet] SET AKTIF=0 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO
				INSERT INTO [dbo].[OgrenciHedefNet]
							([TCKIMLIKNO]
							,[ID_SINAVTURU]
							,[TAKMAAD]
							,[NET]
							,[DONEM])
				SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.TYTSINAVSONUC')
				WITH (
					TAKMAAD VARCHAR(MAX),
					NET DECIMAL(5,2),
					ARTIS DECIMAL(5,2),
					ID_SINAVTURU INT
				) AS j

				INSERT INTO [dbo].[OgrenciHedefNet]
							([TCKIMLIKNO]
							,[ID_SINAVTURU]
							,[TAKMAAD]
							,[NET]
							,[DONEM])
				SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.YKSSINAVSONUC')
				WITH (
					TAKMAAD VARCHAR(MAX),
					NET DECIMAL(5,2),
					ARTIS DECIMAL(5,2),
					ID_SINAVTURU INT
				) AS j

				--PUAN HESAPLA--
				DELETE FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU IN (SELECT ID_SINAVPUANTURU FROM SinavPuanTuru WITH(NOLOCK) WHERE ID_SINAVTURU in (2,4))
				INSERT INTO [dbo].[OgrenciHedefPuan]
							([TCKIMLIKNO]
							,[ID_SINAVPUANTURU]
							,[PUAN])
				SELECT @OGRTCKIMLIKNO, STP.ID_SINAVPUANTURU,(SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)+ (@OOOBP * 0.6) AS PUAN FROM OPENJSON(@SQLJSON, '$.TYTSINAVSONUC')
				WITH (
					ID_SINAV INT,
					TAKMAAD VARCHAR(MAX),
					NET DECIMAL(5,2),
					ARTIS DECIMAL(5,2)
				) AS J
				INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
				INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
				INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV
				GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN

				INSERT INTO [dbo].[OgrenciHedefPuan]
							([TCKIMLIKNO]
							,[ID_SINAVPUANTURU]
							,[PUAN])
				SELECT @OGRTCKIMLIKNO
						,STP.ID_SINAVPUANTURU
						,(
							CASE WHEN EXISTS((SELECT PUAN FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=1 AND PUAN>100))
							THEN (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)*0.6) + (SELECT PUAN*0.4 FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=1)) 
							ELSE (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN))) 
							END
							+ (@OOOBP * 0.6)
						) AS PUAN 
				FROM OPENJSON(@SQLJSON, '$.YKSSINAVSONUC')
				WITH (
					ID_SINAV INT,
					TAKMAAD VARCHAR(MAX),
					NET DECIMAL(5,2),
					ARTIS DECIMAL(5,2)
				) AS J
				INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
				INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
				INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV AND STP.ID_SINAVPUANTURU=SK.ID_SINAVPUANTURU
				GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN
			END
			ELSE
			BEGIN
				IF @ID_KADEME3 IN (17, 18) -- 11, 12 İse TYT-YKS
				BEGIN
					UPDATE [OgrenciHedefNet] SET AKTIF=0 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO
					INSERT INTO [dbo].[OgrenciHedefNet]
								([TCKIMLIKNO]
								,[ID_SINAVTURU]
								,[TAKMAAD]
								,[NET]
								,[DONEM])
					SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.TYTSINAVSONUC')
					WITH (
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2),
						ID_SINAVTURU INT
					) AS j

					INSERT INTO [dbo].[OgrenciHedefNet]
								([TCKIMLIKNO]
								,[ID_SINAVTURU]
								,[TAKMAAD]
								,[NET]
								,[DONEM])
					SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.YKSSINAVSONUC')
					WITH (
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2),
						ID_SINAVTURU INT
					) AS j

					--PUAN HESAPLA--
					DELETE FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU IN (SELECT ID_SINAVPUANTURU FROM SinavPuanTuru WITH(NOLOCK) WHERE ID_SINAVTURU in (2,3))
					INSERT INTO [dbo].[OgrenciHedefPuan]
								([TCKIMLIKNO]
								,[ID_SINAVPUANTURU]
								,[PUAN])
					SELECT @OGRTCKIMLIKNO, STP.ID_SINAVPUANTURU,(SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN) + (@OOOBP * 0.6) AS PUAN FROM OPENJSON(@SQLJSON, '$.TYTSINAVSONUC')
					WITH (
						ID_SINAV INT,
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2)
					) AS J
					INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV
					GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN

					INSERT INTO [dbo].[OgrenciHedefPuan]
								([TCKIMLIKNO]
								,[ID_SINAVPUANTURU]
								,[PUAN])
					SELECT @OGRTCKIMLIKNO
						  ,STP.ID_SINAVPUANTURU
						  ,(
								CASE WHEN EXISTS((SELECT PUAN FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=1 AND PUAN>100))
								THEN (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)*0.6) + (SELECT PUAN*0.4 FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=1)) 
								ELSE (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN))) 
								END
								+ (@OOOBP * 0.6)
						   ) AS PUAN 
					FROM OPENJSON(@SQLJSON, '$.YKSSINAVSONUC')
					WITH (
						ID_SINAV INT,
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2)
					) AS J
					INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV AND STP.ID_SINAVPUANTURU=SK.ID_SINAVPUANTURU
					GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN



					-- 11.SINIF AAYKS
					IF @ID_KADEME3 = 17
					BEGIN
						--UPDATE [OgrenciHedefNet] SET AKTIF=0 WHERE TCKIMLIKNO=@TCKIMLIKNO

						INSERT INTO [dbo].[OgrenciHedefNet]
									([TCKIMLIKNO]
									,[ID_SINAVTURU]
									,[TAKMAAD]
									,[NET]
									,[DONEM])
						SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.AAYKSSINAVSONUC')
						WITH (
							TAKMAAD VARCHAR(MAX),
							NET DECIMAL(5,2),
							ARTIS DECIMAL(5,2),
							ID_SINAVTURU INT
						) AS j

						--PUAN HESAPLA--
						DELETE FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU IN (9, 11, 12, 13)
						INSERT INTO [dbo].[OgrenciHedefPuan]
									([TCKIMLIKNO]
									,[ID_SINAVPUANTURU]
									,[PUAN])
						SELECT @OGRTCKIMLIKNO, STP.ID_SINAVPUANTURU,SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN AS PUAN FROM OPENJSON(@SQLJSON, '$.AAYKSSINAVSONUC')
						WITH (
							ID_SINAV INT,
							TAKMAAD VARCHAR(MAX),
							NET DECIMAL(5,2),
							ARTIS DECIMAL(5,2)
						) AS J
						INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
						INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
						INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV
						WHERE STP.ID_SINAVPUANTURU=9 AND SK.ID_SINAVPUANTURU=9
						GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN

						INSERT INTO [dbo].[OgrenciHedefPuan]
									([TCKIMLIKNO]
									,[ID_SINAVPUANTURU]
									,[PUAN])
						SELECT @OGRTCKIMLIKNO
							  ,STP.ID_SINAVPUANTURU
							  ,(
									CASE WHEN EXISTS((SELECT PUAN FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=9 AND PUAN>100))
									THEN (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)*0.6) + (SELECT PUAN*0.4 FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=9)) 
									ELSE (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN))) 
									END
									+ (@OOOBP * 0.6)
							   ) AS PUAN 
						FROM OPENJSON(@SQLJSON, '$.AAYKSSINAVSONUC')
						WITH (
							ID_SINAV INT,
							TAKMAAD VARCHAR(MAX),
							NET DECIMAL(5,2),
							ARTIS DECIMAL(5,2)
						) AS J
						INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
						INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
						INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV AND STP.ID_SINAVPUANTURU=SK.ID_SINAVPUANTURU
						WHERE SK.ID_SINAVPUANTURU<>9
						GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN
					END
				END
				ELSE -- AAYKS
				BEGIN
					UPDATE [OgrenciHedefNet] SET AKTIF=0 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO

					INSERT INTO [dbo].[OgrenciHedefNet]
								([TCKIMLIKNO]
								,[ID_SINAVTURU]
								,[TAKMAAD]
								,[NET]
								,[DONEM])
					SELECT @OGRTCKIMLIKNO, J.ID_SINAVTURU, J.TAKMAAD, J.NET+J.ARTIS, (SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1)  FROM OPENJSON(@SQLJSON,'$.AAYKSSINAVSONUC')
					WITH (
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2),
						ID_SINAVTURU INT
					) AS j

					--PUAN HESAPLA--
					DELETE FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU IN (9, 11, 12, 13)
					INSERT INTO [dbo].[OgrenciHedefPuan]
								([TCKIMLIKNO]
								,[ID_SINAVPUANTURU]
								,[PUAN])
					SELECT @OGRTCKIMLIKNO, STP.ID_SINAVPUANTURU,(SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)+ (@OOOBP * 0.6) AS PUAN FROM OPENJSON(@SQLJSON, '$.AAYKSSINAVSONUC')
					WITH (
						ID_SINAV INT,
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2)
					) AS J
					INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV AND STP.ID_SINAVPUANTURU = SK.ID_SINAVPUANTURU
					WHERE STP.ID_SINAVPUANTURU = 9
					GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN

					INSERT INTO [dbo].[OgrenciHedefPuan]
								([TCKIMLIKNO]
								,[ID_SINAVPUANTURU]
								,[PUAN])
					SELECT @OGRTCKIMLIKNO
						  ,STP.ID_SINAVPUANTURU
						  ,(
								CASE WHEN EXISTS((SELECT PUAN FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=9 AND PUAN>100))
								THEN (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN)*0.6) + (SELECT PUAN*0.4 FROM OgrenciHedefPuan WHERE TCKIMLIKNO=@OGRTCKIMLIKNO AND ID_SINAVPUANTURU=9)) 
								ELSE (((SUM((J.NET+J.ARTIS)*SK.KATSAYI)+STP.TABANPUAN))) 
								END
								+ (@OOOBP * 0.6)
						   ) AS PUAN 
					FROM OPENJSON(@SQLJSON, '$.AAYKSSINAVSONUC')
					WITH (
						ID_SINAV INT,
						TAKMAAD VARCHAR(MAX),
						NET DECIMAL(5,2),
						ARTIS DECIMAL(5,2)
					) AS J
					INNER JOIN SinavDers VSD WITH(NOLOCK) ON VSD.TAKMAAD=J.TAKMAAD AND VSD.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavKatsayi SK WITH(NOLOCK) ON SK.ID_SINAVDERS=VSD.ID_SINAVDERS AND SK.ID_SINAV=J.ID_SINAV
					INNER JOIN SinavTabanPuan STP WITH(NOLOCK) ON STP.ID_SINAV=J.ID_SINAV AND STP.ID_SINAVPUANTURU=SK.ID_SINAVPUANTURU
					WHERE SK.ID_SINAVPUANTURU IN (11, 12, 13)
					GROUP BY STP.ID_SINAVPUANTURU, STP.TABANPUAN
				END
			END
			
		END

		IF @ISLEM = 8	--	Öğrenci Kazanım Listele					
		BEGIN
			SELECT  SO.ID_SINAV
				,SD.TAKMAAD AS [DERS.AD]
				,SOCB.DOGRU AS [DERS.DOGRU]
				,SOCB.DOGRU+SOCB.YANLIS+SOCB.BOS AS [DERS.SORU]
				,CASE WHEN SDU.AD IS NULL THEN CONVERT(VARCHAR(MAX),SA.KOD) ELSE SDU.AD END AS [DERS.UNITE.AD]
				,SUM(case SOC.DURUM when 'D' then 1 else 0 end) as [DERS.UNITE.DOGRU]
				,SUM(case SOC.DURUM when 'Y' then 1 else 0 end) as [DERS.UNITE.YANLIS]
				,SUM(case SOC.DURUM when 'B' then 1 else 0 end) as [DERS.UNITE.BOS]
				,COUNT(1) as [DERS.UNITE.SORU]
			INTO #TEMP1
			FROM SinavOgrenci SO WITH(NOLOCK)
			INNER JOIN SinavOgrenciCevapBolum SOCB WITH(NOLOCK) ON SOCB.ID_SINAVOGRENCI=SO.ID_SINAVOGRENCI
			INNER JOIN SinavOgrenciCevap SOC WITH(NOLOCK) ON SOC.ID_SINAVOGRENCICEVAPBOLUM=SOCB.ID_SINAVOGRENCICEVAPBOLUM
			INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=SO.ID_SINAV AND SK.AD=SO.KITAPCIK
			INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOCB.ID_SINAVDERS
			INNER JOIN SinavAnahtar SA  WITH(NOLOCK) ON SA.ID_SINAVDERS=SOCB.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK AND SA.SORUNO=SOC.SORUNO
			INNER JOIN v3SinavDersUnite SDU WITH(NOLOCK) on SDU.KOD=SA.KOD
			INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
			WHERE SO.TCKIMLIKNO=@OGRTCKIMLIKNO AND S.AKTIF=1 AND S.OZEL = 0
			GROUP BY SO.ID_SINAV, SD.TAKMAAD, SOCB.DOGRU, SOCB.YANLIS, SOCB.BOS, SDU.AD, SA.KOD
			
			SELECT 
			(
				SELECT 
				[DERS.AD] AS DERSAD, [DERS.UNITE.AD] AS UNITEAD
				,SUM([DERS.UNITE.DOGRU]) AS TD
				,SUM([DERS.UNITE.YANLIS]) AS TY
				,SUM([DERS.UNITE.BOS]) AS TB
				,(SELECT 
						CONVERT(DECIMAL(5,2),CONVERT(DECIMAL(5,2),SUM(DS))/CONVERT(DECIMAL(5,2),SUM(SS))*100.0) 
					FROM (SELECT [DERS.SORU] AS SS, [DERS.DOGRU] DS FROM #TEMP1 SUBT WHERE SUBT.[DERS.AD]=T.[DERS.AD] GROUP BY SUBT.ID_SINAV, [DERS.SORU], [DERS.DOGRU]) ASD
					) 
					AS [DERSYUZDE]
				,CONVERT(DECIMAL(5,2), SUM([DERS.UNITE.DOGRU])/CONVERT(DECIMAL(5,2),SUM([DERS.UNITE.SORU])))*100 AS [UNITEYUZDE]
				FROM
				#TEMP1 T
				GROUP BY [DERS.AD], [DERS.UNITE.AD]
				ORDER BY [DERS.AD], CONVERT(DECIMAL(5,2), SUM([DERS.UNITE.DOGRU])/CONVERT(DECIMAL(5,2),SUM([DERS.UNITE.SORU])))*100 desc
				FOR JSON AUTO
			) J

			DROP TABLE #TEMP1
		END	

		IF @ISLEM = 9	--	OOBP EKLE/GUNCELLE						
		BEGIN
			IF EXISTS (SELECT OOBP FROM OgrenciOOBP WHERE TCKIMLIKNO = @TCKIMLIKNO)
			BEGIN
				UPDATE OgrenciOOBP SET OOBP = @OOBP WHERE TCKIMLIKNO = @TCKIMLIKNO
			END
			ELSE
			BEGIN
				INSERT INTO OgrenciOOBP (OOBP, TCKIMLIKNO) VALUES (@OOBP, @TCKIMLIKNO)
			END
		END

		IF @ISLEM = 10	--	OOBP GETİR								
		BEGIN
			IF EXISTS (SELECT OOBP FROM OgrenciOOBP WHERE TCKIMLIKNO = @TCKIMLIKNO)
			BEGIN
				SELECT OOBP FROM OgrenciOOBP WHERE TCKIMLIKNO = @TCKIMLIKNO
			END
			ELSE
			BEGIN
				SELECT 85
			END			
		END

		IF @ISLEM = 11	--	PUAN TÜRÜ GETİR							
		BEGIN
			
			SELECT @ID_KADEME3 = ID_KADEME3 FROM OkyanusDB.dbo.v3KullaniciKademe3 WHERE TCKIMLIKNO=@OGRTCKIMLIKNO
			IF @ID_KADEME3 IN (17, 18) -- 11, 12 İse TYT-YKS (11. SINIFLAR İÇİN AAYKS)
			BEGIN
				SELECT
				(
					SELECT ID_SINAVPUANTURU,SPT.ID_SINAVTURU,SPT.AD+' ('+ST.KISAAD+')' AD,KOD,MAX_PUAN 
					FROM OgrenciHedef					OH	WITH(NOLOCK)
					INNER JOIN UniversiteTabanPuanlari	U	WITH(NOLOCK)	ON U.PROGRAMKODU=OH.PROGRAMKODU
					INNER JOIN SinavPuanTuru			SPT WITH(NOLOCK)	ON SPT.KOD=U.PUANTURU
					INNER JOIN SinavTuru				ST	WITH(NOLOCK)	ON ST.ID_SINAVTURU	= SPT.ID_SINAVTURU
					WHERE	OH.TCKIMLIKNO=@OGRTCKIMLIKNO 
						AND U.YIL = @AKTIFDONEM and OH.AKTIF = 1
						AND (	@ID_KADEME3 = 17 AND SPT.ID_SINAVTURU IN (2,3,4,6)
							OR	SPT.ID_SINAVTURU IN (2,3,4)
							)

					GROUP BY SPT.ID_SINAVTURU, SPT.ID_SINAVPUANTURU, SPT.AD, SPT.KOD, SPT.MAX_PUAN,ST.KISAAD					
					ORDER BY ST.KISAAD,SPT.AD
					--ORDER BY COUNT(1) DESC
					FOR JSON AUTO
				) PUANTURLER
			END
			ELSE 
			BEGIN
				SELECT
				(
					SELECT SPT.* FROM OgrenciHedef OH WITH(NOLOCK)
					INNER JOIN UniversiteTabanPuanlari U WITH(NOLOCK)	ON U.PROGRAMKODU=OH.PROGRAMKODU
					INNER JOIN SinavPuanTuru SPT		 WITH(NOLOCK)	ON SPT.KOD=U.PUANTURU
					WHERE OH.TCKIMLIKNO=@OGRTCKIMLIKNO AND SPT.ID_SINAVTURU IN (6,4)
						AND U.YIL = @AKTIFDONEM and OH.AKTIF = 1
					GROUP BY SPT.ID_SINAVTURU, SPT.ID_SINAVPUANTURU, SPT.AD, SPT.KOD, SPT.MAX_PUAN
					ORDER BY COUNT(1) DESC
					FOR JSON AUTO
				) PUANTURLER
			END
		END

		IF @ISLEM = 12	--	Veli Öğrenci Hedef Listele				
		BEGIN
			SELECT 
			(
				SELECT	oh.[PROGRAMKODU]
						,tp.[UNIVERSITE]
						,tp.[FAKULTE]
						,tp.[BOLUM]
						,tp.[BOLUM2]
						,tp.[EGITIMDILI]
						,tp.[UCRETBURS]
						,tp.[IL]
						,tp.[UNIVERSITETURU]
						,tp.[OGRENIMSURESI]
						,tp.[OGRENIMTURU]
						,tp.[PUANTURU]
						,tp.[YIL]
						,tp.[TABANPUAN]
						,tp.[KONTENJAN]
						,tp.[PROGRAMTURU]
						,tp.[SONYGSYERLESTIRME]
						,tp.[OKULBIRINCILIGIKONTENJANI]
						,tp.[YERONCELIKLERI]
						,tp.[ENBUYUKPUAN]
						,tp.[BASARISIRALAMA]
						,REPLACE((STUFF((SELECT CAST('@@** ' + [KOSUL] AS VARCHAR(MAX)) 
									FROM UniversiteOzelKosul ok
									WHERE ok.NO IN (SELECT value FROM STRING_SPLIT(REPLACE(tp.OZELKOSULACIKLAMA,' ','') , ','))
									FOR XML PATH ('')), 1, 2, '')),'@@','<br /><br />') AS [OZELKOSULACIKLAMA]
				FROM OgrenciHedef oh
				INNER JOIN UniversiteTabanPuanlari tp on tp.PROGRAMKODU=oh.PROGRAMKODU
				WHERE TCKIMLIKNO=@OGRTCKIMLIKNO 
					--AND DONEM=(SELECT DONEM FROM v3AktifDonem WHERE AKTIF=1) 
					AND TP.YIL = @AKTIFDONEM
					AND AKTIF=1
				ORDER BY KYE_TARIH DESC
				FOR JSON PATH, INCLUDE_NULL_VALUES
			) JSONDATA
		END

		IF @ISLEM = 13	--	ÖĞRENCİ KAZANIM LİSTELE YENİ			
		BEGIN
			DECLARE @ID_KADEME3_OGR INT

			SELECT @ID_KADEME3_OGR = ST.ID_KADEME3 
			FROM OkyanusDB.dbo.v3Ogrenci O
			JOIN OkyanusDB.dbo.v3Sinif S ON S.ID_SINIF = O.ID_SINIF
			JOIN OkyanusDB.dbo.v3SatisTuru ST ON ST.ID_SATISTURU = S.ID_SATISTURU
			WHERE O.TCKIMLIKNO = @OGRTCKIMLIKNO

			SELECT  SO.ID_SINAV
				,SD.TAKMAAD AS [DERS.AD]
				,SOCB.DOGRU AS [DERS.DOGRU]
				,SOCB.DOGRU+SOCB.YANLIS+SOCB.BOS AS [DERS.SORU]
				,CASE WHEN SDU.AD IS NULL THEN CONVERT(VARCHAR(MAX),SA.KOD) ELSE SDU.AD END AS [DERS.UNITE.AD]
				,SA.KOD  AS [DERS.UNITE.KOD]
				,SUM(case SOC.DURUM when 'D' then 1 else 0 end) as [DERS.UNITE.DOGRU]
				,SUM(case SOC.DURUM when 'Y' then 1 else 0 end) as [DERS.UNITE.YANLIS]
				,SUM(case SOC.DURUM when 'B' then 1 else 0 end) as [DERS.UNITE.BOS]
				,COUNT(1) as [DERS.UNITE.SORU]
			INTO #TEMP1X
			FROM SinavOgrenci SO WITH(NOLOCK)
			INNER JOIN SinavOgrenciCevapBolum SOCB WITH(NOLOCK) ON SOCB.ID_SINAVOGRENCI=SO.ID_SINAVOGRENCI
			INNER JOIN SinavOgrenciCevap SOC WITH(NOLOCK) ON SOC.ID_SINAVOGRENCICEVAPBOLUM=SOCB.ID_SINAVOGRENCICEVAPBOLUM
			INNER JOIN SinavKitapcik SK WITH(NOLOCK) ON SK.ID_SINAV=SO.ID_SINAV AND SK.AD=SO.KITAPCIK
			INNER JOIN SinavDers SD WITH(NOLOCK) ON SD.ID_SINAVDERS=SOCB.ID_SINAVDERS
			INNER JOIN SinavAnahtar SA  WITH(NOLOCK) ON SA.ID_SINAVDERS=SOCB.ID_SINAVDERS AND SA.ID_SINAVKITAPCIK=SK.ID_SINAVKITAPCIK AND SA.SORUNO=SOC.SORUNO
			INNER JOIN v3SinavDersUnite SDU WITH(NOLOCK) on SDU.KOD=SA.KOD
			INNER JOIN Sinav S WITH(NOLOCK) ON S.ID_SINAV=SO.ID_SINAV
			WHERE SO.TCKIMLIKNO=@OGRTCKIMLIKNO AND S.AKTIF=1 AND S.OZEL = 0 AND ((@ID_KADEME3_OGR < 15 AND S.DONEM = @AKTIFDONEM) OR @ID_KADEME3_OGR >= 15) -- LİSE DEĞİLSE SADECE MEVCUT DÖNEM
			GROUP BY SO.ID_SINAV, SD.TAKMAAD, SOCB.DOGRU, SOCB.YANLIS, SOCB.BOS, SDU.AD, SA.KOD			

			SELECT
			(
				SELECT	DERSAD = [DERS.AD],
						DERSYUZDE = CONVERT(DECIMAL(5,2),CONVERT(DECIMAL(18,2),SUM([DERS.DOGRU]))/CONVERT(DECIMAL(18,2),SUM([DERS.SORU]))*100.0),
						UNITELER = (
							SELECT	UNITEAD = SUBT.[DERS.UNITE.AD], 
									TD = SUM(SUBT.[DERS.UNITE.DOGRU]), 
									TY = SUM(SUBT.[DERS.UNITE.YANLIS]), 
									TB = SUM(SUBT.[DERS.UNITE.BOS]),
									LINKLIST = ISNULL((SELECT DISTINCT LINK
														FROM OKYANUSDB.DBO.v3SinavDersUniteLink L
														WHERE	L.KOD	= SUBT.[DERS.UNITE.KOD]
															AND L.AKTIF = 1
														FOR JSON PATH, INCLUDE_NULL_VALUES
													),'[]'),
									AKILLIBARKODLIST = ISNULL((SELECT DISTINCT LINK = 'https://www.akilliogretim.com/VideoList/' + L.AKILLIOGRETIMBARKODKOD
														FROM Pusulam.dbo.AkilliOgretimBarkod L
														WHERE	L.ALTKONUKOD	= SUBT.[DERS.UNITE.KOD]															
														FOR JSON PATH, INCLUDE_NULL_VALUES
													),'[]'),
									MORPAKAZANIMLIST = ISNULL((SELECT MK.KOD
														FROM MorpaKazanim MK
														JOIN MorpaDers MD ON MD.ID_MORPADERS = MK.ID_MORPADERS AND MD.AKTIF = 1
														WHERE	MK.KOD_OKY	= SUBT.[DERS.UNITE.KOD]
															AND MK.AKTIF = 1
															AND MD.ID_KADEME3 = @ID_KADEME3_OGR
														FOR JSON PATH, INCLUDE_NULL_VALUES
													),'[]'),
									[UNITEYUZDE] = CONVERT(DECIMAL(5,2), SUM(SUBT.[DERS.UNITE.DOGRU]) / CONVERT(DECIMAL(5,2),SUM(SUBT.[DERS.UNITE.SORU]))) * 100
									
							FROM #TEMP1X SUBT 
							WHERE SUBT.[DERS.AD] = T.[DERS.AD]
							GROUP BY SUBT.[DERS.AD], SUBT.[DERS.UNITE.KOD], SUBT.[DERS.UNITE.AD]
							ORDER BY UNITEYUZDE DESC
							FOR JSON PATH
						) 
				FROM #TEMP1X T
				GROUP BY [DERS.AD]
				ORDER BY DERSYUZDE DESC
				FOR JSON PATH
			) AS J

			DROP TABLE #TEMP1X
		END

		IF @ISLEM = 14	--	Sınav Türü Net Grafik Listele
		BEGIN
			SELECT	 B.NET
					,DERSAD				= D.TAKMAAD
					,SIRA				= 1
					,SINAVAD			= V.AD 
			INTO #SINAVNETGRAFIK
			FROM		SinavOgrenci			O
			JOIN		SinavOgrenciCevapBolum	B	ON  B.ID_SINAVOGRENCI	= O.ID_SINAVOGRENCI
			JOIN		SinavDers				D	ON  D.ID_SINAVDERS		= B.ID_SINAVDERS
			JOIN		Sinav					V	ON  V.ID_SINAV			= O.ID_SINAV
			WHERE	v.AKTIF			= 1		
				AND v.DURUM			= 2	
				AND O.TCKIMLIKNO	= @OGRTCKIMLIKNO
				AND V.DONEM			= @AKTIFDONEM
				AND V.ID_SINAVTURU	= @ID_SINAVTURU
				AND (OZEL=0 OR 0=1)
			UNION
			SELECT	 NET = SUM(B.NET)
					,DERSAD				= 'Toplam Net'
					,SIRA				= 0
					,SINAVAD			= V.AD 
			FROM		SinavOgrenci			O
			JOIN		SinavOgrenciCevapBolum	B	ON  B.ID_SINAVOGRENCI	= O.ID_SINAVOGRENCI
			JOIN		Sinav					V	ON  V.ID_SINAV			= O.ID_SINAV
			WHERE	v.AKTIF			= 1		
				AND v.DURUM			= 2	
				AND O.TCKIMLIKNO	= @OGRTCKIMLIKNO
				AND V.DONEM			= @AKTIFDONEM
				AND V.ID_SINAVTURU	= @ID_SINAVTURU
				AND (OZEL=0 OR 0=1)
			GROUP BY V.AD

			SELECT (
				SELECT	 NETLIST = ISNULL((
											SELECT * FROM #SINAVNETGRAFIK ORDER BY SINAVAD, DERSAD FOR JSON PATH
										), '[]')
						,DERSLIST = ISNULL((
											SELECT DISTINCT SIRA, DERSAD FROM #SINAVNETGRAFIK where DERSAD<>'Toplam Net' ORDER BY SIRA, DERSAD FOR JSON PATH
										), '[]')
				FOR JSON PATH, WITHOUT_ARRAY_WRAPPER
			)

			DROP TABLE #SINAVNETGRAFIK

		END

		IF @ISLEM = 15	--	SINAV TÜRÜ LİSTELE
		BEGIN
			SELECT
			(
				SELECT DISTINCT ST.ID_SINAVTURU, ST.AD, ST.KISAAD 
				FROM SinavTuru				ST	WITH(NOLOCK)
				INNER JOIN Sinav			S	WITH(NOLOCK) ON S.ID_SINAVTURU	= ST.ID_SINAVTURU
				INNER JOIN SinavOgrenci		SO	WITH(NOLOCK) ON SO.ID_SINAV		= S.ID_SINAV
				INNER JOIN v3Ogrenci		O	WITH(NOLOCK) ON O.TCKIMLIKNO	= SO.TCKIMLIKNO
				INNER JOIN vw_SubeGrupSinif	GS	WITH(NOLOCK) ON GS.ID_SINIF		= O.ID_SINIF
				WHERE	SO.TCKIMLIKNO	= @OGRTCKIMLIKNO 
					AND S.AKTIF			= 1 
					AND S.OZEL			= 0
					AND S.DONEM			= @AKTIFDONEM
				FOR JSON PATH
			) AS J
		END
	END

	END TRY
			BEGIN CATCH
			
				SELECT 
					@ErrorSeverity	= ERROR_SEVERITY(),
					@ErrorState		= ERROR_STATE()
							
				SELECT @MSG = /*'Prosedür: ' + ISNULL(ERROR_PROCEDURE(), '') + ', Satır: ' + CAST(ERROR_LINE() as varchar) + ', Hata: ' +*/ ERROR_MESSAGE()
			
				RAISERROR (@MSG , -- Message text.
							@ErrorSeverity, -- Severity.
							@ErrorState -- State.
							);
			END CATCH;
	
	END


